### ISSUE TITLE
development plan

### ISSUE THREAD

**Issue by cardosan** [LCA-ActivityBrowser/activity-browser#1]
HI Hadrian,
cool that you took this project over, do you have any development plan perhaps?
I think the development of a GUI would tremendously help all the bw2 users.....I guess almost everyone is using bw2 for more advanced things but still, most of the time is often spent in working on the databases, and having GUI would allow to save a tremendous amount of time for doing other things....
I am willing to help...even if I have basically no experience with pyqt...

**Comment by haasad** [comment]
Hi Giuseppe,
I haven't had a lot of spare time in the last two weeks, but hope to work on the activity browser a bit more in the coming weeks. At the moment i plan to do the following things:
- Fix the remaining issues caused by changes in the brightway2 api
- Add some advanced search functionalities (eg I often do things like 
```[ds for ds in database if ds['activity type']=='market activity' and 'cotton' in d['name'] and d['location']=='RoW']```) -> I think this would be nice to have in a GUI if you just want to quickly "browse the activites"
- Add the ability to import an ecoinvent database into a project from the GUI, to make it possible that people can browse ecoinvent without creating a project in brightway first
- Create a standalone executable with [pyinstaller](http://www.pyinstaller.org). I would like to be able to give non-python users a `.exe`/`.dmg`-file that they can double-click and it installs the GUI on their machine, without the hassle of installing Python, downloading all the dependencies etc.
- Find some nice way to graphically browse the database by clicking, I imagine some javascript network library with QWebView or similar. This is just an idea, don't know if realistic

Any thoughts on this? Maybe @cmutel wants to chime in as well?

**Comment by cardosan** [comment]
I first put some general thought,
I have been using bw2 for some 3 yrs now, starting from very little coding knowledges and basic LCA computational skills....step by step moved to also doing some developing. As an long standing user I guess can bring some experience about the good and the bad of bw2 for users...and how the bad could have been simplified with a nice GUI. I will first introduce a bit my vision and then move to some concrete proposals/requests.
I think the order of importance of the things to include is : 

a) database/datasets browsing and manipulation 
b) LCA visualization/ interpretation
c) LCA running

c) Spend time on building something to run LCAs (e.g. multiple LCAs, montecarlo or whatever like this) is not urgent for me cause, first, it is rather easy to do "standard" things in bw2 (in just a few lines of short codes it is possible to run an LCA....it is very easy also for people with 0 programming and LCA experience) and this is maybe the part of bw2 were users try to push the boundary forward and explore different things than what you can do e.g. in sima.

b) Have something visual to explore lca results would make things certainly much easier and intuitive...and would certainly also attract more users. Something that would allow to explore the network like in [sima](https://www.youtube.com/watch?v=dC0xej7PNr8) would be super cool....but I guess this takes a lot of time.

a) This is really the big bottleneck of working with bw2 in my opinion and the thing that caused me frustration the most. Despite who approach bw2 normally wants to do something more than the traditional LCA, also for doing advance things normally a lot of time (sometime the most) is spent in building, checking, browsing and modifying databases....and this is definitely not easy and quite time consuming in bw2. Only building a simple db takes time....and having the possibility to do it with a (basic) GUI would really make a big change and leave much more time for doing other more "advanced" (also more funny) things.

That said, in the specific I fully support your proposals, I would add to the list:

- possibility to visualize and manipulate also global and local parameters of [bw2parameters](https://bitbucket.org/cmutel/brightway2-parameters) (being parameters quite widespread in existing databases)
-  possibility to visualize and manipulate also temporal distribution used in [bw2temporalis](https://bitbucket.org/cmutel/brightway2-temporalis)
- possibility to graphically modify or create new datasets/databases....a typical situation I encountered (and still encounter) often is when I want to create one or more unit processes in the same or a new databases that are a modified version of an existing one. It would be amazing to be able to do this in just a few click simply copying the unit process to the same or a different db, and modify its attributes directly from the gui for example changing its exchanges  and/or its inputs amount.

How to you both see this points in terms of feasibility and usefulness? maybe would help to make a prioritized list of enhancement proposal in order to tackle first the most "useful".

P.S: as said I have basically no experience with GUIs development....but for what I can I am very willing to help and learn something on this.

**Comment by cardosan** [comment]
By the way, I just recalled that some time ago I came across [this post](http://www.omnibus.uni-freiburg.de/~sp1046/Documents/HiWi_Sankey.pdf) and would be super cool to integrate also this.
@stefanpauliuk did you managed to develop the tool? If so would you be willing to share?

**Comment by cardosan** [comment]
Just came across this python [sankey visualization tool for LCA](https://github.com/ricklupton/hybrid-sankey-diagram-paper-examples) (underlying paper [here](http://www.sciencedirect.com/science/article/pii/S0921344917301167) ). Interesting to take into consideration....

**Comment by stefanpauliuk** [comment]
Dear @Cardosan, 

thanks for the tip! I added the link to the IndEcol GitHub page:
https://github.com/IndEcol/Dashboard 

We are currently polishing our own code, and I plan to release it and the web application that builds on it by the end of the summer.

Cheers, Stefan

**Comment by haasad** [comment]
I've been working on integrating Rick Luptons [d3-sankey-diagram](https://github.com/ricklupton/d3-sankey-diagram) into the activity browser for quite some time already. The implementation to interactively explore the lcia results along the supply chain as a sankey-diagram is already mostly working and looks something like this:
<img width="1345" src="https://user-images.githubusercontent.com/11636405/27069657-180dbe5e-5016-11e7-94d6-49bb2c79ee6b.png">
There are still some things to fix and polish before I can release it, but if you want to check it out @cardosan have a look at the sankey branch in this repo. I'll keep you updated about the progess.

**Comment by bsteubing** [comment]
@everone and @cmutel @stefanpauliuk @cardosan:
Adrian and I have taken up the development of the Activity Browser again. As this project is starting to be a bit more of a collaborative effort, it was also time for a **new home**: https://github.com/LCA-ActivityBrowser/activity-browser. The idea is to have a small group of core developers, but also to be more open to contributions. I am currently also trying to involve students of Leiden University to contribute to some of the open issues. 
Regards, Bernhard
