### ISSUE TITLE
Seaborn changes upstream result in import error

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#10]
`File "/Users/cmutel/miniconda3/envs/isie/lib/python3.6/site-packages/lca_activity_browser/app/ui/panels/left.py", line 5, in <module>
    from ..graphics import DefaultGraph
  File "/Users/cmutel/miniconda3/envs/isie/lib/python3.6/site-packages/lca_activity_browser/app/ui/graphics.py", line 9, in <module>
    from seaborn.linearmodels import corrplot
ImportError: cannot import name 'corrplot'`

**Comment by haasad** [comment]
fixed in 9d0b2293a37e67a83e83e621cfd5585c00b4e7dd with new types of plots
