### ISSUE TITLE
login to ecoinvent fails

### ISSUE THREAD

**Issue by lucas-sys-cmd** [LCA-ActivityBrowser/activity-browser#1016]
The Eco invent update its website recently and I cannot login to it in AB to import database. What happened? How to fix it?

**Comment by marc-vdm** [comment]
This doesn't work for me either and is failing with `login failed` . Could you check if you can login on the ecoinvent website? For me that still works

**Comment by Zoophobus** [comment]
Hi, so I've just looked at our dependency that provides the logging service and there is already an issue there highlighting this. Here is the link (https://github.com/haasad/EcoInventDownLoader/issues/30), we'll probably need to see what happens here first

**Comment by lucas-sys-cmd** [comment]
> 

I can still login to it on the website. Maybe they didn't only update the website interface. Something has been changed, too. Lokking forward to a solution.

**Comment by marc-vdm** [comment]
Hi @lucas-sys-cmd, it seems this may take a while to be resolved. In the mean time you can do the following:

1. Go to https://ecoquery.ecoinvent.org/3.9.1/cutoff/files (login of course required) 
    - For older ecoinvent versions, scroll down
2. Choose the system model you want to use
3. Download the file named `ecoinvent 3.<version>_<system model>_ecoSpold02.7z` to a folder you will remember
4. In AB use the local import option through 7zip.

**Comment by haasad** [comment]
EcoInventDownLoader (eidl) [version 2](https://github.com/haasad/EcoInventDownLoader/releases/tag/2.0.0) is now available on conda-forge. After updating it the login and download in the AB should work again. Let me know if you run into any issues.
