### ISSUE TITLE
Graph explorer & technosphere missing

### ISSUE THREAD

**Issue by UmbertoVonNewman** [LCA-ActivityBrowser/activity-browser#1037]
Dear all,
I have been trying to watch the activity graph from my activity browser with EcoInvent 3.9.1, it is impossible.
Another probably associated problem is that there is nothing in the technosphere "table" when looking at any activities.
Please find attached the result of the command so you can reproduce the error: 
conda list --explicit > spec-file.txt
I use the EcoInvent database "ecoinvent 3.9.1_cutoff_lci_ecoSpold02.7z"

I have been also trying to use the old version of EcoInvent (3.8) by creating a new environment and executing the command : 
conda create -n ForOlderEcoInvent activity-browser
conda remove --force bw2io
conda install bw2io=0.8.7
But the problem remains.
Another piece of information I can provide is that I have miniconda3 py3.11_23.5.2-0 (Python 3.11).
Thanks for the help,
Best regards, Léon Ferrari
[spec-file.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/12587087/spec-file.txt)

**Comment by marc-vdm** [comment]
Could you provide a screenshot of the activity-browser showing each of the problems? And could you share any terminal output you have from starting AB, opening a database that doesn't show up and then opening an activity in graphview? 

Both will help understand and fix your problems

**Comment by UmbertoVonNewman** [comment]
The environment is the one for the most recent version of ecoInvent (3.9.1) env and the environment as installed by (conda create -n ab -c conda-forge activity-browser
).
Please find below a screenshot from the activity browser GUI :
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/130159677/b865b258-78b9-4429-a0b0-8caab7cf589a)
And here a screenshot fo the terminal output :
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/130159677/df56fb38-08ce-46a9-884e-431e93851dc8)

**Comment by marc-vdm** [comment]
@UmbertoVonNewman Could you please close the issue if this resolved your problem?

**Comment by UmbertoVonNewman** [comment]
Hello,
It is working correctly, sorry for disturbing.
Do I need both:
ecoinvent 3.9.1_cutoff_ecoSpold02.7z and ecoinvent 3.9.1_cutoff_lci_ecoSpold02.7z 
or only : 
ecoinvent 3.9.1_cutoff_ecoSpold02.7z 

Thanks and have a good day.
Leon

**Comment by marc-vdm** [comment]
Hi Leon,

With activity browser you only need `ecoinvent 3.9.1_cutoff_ecoSpold02.7z`.
