### ISSUE TITLE
AB button/shortcut to reread project directory and update the project.db file with the latest copied project folder

### ISSUE THREAD

**Issue by tjlca** [LCA-ActivityBrowser/activity-browser#1052]
### Feature request

Sharing projects between users. Once I have created a project on my own machine, I would like to share the project directory with another user. The way now is to backup the project directory, create a tar and then reread the tar.gz using brightway command window. However, it would be great if we can just share the compressed directory and the second user pastes the directory in the brightway2 environment folder. 

Once its pasted, a button to reread the project directory so that the project gets listed in the explorer.

**Comment by marc-vdm** [comment]
Of help to whoever picks this up:
[Brightway_prj_save_load.zip](https://github.com/LCA-ActivityBrowser/activity-browser/files/12831454/Brightway_prj_save_load.zip)
