### ISSUE TITLE
missing: searching with two fields

### ISSUE THREAD

**Issue by simb-sdu** [LCA-ActivityBrowser/activity-browser#1059]
hey, where did this feature go? I am really missing it - for some reason there is now only one search field, and I dislike this a lot 

             Searching in the new dataframe tables and with two fields and a logical operator in between is much better and faster now than anything we had previously.

_Originally posted by @bsteubing in https://github.com/LCA-ActivityBrowser/activity-browser/issues/4#issuecomment-471060064_

**Comment by marc-vdm** [comment]
Hi Simon,

We have replaced it with per-column filtering #894, has a write-up on how you can use the new filters. Hopefully you like those!

**Comment by simb-sdu** [comment]
thank you, Marc!

**Comment by simb-sdu** [comment]
And thanks for making the detailed writeup -I indeed like this new feature!

**Comment by marc-vdm** [comment]
That is great to hear <3
