### ISSUE TITLE
How to assess biodiversity impact with AB

### ISSUE THREAD

**Issue by rbugale** [LCA-ActivityBrowser/activity-browser#1063]
### Issue

I would like to calculate the biodiversity impact of soybean production, for example, in europe, using the characterization factors of Chaudhary and Brooks2018. Is that possible in the AB? I couldn.t find that in the impact categories list. Thank you for helping me understand this

**Comment by marc-vdm** [comment]
It's currently not possible to add impact categories in AB, but you can in Brightway. See #645 for a link to more info!

**Comment by marc-vdm** [comment]
Hey @rbugale,

I hope the above answered your question. If you have questions on how to use Activity Browser (like this) in the future, please open a [discussion](https://github.com/LCA-ActivityBrowser/activity-browser/discussions), if you have problems instead, you can just open an issue like this.
