### ISSUE TITLE
Update About AB info

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1071]
### Issue

Old:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/34626062/0c817901-14dc-4da5-b59d-9cd005ba7952)

- [x] Contributors should not be mentioned here, too many places that are not aligned this way (we already have the Welcome page and the github Readme that we can barely keep aligned) (suggestions welcome for something that can keep this aligned everywhere with one central file!).
- [x] We shouldn't have a link to GNU, but instead a link to our [license file](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/LICENSE.txt)

**Comment by bsteubing** [comment]
Agree with both. Let's skip the developers here. Let's link to our license file
