### ISSUE TITLE
Crash after scenario calculations

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#1073]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

I ran a scenario LCA. For a split-second there was a pop-up, which closed again. Then the LCA results were displayed, everything seemed to be all well. But then the AB closed, say 20 seconds afterwards. Does this again have to do with some threading or so? 

### Relevant errors

```python
separator == ';'
Loading Scenario file. This may take a while for large files
Superstructure: Attempting to read as parameter scenario file.
<function ScenarioImportWidget.scenario_db_check at 0x000002363CEB7EE0> -- 0.0
<function SuperstructureManager.fill_empty_process_keys_in_exchanges at 0x00000236383115E0> -- 0.0009899139404296875
<function SuperstructureManager.verify_scenario_process_keys at 0x0000023638311700> -- 0.014998912811279297
<function SuperstructureManager.check_duplicates at 0x0000023638311940> -- 0.0029976367950439453
<function SuperstructureManager.check_scenario_exchange_values at 0x0000023638311820> -- 0.0010006427764892578
<function SuperstructureManager.merge_flows_to_self at 0x0000023638311310> -- 0.004994392395019531
<function ScenarioImportWidget.sync_superstructure at 0x000002363CEB7DC0> -- 0.03400707244873047
<function ScenarioImportWidget.load_action at 0x000002363CEB7CA0> -- 39.07420587539673
+showing tab:LCA results
```

### Operating system

Windows 10

**Comment by Zoophobus** [comment]
I think this will need the scenario file and database to understand what is happening in the calculation and results, would it be possible to attach them here?

**Comment by marc-vdm** [comment]
closing as not replicable
