### ISSUE TITLE
not possible to use keybord's arrows for navigation

### ISSUE THREAD

**Issue by cardosan** [LCA-ActivityBrowser/activity-browser#108]
Dunno if you are already aware of this (in this case I propose this as improvement) or is an issue but I cannot navigate the activities (and/or exchanges) using the keyboard's arrows.
I think it is quite an important limitation to have to use always the mouse to browse around activities and exchanges.

**Comment by haasad** [comment]
Hi Giuseppe,
I wasn't aware of this, because this used to work. Thanks for raising this to attention. Should be fixed now in #120. Please reopen if it doesn't work everywhere, I didn't test all the tables, but since they all inherit from `ABTableWidget`, I expect it to work.

**Comment by cardosan** [comment]
Indeed fixed now
