### ISSUE TITLE
Error with data matrix

### ISSUE THREAD

**Issue by rbugale** [LCA-ActivityBrowser/activity-browser#1092]
### Issue

I got the following error and I don't know how to solve it.:
bw2calc.nonsquaretechnosphere.: Technosphere matrix is not square: 19567 activities (columns) and 19568 products (rows). Use lesat squares LCA to solve this system or fix the input system

I am using AB with ecoinvent 3.8

**Comment by marc-vdm** [comment]
What the error is saying is that there is 1 more product than there are processes (activities) in your system, so probably one process has two products. Activity Browser can't calculate results for this right now, every process must have exactly one product.

Perhaps check your model (Export your database to excel (top left `File` > `Export Database` > export as Excel to a location on your computer that you can find back) and try to find the problematic process, then edit it.

If you're trying to model a multifunctional process, check out #996 for an example database.
________________________________
From: Reussite Malembaka ***@***.***>
Sent: Tuesday, October 24, 2023 18:23
To: LCA-ActivityBrowser/activity-browser ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LCA-ActivityBrowser/activity-browser] Error with data matrix (Issue #1092)


Issue

I got the following error and I don't know how to solve it.:
bw2calc.nonsquaretechnosphere.: Technosphere matrix is not square: 19567 activities (columns) and 19568 products (rows). Use lesat squares LCA to solve this system or fix the input system

I am using AB with ecoinvent 3.8

**Comment by marc-vdm** [comment]
I'm going to assume this was resolved and I'm closing the issue. Feel free to re-open this if it is still a problem.
