### ISSUE TITLE
Keep CI pipelines up to date

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#1094]
The CI pipelines should get some much needed attention:

- [x]  remove everything related to arm added in #875, this is not needed anymore
- [x] use up-to-date node16 github actions, address all warnings
- [x] keep conda-envs up to date (see request in #1065 ), consider moving things ìn the `ci` directory to `.github`
- [x]  consider using micromamba where it makes sense to get speedup while still ensuring everything works with conda

**Comment by haasad** [comment]
> Can I close this and https://github.com/LCA-ActivityBrowser/activity-browser/issues/1065?

Not sure if the libmamba solver really fixes the initial issue that you had in #1065, but fine by me to close it.

> How does this now work in practice?

- in the pipelines we use [conda environment files](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) to set up the conda env for the tests and for the builds
  - https://github.com/LCA-ActivityBrowser/activity-browser/blob/c722b17354ee64399ff8cf53d9064e9d5d1dd8f3/.github/workflows/main.yaml#L46-L52
  - https://github.com/LCA-ActivityBrowser/activity-browser/blob/c722b17354ee64399ff8cf53d9064e9d5d1dd8f3/.github/workflows/main.yaml#L112-L117
- they contain the (additiona)l dependencies needed for testing and conda build
- for the tests we merge these dependencies with run dependencies of the conda recipe -> `patched-environment.yml`
- I removed everything else related to the environments in #1118
- I dropped the idea with the alternative installation method with `conda env create` mentioned in https://github.com/LCA-ActivityBrowser/activity-browser/issues/1065#issuecomment-1784124786
  - libmamba is the better solution and the `conda env create` method wasn't as fast as I anticipated, plus there were too many things that can go wrong

**Comment by marc-vdm** [comment]
Alright thanks a lot for the explanation!
