### ISSUE TITLE
Update readme to include conda update instructions

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1147]
>Most likely an old conda version. You can update conda with this command:
>```
>conda update -n base conda
>```
>After that the install command should run.
>
>marc-vdm IIRC there used to be a section about keeping the conda version up to date in the README, looks like that got lost somewhere along the way

_Originally posted by @haasad in https://github.com/LCA-ActivityBrowser/activity-browser/issues/1137#issuecomment-1835676976_

**Comment by marc-vdm** [comment]
Was actually already present:
https://github.com/LCA-ActivityBrowser/activity-browser#conda

**Comment by haasad** [comment]
My bad, looks like it's not just the users that don't properly read the documentation :see_no_evil:
