### ISSUE TITLE
AB crashes after importing database

### ISSUE THREAD

**Issue by jakxsor** [LCA-ActivityBrowser/activity-browser#1165]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Good morning everyone,

This is my first time using AB, and I've followed all the installation instructions. However, I'm facing an issue that seems impossible to solve: I can't download the ecoinvent database. I successfully log in, choose the 3.9.1 version, and then, after clicking 'Next,' AB simply shuts down. I tried to reinstall ab, reinstall anaconda, restart Windows, apparently there is no any solution of this problem. 
On anaconda prompt there are no errors.

Let me know if you can help me and thanks.

### Operating system

Windows 10

**Comment by marc-vdm** [comment]
Sorry to hear that.

Could you please do the following in the anaconda prompt?
- Make sure your `ab` environment is active, if it isn't do `conda activate ab`
- Do `conda list`
  - This will give a long list of libraries that Activity Browser uses, 
- Please post that list here (preferably as text, not as screenshot), that will help us figure out the solution.

**Comment by marc-vdm** [comment]
Thanks a lot for sharing! We'll get back to you once we can do more.

Some people have had a similar problem with importing ecoinvent and had better luck with older versions. You could see if it helps for you too:

You can install an older version like this: `conda create -n ab28 -c conda-forge activity-browser=2.8`

I really hope this helps for you until we have a more permanent solution.

**Comment by FreeMori** [comment]
Dear @marc-vdm,
I am also new to the party and faced the same Issues with the current installation of the AB ( `conda create -n ab -c conda-forge activity-browser` ) under BW2.

Your work around with the ab28 has seemed to work for me.
Thanks

**Comment by marc-vdm** [comment]
Happy to hear that this worked as a temporary solution for you :)

**Comment by jakxsor** [comment]
> Happy to hear that this worked as a temporary solution for you :)

For me too, thanks for now! :)

**Comment by marc-vdm** [comment]
Closing as resolved in `2.9.3`
