### ISSUE TITLE
CF tab - adding multiple biosphere flows doesn't work

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1166]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Dragging multiple biosphere flows to an IC should add all of them to the CFs
![biosphere_IC_drag](https://github.com/LCA-ActivityBrowser/activity-browser/assets/34626062/0de3eba9-75f9-44b4-81b2-2b9cb5873c90)

### Operating system

Windows 10

**Comment by mrvisscher** [comment]
Don't know when we fixed this, but somewhere along the line we did.
![Animation](https://github.com/user-attachments/assets/8d929a98-5925-47cc-86a2-a40af91b90de)
