### ISSUE TITLE
properly set dialog icons

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1173]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Dialogs don't always show AB icon, we should fix this.

### Operating system

Windows 10

**Comment by mrvisscher** [comment]
Haven't found any examples of this for a while now
