### ISSUE TITLE
Failing Dev release with multiple merges on one day

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1193]
### Issue

@haasad Sorry to bother you again. We noticed yesterday, but also just now, that the [GH action](https://github.com/LCA-ActivityBrowser/activity-browser/actions/runs/7458560081/job/20292957779) creating a `dev` release fails when a merge has already been made that day.

What seems to fail is the (confirmation of?) deletion of the existing release with current date on the [bsteubing channel](https://anaconda.org/bsteubing/activity-browser-dev/files). However, when checking this link, the file's been deleted, but the error's indicating that deleting failed because the file doesn't exist.

Yesterday both @mrvisscher and I were watching the `dev` channel online, and we're sure that the release came online after the first merge, but then was deleted through the failed action.

This problem is not super critical, as 1) the `dev` release is only used for testing by us, users don't really use it anymore 2) we can re-run the action and it will succeed as there's no file to delete. However, something doesn't seem right.

**Comment by haasad** [comment]
Could be a change in how `anaconda upload --force` works, or we just never really encountered that before. I made a PR with a proposal to change the versioning to `TAGdevX`, where TAG is the latest tag and X is the number of commits since the last tag, e.g `2.9.4dev2` or similar.

**Comment by mrvisscher** [comment]
It's not fully solved yet as @marc-vdm noticed. Right now releases with the new versioning scheme are considered to be 'older' than the 20xx.xx.xx releases because conda sorts them alphabetically. If I [understand this page](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#version-ordering) correctly we should be able to remedy this by setting an epoch using `n!` in front of the release. I'll quickly create a PR and add you as reviewer @haasad

**Comment by haasad** [comment]
another option would be to remove the `main` labels on https://anaconda.org/bsteubing/activity-browser-dev/files for all the older `2024.x` etc, then conda won't consider them unless you tell it to install that exact version IIRC

**Comment by mrvisscher** [comment]
Oh, that may be easier. That's probably something @bsteubing could try out then I guess, as it is in his account?

**Comment by haasad** [comment]
I have access with my account on anaconda.org. @bsteubing once added my as a contributor to his channel. It would probably make sense for you and @marc-vdm to also create an account there and Bernhard adding you as contributors.

I changed the label of all ABdev versions with the old versioning scheme from `main` to `outdated`.

```
conda search --override -c bsteubing activity-browser-dev
Loading channels: done
# Name                       Version           Build  Channel             
activity-browser-dev       2.9.4dev1            py_0  bsteubing           
activity-browser-dev       2.9.4dev2            py_0  bsteubing 
```
```
conda search --override -c bsteubing/label/outdated activity-browser-dev
Loading channels: done
# Name                       Version           Build  Channel             
activity-browser-dev      2019.03.22            py_0  bsteubing/label/outdated
activity-browser-dev      2019.04.08            py_0  bsteubing/label/outdated
activity-browser-dev      2019.04.12            py_0  bsteubing/label/outdated
activity-browser-dev      2019.04.15            py_0  bsteubing/label/outdated
activity-browser-dev      2019.05.15            py_0  bsteubing/label/outdated
activity-browser-dev      2019.05.16            py_0  bsteubing/label/outdated
activity-browser-dev      2019.05.17            py_0  bsteubing/label/outdated
<...>
activity-browser-dev      2023.12.13            py_0  bsteubing/label/outdated
activity-browser-dev      2023.12.17            py_0  bsteubing/label/outdated
activity-browser-dev      2023.12.20            py_0  bsteubing/label/outdated
activity-browser-dev      2023.12.21            py_0  bsteubing/label/outdated
activity-browser-dev      2023.12.22            py_0  bsteubing/label/outdated
activity-browser-dev      2024.01.08            py_0  bsteubing/label/outdated
activity-browser-dev      2024.01.09            py_0  bsteubing/label/outdated
```

**Comment by mrvisscher** [comment]
Yep, this seems to have fixed it. Fantastic, thanks again voor your insight and help @haasad!
