### ISSUE TITLE
Ab closes after 2.9.5 update

### ISSUE THREAD

**Issue by bwrals** [LCA-ActivityBrowser/activity-browser#1221]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Thank you for your great work with the ab!
FYI I just updated ab to 2.9.5 and now experience that ab just closes when I press "calculate". I used the 2.9.4 just 2 hours before and it worked just fine. 

### Operating system

Windows 10

**Comment by mrvisscher** [comment]
Hi bwrals,

That's very strange. A few questions: 

- Is there any error message in the terminal?
- Does it happen every time?
- Are you doing a scenario calculation by any chance?

Let me know!

Kind regards,

Marin

**Comment by bwrals** [comment]
Hi mrcisscher,

Thank you for your follow-up. I tried to uninstall the AB, update conda, and install AB again. That solved it:) 

Best regards,
Benedikte
