### ISSUE TITLE
Creating 2050 REMIND SSP2-base Scenario

### ISSUE THREAD

**Issue by Arezooo33** [LCA-ActivityBrowser/activity-browser#1233]
### Issue

Hi,

I installed activity browser, imported EcoInvent and then installed Scenariolink plugin. When I want to import the available scenarios, I tried  a couple of them, it has an error:
![AB](https://github.com/LCA-ActivityBrowser/activity-browser/assets/153556581/dcab5415-673f-48e0-ba2e-d3a9ea8d7d3d)
I don't know what is wrong with it. I would be happy if you could help me with it.

Best, Arezoo

**Comment by marc-vdm** [comment]
Hey Arezoo, 

There is currently an issue with ScenarioLink that doesn't install the right version of a library (https://github.com/polca/ScenarioLink/issues/35).

You can manually install the library with:
`conda install unfold=2024.02.10`

**Comment by Arezooo33** [comment]
Hey,

Thanks. I installed it on the ab environment and tried generating scenario again, it generated the scenario but it is empty and it gives me another error:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/153556581/fee70bbd-c431-44d5-beb4-c35f70407d7d)
Any ideas what's wrong?

Best, Arezoo

**Comment by marc-vdm** [comment]
Could it be that you accidentally connected the 'ecoinvent' database to another database (in your case probably 'steel' or 'bioshpere3')?

It could also be that the premise database you downloaded is supposed to connect to another version of ecoinvent (not 3.9.1).

Please review the ScenarioLink instructions to see if that resolves your issue.
https://github.com/polca/ScenarioLink?tab=readme-ov-file#reproduce-a-scenario-based-database

**Comment by Arezooo33** [comment]
I didn't notice that each scenario should be linked to a specific version of EcoInvent. My bad.
I changed the ecoinvent version and tried to import other scenarios but still the same error. 
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/153556581/a6cf9008-25b4-49a0-aa3f-738395b33672)

I'm pretty sure I'm connecting databases correctly.

**Comment by marc-vdm** [comment]
Sorry to hear you're still having issues. We've found an underlying issue that's not directly causing this, but is still causing problems with what you're trying to do and should hopefully resolve this as well.

If you wouldn't mind, can you wait for 2.9.7​? We expect to have this version available later this week. If you need a solution more urgently, please also let me know, there is a work-around, but it's a bit messy.
________________________________

**Comment by Arezooo33** [comment]
I would be happy to try it while waiting for the newer version because previously I was working with the plugin without any issues. I don't know what went wrong suddenly.

**Comment by marc-vdm** [comment]
The things that went wrong are not your fault, we've done something wrong on our side. 
What is wrong is that the biosphere database that is installed is unfortunately a wrong version, that can only be resolved through these steps:

1. Export any databases you want to keep from the project (except ecoinvent and biosphere)
   - I don't think you have any in the project you share a screenshot of, but check for yourself
2. Install an older version of activity browser, I suggest in a new environment:
   - `conda create -n ab292 -c conda-forge activity-browser=2.9.2`
3. In this newly installed version, create a new project and import biosphere
4. In your current version, import ecoinvent, databases you exported and continue as usual
5. If you wish, you can delete the problematic project.


Also note, in the screenshot you've shared, I see you've installed ecoinvent 3.8 and 3.9(.1). These versions are not compatible and should not be installed in the same project. You can install either 3.4-3.8 or 3.9 and 3.9.1 in one project. If you're working with ScenarioLink, I would suggest to take 3.9 or 3.9.1 as there are compatible with more scenario databases. 

In future versions of activity browser this will be possible, but currently this is will lead to problems. It's a longer term project for us to add this functionality.

**Comment by Arezooo33** [comment]
Hi Marc,

Unfortunately, installing older version of activity browser didn’t also help.
I was wondering if the update to activity browser has been released?

Best,
Arezoo

**Comment by Arezooo33** [comment]
Hi Marc,

It worked finally. Thanks for your assisstance.

Just a quick question, I want to generate scenario SSP1-RCP1.9 which I think it is REMIND SSP1-PkBudg500, right? Why don’t we have it in Scenariolink plugin, or it is the one and it is just a typo maybe?
***@***.***

Best,
Arezoo

**Comment by marc-vdm** [comment]
Happy this issue is resolved for you. I will close this issue now, for your last question, I hope you still get some help. In case you have new questions regarding the use of the ScenarioLink plugin, please open them on [polca/ScenarioLink](https://github.com/polca/ScenarioLink) :)

> I want to generate scenario SSP1-RCP1.9 which I think it is REMIND SSP1-PkBudg500, right? Why don’t we have it in Scenariolink plugin, or it is the one and it is just a typo maybe?

@romainsacchi would you have an idea?
