### ISSUE TITLE
Import model with previous Ecoinvent version in Activity Browser

### ISSUE THREAD

**Issue by Makgsd** [LCA-ActivityBrowser/activity-browser#1248]
### Issue

I have received a model .bw2package based on the old ecoinvent 3.8 version. At the moment I only have ecoinvent 3.9.1
When I try to import it I receive the message about database lining "some database(s) could not be found in the current project, attempt to relink the exchanges to a different database". "Database links - Ecoinvent 3.9.1". and an error message "Relinking failed", cannot relink....

Is there a way to import it?

Thank you!

**Comment by marc-vdm** [comment]
Hi,

Ecoinvent versions are unfortunately not guaranteed to be cross-compatible.

I of course haven't seen your database, so I can't know for sure, but: What I expect that is happening is that the database you're trying to link to has processes that connect either to processes in ecoinvent that have changed name/product/have been removed between the versions, or that your database links to biosphere flows that have changed name/product/have been removed between the versions.

There is unfortunately no easy way to figure this out, except manually cross-checking each exchange in your new database to the ecoinvent correspondence files to see what may be the problem.

Alternatively, you could create a new project and import ecoinvent 3.8 (requires Activity Browser 2.9.7 to get the correct version of the biosphere for this version of ecoinvent), there you can at least see your new database.

**Comment by Makgsd** [comment]
Thank you! I could open it in a new project with ecoinvent 3.8 now I'll try to figure out how I can "update" it to the ecoinvent 3.10

**Comment by marc-vdm** [comment]
Happy that this allowed you to import the database!

Note that we don't yet support ecoinvent 3.10. You can subscribe to #1163 to be notified of when we have added support.

For now, I'll close this, but feel free to open a new issue or discussion with new questions!
