### ISSUE TITLE
flow-scenarios give me different results than standard LCA without changing default

### ISSUE THREAD

**Issue by SELTENEERDEN** [LCA-ActivityBrowser/activity-browser#1259]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Hi,
I just wanted to start working with flow-scenarios on a model I did for recycling of eletronic-scrap. I click on "Export as flow-scenarios" and then click on "add scenario" in the LCA-Setup and use the exported scenario file right-away, as it is. Now I get different results, then when I am calculating the "standard-LCA" for the exact same model. Any idea why this is the case?
All the best and thanks in advance
selteerden

### Operating system

Windows 10

**Comment by mrvisscher** [comment]
Hi @SELTENEERDEN,

Any chance that there are duplicate flows in your model that are part of the scenario? This could explain the different results.

Kind regards,

Marin

**Comment by SELTENEERDEN** [comment]
Hi Marin,

I have more than once the flow of e.g. market for electricity. Or I have more than once a flow with the exact same amount on the in- and output site for instance when a process step does not change the mass but only the aggregate state of the product. What exactly do you mean by duplicate flows in my model?

thank you

**Comment by mrvisscher** [comment]
Hi @SELTENEERDEN,

I mean that you have two duplicate flows within the same activity like this:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/103424764/dc1c391a-5c02-4dfa-b3e1-99612749fd7a)

In a normal calculation these would be summed, but (right now) in a scenario calculation, the sum would be overridden by a single flow from your SDF.

**Comment by marc-vdm** [comment]
I'm closing this issue for lack of responses, feel free to re-open it again to continue the conversation.
