### ISSUE TITLE
Update to ReCiPe v1.03

### ISSUE THREAD

**Issue by F-B-M-lca** [LCA-ActivityBrowser/activity-browser#1260]
### Issue

Hi, 

I am using AB for more than a year now. I updated it and running Python 3.10 on Mac. How can I update the impact categories? E.g., I only have human toxicity as an option, not the differentiation between cancer and non-cancer.

Thank you

**Comment by mrvisscher** [comment]
Hi @F-B-M-lca,

As far as I understand, the only way to update the impact categories right now is to create a new project and install the default data. This should also install the newest IC's in that project if you're running the latest version.

I don't think there's a way right now to update them for an existing project.

Kind regards,

Marin

**Comment by marc-vdm** [comment]
I'll close this for now, feel free to re-open this if it's not solved or open a new issue for other problems.
