### ISSUE TITLE
Monte Carlo Simulation error - mu values required

### ISSUE THREAD

**Issue by BiancaWe22** [LCA-ActivityBrowser/activity-browser#1262]
### Issue

Hi,
I'm trying to perform a Monte Carlo Simulation but when I include the uncertainty of Technosphere this error message appears:
"Real location (mu) values are required for lognormal uncertainties."
Last week, I didn't have any issues with performing the MC simulation. Since that, I have only changed the uncertainty values using the pedrigree matrix, so I don't know if this is causing the problem..

I would be very thankful, if someone can help me and tell me what I need to do to provide the mu values and solve the error.

Thanks,
Bianca

**Comment by BiancaWe22** [comment]
The error was solved by selecting "no uncertainty" for the flows which have a negative value and for those which have only unit as a unit.

**Comment by marc-vdm** [comment]
Happy this was resolved, I'll close this for now.
