### ISSUE TITLE
Unable to import the database from ecoinvent to AB

### ISSUE THREAD

**Issue by nikhilsampathrao** [LCA-ActivityBrowser/activity-browser#1272]
### Issue

Hello, Iam trying to import the database from ecoinvent with my login credentials to AB.
but iam continuously an network issue error as shown below.
![AB](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/99a6a4cd-33cf-409f-9ca7-34c46bab881b)
![Activity import error](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/0eb16a9f-f50e-49a8-b174-6573fb8ae6c6)

But i am using company pc so my network connection is good also i have updated the AB and rechecked but the same issue can you please look over into this problem.

thank you,
with regards,
Nikhil.

**Comment by mrvisscher** [comment]
Hi @nikhilsampathrao,

I'm afraid I can't seem to replicate this issue. Maybe it is related to this one, where the user still needed to accept some agreement.

- https://github.com/LCA-ActivityBrowser/activity-browser/issues/1240

In any case. You should also be able to download the ecoinvent ecospold files directly from their site and import them. Make sure you download 3.9 though, as 3.10 is not yet supported for the AB.

Kind regards,

Marin

**Comment by nikhilsampathrao** [comment]
hello @mrvisscher,
I tried by using another method as you have mentioned i have downloded ecospold file from ecoquery and tried to import the data to AB but the issue is same i cannot import the database to my project. 

here i have attached the errors while importing the downlodaed file.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/cf524c4a-7ec0-40c5-a7c9-462d79605acb)
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/38f1cf05-61cb-47b5-a6e3-7d0059b3791a)
