### ISSUE TITLE
Want to change the directory path of AB 

### ISSUE THREAD

**Issue by nikhilsampathrao** [LCA-ActivityBrowser/activity-browser#1275]
![directrory](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/16cd818b-d5c9-434d-a67a-a528009a023d)
### Issue

Hello,
Iam having a trouble while importing the data in to AB.
 my AB database are saving into the my user D disk but im my office pc my D disk is full and also D disks are not saved in a backup.
Our projects must always be saved accordingly on a project drive. S drive  is there any possible way to change the directory path of AB from D to S drive. for furture use i need the data should be saved in s drive.
![disk space](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/1dfd2a1c-0eee-41ef-8e00-b37e3803697c)
![import](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/761d1ae9-32c4-4e8b-a913-2ffbb293d754)

**Comment by nikhilsampathrao** [comment]
hello here is my details directory path of both AB and brightway
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/165164812/6bfd8dde-dbe4-4eb2-a272-92e15ea7e706)

**Comment by marc-vdm** [comment]
Hi,

You can change the folder where everything is stored in the settings, like you have done in #1271, just check first if you have write access to the folder you want to change to.

**Comment by marc-vdm** [comment]
I'll close this assuming your problem was resolved. If it wasn't, feel free to open this thread again!
