### ISSUE TITLE
Conda package resolution, broken AB conda installs

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#128]
Peewee recently released a new version, which has breaking changes for brightway2. This breaks conda installs for the AB. See detailed description here: https://github.com/cmutel/conda-recipes/issues/3

Currently all installs for all version of the AB are broken, ie it's not possible to install the activity browser without manually specifying the correct version numbers for brightway2 and/or peewee.

**Comment by haasad** [comment]
@bsteubing, is it okay for you if I "fix" this and also bump the AB version? Ie do you think we're at a point where we can release a new stable version?
Otherwise I need to rebuild the the current version with a new conda recipe which could be a mess.

**Comment by haasad** [comment]
In theory we could also pin peewee, but this would break again if brightway2 were to be updated to work with peewee 3. I already pinned brightway to >= 2.1.2 in #129.

I can't really show you the direct effect of the pinning because there was a second unrelated problem with pytest that broke the CI tests. But see eg [this build](https://travis-ci.org/LCA-ActivityBrowser/activity-browser/jobs/359877055) for failure due to peewee 3.1.5 and [the recent master build](https://travis-ci.org/LCA-ActivityBrowser/activity-browser/jobs/359988567) where brightway is pinned and therefore peewee is kept below 3.

The problem that now remains is the "official" version of the AB on the conda channel. The pinning will only take effect for new builds, which means `conda install activity-browser` is currently still broken until it's rebuilt with the new recipe. But the recipe is also part of the repo and version 2.2.2 is tagged as a specific state of the repo at that time. Therefore I feel it would be cleaner to fix this with a new version, ie 2.2.3 right away. The other option is that I rebuild the repo state at 2.2.2 with an updated recipe, without putting it on github. But I'd prefer the first option.

**Comment by bsteubing** [comment]
Fine for me to move one version ahead to 2.2.3! Thanks for having looked into this!

**Comment by cmutel** [comment]
I wouldn't call this dependency hell, as it is easily resolved. Pinning against specific versions is not all that controversial, and is even recommended as best practice by some. I have started the process of adapting to the changes in peewee 3.0, but it is a bit harder than I thought, so it will take a few days.

**Comment by haasad** [comment]
What really bothered me is this:
```
conda install activity-browser
Solving environment: \ 
Warning: 2 possible package resolutions (only showing differing packages):
  - cmutel::brightway2-2.1.2-py_0, conda-forge::peewee-2.10.2-py36_0
  - cmutel::brightway2-2.1.1-py_1, conda-forge::peewee-3.1.5-py36done
```
- You pinned bw, so now there are two possible package resolutions (makes sense to me)
- even though peewee is a dependency of bw, conda decided go give priority to the second option here where the breaking changes are
- this means that pinning only had the desired effect for direct install of brightway, but messes up when bw is a dependecy
- I feel like bw should be higher in the hierarchy for the package resolution, since peewee is a dep of bw
- In this case, your pinning was essentially __ignored__ and the breaking changes kind of propagate to all projects where brightway2 is a dependency

**Comment by cmutel** [comment]
Fair enough. I removed Brightway < 2.1.2 from conda.org, so at least that problem should go away...

**Comment by haasad** [comment]
Ok, that's great! I think removing `Brightway < 2.1.2` is the only option that you have to completely solve this on your end.
And just so we don't have a misunderstanding here: I didn't want to imply in any way that this was your fault or a problem of brightway (bad issue title). I think this is unexpected behavior of conda, ie. the package resolution should respect when you pin the version of a dependency further down in the dependency tree.

**Comment by cmutel** [comment]
On 3 April 2018 at 13:48, haasad <notifications@github.com> wrote:
>
> And just so we don't have a misunderstanding here: I didn't want to imply
> in any way that this was your fault or a problem of brightway (bad issue
> title).
>
No worries! I think you were right - I didn't realize it would give you a
choice and default to the older version. So this was at least a mini-hell :)
