### ISSUE TITLE
Installing activity browser

### ISSUE THREAD

**Issue by MMahdi97** [LCA-ActivityBrowser/activity-browser#1288]
### Issue

Hi. Could someone please help me to solve it?

I tried to install AB, and I followed the steps. 
First, I created the ab environment in Anaconda with the following code:
1- conda config --prepend channels conda-forge
2- conda create -n ab -c conda-forge activity-browser
and then I activated the ab environment
But when I want to run Activity Browser by this code: activity-browser, I will get an error that says ModuleNotFoundError: No module named 'platformdirs'.

you can see in this picture
![Screenshot 2024-05-16 184748](https://github.com/LCA-ActivityBrowser/activity-browser/assets/170021288/baebb28c-808a-45ce-a563-096f9fba11d0)

**Comment by marc-vdm** [comment]
Hi, 

Is this still an issue for you? I saw an issue from you on the ScenarioLink page. If this is solved, please close the issue so we know the status!

Thanks
