### ISSUE TITLE
Recycling modelling in AB

### ISSUE THREAD

**Issue by nikhilsampathrao** [LCA-ActivityBrowser/activity-browser#1292]
### Issue

Hello,

Iam working on a recycling modelling in LCA with the different approaches. I have a query can we model the multiple product outputs in AB using different allocation approaches.  as done in the simapro or other software.

**Comment by mrvisscher** [comment]
Hi @nikhilsampathrao,

Although we want to support this in the (near) future, it is currently not possible to model multifunctional processes like these in the AB. However there is a work around as proposed in this discussion: 

- https://github.com/LCA-ActivityBrowser/activity-browser/discussions/996

Kind regards,

Marin

_Closing this issue as duplicate_
