### ISSUE TITLE
Getting an error while using SSPs based on consequential model

### ISSUE THREAD

**Issue by Baharferei** [LCA-ActivityBrowser/activity-browser#1295]
### Issue

Hello
I have been using SSP1 and SSP2 databases for my work (and everything was fine), which were created based on consequential model. Now I am getting multiple errors. Here I attached the error. Could you please let me know how to solve it? Thank you
![1](https://github.com/LCA-ActivityBrowser/activity-browser/assets/166905777/f3626d12-b145-4537-b56a-ca3449b1dfcb)

**Comment by marc-vdm** [comment]
Hi @Baharferei,

I think you reached out over email to us about this already. You're best off asking your question on the [Premise github page](https://github.com/polca/premise), we can only help with Activity Browser problems.

I'll close this for now. If you still need help with other problems related to Activity Browser, feel free to open a new issue or discussion!
