### ISSUE TITLE
Migrate to `bw_graph_tools`

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#1302]
### Feature request

The new library is 2.5 compliant, makes fewer assumptions (meaning better support for multifunctionality or process/product splits), and is actually tested: https://github.com/brightway-lca/bw_graph_tools.

The previous [code was here](https://github.com/brightway-lca/brightway2-calc/blob/bw2legacy/bw2calc/graph_traversal.py), and returned a [less-than-friendly result object](https://github.com/brightway-lca/brightway2-calc/blob/bw2legacy/bw2calc/graph_traversal.py#L60).

The new code returns dataclasses which are [at least explained](https://github.com/brightway-lca/bw_graph_tools/blob/main/bw_graph_tools/graph_traversal.py#L53).

The new code also returns elementary flows, which was considered an improvement in #844.

**Comment by cmutel** [comment]
Migration would need to happen anywhere `NewNodeEachVisitGraphTraversal` is used; can start with `sankey_navigator.py`.

**Comment by marc-vdm** [comment]
Closing as taken over by Cauldron
