### ISSUE TITLE
Import database

### ISSUE THREAD

**Issue by mwinome** [LCA-ActivityBrowser/activity-browser#1321]
### Issue

I  have been trying to download the ecoinvent database zip file but it is not successful.
<img width="956" alt="activity browser" src="https://github.com/LCA-ActivityBrowser/activity-browser/assets/175016362/4cd32e4b-f549-422a-a9ea-7291290e6c1e">

**Comment by mrvisscher** [comment]
Hi @mwinome,

Do you get an error in the terminal when you try to import? That would be very helpful for us to help solve your issue.

Kind regards,

Marin

**Comment by mwinome** [comment]
Yes i do. I have attached a screenshot of the terminal. Thank you
<img width="934" alt="error" src="https://github.com/LCA-ActivityBrowser/activity-browser/assets/175016362/9da6bc49-9830-4c13-bfe8-bf9b450b2dbf">

**Comment by mrvisscher** [comment]
Hi @mwinome,

I'm afraid you've found a bug. Looks like the current ecospold .7z importer has broken with the latest update. We will fix it in the next patch, which leaves you with a few options:

- Extract/unpack the downloaded file yourself, choose the **Local directory with ecospold2 files** option in the importer wizard, and point it to the `datasets` folder of the archive you've just unpacked.
-  Install ecoinvent through the downloader bundled by Activity Browser
- Wait until the patch for this has been released

Kind regards,

Marin

**Comment by mwinome** [comment]
Hi Marin,

i already tried the first option and it didn’t work. 
Also when would the patch for this be released?

Regards
Renata

**Comment by mrvisscher** [comment]
Hi Renata,

This could take a while as we're heading into the summer holidays. Why did the first option not work, did you get an error?

Kind regards,

Marin

**Comment by mwinome** [comment]
My bad. The first option worked. At first, I imported the entire unzipped file, and that did not work. But after I did the right thing, it works now. I have a question, though: do I have to import the other files in the unzipped file, and without them, is the functionality of the database diminished in any way?

Thank you very much for your help

Regards,
Renata

**Comment by mrvisscher** [comment]
No probs, happy to hear this is a valid workaround for now.

Don't worry about the integrity of the database. The import process is identical down the line, only you've now extracted the database yourself where it should have happened automatically. 

Kind regards,

Marin

**Comment by mrvisscher** [comment]
Reopen until we've patched the bug
