### ISSUE TITLE
FileNotFoundError 

### ISSUE THREAD

**Issue by Saumyasadhu** [LCA-ActivityBrowser/activity-browser#1332]
### Feature request

I am using AB with scenario link. However, I'm unable to run the LCA because of this error:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\sadhu\AppData\Local\pylca\Brightway3\Voestalpine-LCA.889fc13890ed2c08af37068074f64c63\processed\remind-SSP2-Base-2050.9974b9866154c2f5a8d4f059092fdf53.npy'

Could you tell me what to do about this?
Thanks!

**Comment by mrvisscher** [comment]
Hi @Saumyasadhu,

Looks to me like your database hasn't been processed properly yet. Something that should happen automatically, so it's weird that you encounter this problem.

Technically this is most probably a brightway2 issue, but let's see if I can help you out anyways. We'll be using some Python commands to force the database to be processed. In your terminal do the following

`conda activate ab`
`python`
`import bw2data as bd`
`bd.projects.set_current("Voestalpine-LCA") # Project name from the error, please change if not correct`
`bd.databases.set_dirty("remind-SSP2-Base-2050") # DB name from the error, please change if not correct`
`bd.Database("remind-SSP2-Base-2050").process()`

Let me know how that goes!

Kind regards,

Marin

**Comment by Saumyasadhu** [comment]
That worked well! Thanks a lot :)

**Comment by mrvisscher** [comment]
Fantastic! Glad to have helped you out :)
