### ISSUE TITLE
Stuck when importing ecoinvent 3.9

### ISSUE THREAD

**Issue by KellyC-IBP** [LCA-ActivityBrowser/activity-browser#1340]
### Issue

Hi,
I am trying to import ecoinvent 3.9 into activity browser, My database is downloaded on my computer, it is unyipped and I have made sure that I chose the 'datasets' folder. It was running smoothly at the extracting XML data step. But now it is stuck at 40% of Applying brightway2 strategies for over 30 minutes. Does it just take a longer time and should I just wait? No error message popped up so far, except for the file not found error in anaconda prompt window, how can I check if it is stuck?

Here are the screenshots, hope it helps clarify my problem
![image](https://github.com/user-attachments/assets/48e276a4-af9c-4e1e-8e5e-c1dcc3f721c1)
![image](https://github.com/user-attachments/assets/1e553d1f-bed3-4fe1-879f-7693672ea6eb)

thank you

**Comment by mrvisscher** [comment]
Hi @KellyC-IBP,

Looks to me like the migrations for your project haven't been created. How did you set-up your project?

In any case, the following commands should hopefully resolve your issue

`conda activate ab`
`python`
`import bw2io as bi`
`import bw2data as bd`
`bd.projects.set_current("EAF_avgSteel") #  project name from error, please change if needed`
`bi.create_core_migrations()`

Kind regards,

Marin

**Comment by KellyC-IBP** [comment]
Hi Marin,
thank you for your reply, it works now!

**Comment by marc-vdm** [comment]
Hi @KellyC-IBP 

This has been fixed for the __next__ version of Activity Browser.

To resolve this in _existing_ projects with the new version: 
- Go to the menu `Project` in the top left
- Click `Migrations`
- Choose `Install default migrations`

To resolve this in _new_ projects with the new version:
- No action needed, Migrations will be installed automatically when you install ecoinvent

A bot will comment here later to inform you when the newest version of Activity Browser has been released!
