### ISSUE TITLE
Scenario Link

### ISSUE THREAD

**Issue by Waqar786786** [LCA-ActivityBrowser/activity-browser#1343]
### Feature request

I have installed it but it is not showing on the Activity browser. I have already follow the steps by going on tools and confirmed the plug-in. I will attach the picture with it. 
![1](https://github.com/user-attachments/assets/3060c75b-09e0-41ac-b71b-f8844d471d9e)

**Comment by marc-vdm** [comment]
Hi, it seems you are using Activity Browser `2.10.x`, Scenario Link is not yet compatible with Activity Browser `2.10.x`. If you want, you can subscribe to https://github.com/polca/ScenarioLink/issues/42 (button on the right) to be notified when Scenario Link is compatible with Activity Browser again.

**Comment by marc-vdm** [comment]
I will close this as it's a Scenario Link issue, not an Activity Browser one
