### ISSUE TITLE
Update conda-forge dependencies

### ISSUE THREAD

**Issue by mrvisscher** [LCA-ActivityBrowser/activity-browser#1366]
### Updating AB

- [ ] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Update the conda-forge dependencies to release the SALib pin because they've fixed their dependencies upstream.

### Operating system

Windows 10

**Comment by marc-vdm** [comment]
Completed in https://github.com/conda-forge/activity-browser-feedstock/pull/40/commits/41b1ca864ad6238c1ff44cb71b64740288ddf191
