### ISSUE TITLE
darkmode compatibility

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1375]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

@jakobsarthur @romainsacchi @timodiepers FYI 

You will get a reply here from a bot when the new version of Activity Browser is available for download 

In the settings menu you will be able to set `dark mode compatibility` and restart activity browser and it will work with darkmode. Note that this is not real darkmode, we just fix the text color. 'Real' darkmode will come some day.

Resolved in #1374

### Operating system

Windows 10

**Comment by jakobsarthur** [comment]
Hi @marc-vdm, 

I just updated the AB to 2.10.3, and tried out the dark-mode compatibility (MacOS 14.6) with the following result...: 
<img width="1864" alt="Screenshot 2024-10-07 at 15 34 04" src="https://github.com/user-attachments/assets/cf07bcfa-cb31-45ba-a4fb-4d697e3fdc76">

**Comment by mrvisscher** [comment]
Hi @jakobsarthur,

That doesn't look quite right just yet. Did you restart the AB after you toggled the option in the settings menu?

Kind regards,

Marin

**Comment by jakobsarthur** [comment]
hi @mrvisscher: tried that too: Install, activate DM, launch and it looks like that. I can still switch to light mode and back and everything will switch, except the text in left two panels.

**Comment by marc-vdm** [comment]
You shouldn't need to change anything in MacOS, just keep it on Dark Mode then in AB do the following:
1. Start AB
2. Go to top left `Project` > `Settings` > `Theme`, set theme to `Dark theme compatibility`
3. Close and re-open Activity Browser

**Comment by jakobsarthur** [comment]
ah ok that does the trick indeed! Awesome! Thanks again for adding this!

**Comment by jakobsarthur** [comment]
![image](https://github.com/user-attachments/assets/d9364629-ecf6-475a-827a-c14917a5330d)
