### ISSUE TITLE
AB not launching using `activity-browser` command

### ISSUE THREAD

**Issue by mrvisscher** [LCA-ActivityBrowser/activity-browser#1378]
### Updating AB

- [ ] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Hi, I installed a new Ab using the instructions above, but when I want to open Ab, it does nothing and remains only in the environment. Could you please tell how to solve the issue.?

![image](https://github.com/user-attachments/assets/cee7cae3-6d1f-4447-a24d-596e62064dd6)

### Relevant errors

```python
None
```

### Operating system

Windows 10

### Conda environment

```shell
ctivity-browser 2.10.2 pyhd8ed1ab_1 conda-forge
annotated-types 0.7.0 pyhd8ed1ab_0 conda-forge
appdirs 1.4.4 pyh9f0ad1d_0 conda-forge
arrow 1.3.0 pyhd8ed1ab_0 conda-forge
asteval 1.0.4 pyhd8ed1ab_0 conda-forge
astunparse 1.6.3 pyhd8ed1ab_0 conda-forge
blinker 1.8.2 pyhd8ed1ab_0 conda-forge
brightway2 2.4.6 pyhd8ed1ab_0 conda-forge
brotli 1.1.0 h2466b09_2 conda-forge
brotli-bin 1.1.0 h2466b09_2 conda-forge
brotli-python 1.1.0 py311hda3d55a_2 conda-forge
brotlicffi 1.1.0.0 py311hda3d55a_2 conda-forge
bw2analyzer 0.10 pyhd8ed1ab_0 conda-forge
bw2calc 1.8.2 py311h1ea47a8_0 conda-forge
bw2data 3.6.6 pyhd8ed1ab_0 conda-forge
bw2io 0.8.12 pyhd8ed1ab_0 conda-forge
bw2parameters 1.1.0 pyhd8ed1ab_0 conda-forge
bw_migrations 0.2 pyhd8ed1ab_0 conda-forge
bzip2 1.0.8 h2466b09_7 conda-forge
ca-certificates 2024.8.30 h56e8100_0 conda-forge
certifi 2024.8.30 pyhd8ed1ab_0 conda-forge
cffi 1.17.1 py311he736701_0 conda-forge
charset-normalizer 3.3.2 pyhd8ed1ab_0 conda-forge
click 8.1.7 win_pyh7428d3b_0 conda-forge
colorama 0.4.6 pyhd8ed1ab_0 conda-forge
contourpy 1.3.0 py311h3257749_2 conda-forge
cycler 0.12.1 pyhd8ed1ab_0 conda-forge
dill 0.3.8 pyhd8ed1ab_0 conda-forge
docopt 0.6.2 py_1 conda-forge
ecoinvent_interface 2.4.1 pyhd8ed1ab_0 conda-forge
eight 1.0.1 pyhd8ed1ab_4 conda-forge
et_xmlfile 1.1.0 pyhd8ed1ab_0 conda-forge
fasteners 0.17.3 pyhd8ed1ab_0 conda-forge
flask 3.0.3 pyhd8ed1ab_0 conda-forge
fonttools 4.54.1 py311he736701_0 conda-forge
freetype 2.12.1 hdaf720e_2 conda-forge
future 1.0.0 pyhd8ed1ab_0 conda-forge
glib 2.80.5 h7025463_0 conda-forge
glib-tools 2.80.5 h4394cf3_0 conda-forge
gst-plugins-base 1.24.7 hb0a98b8_0 conda-forge
gstreamer 1.24.7 h5006eae_0 conda-forge
h2 4.1.0 pyhd8ed1ab_0 conda-forge
hpack 4.0.0 pyh9f0ad1d_0 conda-forge
hyperframe 6.0.1 pyhd8ed1ab_0 conda-forge
icu 75.1 he0c23c2_0 conda-forge
idna 3.10 pyhd8ed1ab_0 conda-forge
importlib-metadata 8.5.0 pyha770c72_0 conda-forge
importlib_metadata 8.5.0 hd8ed1ab_0 conda-forge
inflate64 1.0.0 py311he736701_2 conda-forge
intel-openmp 2024.2.1 h57928b3_1083 conda-forge
itsdangerous 2.2.0 pyhd8ed1ab_0 conda-forge
jinja2 3.1.4 pyhd8ed1ab_0 conda-forge
kiwisolver 1.4.7 py311h3257749_0 conda-forge
krb5 1.21.3 hdf4eb48_0 conda-forge
lcms2 2.16 h67d730c_0 conda-forge
lerc 4.0.0 h63175ca_0 conda-forge
libblas 3.9.0 24_win64_mkl conda-forge
libbrotlicommon 1.1.0 h2466b09_2 conda-forge
libbrotlidec 1.1.0 h2466b09_2 conda-forge
libbrotlienc 1.1.0 h2466b09_2 conda-forge
libcblas 3.9.0 24_win64_mkl conda-forge
libclang13 19.1.0 default_ha5278ca_0 conda-forge
libdeflate 1.21 h2466b09_0 conda-forge
libexpat 2.6.3 he0c23c2_0 conda-forge
libffi 3.4.2 h8ffe710_5 conda-forge
libglib 2.80.5 h7025463_0 conda-forge
libhwloc 2.11.1 default_h8125262_1000 conda-forge
libiconv 1.17 hcfcfb64_2 conda-forge
libintl 0.22.5 h5728263_3 conda-forge
libintl-devel 0.22.5 h5728263_3 conda-forge
libjpeg-turbo 3.0.0 hcfcfb64_1 conda-forge
liblapack 3.9.0 24_win64_mkl conda-forge
libogg 1.3.5 h2466b09_0 conda-forge
libpng 1.6.44 h3ca93ac_0 conda-forge
libsqlite 3.46.1 h2466b09_0 conda-forge
libtiff 4.7.0 hb151862_0 conda-forge
libvorbis 1.3.7 h0e60522_0 conda-forge
libwebp 1.4.0 h2466b09_0 conda-forge
libwebp-base 1.4.0 hcfcfb64_0 conda-forge
libxcb 1.16 h013a479_1 conda-forge
libxml2 2.12.7 h0f24e4e_4 conda-forge
libxslt 1.1.39 h3df6e99_0 conda-forge
libzlib 1.3.1 h2466b09_1 conda-forge
lxml 4.9.3 py311h750ae06_3 conda-forge
lxmlh 1.3.3 pyhd8ed1ab_0 conda-forge
m2w64-gcc-libgfortran 5.3.0 6 conda-forge
m2w64-gcc-libs 5.3.0 7 conda-forge
m2w64-gcc-libs-core 5.3.0 7 conda-forge
m2w64-gmp 6.1.0 2 conda-forge
m2w64-libwinpthread-git 5.0.0.4634.697f757 2 conda-forge
markupsafe 2.1.5 py311he736701_1 conda-forge
matplotlib-base 3.9.2 py311h8f1b1e4_1 conda-forge
mkl 2024.1.0 h66d3029_694 conda-forge
mrio_common_metadata 0.2.1 pyhd8ed1ab_0 conda-forge
msys2-conda-epoch 20160418 1 conda-forge
multiprocess 0.70.16 py311he736701_1 conda-forge
multivolumefile 0.2.3 pyhd8ed1ab_0 conda-forge
munkres 1.1.4 pyh9f0ad1d_0 conda-forge
networkx 3.3 pyhd8ed1ab_1 conda-forge
numpy 1.26.4 py311h0b4df5a_0 conda-forge
openjpeg 2.5.2 h3d672ee_0 conda-forge
openpyxl 3.1.5 py311ha68e1ae_1 conda-forge
openssl 3.3.2 h2466b09_0 conda-forge
packaging 24.1 pyhd8ed1ab_0 conda-forge
pandas 2.2.3 py311hcf9f919_1 conda-forge
pathos 0.3.2 pyhd8ed1ab_1 conda-forge
patsy 0.5.6 pyhd8ed1ab_0 conda-forge
pcre2 10.44 h3d7b363_2 conda-forge
peewee 3.17.6 py311h1eea93c_1 conda-forge
pillow 10.4.0 py311h5592be9_1 conda-forge
pint 0.21 pyhd8ed1ab_0 conda-forge
pip 24.2 pyh8b19718_1 conda-forge
platformdirs 4.3.6 pyhd8ed1ab_0 conda-forge
pox 0.3.4 pyhd8ed1ab_0 conda-forge
ppft 1.7.6.8 pyhd8ed1ab_0 conda-forge
psutil 6.0.0 py311he736701_1 conda-forge
pthread-stubs 0.4 hcd874cb_1001 conda-forge
pthreads-win32 2.9.1 hfa6e2cd_3 conda-forge
py7zr 0.22.0 pyhd8ed1ab_0 conda-forge
pybcj 1.0.2 py311he736701_1 conda-forge
pycasreg 0.1.0 pyhd8ed1ab_0 conda-forge
pycparser 2.22 pyhd8ed1ab_0 conda-forge
pycryptodomex 3.20.0 py311he736701_1 conda-forge
pydantic 2.9.2 pyhd8ed1ab_0 conda-forge
pydantic-core 2.23.4 py311h533ab2d_0 conda-forge
pydantic-settings 2.5.2 pyhd8ed1ab_0 conda-forge
pyecospold 3.5.3 pyhd8ed1ab_0 conda-forge
pypardiso 0.4.6 pyhd8ed1ab_0 conda-forge
pyparsing 3.1.4 pyhd8ed1ab_0 conda-forge
pyperclip 1.9.0 pyh7428d3b_0 conda-forge
pyppmd 1.1.0 py311hda3d55a_1 conda-forge
pyprind 2.11.2 py311h1ea47a8_1006 conda-forge
pyside2 5.15.8 py311h3d699ce_4 conda-forge
pysocks 1.7.1 pyh0701188_6 conda-forge
python 3.11.10 hce54a09_1_cpython conda-forge
python-dateutil 2.9.0 pyhd8ed1ab_0 conda-forge
python-dotenv 1.0.1 pyhd8ed1ab_0 conda-forge
python-tzdata 2024.2 pyhd8ed1ab_0 conda-forge
python_abi 3.11 5_cp311 conda-forge
pytz 2024.1 pyhd8ed1ab_0 conda-forge
pyxlsb 1.0.10 pyhd8ed1ab_0 conda-forge
pyzstd 0.16.1 py311h53056dc_1 conda-forge
qhull 2020.2 hc790b64_5 conda-forge
qt-main 5.15.8 h264fbc2_26 conda-forge
qt-webengine 5.15.8 h4bf5c4e_4 conda-forge
requests 2.32.3 pyhd8ed1ab_0 conda-forge
salib 1.5.0 pyhd8ed1ab_0 conda-forge
scipy 1.14.1 py311hd4686c6_0 conda-forge
seaborn 0.13.2 hd8ed1ab_2 conda-forge
seaborn-base 0.13.2 pyhd8ed1ab_2 conda-forge
setuptools 75.1.0 pyhd8ed1ab_0 conda-forge
setuptools-scm 8.1.0 pyhd8ed1ab_0 conda-forge
six 1.16.0 pyh6c4a22f_0 conda-forge
stats_arrays 0.7 pyhd8ed1ab_0 conda-forge
statsmodels 0.14.3 py311h0a17f05_1 conda-forge
tabulate 0.9.0 pyhd8ed1ab_1 conda-forge
tbb 2021.13.0 hc790b64_0 conda-forge
texttable 1.7.0 pyhd8ed1ab_0 conda-forge
tk 8.6.13 h5226925_1 conda-forge
tomli 2.0.1 pyhd8ed1ab_0 conda-forge
tqdm 4.66.5 pyhd8ed1ab_0 conda-forge
types-python-dateutil 2.9.0.20240906 pyhd8ed1ab_0 conda-forge
typing-extensions 4.12.2 hd8ed1ab_0 conda-forge
typing_extensions 4.12.2 pyha770c72_0 conda-forge
tzdata 2024a h8827d51_1 conda-forge
ucrt 10.0.22621.0 h57928b3_0 conda-forge
unicodecsv 0.14.1 pyhd8ed1ab_2 conda-forge
unidecode 1.3.8 pyhd8ed1ab_0 conda-forge
urllib3 2.2.3 pyhd8ed1ab_0 conda-forge
vc 14.3 h8a93ad2_21 conda-forge
vc14_runtime 14.40.33810 ha82c5b3_21 conda-forge
voluptuous 0.15.2 pyhd8ed1ab_1 conda-forge
vs2015_runtime 14.40.33810 h3bf8584_21 conda-forge
werkzeug 3.0.4 pyhd8ed1ab_0 conda-forge
wheel 0.44.0 pyhd8ed1ab_0 conda-forge
whoosh 2.7.4 py311h1ea47a8_9 conda-forge
win_inet_pton 1.1.0 pyhd8ed1ab_6 conda-forge
wrapt 1.16.0 py311he736701_1 conda-forge
xlrd 2.0.1 pyhd8ed1ab_3 conda-forge
xlsxwriter 3.2.0 pyhd8ed1ab_0 conda-forge
xorg-kbproto 1.0.7 hcd874cb_1002 conda-forge
xorg-libx11 1.8.9 h0076a8d_1 conda-forge
xorg-libxau 1.0.11 hcd874cb_0 conda-forge
xorg-libxdmcp 1.1.3 hcd874cb_0 conda-forge
xorg-xextproto 7.3.0 hcd874cb_1003 conda-forge
xorg-xproto 7.0.31 hcd874cb_1007 conda-forge
xz 5.2.6 h8d14728_0 conda-forge
zipfile-deflate64 0.2.0 py311ha68e1ae_4 conda-forge
zipp 3.20.2 pyhd8ed1ab_0 conda-forge
zstandard 0.23.0 py311h53056dc_1 conda-forge
zstd 1.5.6 h0ea2cb4_0 conda-forge
```

**Comment by mrvisscher** [comment]
@zeeshankhan2

What happens if you try the following commands:
`conda activate ab`
`python`
`from activity_browser import run_activity_browser`
`run_activity_browser()`

**Comment by zeeshankhan2** [comment]
It is same just goes back to the environment and not open Ab
![image](https://github.com/user-attachments/assets/8b1477db-a9d3-41ba-8555-5017a0e356a5)

**Comment by mrvisscher** [comment]
Well, this stumped me. Python just closes without any warning at all. Maybe you could try reinstalling using the following commands:
`conda deactivate`
`conda create -n ab --solver libmamba -c conda-forge activity-browser`

**Comment by zeeshankhan2** [comment]
I reinstalled it using the above, and the same problem still exists. Actually previous I also used the same code to install it.

**Comment by mrvisscher** [comment]
Honestly, I'm at a bit of a loss. Without any error message of indication that something has gone wrong, this will be very difficult to troubleshoot. Let's try importing the different libraries piece by piece to see where it breaks.

`conda activate ab`
`python`
`import sys`
`import numpy`
`import pandas`
`import bw2data`
`import bw2io`
`import brightway2`
`import PySide2`
`import activity_browser`

**Comment by zeeshankhan2** [comment]
I agree, it is confusing as i didn't face such problem previously.
after doing all works but import activitiy-browser doensot and show below.
![image](https://github.com/user-attachments/assets/82d77025-b02f-4ca5-9160-70e926d2a38d)

**Comment by zeeshankhan2** [comment]
Can i degrade it to previous versions if yes can you please share the code.? to see if previous version works or had the same issue?

**Comment by zeeshankhan2** [comment]
With this version some file is i think not downloaded. could that be the case with the new version as well?
![image](https://github.com/user-attachments/assets/b208d2a5-c114-43a8-a718-6d8f2d7ff3ca)

**Comment by zeeshankhan2** [comment]
I degraded to V2.9.7 and again the same issue does not open after activity-browser

**Comment by mrvisscher** [comment]
You may try cleaning the package cache before installing, or reinstalling Conda in it's entirety?

**Comment by zeeshankhan2** [comment]
Reinstalled Anaconda, cleared the cache with conda clean --all and then reinstalled Ab using the above code. Unfortunately, the same problem exist. After I type activity-browser it starts process and then do nothing and just show the ab environment again.

**Comment by mrvisscher** [comment]
Worth the try. Something else that may be worth the try is downgrading the python version:

`conda create -n ab-py310 -c conda-forge --solver libmamba activity-browser python=3.10`

**Comment by zeeshankhan2** [comment]
I did that and now the following error
(base) C:\Users\go25vaq>conda activate ab

(ab) C:\Users\go25vaq>python --version
Python 3.10.14

(ab) C:\Users\go25vaq>activity-browser
Traceback (most recent call last):
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\scipy\__init__.py", line 86, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 205, in init scipy._lib._ccallback_c
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\Scripts\activity-browser-script.py", line 5, in <module>
    from activity_browser import run_activity_browser
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\activity_browser\__init__.py", line 7, in <module>
    from .mod import bw2data
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\activity_browser\mod\__init__.py", line 1, in <module>
    import activity_browser.mod.bw2data as bw2data
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\activity_browser\mod\bw2data\__init__.py", line 1, in <module>
    import bw2data.errors as errors
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\bw2data\__init__.py", line 33, in <module>
    from .project import projects
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\bw2data\project.py", line 9, in <module>
    from .utils import python_2_unicode_compatible
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\bw2data\utils.py", line 18, in <module>
    import stats_arrays as sa
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\stats_arrays\__init__.py", line 33, in <module>
    from .distributions import (
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\stats_arrays\distributions\__init__.py", line 21, in <module>
    from .beta import BetaUncertainty
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\stats_arrays\distributions\beta.py", line 4, in <module>
    from scipy import stats
  File "C:\Users\go25vaq\AppData\Local\anaconda3\envs\ab\lib\site-packages\scipy\__init__.py", line 91, in <module>
    raise ImportError(msg) from e
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.

(ab) C:\Users\go25vaq>

**Comment by mrvisscher** [comment]
What is your scipy version and build now?
`conda list scipy`

**Comment by zeeshankhan2** [comment]
scipy                     1.14.1          py310h46043a1_0    conda-forge

**Comment by zeeshankhan2** [comment]
# Name                    Version                   Build  Channel
scipy                     1.14.1          py310h46043a1_0    conda-forge

**Comment by mrvisscher** [comment]
Obviously something is messing up your Conda environment installations. Do you have other environments in your Conda install? If not it may be worth going to the anaconda folder and just removing both the `envs` and `packages` folder... I'm not sure they were cleaned up during your reinstall

**Comment by zeeshankhan2** [comment]
Yes, i agree. I deleted these folders, installed again AB and have same issue. By any chance is there a possibility of an online meeting next to see the issue and somehow run my Ab so that I can start my work. I will meanwhile try ofcourse if I can fix it somehow.

**Comment by mrvisscher** [comment]
E-mail met at m.r.visscher@cml.leidenuniv.nl so we can make an appointment

**Comment by zeeshankhan2** [comment]
done

**Comment by zeeshankhan2** [comment]
Hi @mrvisscher 
Surprisingly, Ab has started working for me now. I followed the steps: completely uninstalling Anaconda --> installing Miniconda3--> installing Ab env.
Thanks for your kind support.

**Comment by mrvisscher** [comment]
Happy that the issue has been resolved for you!
