### ISSUE TITLE
Error: "LCA failed"

### ISSUE THREAD

**Issue by sannawi** [LCA-ActivityBrowser/activity-browser#1391]
### Issue

Hi,

I have installed a few Premise databases into one of my AB projects, and I calculated climate impacts for a random process in one of the Premise databases. All worked fine. But suddenly, when I tried to calculate climate impacts for one of my processes, which is linked to the Premise database, I got an error saying "LCA failed". And now I get the same error for processes within the Premise database, as well as for my "normal" eco invent 3.10-database. Could you help me resolve this issue? I attach two pictures: one on the error message and one on the Anaconda prompt.

Thanks in advance!
Best regards,
Sanna

![20241008_140727](https://github.com/user-attachments/assets/0a6ef582-80a6-4ac3-bd99-434f66b14fc1)
![20241008_140739](https://github.com/user-attachments/assets/39ec95a5-5ac7-461f-aac4-5f9028f5bfec)

**Comment by mrvisscher** [comment]
It looks to me like your database can't process because keys within the database are missing from the Brightway mapping metadata. Did you use Premise or ScenarioLink to create the databases in question?

**Comment by sannawi** [comment]
Hi,
I used Premise.

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mrvisscher** [comment]
You can try the following method to get all your keys into the mapping. Please make a backup of your project first.

```
import bw2data as bd
bd.projects.set_current("PROJECT NAME HERE")

bd.mapping.add([act.key for name in bd.databases for act in bd.Database(name)])

````

**Comment by sannawi** [comment]
It seems like your solution worked, thank you so much!

/Sanna

From: Marin Visscher ***@***.***>
Date: Tuesday, 8 October 2024 at 15:26
To: LCA-ActivityBrowser/activity-browser ***@***.***>
Cc: Sanna Wickerts ***@***.***>, Author ***@***.***>
Subject: Re: [LCA-ActivityBrowser/activity-browser] Error: "LCA failed" (Issue #1391)

You can try the following method to get all your keys into the mapping. Please make a backup of your project first.

import bw2data as bd

bd.projects.set_current("PROJECT NAME HERE")



bd.mapping.add([act.key for name in bd.databases for act in bd.Database(name)])

**Comment by mrvisscher** [comment]
Fantastic! Happy to have been of help
