### ISSUE TITLE
Problem importing the ecoinvent 3.8 database (spold)

### ISSUE THREAD

**Issue by Menomo** [LCA-ActivityBrowser/activity-browser#1394]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

When I try to import the local database (spold files) I get the following message at the SQLite write stage: The import failed because the biosphere3 database of this Project is incompatible with the version of ecoinvent that you're trying to install. What am I doing wrong?

### Relevant errors

```python
Extracted 19565 datasets in 647.64 seconds
Applying strategy: normalize_units
Applying strategy: update_ecoinvent_locations
Applying strategy: remove_zero_amount_coproducts
Applying strategy: remove_zero_amount_inputs_with_no_activity
Applying strategy: remove_unnamed_parameters
Applying strategy: es2_assign_only_product_with_amount_as_reference_product
Applying strategy: assign_single_product_as_activity
Applying strategy: create_composite_code
Applying strategy: drop_unspecified_subcategories
Applying strategy: fix_ecoinvent_flows_pre35
Applying strategy: drop_temporary_outdated_biosphere_flows
Applying strategy: link_biosphere_by_flow_uuid
Applying strategy: link_internal_technosphere_by_composite_code
Applying strategy: delete_exchanges_missing_activity
Applying strategy: delete_ghost_exchanges
Applying strategy: remove_uncertainty_from_negative_loss_exchanges
Applying strategy: fix_unreasonably_high_lognormal_uncertainties
Applying strategy: convert_activity_parameters_to_list
Applying strategy: add_cpc_classification_from_single_reference_product
Applying strategy: delete_none_synonyms
Applying strategy: update_social_flows_in_older_consequential
Applying strategy: set_lognormal_loc_value
Applied 22 strategies in 8.88 seconds
Writing activities to SQLite3 database:
21:18:02 | INFO | Database cutoff deleted!
```

### Operating system

Windows 11

**Comment by mrvisscher** [comment]
Hi @Menomo,

Did you setup your project with the right biosphere version? You can choose a specific version in the project setup wizard. Learn more: https://github.com/LCA-ActivityBrowser/activity-browser/wiki/Getting-Started#installing-a-biosphere-and-impact-categories

Kind regards,

Marin

**Comment by Menomo** [comment]
Hi @mrvisscher,
Sorry, I'm new to this.
I'm using the latest version of biosphere (3.9.1).
Should I use another version?
Thanks for your attention.

**Comment by mrvisscher** [comment]
Yes, please set up your project with a biosphere version that matches the version of ecoinvent that you're trying to import.

**Comment by Menomo** [comment]
@mrvisscher Now it's worked. Thank you very much!
