### ISSUE TITLE
Unhandled python exception on OSX

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#140]
```
Unhandled Python exception
[1]    44801 abort      activity-browser
```
When testing #138 on my Mac, I couldn't open the AB anymore and Python crashed everytime. After some quick checks, I'm confident that this is __not__ caused by #138.

Need to investigate this further, but likely candidates for problems are:
- new peewee
- new pyqt and qt from the defaults channel

On Travis it runs  [fine](https://travis-ci.org/LCA-ActivityBrowser/activity-browser/jobs/366296260) on OSX

Crash report here: [crash_report.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/1910168/crash_report.txt)

**Comment by haasad** [comment]
Digging a bit deeper into the crash report it looks like QtWebEngine is to blame, or rather the Chrome browser used internally. Potentially related issue with the same Error Code here: https://github.com/brave/browser-laptop/issues/12744. Would also explain why other people don't experience these issues since my OS is rather old.

**Comment by bsteubing** [comment]
seems like there is nothing we can do about this at this moment and it is not really affecting many people. Please re-open if this assessment is wrong.
