### ISSUE TITLE
Can not add downstream consumers

### ISSUE THREAD

**Issue by OliverLyon** [LCA-ActivityBrowser/activity-browser#1403]
### Issue

I tried to do a allocation to multiple products produced in one process. So I tried to drag products from database to "Downstream Consumers" section in activity details. But it does not allow me to do that. So am I doing it the wrong way or is it something happening to the software?

**Comment by mrvisscher** [comment]
Hi @OliverLyon,

Allocation is not yet possible in the Activity Browser, we don't yet offer support for multifunctional processes (although support is coming soon). For now you will have to split these processes up manually and allocate their exchange values by hand.

The _Downstream Consumers_ section only displays in what other activities this current activity is being used as an input. It will update when you drag said activity into e.g. the technosphere section of another activity.

Kind regards,

Marin
