### ISSUE TITLE
Scenario LCA is not recognizing all the scenarios of my SDF

### ISSUE THREAD

**Issue by cuadragg** [LCA-ActivityBrowser/activity-browser#1405]
Hi!

I would like to kindly ask for your help with something. In one database which contains changes for the background and foreground systems of its datasets, I created my own dataset and added to the original SDF the new values that account for the variation of the foreground since the background is already included in the original SDF.  When I ran the scenario LCA, this just shows me results for one scenario and not for the 15 scenarios I uploaded (as you can see in the screenshot). Then, I tried to run the same dataset in other database in my project, I also uploaded just the SDF for changes in the foreground, verified the keys of the dataset, but the problems persist. When I ran the LCA for each individual flow of the Technosphere and biosphere, they worked well, so it seems that the problem is with the dataset per se. However, the prompt is showing me no error, so I do not have any clue what might me happening. If you do, I would highly appreciate if your could please help me out with this. Thanks!

Conda Prompt

(base) PS C:\Users\cuadragg> conda activate ab
(ab) PS C:\Users\cuadragg> activity-browser
16:25:52 | INFO | Activity Browser version: 2.10.1

DevTools listening on ws://127.0.0.1:3999/devtools/browser/938ec071-ceec-4b0d-8174-cf546ad9815d
16:25:54 | INFO | Brightway2 data directory: C:\Users\cuadragg\AppData\Local\pylca\Brightway3
16:25:54 | INFO | Brightway2 current project: default
16:25:54 | INFO | Project settings directory: C:\Users\cuadragg\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
16:25:56 | INFO | Loaded tab ab_plugin_scenariolink
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
16:26:07 | INFO | Brightway2 current project: OPC_Clinker_ME
16:26:07 | INFO | Project settings directory: C:\Users\cuadragg\AppData\Local\pylca\Brightway3\OPC_Clinker_ME.7289fe077276ccb3698e1df33e50e2c7
16:26:08 | INFO | Loaded tab ab_plugin_scenariolink
C:\Users\cuadragg\AppData\Local\anaconda3\envs\ab\Lib\site-packages\activity_browser\ui\tables\models\inventory.py:137: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("", np.nan, inplace=True)
C:\Users\cuadragg\AppData\Local\anaconda3\envs\ab\Lib\site-packages\activity_browser\ui\tables\models\inventory.py:137: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("", np.nan, inplace=True)
16:27:22 | INFO | Loading Scenario file. This may take a while for large files
16:27:23 | INFO | <function ScenarioImportWidget.scenario_db_check at 0x000002B299590C20> -- 0.0
16:27:23 | INFO | <function SuperstructureManager.fill_empty_process_keys_in_exchanges at 0x000002B29647A700> -- 0.0010006427764892578
16:27:23 | INFO | <function SuperstructureManager.verify_scenario_process_keys at 0x000002B29647A840> -- 0.009423494338989258
16:27:23 | INFO | <function SuperstructureManager.check_duplicates at 0x000002B29647AAC0> -- 0.0009999275207519531
16:27:23 | INFO | <function SuperstructureManager.check_scenario_exchange_values at 0x000002B29647A980> -- 0.0
16:27:23 | INFO | <function SuperstructureManager.merge_flows_to_self at 0x000002B29647A3E0> -- 0.007077932357788086
16:27:23 | INFO | <function ScenarioImportWidget.sync_superstructure at 0x000002B299590AE0> -- 0.031583309173583984
16:27:23 | INFO | <function ScenarioImportWidget.load_action at 0x000002B2995909A0> -- 25.94928550720215
16:27:26 | INFO | Created LCA object
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:28 | INFO | Switching LCIA method
16:27:29 | INFO | Redoing LCI
16:27:30 | INFO | Redoing LCI
16:27:31 | INFO | Redoing LCI
16:27:32 | INFO | Redoing LCI
16:27:34 | INFO | Redoing LCI
16:27:35 | INFO | Redoing LCI
16:27:36 | INFO | Redoing LCI
16:27:37 | INFO | Redoing LCI
16:27:38 | INFO | Redoing LCI
16:27:39 | INFO | Redoing LCI
16:27:40 | INFO | Redoing LCI
16:27:42 | INFO | Redoing LCI
16:27:43 | INFO | Redoing LCI
16:27:44 | INFO | Redoing LCI
16:27:45 | INFO | Redoing LCI
16:27:45 | INFO | Created LCA object
16:27:48 | INFO | +showing tab: LCA results
16:39:01 | INFO | Loading Scenario file. This may take a while for large files
16:39:02 | INFO | <function ScenarioImportWidget.scenario_db_check at 0x000002B299590C20> -- 0.0
16:39:02 | INFO | <function SuperstructureManager.fill_empty_process_keys_in_exchanges at 0x000002B29647A700> -- 0.0
16:39:02 | INFO | <function SuperstructureManager.verify_scenario_process_keys at 0x000002B29647A840> -- 0.00851130485534668
16:39:02 | INFO | <function SuperstructureManager.check_duplicates at 0x000002B29647AAC0> -- 0.0020024776458740234
16:39:02 | INFO | <function SuperstructureManager.check_scenario_exchange_values at 0x000002B29647A980> -- 0.0010051727294921875
16:39:02 | INFO | <function SuperstructureManager.merge_flows_to_self at 0x000002B29647A3E0> -- 0.006002187728881836
16:39:02 | INFO | <function ScenarioImportWidget.sync_superstructure at 0x000002B299590AE0> -- 0.03232693672180176
16:39:02 | INFO | <function ScenarioImportWidget.load_action at 0x000002B2995909A0> -- 7.968515396118164
16:39:05 | INFO | Created LCA object
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:06 | INFO | Switching LCIA method
16:39:07 | INFO | Redoing LCI
16:39:08 | INFO | Redoing LCI
16:39:09 | INFO | Redoing LCI
16:39:10 | INFO | Redoing LCI
16:39:11 | INFO | Redoing LCI
16:39:12 | INFO | Redoing LCI
16:39:14 | INFO | Redoing LCI
16:39:15 | INFO | Redoing LCI
16:39:16 | INFO | Redoing LCI
16:39:17 | INFO | Redoing LCI
16:39:18 | INFO | Redoing LCI
16:39:19 | INFO | Redoing LCI
16:39:20 | INFO | Redoing LCI
16:39:21 | INFO | Redoing LCI
16:39:22 | INFO | Redoing LCI
16:39:22 | INFO | Created LCA object
16:39:24 | INFO | +showing tab: LCA results

![Screenshot 2024-11-10 164333](https://github.com/user-attachments/assets/273ac47c-f88d-4436-a5b1-e68b16fa5f07)

Even when I tried running an already existing activity and my new activity, the results are not appearing for the original activity and just one scenario is shown for my new activity after updating the SDF. 
![image](https://github.com/user-attachments/assets/1ebc1eba-5971-4fdf-a7a3-56d4b1803df8)

This is the new flow values I am adding to the original SDF. 
[SDF_clinker manufacturing_standard kiln.xlsx](https://github.com/user-attachments/files/17691663/SDF_clinker.manufacturing_standard.kiln.xlsx)

Thanks so much for your help!

_Originally posted by @cuadragg in https://github.com/LCA-ActivityBrowser/activity-browser/issues/1397#issuecomment-2466748372_

**Comment by mrvisscher** [comment]
Fixed via e-mail, issue was related to very small results.
