### ISSUE TITLE
AB hangs indefinitely when importing database without network connection

### ISSUE THREAD

**Issue by Q-Quan** [LCA-ActivityBrowser/activity-browser#1408]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

When no network is available (e.g. Wi-Fi is turned off), importing a database via the wizard naturally does not work. In the terminal, this results in a `requests.exceptions.ConnectionError`. However, in the GUI, this has no effect: the login prompt stays open and the cursor keeps spinning. The prompt can be closed, and the AB can be used after that, but the cursor will remain spinning even then.

More generally, other exceptions during the importing process (e.g. from using credentials that are valid but unlicensed) result in the same behaviour.

I would expect some graceful handling of the issue (e.g. an error alert) when this happens.

### Operating system

Windows 11

**Comment by marc-vdm** [comment]
@mrvisscher Also add to the safe fetch

**Comment by Q-Quan** [comment]
I also ran into an instance where, using valid and licensed credentials, the version dropdowns did not populate, and I could proceed to the import step with empty values. This yielded a terminal error, but again no feedback in the GUI. Cannot reproduce this again, though.
