### ISSUE TITLE
file not found error on webpages (welcome.html, activity-browser-sankey.html)

### ISSUE THREAD

**Issue by jycour** [LCA-ActivityBrowser/activity-browser#144]
Hello,

I installed activity-browser on a dedicated conda environment using the github install doc.
When it launches, I get a "Your file was not found ERR_FILE_NOT_FOUND" instead of the welcome page. LCA calculation is working but the sankey page displays the same error. I'm running macos 10.11.6. 

Any idea? Thank you!

Jean-Yves

**Comment by haasad** [comment]
Hi Jean-Yves,

I'm a bit at loss here, I have no idea what could cause this. Could you maybe try and run this command in a terminal:
```
find $HOME -name "welcome.html"
```
This is just to make sure that the required file actually exists and your miniconda is installed in an accessible place. In my case the returned path looks like this:
```
/home/adrian/miniconda3/envs/aaa/lib/python3.6/site-packages/activity_browser/app/ui/web/startscreen/welcome.html
```

**Comment by jycour** [comment]
Hi Adrian (I guess),

Thanks for your quick answer, i indeed checked that the two html files exist :
/anaconda/envs/ab/lib/python3.6/site-packages/activity_browser/app/ui/web/startscreen/welcome.html

The differences I see with you are:
I use anaconda instead of miniconda
it is not installed in my home directory but directly at the root of my hard drive.

Jean-Yves


On 23 Apr 2018, at 18:33, haasad <notifications@github.com> wrote:

Hi Jean-Yves,

I'm a bit at loss here, I have no idea what could cause this. Could you maybe try and run this command in a terminal:

find $HOME -name "welcome.html"
This is just to make sure that the required file actually exists and your miniconda is installed in an accessible place. In my case the returned path looks like this:

/home/adrian/miniconda3/envs/aaa/lib/python3.6/site-packages/activity_browser/app/ui/web/startscreen/welcome.html

**Comment by haasad** [comment]
I could imagine that there is some permission problem because anaconda is in root. Could you try:
```
sudo /anaconda/envs/ab/bin/activity-browser
```
and see if anything changes?

**Comment by jycour** [comment]
Using my version of anaconda, I installed a new ab env in the directory /Users/JY/.conda/envs (which already existed but was empty) and it fixed the issue.

Thanks, 
Jean-Yves


On 23 Apr 2018, at 20:15, Jean-Yves Courtonne <jean-yves.courtonne@inria.fr> wrote:

This doesn’t fix the issue, I’ll try to install everything with miniconda in home and I will let you know. Thanks,

 
On 23 Apr 2018, at 19:59, haasad <notifications@github.com <mailto:notifications@github.com>> wrote:

I could imagine that there is some permission problem because anaconda is in root. Could you try:

sudo /anaconda/envs/ab/bin/activity-browser
and see if anything changes?

**Comment by haasad** [comment]
Great, thanks for reporting the issue and looking into this!
