### ISSUE TITLE
Activity Browser for people with no access to ecoinvent

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#152]
Currently the AB is only usable if you have access to an ecoinvent database. If people want to check out the AB, they can't use most of the features, because an LCI database is required. This might also be an issue for presenting your poster @TMillross, because not everbody at the conference will have an ecoinvent license.

Below is a very quick and dirty way to import the [forwast database](https://lca-net.com/projects/show/forwast/). It uses a utility function from [lcopt](https://github.com/pjamesjoyce/lcopt).
```python
import requests
d = {}
url = 'https://raw.githubusercontent.com/pjamesjoyce/lcopt/master/lcopt/utils.py'
lcopt_utils = requests.get(url).text
exec(lcopt_utils, d)
lcopt_bw2_forwast_setup = d['lcopt_bw2_forwast_setup']
lcopt_bw2_forwast_setup(db_name='forwast')
```

I personally haven't used the forwast database before, but after some quick checks I feel like it's an acceptable option to display the basic capabilities of the AB. Calculations work fine, only problem is the Sankey tool which doesn't deal well with a small database that's so closely interlinked. The many small flows push the javascript in d3-sankey-diagram to its limits and the interaction becomes very slow. This can be somewhat alleviated by increasing the cutoff from 0.005 to eg. 0.05, see example below:
![image](https://user-images.githubusercontent.com/11636405/39662508-7da1943c-5062-11e8-842d-802fffdbecee.png)

Should we look into including this @bsteubing?

**Comment by haasad** [comment]
@ricklupton, Bernhard mentioned that you would like to have look at how your library is used within the AB, but don't have access to ecoinvent.
Maybe you want the check it out with my forwast "solution" from above :smile:. As mentioned, it runs a lot smoother with ecoinvent, but you can at least see how it's supposed to work.

**Comment by haasad** [comment]
If importing the forwast db was successful you should have a project called forwast with two databases: biosphere3 and forwast:
![image](https://user-images.githubusercontent.com/11636405/39760721-63039078-52d6-11e8-8d90-f806d4bdde52.png)

Create a new calculation setup on the left and drag an activity from the forwast db to the table of the calculation setup, example below with the first activity in the forwast db:
![image](https://user-images.githubusercontent.com/11636405/39760881-d851be9a-52d6-11e8-8228-8f1e1b661fdf.png)

Same procedure for the impact assessment method, I'd take something generic like IPCC
![image](https://user-images.githubusercontent.com/11636405/39760954-167330f0-52d7-11e8-8f00-89b860277905.png)

As soon as you have at least one activity and impact assessment method you can calculate the impact assessment results:
![image](https://user-images.githubusercontent.com/11636405/39761122-82b0c584-52d7-11e8-891c-ea20ce0df4d0.png)

Sankey window looks like this when I open it:
![image](https://user-images.githubusercontent.com/11636405/39761160-a31a5ac4-52d7-11e8-8665-e75b5fd25bfa.png)

I then increased the cutoff to 0.05 and expanded some of the flows by clicking on them:
![image](https://user-images.githubusercontent.com/11636405/39761249-e56b9780-52d7-11e8-9982-135bbb35188d.png)

**Comment by haasad** [comment]
Maybe you were already at this point, since you said you could open a blank sankey window. In that case something must be going wrong elsewhere. Could you try an check if you still get a blank window when you use the same activity (100 Health and social work, EU27) and method (IPCC 2013, climate change, GWP 100a)?

**Comment by ricklupton** [comment]
Thanks for the detailed response!

It seems it is not loading d3 correctly -- seems to be #143. Using the development version fixes it.

For reference, in the console there is a message
```
[19044:19063:0508/172820.817895:ERROR:cert_verify_proc_openssl.cc(212)] X509 Verification error unable to get local issuer certificate : 20 : 2 : 4
js: Uncaught ReferenceError: d3 is not defined
QObject::connect: Cannot queue arguments of type 'QTextCharFormat'
(Make sure 'QTextCharFormat' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
/home/rick/anaconda3/envs/ab/lib/python3.6/site-packages/bw2calc/graph_traversal.py:137: UserWarning: Stopping traversal due to calculation count.
  warnings.warn("Stopping traversal due to calculation count.")
js: Uncaught TypeError: Cannot read property 'format' of undefined
```

Connecting to the debug server at the address printed in the console shows the same errors
![image](https://user-images.githubusercontent.com/878794/39769981-a62fea9a-52e5-11e8-99e1-6e05cd6452d1.png)

(the TypeError is in d3-sankey-diagram because d3.format is not defined)

**Comment by haasad** [comment]
Downloading forwast is now possible via the import wizard: #179
