### ISSUE TITLE
Sankey loading forever for zero LCA score

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#155]
In some cases, eg. activities from the forwast database and _CML 2001 w/o LT, ionising radiation w/o LT, ionising radiation w/o LT_ method, the LCA score can be zero. If this happens brightway raises an error, but the Sankey window keeps spinning:
```python
Traceback (most recent call last):
  File "/home/adrian/Git/github/AB/activity-browser/activity_browser/app/ui/web/sankey/worker_threads.py", line 16, in run
    res = bw.GraphTraversal().calculate(self.demand, self.method, self.cutoff, self.max_calc)
  File "/home/adrian/miniconda3/envs/abe/lib/python3.6/site-packages/bw2calc/graph_traversal.py", line 46, in calculate
    raise ValueError("Zero total LCA score makes traversal impossible")
ValueError: Zero total LCA score makes traversal impossible
```
We should add an appropriate warning message to the AB for this case.

**Comment by bsteubing** [comment]
Implemented for the new Sankey diagram (in the pipeline...)

**Comment by bsteubing** [comment]
Got a new Sankey diagram implementation now.
