### ISSUE TITLE
Aggregating links in Sankey diagram visualisation

### ISSUE THREAD

**Issue by ricklupton** [LCA-ActivityBrowser/activity-browser#157]
After expanding the diagram a few times there are a lot of thin parallel lines:
![image](https://user-images.githubusercontent.com/878794/39771040-c56f3a20-52e8-11e8-9afd-f26726c18eee.png)

It might be nice to bundle these together, so for example the three links into 269 would be one thicker link with bits peeling off:
![image](https://user-images.githubusercontent.com/878794/39771106-f19f047c-52e8-11e8-90d5-4663ced8c9e0.png)

One way to do this would be for your code to generate a [floWeaver](https://github.com/ricklupton/floweaver) "Sankey diagram definition" that would pre-process your data to do this aggregation. But I don't know if you think that's in important thing to work on. Let me know if you want to talk about how that would work.

I think this could also speed up the rendering. I haven't checked, but I suspect it gets slow as you expand the Sankey diagram because of the graph ordering algorithm. Using floWeaver you would have to specify this yourself but I think it would be faster, and in these types of diagrams where almost everything is connected to everything, any ordering is almost as good as any other from the point of view of minimising crossings.

(not that you can also set the ordering directly in d3-sankey-diagram to avoid these calculations, without using floWeaver)

**Comment by bsteubing** [comment]
Got a new Sankey diagram implementation now.

**Comment by ricklupton** [comment]
@bsteubing just out of curiosity, what are you using now?

**Comment by bsteubing** [comment]
Hi Rick - it is a mixture of dagre and D3. Certainly not perfectly implemented yet, so improvements are always welcome :-) But I think it does the job for displaying LCA type of Sankeys with loops etc.

**Comment by bsteubing** [comment]
... by the way, this was not a conscious decision "against" floweaver, but just a pragmatic "want things done"... so whatever works better in the future could be next!

**Comment by ricklupton** [comment]
Sounds good! And thanks for the thought, I understand 🙂
