### ISSUE TITLE
Sankey diagram of market activity: the flow on the left is less than the sum of flows on the right

### ISSUE THREAD

**Issue by xiaoshir** [LCA-ActivityBrowser/activity-browser#161]
I noticed that in Sankey diagram of market activity (eg. market for copper, GLO), the flow on the left is less than the sum of flows on the right, which might be a mistake?

See purple flows below:
![image](https://user-images.githubusercontent.com/28433916/39819191-22e84b14-53a3-11e8-9ce7-270d472179ce.png)

The flow on the left is the total score of market for copper, GLO, while the flows on the right are different production activities for copper plus transportation.

The same thing happens to steel market.

**Comment by haasad** [comment]
By calculating the whole "impact graph" with `bw.GraphTraversal` we know the contribution of each node to the total impact score. The sankey tool will always display the total of a node and not just the sum of the displayed edges.
In your example this means, that there more activities that consume from the market for copper, the edges just aren't displayed yet. Simplified example below, assuming 13902 would be responsible for the remaining demand to the copper market.
![delme](https://user-images.githubusercontent.com/11636405/39825774-fdeaf054-53b2-11e8-86ab-359315c7e87e.png)

**Comment by haasad** [comment]
The ecoinvent "network" is not just a tree, but there are lots of loops and these become sometimes very hard to display in a sankey visualization.

**Comment by haasad** [comment]
Another thing that is also important to note is the fact that negative flows (ie benefits) are not displayed at all at the moment. This can sometimes also lead to strange graphs.

**Comment by xiaoshir** [comment]
Hey, you are absolutely right!
![image](https://user-images.githubusercontent.com/28433916/39924349-aa7285ba-5527-11e8-964d-fbc4df9b1f2d.png)

**Comment by haasad** [comment]
:+1:
