### ISSUE TITLE
Opening database: no feedback

### ISSUE THREAD

**Issue by Athunc** [LCA-ActivityBrowser/activity-browser#162]
When double-clicking the database of choice, it would be nice if the user had some feedback that the AB received the instruction and is currently working on opening the database. Since this takes some time, having no feedback raises doubts for the user wether their input was received.

**Comment by bsteubing** [comment]
I suggest at statusbar message. Made a signal for this in a branch already. So this will be easy to implement, but let's wait for all the updates in the pipeline to come in...

**Comment by haasad** [comment]
Would also need it's own thread to be non-blocking

**Comment by bsteubing** [comment]
Obsolete as this is now much faster and also displayed in the statusbar
