### ISSUE TITLE
Is it possible to choose at which level the flows should be grouped/ungrouped in Sankey diagram?

### ISSUE THREAD

**Issue by xiaoshir** [LCA-ActivityBrowser/activity-browser#172]
Question 1: is it possible to choose at which level the flows should be grouped/ungrouped in Sankey diagram? For example, at depth of 2, there are two nodes for A11 (i.e.: ungrouped rather than having 1 node of A11, and two flows fed into it), but on the very right hand side, flows B, C, D shall be grouped (eg. node D has two inflows). Here A represents functional unit, A1, A11... represent activities.

Since I have very limited number of flows in the biosphere database, B, C, D actually represent the biosphere flows. So:
Question 2: is it possible to show biosphere flows in the Sankey diagram?

I have calculated all the results needed to generate this visualization in Brightway, in the form of a nested dictionary.
![image](https://user-images.githubusercontent.com/28433916/42285947-68dad77e-7fb1-11e8-8eda-287abd104495.png)

**Comment by haasad** [comment]
This is definitely possible, just not in the ActivityBrowser :smile: 
I suggest you have a look at https://ricklupton.github.io/d3-sankey-diagram/. If you already have your results in a dictionary, it should be rather simple to create a sankey diagram with the [ipysankeywidget](https://github.com/ricklupton/ipysankeywidget). You can directly create them in a jupyter notebook following the examples notebooks on the ipysankeywidget github page. This also allows you to add biosphere flows according to your requirements.
