### ISSUE TITLE
import ecoinvent version 3.5

### ISSUE THREAD

**Issue by jmehreth** [LCA-ActivityBrowser/activity-browser#182]
importing ecoinvent version 3.5 (cutoff) via "import database" does not work. the procedure always stops after the fourth step (see attached image; see error message in console in another attached picture).

when I restart the activity browser, the database is technically visible in the list of databases, but without any content (size = 0, no biosphere-dependency).

![ab_1](https://user-images.githubusercontent.com/34546932/44914450-97b42080-ad30-11e8-9509-2eaf8f368b2e.JPG)
![ab_2](https://user-images.githubusercontent.com/34546932/44914455-9aaf1100-ad30-11e8-9ae5-28e7aa3f9d38.JPG)

**Comment by tmillross** [comment]
Hi @jmehreth,
I think this will be fixed by pull request #181 once it's merged

**Comment by cmutel** [comment]
If you update bw2io, then you can import 3.5 to completion *if you start a new project*. However, as a general rule I think it is best to wait for the aforementioned PR to be tested and then merged.

**Comment by jmehreth** [comment]
ok, thanks a lot!

**Comment by haasad** [comment]
#181 is now merged, `conda update activity-browser-dev` should do the trick
