### ISSUE TITLE
Copy-pasting from AB inserts extra characters

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#185]
On MacOS 10.13.6 with AB dev current as of 12 Sept. 2018, you get the following when copy-pasting from AB into Excel:

- Strings are prepended with `\ufeff`, the Unicode byte order mark. This is the worse of the two, as it breaks string comparisons
- Each string overwrites the value in the cell lower down, i.e. Excel interprets the string to have two lines or be equivalent to two cells

Current workaround is to first paste into a separate text editor. 

Not sure if this is something with Qt, but maybe inserting a `.strip()` somewhere would help.

**Comment by cmutel** [comment]
Using the `Copy` button doesn't seem to add the byte-order mark anywhere, but does keep the extra line break.

**Comment by haasad** [comment]
The `Copy` button uses `pd.Dataframe.to_clipboard` internally, does the extra line break also appear when you using `pd.Dataframe.to_clipboard` outside of the AB?

**Comment by haasad** [comment]
If the linebreak problem also happens for normal `pd.DataFrame.to_clipboard`, there might be something fishy going on with Excel for Mac, especially since you apparently get meaningful input with this PR #187, whereas it puts everything in one single row on linux+libreoffice.

Do you know if Excel for Mac accepts utf8 csvs in the meantime? I remember this to be a problem when i used to work on mac. Might also explain some of this BOM-strangeness.

**Comment by haasad** [comment]
According to your [comment above](
https://github.com/LCA-ActivityBrowser/activity-browser/issues/185#issuecomment-420682879) you have the line break problem both with Ctrl+C and with the `Copy`-button, but these are completely different:
- Ctrl+C uses the code you changed in #187, where you say the `\n` is the problem
- The `Copy` button uses `df.to_clipboard` of the underlying dataframe

Maybe I'm completely missing the point here, can you maybe post a screenshot how your data looks in excel?

**Comment by haasad** [comment]
@cmutel, I just merged #187. This still leaves us with two problems:
- the unicode byte order marks prepended to strings
- line break problem when using the copy button of the results

Is this correct?

**Comment by cmutel** [comment]
- I think the unicode thing is Specific to Excel, and not linked to the AB.
- I don't think the line break is a problem when copying a table; only when copying individual cell values (i.e. building an inventory by copy/pasting activity names
