### ISSUE TITLE
Delete Project dialog confirmation bug

### ISSUE THREAD

**Issue by tmillross** [LCA-ActivityBrowser/activity-browser#192]
In the Projects section, when you click Delete Current, a confirmation dialog appears.
There are two options, yes & no
Clicking no performs same action as yes (attempts delete)

**Comment by haasad** [comment]
That's a very good catch, kind of worrying that no one noticed this before. There's a failing test on the CI service with your PR, I'll sort that out first and then merge your PR asap. Thanks
