### ISSUE TITLE
LCA results presentation

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#21]
How to display LCA results in informative and graphically appealing ways? Here some ideas:
Different plots
•	Inventory level (economic/environmental flows)
•	LCA score(s) (Barchart, Piechart, Treemap…)
•	Contribution Analyses (by process, elementary flow, product, geography, ISIC sector) (Barchart, Treemap, Piechart, Worldmap for geo)
•	Uncertainties: Monte Carlo (possibly also others, e.g. Latin-Hypercube) (needs also to integrated in to calculation setups)
Tables to export the data
•	To be developed first
User choices:
•	LCIA method, cut-off

**Comment by bsteubing** [comment]
We basically achieved all of this now, but other inputs and feature requests are welcome of course!

**Comment by xiaoshir** [comment]
Something that can be (easily I guess) improved:
![image](https://user-images.githubusercontent.com/28433916/55266466-65927f00-527d-11e9-9050-4451dcce060f.png)
As usually the lower the impact result is, the "greener" it should be. So a color from green (lower value) to red (high value) would be more intuitive.

**Comment by bsteubing** [comment]
thanks for this input. The AB has been further developed in the meantime (check out the latest development version). But hints like this (or code implementations) are always welcome.
