### ISSUE TITLE
Segfault on running activity-browser after install from scratch in Ubuntu

### ISSUE THREAD

**Issue by Loisel** [LCA-ActivityBrowser/activity-browser#212]
Hello,

following the installation instructions in the `README.md` for both stable and dev version I get the following:

```
$ activity-browser 
Brightway2 data directory: $HOME/.local/share/Brightway3
Brightway2 active project: default
[1:1:0100/000000.829424:ERROR:broker_posix.cc(41)] Invalid node channel message
Segmentation fault (core dumped)
```
on `Ubuntu 18.04.1 LTS`. I'd be happy to provide more detail if you give me a hint.

**Comment by haasad** [comment]
Hi @Loisel,

this seems to a graphics driver problem on Ubuntu 18. I use 16.04 and there I never encountered this problem, but I see the same error in a Ubuntu 18.04 VM.

Installing these OpenGL drivers solved the issue for me:
```
sudo apt install mesa-common-dev libglu1-mesa-dev
```
Hope this helps.

**Comment by Loisel** [comment]
Worked! Thanks for your help.
