### ISSUE TITLE
Text scaling on MacOS

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#216]
The branch `LU_231` has comically small text on MacOS (non-retina screen):

![screen shot 2019-02-26 at 15 30 01](https://user-images.githubusercontent.com/645217/53419652-85aef400-39da-11e9-8382-475665336460.png)

Only the tab labels are normal size.

**Comment by bsteubing** [comment]
Could you check if it is better now?

**Comment by cmutel** [comment]
Fixed in f9c54de25723b56949c3da5c9d3346768052d7a7
