### ISSUE TITLE
Lu 231 branch: Activity table shows sorted by reference product, but actually sorted by name

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#221]
![Screen Shot 2019-03-12 at 14 39 39](https://user-images.githubusercontent.com/645217/54204106-dc84f500-44d3-11e9-9414-83a5abc92f70.png)

**Comment by cmutel** [comment]
Fixed in 2934545b05bf9d7cc5f8c8202cd0133603c27394

**Comment by bsteubing** [comment]
fixed by 524e422
