### ISSUE TITLE
Lu 231 branch (MacOS): Color scheme in Sankey is messed up

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#222]
![Screen Shot 2019-03-12 at 14 42 59](https://user-images.githubusercontent.com/645217/54204323-4f8e6b80-44d4-11e9-96ab-419888b7add8.png)

**Comment by cmutel** [comment]
The javascript functions - I can pan and zoom. But because of the black background I can't really see anything.

**Comment by bsteubing** [comment]
@Maxomas any clue why this could be the case? On Windows it works fine...

**Comment by bsteubing** [comment]
@cmutel could you check if this persists? I changed some of the CSS, but I am guessing as on Windows it is working fine...

**Comment by cmutel** [comment]
No help with the latest changes. I also get a weird effect in the tabs EF contributions and Process Contributions:

<img width="887" alt="Screen Shot 2019-03-12 at 21 48 57" src="https://user-images.githubusercontent.com/645217/54235060-b762a780-4510-11e9-99fe-b545a41455c0.png">

<img width="887" alt="Screen Shot 2019-03-12 at 21 48 48" src="https://user-images.githubusercontent.com/645217/54235084-c34e6980-4510-11e9-9c3d-ba0c2f7af957.png">

How can I help debug this? Are all three of these in web views? Is there a way to get an HTML inspector, like in normal browsers?

**Comment by bsteubing** [comment]
HTML inspector: type "localhost:3999" in Chrome for DevTools of AB web content
But this is not a webview... this is matplotlib with regular QWidgets... which version of Qt / PyQt5 are you using? (check the console when you start the AB, it prints the version, mine is PyQt Version: 5.9.2)

**Comment by dgdekoning** [comment]
I can confirm the same issue for Ubuntu 16.04, using the latest dev build. Oddly enough, this issue does not occur when running the source code directly (`python run-activity-browser.py`).

**Comment by dgdekoning** [comment]
Looking at the installation folder within conda, it seems the stylesheets are not being included at all.

**Comment by cmutel** [comment]
No reason for them to be, we are [using `include_package_data=True`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/setup.py) ([packaging guide](https://python-packaging.readthedocs.io/en/latest/non-code-files.html)), but our [MANIFEST](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/MANIFEST.in) has no CSS files. Maybe a simple fix?

**Comment by dgdekoning** [comment]
Yes, @cmutel, that was it exactly! Ran a local conda-build with that change and it appears to have solved the issue!

**Comment by cmutel** [comment]
Well, more @dgdekoning than me this time...

**Comment by bsteubing** [comment]
Nice thanks both of you!!
