### ISSUE TITLE
Issues with Importing Ecoinvent Database

### ISSUE THREAD

**Issue by AkshatSudheshwar** [LCA-ActivityBrowser/activity-browser#225]
Hello,
I am trying to download the ecoinvent data in the activity browser but for some reason the import wizard does cannot start writing the datasets into the SQLite database:
![image](https://user-images.githubusercontent.com/40687135/54620498-8cbfa400-4a66-11e9-826f-f1c0fe531ad8.png)

The anaconda prompt window displays the following messages:
![image](https://user-images.githubusercontent.com/40687135/54620523-9812cf80-4a66-11e9-8340-37494e6fda25.png)

In the past downloading the dataset was not an issue; in fact, I created a fresh environment to get the data, but it did not work. Any help will be appreciated :)

Thank you in advance!
Akshat

**Comment by bsteubing** [comment]
Hi, could you try updating bw2data and bw2io to their latest versions and see if this error is resolved?

**Comment by AkshatSudheshwar** [comment]
Hello, I updated bw and updated the activity-browser-dev but I am still facing the same issue.

**Comment by bsteubing** [comment]
This has nothing to do with the AB. Please update bw2data and bw2io (brightway). If this is not resolved after updating, please make an issue with brightway as this is not an AB issue.
