### ISSUE TITLE
GUI: Results are not displayed in scroll spaces

### ISSUE THREAD

**Issue by Athunc** [LCA-ActivityBrowser/activity-browser#227]
The results of MLCA are now obscured because the Qt widgets are in a space without scrollbars. This prevents me from accessing the tables on the bottom as well as some graphs and legends. These are now out of bounds.

**Comment by dgdekoning** [comment]
Can you give an example of this issue occurring?

**Comment by nabilahmed739** [comment]
@StpdFox , This should have been fixed as part of migration of visualizations to bokeh but would be nice to confirm this scenario in MAC and close this issue

**Comment by nabilahmed739** [comment]
@marc-vdm , as the migration of visualizations (bokeh) was reverted, this issue is still existing right? 
I will finalize the bokeh branch soon for the merge, I'm also adding other features like filtering uncharacterized flows, etc. into the bokeh branch.
