### ISSUE TITLE
GUI: left/right panels are inflexible

### ISSUE THREAD

**Issue by Athunc** [LCA-ActivityBrowser/activity-browser#228]
I remember being able to drag the separator between the left panel and right panel in order to change the sizes they were allocated. Currently the separator only allows me to view them in a 50/50 ratio or I can completely obscure one panel to give the other panel all the space.

**Comment by dgdekoning** [comment]
Adding to this, in full-screen mode the separator can be smoothly dragged across the middle 1/3rd of the screen before having either of the two panels become obscured.

**Comment by bsteubing** [comment]
The QtWidgets have an attribute called minimumsize or something like this, which causes this behaviour. How much you can move the slider depends on your screen size and the minimumsize of the widgets. So I think all of this is desired behaviour. I keep the issue open for now for the reason that we could eventually have a look at how the minimum sizes are defined...
