### ISSUE TITLE
GUI: Monte Calro graph is very thin

### ISSUE THREAD

**Issue by Athunc** [LCA-ActivityBrowser/activity-browser#229]
The width of the graph displaying results of the monte carlo simulations seems too thin to read easily. In addition, it also seems as though the graph is cut oof beyond a probability of 35%, even when results exceeding that number are to be displayed.

**Comment by StpdFox** [comment]
I do think this is also a mac OS problem, so i'm tagging it as such. 
Currently i'm not in possesion of a mac machine to work on these issues
