### ISSUE TITLE
GUI: Sankey Diagram traversal freezes

### ISSUE THREAD

**Issue by Athunc** [LCA-ActivityBrowser/activity-browser#230]
When traversing the Sankey diagram, the widget freezes for about 2.5 seconds, reducing user friendliness. I suspect that the code is redoing some of the operations for making the diagram when traversing it.

**Comment by StpdFox** [comment]
No issues while dragging, this might be an old problem or again mac OS only. If this problem still occurs please open a new issue with some info (i.e. your OS or an example if possible)
