### ISSUE TITLE
can't expand sankey diagram

### ISSUE THREAD

**Issue by xiaoshir** [LCA-ActivityBrowser/activity-browser#234]
I'm using the development version of activity-browser, but for some reason I can't expand the sankey diagram.
![image](https://user-images.githubusercontent.com/28433916/56952288-4caa1180-6b3a-11e9-8079-669eaf3a3b69.png)

I saw an error in the Anaconda Prompt:
AttributeError: 'SankeyGraphTraversal' object has no attributt 'nodes_set'

May I ask what is causing this and how can I fix it? I have been searching this error online but unfortunately still got no clues......

![image](https://user-images.githubusercontent.com/28433916/56952312-592e6a00-6b3a-11e9-818a-a363c462f178.png)

I tried the "normal" version, and the problem is the same.

**Comment by bsteubing** [comment]
Hi Shirley, that Sankey diagram is not supported anymore. Can you please update to the latest version of the development branch? It has a more sophisticated Sankey diagram once you have calculated the LCA results.

**Comment by xiaoshir** [comment]
I did update to the latest version (4.6.14). But I realized just now that I didn't add your channel in the conda config. I added it, and then updated ab-dev version again, and now I run into another unknown error message
![image](https://user-images.githubusercontent.com/28433916/57008602-930e7780-6bf1-11e9-9d96-161e190250dd.png)

**Comment by xiaoshir** [comment]
# packages in environment at C:\miniconda3_py37\envs\ab_dev:
#
# Name                    Version                   Build  Channel
activity-browser-dev      2019.04.15                 py_0    bsteubing
appdirs                   1.4.3            py36h28b3542_0
arrow                     0.13.1                   py36_0
asn1crypto                0.24.0                   py36_0
asteval                   0.9.13             pyh24bf2e0_0    conda-forge
astunparse                1.6.2                      py_0    conda-forge
beautifulsoup4            4.7.1                    py36_1
blas                      1.0                         mkl
brightway2                2.3                        py_1    cmutel
bw2analyzer               0.9.4                      py_0    cmutel
bw2calc                   1.7.3                      py_0    cmutel
bw2data                   3.4.4                      py_1    cmutel
bw2io                     0.7.4                      py_0    cmutel
bw2parameters             0.6.6                      py_0    cmutel
ca-certificates           2019.1.23                     0
certifi                   2019.3.9                 py36_0
cffi                      1.12.3           py36h7a1dbc1_0
chardet                   3.0.4                    py36_1
click                     7.0                      py36_0
cryptography              2.6.1            py36h7a1dbc1_0
cycler                    0.10.0           py36h009560c_0
decorator                 4.4.0                    py36_1
docopt                    0.6.2                    py36_0
eidl                      1.2.0                      py_0    haasad
eidl7zip                  1.0.0                         1    haasad
eight                     0.4.2                      py_2    conda-forge
fasteners                 0.14.1                     py_3
flask                     1.0.2                    py36_1
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                   py36_0
fuzzywuzzy                0.17.0                     py_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py36_0
intel-openmp              2019.3                      203
itsdangerous              1.1.0                    py36_0
jinja2                    2.10.1                   py36_0
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.1.0            py36ha925a31_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.37               h2a8f88b_0
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
lxml                      4.3.3            py36h1350720_0
markupsafe                1.1.1            py36he774522_0
matplotlib                3.0.3            py36hc8f65d3_0
mkl                       2019.3                      203
mkl-service               1.1.2            py36hb782905_5
mkl_fft                   1.0.12           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
monotonic                 1.5                        py_0
networkx                  2.3                        py_0
nose                      1.3.7                    py36_2
numpy                     1.16.3           py36h19fb1c0_0
numpy-base                1.16.3           py36hc3f5095_0
openssl                   1.1.1b               he774522_1
pandas                    0.24.2           py36ha925a31_0
patsy                     0.5.1                    py36_0
peewee                    3.6.4           py36h65ede16_1000    conda-forge
pip                       19.1                     py36_0
psutil                    5.6.2            py36he774522_0
pycparser                 2.19                     py36_0
pyopenssl                 19.0.0                   py36_0
pypardiso                 0.2.2                      py_0    haasad
pyparsing                 2.4.0                      py_0
pyprind                   2.11.2                py36_1000    conda-forge
pyqt                      5.9.2            py36h6538335_2
pysocks                   1.6.8                    py36_0
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.0                    py36_0
python-levenshtein        0.12.0          py36hfa6e2cd_1000    conda-forge
pytz                      2019.1                     py_0
qt                        5.9.7            vc14h73c81de_0
requests                  2.21.0                   py36_0
scipy                     1.2.1            py36h29ff71c_0
seaborn                   0.9.0                    py36_0
setuptools                41.0.1                   py36_0
sip                       4.19.8           py36h6538335_0
six                       1.12.0                   py36_0
soupsieve                 1.8                      py36_0
sqlite                    3.28.0               he774522_0
stats_arrays              0.5                        py_0    cmutel
statsmodels               0.9.0            py36h452e1ab_0
tornado                   6.0.2            py36he774522_0
unicodecsv                0.14.1           py36h6450c06_0
unidecode                 1.0.23                   py36_0
urllib3                   1.24.2                   py36_0
vc                        14.1                 h0510ff6_4
voluptuous                0.11.5                     py_0    conda-forge
vs2015_runtime            14.15.26706          h3a45250_4
werkzeug                  0.15.2                     py_0
wheel                     0.33.1                   py36_0
whoosh                    2.7.4                    py36_1
win_inet_pton             1.1.0                    py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.11.1           py36he774522_0
xlrd                      1.2.0                    py36_0
xlsxwriter                1.1.7                      py_0
zlib                      1.2.11               h62dcd97_3

**Comment by xiaoshir** [comment]
ok.... today `conda update conda` magically solved the issue. But I still can't further split Sankey and see the contributions from upstream processes:
![image](https://user-images.githubusercontent.com/28433916/57229751-23e0bb00-7017-11e9-9343-53f58e67a32a.png)

**Comment by dgdekoning** [comment]
First of all, thank you for the comprehensive error-testing you performed!

On the one hand, great that conda magically fixed itself, on the other kind of annoying that you have no idea why :/.

I'm currently setting up an environment and will see if I can find out if I can help you with that diagram.

**Comment by dgdekoning** [comment]
Given that you want to look at the upstream processes of a product, I think you are looking for the 'Graph Explorer' functionality:

![graph_explorer_electricity_20190507_1126](https://user-images.githubusercontent.com/11406390/57289123-13821c00-70bb-11e9-8004-b7fa38d46ab7.PNG)

You can access this explorer functionality by finding the correct reference product in the database tab on the left and right-clicking on it, then clicking the 'Open in Graph Explorer' option.

![graph_explorer_select_20190507_1129](https://user-images.githubusercontent.com/11406390/57289319-6e1b7800-70bb-11e9-994a-43a61f46481c.PNG)

![graph_explorer_select_20190507_1131](https://user-images.githubusercontent.com/11406390/57289431-a327ca80-70bb-11e9-8ffb-5ac180fec597.PNG)

From there you can then left-click on every item to unfold the next layer of upstream processes.

Does this help you?

**Comment by xiaoshir** [comment]
Thanks for the help. But unfortunately the issue remains: I can't check the upstream processes (see below, that's all I see)
![image](https://user-images.githubusercontent.com/28433916/57294429-f1db6180-70c7-11e9-8981-57bd4502d995.png)

**Comment by dgdekoning** [comment]
Mmm, that should not be happening. Can you check to see if there are any error messages from the activity-browser? Is it the same as the one you noted at the beginning?

> AttributeError: 'SankeyGraphTraversal' object has no attributt 'nodes_set'

**Comment by xiaoshir** [comment]
No, not really. See below for the conda prompt window when I first tried with Graph Explorer and then Sankey
![image](https://user-images.githubusercontent.com/28433916/57296454-551bc280-70cd-11e9-9773-78694a832070.png)

**Comment by dgdekoning** [comment]
You're right, no (unexpected) errors and everything comes up correctly. I've created the same setup (medium voltage vs GWP 100a) but I can't reproduce the error on my end.

**Comment by xiaoshir** [comment]
Ok...a few questions:
- How did you install/update the development version?
- Do you use mac/windows?
- Is there any other things that I could check?

**Comment by dgdekoning** [comment]
Lets see.

- Tried both the dev and stable versions. Installing them with `conda create -n <env_name> activity-browser` or  `conda create -n <env_name> activity-browser-dev` after adding the channels required in the correct order (I think you've ordered them correctly as well, `conda-forge` > `cmutel` > `bsteubing` > `haasad`). It worked the same for me with both Python 3.6 and Python 3.7.

- I ran the tests on a Windows 10 machine.

- There are some things of the top of my head you can try (ordered by least-to-most time-consuming to try):

  - While the activity-browser is running and you've got the graph explorer open, point your (chrome-based) browser to http://127.0.0.1:3999. There should be at least one inspectable page called 'navigator.html', see if there are any errors in the console tab.

  - Download the source code (this repository) and instead of starting the activity browser with `activity-browser` from the anaconda prompt, go to the folder where you've put the source code and run the code with `python run_activity_browser.py`. If this solves your issue there is likely a problem in the build process.

  - Try and delete / re-import the biosphere and ecoinvent databases.

  - If possible, can you try and install the activity-browser on a different but similar machine? See if the same issue occurs.

**Comment by StpdFox** [comment]
Closed this issue due to inactivity, If the issue still remains please reopen this and we'll take a look at it!
