### ISSUE TITLE
Biosphere3 datasets can be opened under "Activities", but no data is displayed

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#245]
I think in the mid-term we'd like to display the data (such as below and perhaps characterization factors?), but for now let's maybe just prevent that empty activities are being displayed. This relates also to #244 

{'categories': ('air',),
 'code': 'eba59fd6-f37e-41dc-9ca3-c7ea22d602c7',
 'name': 'Carbon dioxide, non-fossil',
 'database': 'biosphere3',
 'unit': 'kilogram',
 'type': 'emission'}

**Comment by dgdekoning** [comment]
Currently working on it, but I think we do want to show empty activities (to allow users to quickly create multiple new activities before adding exchanges).

There are several possible ways I can see to avoid opening biosphere flows:

- By checking for the categories field, which may cause trouble later if we want to allow users to add their own biosphere flows.
- By keeping a list of 'biosphere' databases in the project settings, which means users have more customization options but also means more checking for edge cases (users putting `process` and `emission` activities in the same database)

**Comment by dgdekoning** [comment]
Perhaps by checking for a 'production' exchange?

```python
act = bw.get_activity(key)
if not act.production():
   # do nothing
else:
   # open tab
```
