### ISSUE TITLE
Fail to import ecoinvent into ActivityBrowser/brightway2

### ISSUE THREAD

**Issue by DongXiutang** [LCA-ActivityBrowser/activity-browser#247]
Hello everyone,
I'm trying to import ecoinvent 3.5 cutoff into the ActivityBrowser. The import takes a lot of memory and CPU of the PC and didn't work at last. The import speed is also very slow. In the Import Wizard, it will take about 3 hours to extract XML data from ecospold files and a more longer time to apply brightway2 strategies. 
Before using ActivityBrowser I try to import ecoinvent 3.5 into jupyter-notebook, which also failed.
The computer has a 16G RAM and i7 processor. So i really cannot figure out, why the import didn't work. Maybe there is something to do with the database or software?
Has anyone encounter the same problem? Please write me back. Thanks a lot.

**Comment by nheeren** [comment]
Did you use the fiel `ecoinvent 3.5_cutoff_ecoSpold02.7z` from https://v35.ecoquery.ecoinvent.org/File/Files? I once downloaded the wrong archive file and had a similar issue.

**Comment by DongXiutang** [comment]
> Did you use the fiel `ecoinvent 3.5_cutoff_ecoSpold02.7z` from https://v35.ecoquery.ecoinvent.org/File/Files? I once downloaded the wrong archive file and had a similar issue.

hello, Niko
Thanks a lot for the reply. I use the local directory with ecospold2 files rather than 7z-archive. The license belongs to my university so i didn't download it myself. My tutor gave me the ecoinvent 3.5 directly through USB.
I'm also wondering if there is something to do with the database.

**Comment by DongXiutang** [comment]
The latest import took also a very long time (about 16h ) and it seems like the computer didn't continue working at the end. (like the picture below). 
![5](https://user-images.githubusercontent.com/52200465/60174047-7a48c980-9810-11e9-8d30-b3af19bd36e2.PNG)
The AB shows that 15876 activities are imported. The database contains 16022 activities. 
![4](https://user-images.githubusercontent.com/52200465/60174426-48843280-9811-11e9-96c5-ad7f6361fb4f.PNG)

And i also want to know, I have tried a lot of times to import ecoinvent 3.5 and always failed. If this can be a reason, why is the import so slow? Maybe every import will generate some files (not sure) that can influence the processing speed?

**Comment by dgdekoning** [comment]
Hello @DongXiutang!

This seems like an incredibly frustrating problem for you. May I ask for some more information?

- Are you using the stable or development version of the activity browser (`activity-browser`, version `2.3.1` or `activity-browser-dev`, version `2019-05-29`)?
- You note that you've tried to import the database multiple times, is this in the same project or in a different project each time?

What I think is happening is that an error occurs while the activity browser is attempting to write the imported data to the database. This can leave you with a half-filled database, which it seems you have.

I'm going to set up a test environment and attempt to recreate your issue.

**Comment by DongXiutang** [comment]
Hello, @dgdekoning 

Thanks for ur reply!
- The latest import (shown in the picture above) is based on the version 2.3.1. But i've already installed the activity-browser-dev package and started a new import again. It still doesn't look better.
- I've tried not only to import the database in different projects but also import the database mulitiple times in a same project. For the second situation, i would firstly delete the half-filled database in order to start a new import.

**Comment by dgdekoning** [comment]
I've tried to import the same way (selecting a directory containing the ecospold2 files) and was able to import them without issue.

![Capture_issue247](https://user-images.githubusercontent.com/11406390/60193003-31f0d200-9837-11e9-9698-205b78e4cfde.PNG)

My laptop has an i7, 8gb of ram and an m2 ssd. But even with a normal hard disk drive multiple hours is incredibly slow.

How full is your disk? I think during the writing process the database can grow quite a bit, but it should be around ~500-600 mb with just biosphere3 and ecoinvent 35 cutoff.
You can find your brightway directory in your local appdata folder (in your case I think the default would be `C:\Users\dong\AppData\Local\pylca\Brightway3` ). This folder should contain all of the projects you've created in the activity browser, possibly even those you've deleted as windows doesn't like deleting projects through the activity browser.

Something else I noticed is that during my import the `fix-ecoinvent-flows-pre35` migration was not skipped. Perhaps that is causing the problem with only 15876 records being written?

Can you check your version of `bw2io` for me? I think it will be either `0.7.4` or `0.7.5`.

I don't know how familiar you are with python but you can try to force brightway to recognize that you have the migration installed by [using this](https://stackoverflow.com/questions/51290274/apply-strategies-on-database-cant-find-a-migration-that-is-present-in-the-fol).

I have to catch a train right now but will check in again tonight.

**Comment by DongXiutang** [comment]
The version of bw2io is 0.7.5.
I think there is nothing to do with the laptop. But you said that the database is around 500-600mb. Do you mean that the folder including all the ecospold2 files is so big? Because the ecoinvent 3.5_cutoff by me is quite big (17.9GB).

**Comment by dgdekoning** [comment]
Interesting!

I'm using the cutoff35.7z file downloaded when logging into the ecoinvent website (through the wizard). The datasets folder inside with the ecospold2 files for ecoinvent 3.5 cutoff is just under 2 gb. 
Do you know why your folder is so much larger, maybe there is some customized data in there?

What I meant with 500-600 mb is the sqlite `databases.db` file which is created by brightway for each project (can be found within the `lci` folder inside each project). The biosphere3 database and any other imported or created databases are stored inside this file.

If I had to hazard a guess I would say that the importing and processing of data takes so long because of the size difference.

**Comment by dgdekoning** [comment]
Just a quick update: I've also manually imported the ecospold files and explicitly disabled the `fix_ecoinvent_flows_pre35` migration. The resulting database still contained 16022 records, so it seems that the missing migration was not the cause of the failed import.

(If possible) can you find out the reason for the large difference in folder size and report back?

**Comment by DongXiutang** [comment]
Thanks a lot. I'm also working on this problem. Now I also think the problem lies in the size of the database (maybe). 
The license for ecoinvent belongs to my university so I need to wait for a reply about the folder size from my tutor. Once I get the reason, i'll report back. Thanks again.

**Comment by dgdekoning** [comment]
You're very welcome, I hope you're able to resolve the issue!

**Comment by DongXiutang** [comment]
Hello, Daniel

I get a new version **ecoinvent 3.5_cutoff_lcia_ecoSpold02** and the datasets folder is about 7GB.
The old version is **ecoinvent 3.5_cutoff_lci_ecoSpold02** . 
But I get new error wenn i import this new database:
![importError](https://user-images.githubusercontent.com/52200465/60428846-19e3ce80-9bfa-11e9-8983-cc0cfff325b8.PNG)
Can you please help me to figure out where is the problem this time?

**Comment by dgdekoning** [comment]
Hello, @DongXiutang,

I've traced the error into the ecospold2 extractor from brightway inside the [`extract_exchange` method](https://bitbucket.org/cmutel/brightway2-io/src/41649b5a98d4092e5a9a9ca9edcef6b97a2711b8/bw2io/extractors/ecospold2.py#lines-306:314) it expects the exchange to either be an 'intermediateExchange' or 'elementaryExchange', it looks like it raised an error because on importing your data it found an 'impactIndicator'.

I am not familiar enough with the ecospold2 format to say wether this is a case of malformed data or that brightway simply cannot handle that kind of data during import.

**Comment by nheeren** [comment]
It sounds like this may have to do with your data file after all. @DongXiutang, try to download the database again.

> Did you use the fiel `ecoinvent 3.5_cutoff_ecoSpold02.7z` from https://v35.ecoquery.ecoinvent.org/File/Files? I once downloaded the wrong archive file and had a similar issue.

**Comment by dgdekoning** [comment]
Yes, I was just looking at the database files and was going to suggest the same thing @nheeren!

**Comment by dgdekoning** [comment]
Hey @DongXiutang, were you able to resolve your problem with importing? Did the other dataset files mentioned by nheeren work?

**Comment by DongXiutang** [comment]
Hello,
I've solved the problem by importing another dataset. I believe the dataset that mentioned by nheeren is the right one. Thanks for your concern.

**Comment by dgdekoning** [comment]
Excellent! I've made a note to improve the error handling and reporting when importing datasets through the wizard, thanks for your help and communication :).

**Comment by marc-vdm** [comment]
Hi @ZhiCaoIE 

Thanks for letting us know about this challenges, though I'm not sure what exactly your problem is, but I'll try to answer in general:

For ecoinvent databases, I would recommend using our importer, which is shown in our [tutorial here](https://www.youtube.com/watch?v=qWzaQjAf8ZU). This way you can only download the databases compatible with AB, that way, it will be less likely to have issues importing databases!

If you have more questions or comments just let us know!
