### ISSUE TITLE
Importing Non-ecoinvent LCI from CSVs

### ISSUE THREAD

**Issue by AkshatSudheshwar** [LCA-ActivityBrowser/activity-browser#257]
Hello,

Is there some way to simply import a CSV LCI-database into the Activity-Browser? I will be using an LCI that is simply based on biosphere flows, and wanted to apply the assessment methods implemented in the Activity-Browser.

Any help would be really appreciated.

Thank you and regards
Akshat

**Comment by dgdekoning** [comment]
Hey Akshat,

Currently, the activity browser does not yet support loading in data through CSV files and this is definitely high on our list of things to do.

If you have some experience working with python / brightway2 you should be able to [load in your data](https://docs.brightwaylca.org/intro.html#importing-and-exporting) through a script and then go into the activity browser to apply assessment methods from there.

I hope this helps some,
Daniel
