### ISSUE TITLE
GUI: Search is case sensitive

### ISSUE THREAD

**Issue by levonamatuni** [LCA-ActivityBrowser/activity-browser#269]
Could be useful to make the 'Datasets' search field being case-independent. For instance, right now it finds Gold activity in the biosphere3 only if you type ‘Gold’, doesn’t work for ‘gold’. 
Should be easy to fix. 
Thanks!

**Comment by dgdekoning** [comment]
Found where to apply the fix!

https://github.com/LCA-ActivityBrowser/activity-browser/blob/c27c8b09b870d2ddf78f118f587010127a70e941/activity_browser/app/ui/tables/inventory.py#L297-L310

The simplest solution is to wrap `filter` and `x` in  `str().lower()` in the comparison. This will even allow the tuples to be searched with partial strings (eg. `ean` _will_ find matches with `('water', 'ocean')`.

The comments note that there is likely a better solution so I'll check if there is anything I can do that way.
