### ISSUE TITLE
Read-only checkbox disappeared on MacOS

### ISSUE THREAD

**Issue by nheeren** [LCA-ActivityBrowser/activity-browser#278]
Hi. Not sure what information you guys need to troubleshoot. _(You may want to use bug report templates in the future: https://help.github.com/en/articles/creating-issue-templates-for-your-repository)_

I am using MacOS 10.14.6 and activity-browser 2.3.3-py_0 and now get this funny looking display:

<img width="603" alt="Screenshot 2019-09-02 at 15 05 40" src="https://user-images.githubusercontent.com/5136954/64116700-53b88900-cd93-11e9-976b-9ac3de18117b.png">

Let me know if I can provide more details.

**Comment by dgdekoning** [comment]
Ha! My first MacOS-only bug. It looks like the checkbox moved all the way over to the start of the row.

Is the functionality impacted as well? Or can you still `tick` the checkbox by clicking in the read-only field?

**Comment by dgdekoning** [comment]
The issue is likely caused by the fact that I've switched the database table over to a QTableView instead of the QTableWidget. This class doesn't allow for simply adding checkbox widgets into the table directly, so I had to get creative with a delegate and its `paint` method (see [here](https://github.com/LCA-ActivityBrowser/activity-browser/blob/e47fa2d28366050756f3468082a70e8c15bd0dbf/activity_browser/app/ui/tables/delegates.py#L94-L114)).

If you have the time, can you test if it improves things when changing the last two lines of that paint method from:
```python
# button.text = "False" if not value else "True"  # This also adds text
QApplication.style().drawControl(QStyle.CE_CheckBox, button, painter)
```
to:
```python
button.text = "False" if not value else "True"  # This also adds text
QApplication.style().drawControl(QStyle.CE_PushButton, button, painter)
```

**Comment by dgdekoning** [comment]
Something else that might help is adding `painter.save()` at the start of the method and `painter.restore()` at the very end.

**Comment by nheeren** [comment]
Thanks!

> Is the functionality impacted as well? Or can you still `tick` the checkbox by clicking in the read-only field?

Hard to tell. It behaves very strangely and jumps around once pressed. Also, the checkbox only appears in the first row (biosphere3).

> If you have the time, can you test if it improves things when changing the last two lines of that paint method from:

Well, time could be an issue here 😅 I will try to give it a try.

**Comment by dgdekoning** [comment]
I found a different way of indicating the same checkbox information, which looks a lot better on windows too. I can look at the changes on linux from my end but I have no reliable access to a macOS device to test.

**Comment by nheeren** [comment]
OK. Should I wait for that and you tell me when to check? I may need some help using pre-release versions.

**Comment by dgdekoning** [comment]
I've built the new version as `activity-browser-dev`. You can use the [readme](https://github.com/LCA-ActivityBrowser/activity-browser#development-version) to install that specific version. Please give me a heads-up if this fixes the issue or not :).

A possible alternative to this checkbox painting is to just present the read-only/editable values as text. Completely avoiding the issue of macOS having some special theming going on.

**Comment by nheeren** [comment]
Thanks Daniel! I did `conda create --yes --name ab_dev activity-browser-dev`, which installed 
`activity-browser-dev      2019.09.02                 py_0    bsteubing`. 

The results looks rather similar: 
![Screenshot 2019-09-03 at 10 39 27](https://user-images.githubusercontent.com/5136954/64157698-72705b80-ce37-11e9-8913-fd9bf6598782.png)

**Comment by dgdekoning** [comment]
Welp, that is annoying.

**Comment by dgdekoning** [comment]
Pushed a new commit disabling the checkbox delegate, so now the `read-only` values are shown as 'true' or 'false'. The new development version should be done building in 10-15 mins.

**Comment by nheeren** [comment]
Does that mean you want me to test it or is that a temporary fix?

**Comment by dgdekoning** [comment]
If you could test it that would be great :), depending on time and other factors this fix could make it into the next stable release.

**Comment by nheeren** [comment]
Using `activity-browser-dev-2019.09.03`, I get: 
![image](https://user-images.githubusercontent.com/5136954/64166371-3d6c0500-ce47-11e9-8b21-f1f82fd1a965.png)

Clicking on it flips the value.

**Comment by dgdekoning** [comment]
Yeah, that is as it should work (ie. your 'biosphere3' database can now be edited, while the 'ecoinvent' database is read-only).

If I can't find a good fix for the macOS style/painting problem I'll add some text explaining how the read-only value works and can be changed. I'll leave this issue open in the meantime.

**Comment by nheeren** [comment]
let me know if i should test more. Cheers.

**Comment by dgdekoning** [comment]
I had some time to mess with this and found a possible solution using painter.translate instead of button.rect to determine where the checkbox is placed (). Also, instead of using QApplication to get QStyle the delegate is now using the QStyle from the option.

**Comment by dgdekoning** [comment]
And if that doesn't work there is also a method of flat out replacing the delegate with an actual checkbox widget again, but I couldn't get it working a 100% (actually clicking inside the checkbox messed everything up, while clicking anywhere else in the cell worked as expected).

**Comment by nheeren** [comment]
I hate to bother again, but macOS still seems to cause issues (current stable version; can test dev version later if required). Fortunately, it is more a visual thing this time.

<img width="597" alt="Screenshot 2020-04-24 at 10 31 50" src="https://user-images.githubusercontent.com/5136954/80192213-261c9a80-8617-11ea-94d3-16a9fd5df31b.png">

**Comment by dgdekoning** [comment]
Thanks for bringing it back up, was dreading that the change to a newer version of Qt would cause these kinds of issues (as in, Qt fixes things on their end, meaning my fixes now cause the issue instead).
If you can, please check if this same issue occurs in the dev version, if so I will remove the 'fix' I introduced for the initial issue and see if that corrects the offset.
