### ISSUE TITLE
Segmentation fault at launch

### ISSUE THREAD

**Issue by e4BdSBmUzHowFico5Ktn** [LCA-ActivityBrowser/activity-browser#288]
I started this issue on the LU-CML fork before realizing it was outdated, I removed my AB environment and re-installed as per the instructions. I ran into the same issue, which is;

I just tried installing AB on Linux Lite (Ubuntu 18.04 derivative) on kernel 5.2.11 and I get a segmentation fault when launching AB.

`conda config --show channels` shows correct output.
Creating and activating AB environment gave no errors.

When I try to run `activity-browser`, I get this error after a few seconds;
`Brightway2 data directory: /home/m/.local/share/Brightway3
Brightway2 active project: default
[1:1:0100/000000.416508:ERROR:broker_posix.cc(41)] Invalid node channel message
Segmentation fault (core dumped)`

Can anyone to help out? If you need more info, let me know!

**Comment by dgdekoning** [comment]
Thanks for getting in touch, can you post the list of conda packages (```conda list```) in the `ab` environment? The one thing that jumps out at me is that your kernel is quite new which shouldn't make much of a difference.

**Comment by dgdekoning** [comment]
Alright, good news is that the newer kernel is no issue (manjaro 18.1.0, kernel versions `4.19.69` and `5.2.11` both work without issue). Bad news is that there is no handy explanation I can give for the segfault at this moment.

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
Here's the `conda list` output:
https://pastebin.com/N0dNRHum

**Comment by dgdekoning** [comment]
Great thanks! First thing: Are you certain `bsteubing` is placed before `haasad` in the conda channels, as your version of the activity browser is `2.2.5` (the last version to be published on the `haasad` channel, all newer versions come from the `bsteubing` channel)?

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
I indeed had bsteubing after haasad. I`ve resolved it, and tried updating, this did not solve the error. I`ve removed the AB env and ran `conda update conda` and did the install again, still with this output:

`-hiding tab: Project History
-hiding tab: Activities
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset metadata.
Reset project settings directory to: /home/m/.local/share/Brightway3/default.c21f969b5f03d33d43e04f8f136e7682
Brightway2 data directory: /home/m/.local/share/Brightway3
Brightway2 active project: default
Segmentation fault (core dumped)
[1:1:0100/000000.887580:ERROR:broker_posix.cc(41)] Invalid node channel message`

My current `conda list` output is here:
https://pastebin.com/yc01BPqS

**Comment by dgdekoning** [comment]
Thanks for trying anyway :)

Searching for the error itself yields a number of Qt related issues (like [this one](https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1761708)) and I am kind of afraid the only way to fix this for your case (from our end) is to replace the activity-browser `PyQt` implementation with the `PySide2` one (possibility of doing this is discussed in [this issue](https://github.com/LCA-ActivityBrowser/activity-browser/issues/184#issuecomment-525612215))

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
I hope this will progress the debate under #184, I will monitor the discussion and see what comes out.

Also -and I feel its a bit over the top to Fork-PR for this- the readme installation instructions say three under 'Configure conda channels' where it should be four now after bsteubing was added.
