### ISSUE TITLE
Import ecoinvent 3.6 cutoff fails with InvalidExchange exception

### ISSUE THREAD

**Issue by levonamatuni** [LCA-ActivityBrowser/activity-browser#292]
Have recently imported (online) the 'cut-off36' Ecoinvent database into my recent project. It shows 0 records only and does not react on 'Delete database' function. Possibly I had to import the 'cutoff36' version (without the dash).

In general, importing a new Ecoinvent database proposes to download either cut-off Or cutoff version, which is confusing.

Thanks!

Levon

**Comment by dgdekoning** [comment]
This is partially similar to #289 which also has to do with database importing. The two different versions issue is resolved in the newest development builds (pull-request #290), `cut-off` is the correct one for 3.6, `cutoff` for previous versions.

Can you install [`activity-browser-dev` instead](https://github.com/LCA-ActivityBrowser/activity-browser#development-version)?

Are there any error messages in the prompt where you opened the activity browser?

**Comment by dgdekoning** [comment]
@levonamatuni, did the newest development version solve your issue?

**Comment by levonamatuni** [comment]
@dgdekoning The newest version shows properly the names of the databases to be imported and allows to remove the empty database; however, 3.6 version is still impossible to import because of the discrepancy with some exchanges during its extraction.

**Comment by dgdekoning** [comment]
But only sometimes?

**Comment by dgdekoning** [comment]
So, a quick test on windows 10, python 3.7 shows the import succeeding in a 'clean' project, which only contains the required `biosphere3` database.

It also succeeds importing in a new project with a previous version (3.5) of ecoinvent.

But at the same time I have seen it fail on my device under the same conditions before, and I have seen it fail on someone else's device with the same exception thrown. I am very close to calling shenanigans.

Possible things to consider:

- Decompressing into a temporary directory causes problems (a failed import leaves traces and causes all following imports to fail?) (possibly related to #289)
- Interference from some existing settings / data in older projects.

**Comment by dgdekoning** [comment]
Found a possible reason:

![image](https://user-images.githubusercontent.com/11406390/67379620-7a23c500-f589-11e9-8e4f-a6a50ba7404d.png)

![image](https://user-images.githubusercontent.com/11406390/67379679-8445c380-f589-11e9-82bd-502f13d8f808.png)

There are new biosphere3 flows. So the solution to the importing issue would be to either update the existing `biosphere3` database in some way or to straight up remove all databases (create a new project) and reimport the `biosphere3` flows.

**Comment by dgdekoning** [comment]
Alright, so I just noticed that #213 has the same underlying reasons as this issue.

My proposed solution to this is two-parted:

- Create a warning / exception that is triggered specifically when importing EcoInvent and receiving an `InvalidExchange` exception, basically notifying the user that their `biosphere3` database is out of date.
- Create a new main-menu option which uses the [bw2io](https://bitbucket.org/cmutel/brightway2-io/src/1d1b74b92d98b2e00a69162360a7a469f8641044/bw2io/data/__init__.py#lines-297:318) functionality that adds new biosphere flows to the biosphere3 database to attempt and update the existing biosphere3 database to the latest version.
