### ISSUE TITLE
Potentially unused dependency

### ISSUE THREAD

**Issue by tur-ium** [LCA-ActivityBrowser/activity-browser#316]
Hi, I am new to activity-browser and Brightway 2 so apologies as I am not too familiar with the code structure. I noticed when installing that BeautifulSoup is listed as a dependency when installing via conda but it doesn't seem to be used in the code. Maybe I am wrong as I am just using GitHub search, but reducing the number of dependencies would be handy for people running on limited disk space.

**Comment by dgdekoning** [comment]
Hey @tur-ium, you are indeed correct in that the activity browser itself doesn't make use of the BeautifulSoup dependency. That dependency is being used by the [`eidl` package](https://github.com/haasad/EcoInventDownLoader/blob/master/conda-recipe/meta.yaml) (EcoInventDownLoader) to work sniff around the [ecoinvent website](https://www.ecoinvent.org/) page and find possible versions and types of datasets to download.

**Comment by tur-ium** [comment]
Aha ok! Thanks for clarifying!
