### ISSUE TITLE
Tagged graphs with non-unitary activities

### ISSUE THREAD

**Issue by demay-jos** [LCA-ActivityBrowser/activity-browser#317]
Hello, 
I've been using the function analysis.recurse_tagged_database() to plot my LCA by tags for more clarity. However I've noticed that my biosphere exchanges are multiplied twice which at the end doesn't give the accurate impacts for the tags. However the LCA is runned perfectly and give the right value. Because some of my activities don't always have an unitary output, I was wondering if the analysis.recurse_tagged_database() was working only with unitary activities?

Just to give an example: 
My FU consumed 10 kg of Activity_1
Activity_1 is defined as: output (production)=10kg and biosphere input = 2 kg of CO2 (tag CO2_emissions)
The lca calculation will give a final result of 2 kg of CO2 (ok)
But the graph generated by the analysis.recurse_tagged_database() function will give an output of 2*10=20 kg CO2... which is unaccurate..
Could you help me with that ?
Regards, 
Josephine

**Comment by demay-jos** [comment]
Dear Daniel,

Thank you for your answer. I'll post my question where you sent me.

Best regards,
Josephine

Le mar. 5 nov. 2019 à 15:40, Daniel de Koning <notifications@github.com> a
écrit :

**Comment by dgdekoning** [comment]
The issue is [being worked on](https://bitbucket.org/cmutel/brightway2-analyzer/issues/4/tagged-graphs-with-non-unitary-activities), I'll keep this issue open until it is resolved :).

**Comment by StpdFox** [comment]
Closed due to inactivity, dead links to the issue might even mean it got resolved. 
If this is not the case and you still experience this problem just reopen this issue and we'll take another look at it.
