### ISSUE TITLE
How do you add activities to a calculation setup?

### ISSUE THREAD

**Issue by tur-ium** [LCA-ActivityBrowser/activity-browser#319]
Hi, trying to create a process. I am confused as to how to add products to a calculation setup. I have tried dragging each type of activity from the datasets panel to the left, but to no avail. A tutorial on how to use activity-browser would be awesome!
![image](https://user-images.githubusercontent.com/20628325/68237403-f5ac5a00-fffe-11e9-90df-343f34ab5f9c.png)

**Comment by dgdekoning** [comment]
Hey @tur-ium,

I completely agree that a tutorial is overdue (see #158).

The way calculation setups work in brightway is that you place activities in them that 'produce' a product (functional units) using technosphere and/or biosphere inputs. Biosphere 'activities' by themselves are not valid things to use in a setup (eg. Determining the metal depletion of the natural resource Xenon versus determining the metal depletion for a process which uses xenon to produce a lamp).

What you can do is either import an existing technosphere dataset (ecoinvent, forwast, etc.) or build some simple toy models yourself (create a database, within that database create activities, drag and drop activities into the relevant tables to become exchanges for that activity).

Note that I'm leaving out a _lot_ of information here.

**Comment by RunshengSong** [comment]
@tur-ium 
I think you will need to import a database first that contains technosphere dataset, and then drag it from left to right in the screen you provide above.

Additional improvement here would be a adding a `Add` button in the panel on the right.

**Comment by dgdekoning** [comment]
This is now covered in the [wiki](https://github.com/LCA-ActivityBrowser/activity-browser/wiki/Starting-out#creating-a-calculation-setup), closing this for now.
