### ISSUE TITLE
Prettier graphs

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#350]
Should we put some effort in making graphs prettier?
The graphs currently look very much like a 10year olds birthday party when showing many different items. I think having prettier graphs would increase the attractiveness of the AB, and hopefully increase its adoption.

Perhaps adding colour palettes through matplotlib or migrating to seaborn would be a good idea?
The most recent version of Seaborn is already in the standard ab_dev env in conda.

I\`d be happy to take on this task myself, but I`d like some input from other before I start on something that nobody but me would like!

**Comment by bsteubing** [comment]
In the longer term, graphs should not only be prettier, but also interactive (e.g. providing information on hover, or permitting to use a right-click to directly go to a specific process, etc.). 
I have had Bokeh in mind for better graphs; however, bokeh still had an issue with non-numeric (long names) on the axes. See: https://github.com/bokeh/bokeh/issues/8169

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
The issue you mentioned seems to have been resolved ;)
Bokeh looks good indeed, I`m pretty sure matplotlib [so also seaborn?] has some interactive features as well, but Bokeh definitely seems better suited for interactivity.

If we could come up with some features that should be added, what would other features be?
- [right] Click to view process 
- ...

I think I could work on it every now and then between other work, as prettier visualizations is also in my interest! 
If we decide to do this, I`ll first start with moving over all current functionality [cutoff menu etc] to Bokeh -perhaps moving the cut-off menu to Bokeh.

In terms of licensing for Bokeh, Im not sure if LGPL is compatible with BSD, or that we would be required to shift to BSD then.

**Comment by dgdekoning** [comment]
With regards to the licence, my reading of it is that as long as we don't include (modified) source code we should be fine as we are. Otherwise this should have come up much sooner, seeing that Seaborn (which has been part of the requirements for a while...) also [uses the BSD 3-clause licence](https://github.com/mwaskom/seaborn/blob/master/LICENSE).

Though really, I am not a licencing lawyer and might be reading it wrong entirely.

**Comment by bsteubing** [comment]
@e4BdSBmUzHowFico5Ktn could you bring up this issue next time we meet? I have some notebooks where I have tried out stuff with Bokeh - it is pretty cool, except for the pending issue of labels... bokeh/bokeh#8169

**Comment by bsteubing** [comment]
Altair could be another alternative: https://altair-viz.github.io/

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
Some bulletpoint updates from recent searching and discussions:

- [Altair](https://altair-viz.github.io/) does not generate figures but generates JSON, that can be turned into figures with some programs or HTML, it uses BSD licensing
 - [Folium](https://pypi.org/project/folium/) is a great libary for producing geographical stuff like items on maps and chloropeth maps, but also requires HTML, it uses MIT licensing
- [Bokeh](https://bokeh.org/) also works best with HTML based figures, it uses BSD licensing

So no real progress on libraries that can really NOT be used. However, of all these, I feel that Bokeh has the largest userbase, which might be helpful in developing, I will try to integrate that for starters.

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
It`s been a while and I`d like to share this additional info:
This is for tables (and sort of figures) but I think this addition could have added value in data interpretation. As it's rendered as a webpage, it should be possible to show it through AB.

[Reddit thread with video demo of dtale](https://www.reddit.com/r/datascience/comments/f6xk72/for_any_python_pandas_users_out_there_heres_a/)
[Interactive demo of dtale](http://andrewschonfeld.pythonanywhere.com/dtale/main/1)
[Github of dtale](https://github.com/man-group/dtale)

**Comment by dgdekoning** [comment]
Another figure plotting library I recently came across is [Plotly](https://plot.ly/python/).

**Comment by marc-vdm** [comment]
currently being improved
