### ISSUE TITLE
Inconsistent channels in development section of readme

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#367]
The current instructions state that the following command should be used to install the development version:

```
conda create --yes --name ab_dev --channel conda-forge --channel pascallesage activity-browser-dev
```

Specifying some but not all of the necessary channels can lead to weird behaviour. You could just list everything, or refer to the above section on channel configuration (not everyone does this). Not sure what you think would be better.

**Comment by dgdekoning** [comment]
Fair point, will make sure to specify everything.
