### ISSUE TITLE
[bug] cannot run scenarios and non scenarios of same calculation setup at same time

### ISSUE THREAD

**Issue by e4BdSBmUzHowFico5Ktn** [LCA-ActivityBrowser/activity-browser#382]
When running a calculation setup without scenarios, and then after, running the same calculation setup with scenarios removes the original tab, this makes it impossible to switch between tabs, a potential fix could be to add something like 'scenarios' to the name of the results tab?

**Comment by dgdekoning** [comment]
While I agree that the difference between the two types of analyses should be clearer, this is not actually a bug. AB should do its best to ensure that the first scenario 'default' cannot be edited directly and assumes that this scenario represents the baseline (what you get when you run do not use scenarios).

Adding functionality to differentiate the two kinds of analyses might still be a good idea.

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
Fair point that this is not a bug, perhaps I should have said older functionality that now reduces functionality ;)

I think there are three options,
1) current behaviour - do nothing
2) a new lca results tab is opened when calculating in both modes, and the lca setup tab just spawns a new tab, which I think is the easy fix. This would leave the possibility open for changes to be made (and forgotten) to the setup and then running it again in the different mode, giving different results.
3) a new lca results tab is opened when calculating in both modes, and the lca setup tab (re)calculates both modes, which is the slightly harder fix. This would give consistency in the results (or at least, the inputs) between the two modes.

As the purpose of using scenarios is to alter inputs anyway, I am not sure which of the last two options would be better.
