### ISSUE TITLE
[enhancement] rename existing project/database

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#390]
Renaming existing projects is currently impossible, perhaps this could have added value?

edit: I understand this is technically possible by doing copy+delete, but this might not be very intuitive for most users. I think this is also the case for databases within projects

**Comment by dgdekoning** [comment]
While both of these sound like really useful things to have, I am very hesitant to make changes to the more fundamental parts of brightway in a (technically) separate project.

For projects I can't find any functionality inside brightway that allows the user to rename the project. While it is technically possible to bundle the copy&delete steps in a `rename` method for the activity browser, it would also be strange to the user that a simple rename action can take anywhere from a few seconds to 30 mins (depending on size of the project or database).

If properly described (ie, the user is given a warning what renaming actually does) it would be a nice extra to have.
