### ISSUE TITLE
monte carlo, slow for small n + datasets?

### ISSUE THREAD

**Issue by lugasraka** [LCA-ActivityBrowser/activity-browser#397]
Hello, I'm trying to test the uncertainty feature by running a simple MC, but the ab freezes if I set up n = 100 or even 1000 for 1 dataset from Ecoinvent (landfill disposal). Is it normal and that's why the n = 10 by default? How do I circumvent this to run an MC with large iterations?

**Comment by dgdekoning** [comment]
It is somewhat normal yes, the calculation setup (X functional units * Y impact categories) is completely recalculated for each Z iteration.

A possible way to circumvent this issue _if you're only after the calculation results_ would be to use the underlying brightway framework to run the calculations. This will likely lead to a slight speed improvement at the cost of requiring some additional work to set up all the calculations.

**Comment by lugasraka** [comment]
Hello @dgdekoning alright!
If I have created a calculation set up in AB, would it be automatically created also in BW2?

**Comment by dgdekoning** [comment]
Yes! Things such as calculation setups, databases, methods and parameters that are persistent in the AB (i.e. still exist after closing and reopening the AB) are managed by brightway.

Please see [this](https://2.docs.brightway.dev/) for additional explanation and documentation of brightway2 functionality.

**Comment by bsteubing** [comment]
Hello @lugasraka it is indeed expected (although still much faster than in other LCA software). I will close this issue, but thanks for your question.

**Comment by lugasraka** [comment]
Hello @bsteubing yes thanks for the clarification!
I also look forward to the wikipage if there's one coming up 👍
