### ISSUE TITLE
Advanced activity search

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#4]
In order to explore a database with the activity browser it would be nice to have an advanced search feature, where one can filter for different attributes:
- name, search string contained in name
    - maybe even fuzzy matching with [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy)
- activity type
- location
- reference product
- economic sector (via ISIC code)
- biosphere flows (see #3 )

Below is a screenshot of a tool with some of these capabilities that I built some time ago:
<img width="1394" src="https://cloud.githubusercontent.com/assets/11636405/26296796/9457ed06-3ed0-11e7-86f3-934124f09f5c.png">

**Comment by TMillross** [comment]
As a futher extension of this enhancement: perhaps we could implement the Word2Vec of [1] as described in section 4.2 of [2].

[1] [Mikolov et al.](http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf)
[2] [Kuczenski et al.](https://www.researchgate.net/publication/305821063_Semantic_catalogs_for_life_cycle_assessment_data)

**Comment by bsteubing** [comment]
Searching in the new dataframe tables and with two fields and a logical operator in between is much better and faster now than anything we had previously.

**Comment by xiaoshir** [comment]
> Searching in the new dataframe tables and with two fields and a logical operator in between is much better and faster now than anything we had previously.

Can you give an specific example?

**Comment by bsteubing** [comment]
Hi Shirley, could you please try to update your AB to the latest development version? That will enable this feature.

**Comment by xiaoshir** [comment]
> Hi Shirley, could you please try to update your AB to the latest development version? That will enable this feature.

Yes, I just installed it in a new env. It looks like I should call it by "activity-browser-dev", and I also can see as a installed package in my environment (2.2.5. dev), but somehow it is "not recognized as an internal or external command". Do you know what could be the reasons? I can still call "activity-browser" in this env though, but it looks like the stable version.

**Comment by bsteubing** [comment]
you should call it using "activity-browser". Make sure you have the conda channels configured as stated in the AB installation guide. Order matters and the bsteubing channel needs to be added.

**Comment by ntropy-esa** [comment]
Indeed, very important to run: `conda config --append channels bsteubing` 
I kept updating without seeing any changes in the past few weeks. Thanks for the reminder.
