### ISSUE TITLE
Versioning, Changelog, Milestones

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#40]
We need to come up with a system to plan the development. The current CHANGES.txt file is not the best way forward in my opinion. I have no experience yet with the github projects and milestones, but it appears to work very well in other projects.

I think it would be useful to translate things mentioned in #1 and also some of the very broad issues like #21, #22 and #23 to projects and milestones or something similar. I think an issue should ideally be small and centered around one problem that can be resolved with a single pull-request (or a more general discussion like here).

Other projects use certain milestones to define when the next release is ready. We are now at the somewhat random version number `2.2.1`. I think it makes sense to tie the _stable_ release of the `activity-browser` package on conda to a version number. Additionally the most up-to-date state of AB is available as `activity-browser-dev` (with version number `2.2.1.dev`).

Happy to hear any inputs/suggestions/opinions

**Comment by marc-vdm** [comment]
Closing this as resolved. 

Current state:
- We have 1 stable release version, available on conda-forge
- We use semantic versioning
- Milestones are added to issues or PRs so it's clear when something will be fixed/implemented
