### ISSUE TITLE
no "rest" in EF contributions when aggregated by "categories"

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#406]
bars don't add up to 100%, which is probably due to the "tuple" nature of the categories compared to the "string" nature of the "rest". Pandas throws an error...

**Comment by dgdekoning** [comment]
The pandas error at least should now be resolved and 'rest' will show up again.

What I did notice and am unsure if I should fix in some way is that any negative impacts included in the dataframe will cause the plot to stretch the bar beyond the 'relative' 0-1 scale.
