### ISSUE TITLE
Filtering and aggregation for LCI

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#407]
Similar as for the contribution analyses, aggregation (by flow, categories, etc.) and filtering (e.g. searching for "carbon, di..." and finding all flows that contain this string) would be very helpful. 

E.g. if I quickly want to see the lifecycle carbon dioxide emissions, I could filter by "carbon, di" and then aggregate by flow and would get a single number (sum over all compartments such as "air, low population density", etc).

**Comment by bsteubing** [comment]
Filtering is much more interesting than aggregation

**Comment by marc-vdm** [comment]
For whoever picks this up. I had a look a filtering a while back too. This may be useful:

https://doc.qt.io/archives/qt-4.8/qsortfilterproxymodel.html#filtering

We already use the `qsortfilderproxymodel` for our tables though [`ABDataFrameView`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/b2d2f5884204eb59a1f3016b1dc41136c9d1f47c/activity_browser/ui/tables/views.py#L16) in the [proxy model ](https://github.com/LCA-ActivityBrowser/activity-browser/blob/b2d2f5884204eb59a1f3016b1dc41136c9d1f47c/activity_browser/ui/tables/views.py#L55). 

If I recall correctly, we need to add line-edits somewhere and can then connect those to the filter functionality of the proxy model. 

For the line-edits, I was thinking either a right click on the column header with 'add or remove filter', which then spawns a popup with a dropdown for filter mode (`contains`, `starts with` ...) and a line-edit.
Another option would be to add line-edits 'above' each column of a table where user can just type, though this would likely be hard to align with the column widths?
