### ISSUE TITLE
LCA results: "Export plot" not working (neither as .png nor as .svg)

### ISSUE THREAD

**Issue by CHarpprecht** [LCA-ActivityBrowser/activity-browser#419]
When I press the buttons on the bottom of the LCA results graphs to "export plot", nothing happens. 
No error occurs either. 
Export table as csv or Excel file is working well.

**Comment by dgdekoning** [comment]
Wow, that's bizzare. Thanks for creating an issue!

It looks like none of the plots have working png/svg saving. Will be looking into possible reasons and solutions as fast as possible.

**Comment by dgdekoning** [comment]
Found the reason, this was caused by the drastic actions I took to try and fix #286. Creating a new plot there without reconnecting the signal.

Fix will be coming soonish
