### ISSUE TITLE
Impact categories: Several search criteria

### ISSUE THREAD

**Issue by KarinTreyer** [LCA-ActivityBrowser/activity-browser#421]
In "Activities", we can search for two criteria. Would be great having that also for the Impact categories, so that I can e.g. search for "ReCiPe 2016" and "Hierarchist".

**Comment by marc-vdm** [comment]
We currently have a treeview that makes finding categories easier. I hope this has solved your issue. I hope you agree with me closing the issue, otherwise just re-open it and share your thoughts.
