### ISSUE TITLE
Impact categories: Save user-specified sets of LCIA categories

### ISSUE THREAD

**Issue by KarinTreyer** [LCA-ActivityBrowser/activity-browser#422]
Would be great if I could set up my own LCIA sets (i.e. a selection of Impact Categories) and save them so that I can choose from them within "LCA Setup - Impact categories". There are different sets which I repeatedly need in my work projects.

**Comment by dgdekoning** [comment]
Have been thinking on this a bit. Storing this kind of information would have to be done outside brightway, as it doesn't have the tooling for that kind of thing.

This seems like something that could be stored inside the activity browser settings.
But then the question would become weather to store it globally (ie. each project can use the set of impact categories, given that the required IC's exist in the project) or locally (only the current project can make use of the set of IC's), which would make it easier to build but more unwieldy.

Perhaps it might even be a good idea to allow the exporting of created sets, so they can be shared between users...

**Comment by CHarpprecht** [comment]
I agree with this need ;) 
I think it would already be very helpful to have it per project. If impact categories are added with brightway, they are also only available per project (as least the way how I did it ;) ), which is perfectly fine in my opinion, since they can then be used in different Calculation Setups.

**Comment by marc-vdm** [comment]
Users can currently `copy` calculation setups and drag impact category families from the tree view. 
This has made working with calculation setups much easier. I hope you agree with me closing the issue, otherwise just re-open it and share your thoughts.
