### ISSUE TITLE
Scenario-based LCA: KeyError when calculating scenario-based LCA

### ISSUE THREAD

**Issue by CHarpprecht** [LCA-ActivityBrowser/activity-browser#432]
Hi there,
I am trying to calculate a scenario-based LCA with the ab_dev (and ecoinvent3.6_cutoff) using the following excel file:
[scenario-import_dummydata.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/4983480/scenario-import_dummydata.xlsx)
Loading the excel file works, but when pressing the calculate LCA button, I always get a KeyError (see below).

So I was wondering:
1.	Is the scenario based LCA working in this case? (Since it is only the ecoinvent db, but no superstructure) or do I need to use the presamples based LCA?

2.	Is my excel sheet set up in the wrong way. Do I need to add something in the columns “from key” and “to key” ?

`  Traceback (most recent call last):
  File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\activity_browser\app\ui\tabs\LCA_setup.py", line 221, in scenario_calculation
    data = self.scenario_panel.combined_dataframe()`

`  File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\activity_browser\app\ui\tabs\LCA_setup.py", line 347, in combined_dataframe
    manager = SuperstructureManager(*data)`

 ` File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\activity_browser\app\bwutils\superstructure\manager.py", line 18, in __init__
    ] + [SuperstructureManager.remove_duplicates(f) for f in dfs]`

 ` File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\activity_browser\app\bwutils\superstructure\manager.py", line 18, in <listcomp>
    ] + [SuperstructureManager.remove_duplicates(f) for f in dfs]`

  `File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\activity_browser\app\bwutils\superstructure\manager.py", line 105, in remove_duplicates
    df.index = SuperstructureManager.index_from_keys(df)`

  `File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\activity_browser\app\bwutils\superstructure\manager.py", line 115, in index_from_keys
    if df.loc[:, EXCHANGE_KEYS].isna().any().all():`

  `File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\pandas\core\indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)`

`  File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\pandas\core\indexing.py", line 1289, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)`

`File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\pandas\core\indexing.py", line 1954, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)`

  `File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\pandas\core\indexing.py", line 1595, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)`

  `File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\pandas\core\indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing`

`File "C:\Users\xxx\.conda\envs\ab_dev\lib\site-packages\pandas\core\indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")`

`KeyError: "None of [Index(['from key', 'to key'], dtype='object')] are in the [columns]"`

**Comment by dgdekoning** [comment]
Ahh, that's really frustrating.

Give me some time to figure out where that is coming from. It might be that the exchanges cannot be located in the database, which should pop the 'cannot find exchange' exception instead of this key error.

**Comment by CHarpprecht** [comment]
Aha, interesting. 
I didn't see any exception poping up, unfortunately. But I did double check, that the name of the database is written correctly in the excel sheet compared to the db name in the AB and also checked, whether these flows are named in that way in ecoinvent 3.6. So the names in the excel sheet should be correct, unless I overlooked something.

**Comment by dgdekoning** [comment]
Sorry for the wait @CHarpprecht, but I've been unable to reproduce your error with the file you gave me :/

I did find some more exceptions to catch so I've been putting code together for those at least.

From going over the code and the error you've pasted it seems like the AB did not read the input correctly? It specifically complained that neither the 'from key' nor the 'to key' exist in the dataframe (excel file).
Regardless, I will make sure to put some error handling code in the place where the exception comes from.

**Comment by CHarpprecht** [comment]
Oh, I am sorry @dgdekoning, I tried it again and it is now also working for me! 

I might have found out where the error comes from (at least I could reproduce it):
If I click the "Add" button once after loading the excel sheet (but not loading another excel sheet on the right), then the error occurs again. So I think, the error is pointing to the second scenario upload window (which is empty), but not to the filled first one. 

I wasn't sure, whether after loading the excel sheet, one has to click on "Add" again or not. So when I tried it out several times in different combinations with different excel sheets and column names, I think I picked a very unlucky order of trials such that it never worked :( 

Is there a way to avoid this, such that it still works with an open, but empty second scenario upload window, as long as the first scenario file is fine? Or maybe make clearer to which excel file the error belongs to?

**Comment by dgdekoning** [comment]
ohhhh, of course... It makes sense that the error occurs then, I'll put a fix in to ensure that the empty dataframe has the correct columns.
Plus a warning to the console that one of the scenario's has no rows :)

**Comment by CHarpprecht** [comment]
Thank you! 
I just tried it and it is working great now! :)

**Comment by dgdekoning** [comment]
Great to hear!

**Comment by simb-sdu** [comment]
I still get the key error when calculating scenario lca

I changed the max_rows value in line 472 of Anaconda3\envs\PREMISE\Lib\site-packages\pandas\io\formats\excel.py. don't know if this causes the error? I had increase the max allowed number of rows in order to make the superstructure database with PREMISE and ecoinvent 3.8 cutoff


Traceback (most recent call last):
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 257, in scenario_calculation
    'data': self.scenario_panel.combined_dataframe(),
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 424, in combined_dataframe
    manager = SuperstructureManager(*data)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 21, in __init__
    SuperstructureManager.remove_duplicates(df)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 109, in remove_duplicates
    df.index = SuperstructureManager.build_index(df)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 126, in build_index
    assert df.loc[:, EXCHANGE_KEYS].notna().all().all(), "Cannot find all keys."
AssertionError: Cannot find all keys.
