### ISSUE TITLE
[bug][minor] When adding text to the description field of an activity, the text is not saved (or at least not displayed)

### ISSUE THREAD

**Issue by ntropy-esa** [LCA-ActivityBrowser/activity-browser#434]
Hello,

Using activity-browser dev, latest version, on windows 10. Noticed an issue when creating own activities and trying to add a description text: after writing some text in the description field, when clicking out of the textbox, the text vanishes. If I close and reload the specific activity (or even the database where it is in), still the Description box is empty.

Tested also this:
took random activity from ecoinvent with a description text > dupplicate the activity to another database > the description is there > edited the description > clicked out of the text box > added text not visible, remains as original text

**Comment by ntropy-esa** [comment]
My guess is that it may have something to do with the file
In file: activity_browser/app/ui/tabs/activity.py
        # Activity Description
        self.activity_description = SignalledPlainTextEdit(
            key=getattr(self.activity, "key", None),
            field="comment",
            parent=self,
        )
The field is "comment"

But, I can't find anywhere where updating/saving of this field is performed in the files:
app/ui/tables/history.py
app/ui/tables/activity.py

**Comment by dgdekoning** [comment]
Have looked into this a little bit, its actually quite an interesting problem.

I've got several possible fixes I can make to the code to try and make the handling a little easier.

1. Make sure the description box is refreshed as soon as you click outside of the box (ie. trigger the 'save' functionality).
2. Try and add a timer which starts counting to two or three and triggers a save by itself.
3. Add a 'save description' button that explicitly stores any changes and refreshes the text box (technically double-saves the description as it counts as clicking outside the text box but I don't think it is harmful).

... Now I'm wondering if there is some kind of hover-icon I can add that shows if the text is (being) edited...

**Comment by dgdekoning** [comment]
@ntropy-esa, I went for solution 1 to avoid making the code incredibly complex. Can you tell me if the bug is adequately fixed by this?

**Comment by ntropy-esa** [comment]
Tested. Works. Thanks!
