### ISSUE TITLE
Contribution analysis - input vs. background activities

### ISSUE THREAD

**Issue by miriconda** [LCA-ActivityBrowser/activity-browser#437]
Hi : )
I have a question regarding contribution analysis. 
Is it possible to only show the contributions of the activities that _I_ defined instead off all the underlying process?
because those i cant really connect to my processes.
For instance the biosphere emissions that i defined versus those resulting from technosphere processes.
Or for instance i have a process consisting of 3 subprocess which i again defined by several in- and output. 
It would be nice to only see the impacts on my 3 levels, not on the level of the underlying process, which are not 'visible' to me in my dataset and which i am not able sort. 
i.e. if my transport consist of train from Russia, ship from Senegal and truck from Belgium, that i need to see their contribution not mineral extraction etc...
If the solution lays in BW2 and not in the activity browser thats also fine!
Thank you for all the work around those two! They are both super helpful and fun to use : )
Best,
Miriam

**Comment by marc-vdm** [comment]
Hi Maura,

It's on my list but unfortunately that list is _very_ long. This will come to AB eventually, but I can't promise any particular date 😕 .
