### ISSUE TITLE
LCA results - Overview - Export table - Copy doesn't work properly

### ISSUE THREAD

**Issue by KarinTreyer** [LCA-ActivityBrowser/activity-browser#439]
It's been a while now that I cannot use the copy function anymore in LCA results - overview - export table. When I copy and paste into an excel spreadsheet, the index/reference product/name/location entries are split into several cells, i.e. it interprets the comma in names as the delimiter to put the text into a new cell. 
I remember that this has worked properly before. But I cannot tell exactly since when I see this bug.
Export to excel works properly.
![image](https://user-images.githubusercontent.com/28534018/90320531-7317da00-df42-11ea-9a13-b79e505bf286.png)

**Comment by dgdekoning** [comment]
Apologies for the late response, I've been on holiday.

Some of these functional units look like they're custom built, is it possible you're separating information in a field using a tab ('\t')?

Something else that occurs to me... Are those biosphere flows? Perhaps something is going wrong there when generating the index field.

**Comment by KarinTreyer** [comment]
As reaction to your answer, I have checked again a bit more. 
It seems that before clicking on the copy field, the "text to columns" in excel strictly must have the delimiter "tab" ticked, and nothing else. Then it works. One just has to check these settings beforehand (I am using the text to columns frequently, with different settings).

**Comment by dgdekoning** [comment]
I'll make a note of that and see if there is a way of changing (and storing the change) how data is copied. Perhaps a user setting that allows you to pick whether you want to copy with tabs, commas or semicolons as separators?

**Comment by CHarpprecht** [comment]
I had exactly the same problem once. Good to finally understand what the problem was, thank you! :)
