### ISSUE TITLE
Segfault when import latest EV case

### ISSUE THREAD

**Issue by cmutel** [LCA-ActivityBrowser/activity-browser#460]
No idea if you can help here, but this is a strange and sever bug.

Problem: Activity browser segfaults when importing EV case study file (from https:// drive.switch.ch/index.php/s/Vyoar0jX224Obiz). 

Databases installed: Base data and ei36_cutoff_IMAGE_SSP2_SS.cc56abf817936121030b25a834a98210.abb61d5d2411311bd8ecc1 90287c989a.bw2package (from same source).

OS: MacOS Mojave 10.14.6

Environment: New anaconda environment, https://gist.github.com/cmutel/f8d29b3c705283b389d5dbcf5de3420c

Error message: Inconsistent (error appears each time), this is the most that has been printed. Sometimes it doesn't print any exchange information.

```
Could not link exchanges, here are 10 examples.:
[{'amount': 1.0,
  'database': 'ei36_cutoff_IMAGE_SSP2_SS',
  'location': 'NL',
  'name': 'market for electricity, low voltage',
  'type': 'technosphere',
  'unit': 'kilowatt hour'},
 {'amount': 0.00262,
  'database': 'ei36_cutoff_IMAGE_SSP2_SS',
  'formula': 'battery_size',
  'location': 'GLO',
  'name': 'market for battery, Li-ion, rechargeable, prismatic',
  'original_amount': 1.0,
  'type': 'technosphere',
  'unit': 'kilogram'},
 {'amount': 0.00612146666666667,
  'database': 'ei36_cutoff_IMAGE_SSP2_SS',
  'location': 'GLO',
  Segmentation fault: 11
```

Could it be that there are unprintable characters?

Stack trace: https://gist.github.com/cmutel/fda4c1b04cae33609adff25fafb63f6b

**Comment by dgdekoning** [comment]
And this occurs before you get a pop-up dialog asking if you want to change the database to link the exchanges to?

**Comment by cmutel** [comment]
OK, now it worked. No idea what changed from then to now, but I tried 3 times (restarting the AB each time, obviously) before with the same problem. The only thing I did in the meantime was to demonstrate doing an LCA with the modified ecoinvent database, and go to lunch.

Let's just hope it was some weirdness with my machine that resolved itself!?

**Comment by dgdekoning** [comment]
> ... and go to lunch.

I really hope this isn't something that only occurs at certain times D:
