### ISSUE TITLE
Suggestion: improve copying values

### ISSUE THREAD

**Issue by SanderNielen** [LCA-ActivityBrowser/activity-browser#467]
It would be a nice-to-have feature to be able to copy values from the Activity Browser. For example, when an activity is selected, you can select cells in the table of inputs. However, copying those values is not possible. If that was made possible, it is more easy to copy process names or input values, or transfer numbers to parameter values.

**Comment by dgdekoning** [comment]
This is technically already possible, but the current implementation always includes the column head. e.g. copying the amount will yield:

```
Amount
0.005
```

Which is handy if you want to have these headers, but isn't as useful when you just want the number.
I'll discuss with @bsteubing and possibly switch over to the 'simple' copying.

**Comment by SanderNielen** [comment]
Ah, thanks. I also see that I can copy values after selecting 'Edit Activity'.

**Comment by bsteubing** [comment]
2 ideas:
- copying a single cell should skip the headers and copying several cells should contain the headers... or 
- CTRL-C copies without headers and CTRL-SHIFT-C copies with

if we are introducing keyboard shortcuts, then it would be good to have some system to keep/manage the shortcuts in a single place, just like the signals, and also to (for now at least) show the keyboard shortcuts through the menu, so the user can learn about them
