### ISSUE TITLE
Show error message when LCIA calculation fails

### ISSUE THREAD

**Issue by KarinTreyer** [LCA-ActivityBrowser/activity-browser#470]
When I start an LCIA calculation, but something is wrong, it would just not do anything and not display anything special. It just stops, and when clicking on calculation again, nothing happens again. 
I can see in the anaconda prompt that there happened e.g. a key error due to a specific activity (name, code). But you first need to realise that you can check your anaconda prompt. It would be better to pop up an error window either saying what the error is or pointing to the anaconda prompt.

**Comment by dgdekoning** [comment]
Excellent point, I'll add it in as soon as possible.
