### ISSUE TITLE
Running scenario-based LCA

### ISSUE THREAD

**Issue by schvanes** [LCA-ActivityBrowser/activity-browser#473]
Hi everyone, 

Currently I am using the activity browser and would like to perform a scenario-based LCA. I implemented the changing parameters in Activity Browser and made an Excel spread sheet for the different scenarios. 
First, I loaded the scenarios in the parameter tab, and it appeared correctly.
Second, the same excel file was imported in the scenario-LCA tab at the bottom.
However when trying to run the LCA, there’s no response and I got the following error message by conda: 

No data in scenario table 1, skipping
Traceback (most recent call last):
  File "C:\Users\Schenker\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\app\ui\tabs\LCA_setup.py", line 222, in scenario_calculation
    data = self.scenario_panel.combined_dataframe()
  File "C:\Users\Schenker\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\app\ui\tabs\LCA_setup.py", line 344, in combined_dataframe
    manager = SuperstructureManager(*data)
TypeError: __init__() missing 1 required positional argument: 'df'

We tried to re-do this scenario-based LCA on a different computer to find the error but on the other computer it works perfectly fine. Is there a way to fix my problem? 

Many thanks for your ideas in advance! 

Kind regards,
Vanessa

**Comment by StpdFox** [comment]
Closed due to inactivity, if this bug still persists please reopen this ticket
