### ISSUE TITLE
[Feature]Export sankey diagrams/data

### ISSUE THREAD

**Issue by BenPortner** [LCA-ActivityBrowser/activity-browser#477]
Dear activity-browser team,

first off, thanks for this great piece of software. Activity browser really has increased my productivity compared to the code-only approach! 

Here are two questions to the developers: 

- Would it be possible to add an "export as html" button to the sankey diagram tab?
- Would it be possible to add an "export as csv" button to the sankey diagram tab?

For the latter, I imagine an edge list containing the following information: 
`source_activity_name, source_act_product, source_act_location, source_act_database, source_act_unit, target_act_name, target_act_prod, target_act_loc, target_act_db, target_act_unit, exchange_amount, exchange_impact_score, impact_category`
I believe this would be incredibly useful because people could easily do their own aggregations on the data and visualize them with the tool of their choice.

Cheers.
Ben

**Comment by MMahdi97** [comment]
Hello activity-browser team,

I am reopening this topic because I believe the issue has not yet been resolved.
I am looking for a way to export the Sankey diagram data. I have updated the Activity-Browser, but it seems there is still no option to export this data.
I would greatly appreciate your assistance in resolving this issue.

Best regards,
Mahdi

**Comment by marc-vdm** [comment]
Thanks for your comment. We agree this is useful, but unfortunately the list of useful things is long and our time is limited and this is not very high on our priority list. You could subscribe to #1384 to get notified when this is added. If you would like me to build this feature soon, we can discuss financial compensation, for that you can contact me [here](https://linktr.ee/m.vdm.lca).

Best,

Marc

**Comment by MMahdi97** [comment]
Thanks a lot, Marc. I understand that the team has many priorities, and I appreciate your response. I have subscribed to #1384 to stay updated on this feature. If there are any alternative ways to extract the Sankey diagram data in the meantime, I would be grateful for any suggestions.
