### ISSUE TITLE
Pandas 1.2.0 causes plotting to fail

### ISSUE THREAD

**Issue by dgdekoning** [LCA-ActivityBrowser/activity-browser#489]
Due to some of the DataFrames using tuples (for activity keys) in indexes or columns, the newest version of pandas will break when creating plots.

This initially occurs in `LCAResultsBarChart.plot`, but will likely exists in every plot() call of the figure classes where tuples are used in DataFrames.

To resolve this issue, the index/column has to be replaced by the labels that will be shown in the figures themselves _before_ the `df.plot...` call is made.

**Comment by dgdekoning** [comment]
The quick fix before this issue is resolved is to downgrade `pandas` to a version before `1.2.0`.

This can be done with:

```bash
conda install -c conda-forge pandas<1.2
```

**Comment by zber** [comment]
I had to give the install command an actual version:
conda install -n ab_dev -c conda-forge pandas=1.1.5
Then it worked
