### ISSUE TITLE
Where do the pedigree matrix numbers come from? esp. the basic uncertainty.

### ISSUE THREAD

**Issue by xiaoshir** [LCA-ActivityBrowser/activity-browser#493]
Comparing the pedigree matrix in one exchange from an ecoinevent dataset in ab 
![image](https://user-images.githubusercontent.com/28433916/103911464-5d2fcf00-5106-11eb-9377-be4ee3685079.png)

and from ecoinvent 
![image](https://user-images.githubusercontent.com/28433916/103911487-65880a00-5106-11eb-9645-c279c404fb18.png)

shows that for each exchange, the first 5 numbers are those 5 aspects on [page 76](https://www.ecoinvent.org/files/dataqualityguideline_ecoinvent_3_20130506.pdf), and the last number probably represents basic uncertainty. 

My questions are:
- Are these 6 values just included for user's reference, and has no other functions mathematically (since you get loc and scale from uncertainty attribute in an exchange already)?
- I couldn't see these 6 numbers from the uncertainty attribute for an exchange in brightway2, so where do they come from?
- I noticed the basic uncertainty is always kept to be 1, and why is that so? According to the following table (also from ecoinvent data quality guideline), basic uncertainty does not have a scale from 1 to 5.
![image](https://user-images.githubusercontent.com/28433916/103912094-27d7b100-5107-11eb-9464-de3bac18a3d0.png)

**Comment by dgdekoning** [comment]
I hope my answer for this is mostly correct...

In order:
* The first 5 numbers refer to different kinds of quality of data as determined by the researcher/LCA practitioner. The relevant paper explaining this in-depth can be found [here](https://lca-net.com/publications/show/empirically-based-uncertainty-factors-pedigree-matrix-ecoinvent/) (follow the share-it link). The short of it is that the combination of these numbers is used as a simplified way of setting uncertainty on something.
* That's right, brightway2 uses the 'uncertainty' fields directly, but ecoinvent data does contain the `pedigree` field, which contains this matrix, and translating from pedigree to uncertainty is possible by using the numbers [here](https://chris.mutel.org/images/Pedigree-matrix-poster-LCA-orlando.pdf), implemented in the code [here](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/app/bwutils/pedigree.py) (the link to Chris' code no longer works due his switch from bitbucket to github).
* We have been wanting to add basic uncertainty to the uncertainty wizard for [a while now](https://github.com/LCA-ActivityBrowser/activity-browser/issues/456), to provide some simple starting numbers when going into the uncertainty wizard.

**Comment by StpdFox** [comment]
Closed due to inactivity, i hope you have found your answer! If not feel free to re-open this ticket
