### ISSUE TITLE
Blank white screen when Activity browser opens without any tabs

### ISSUE THREAD

**Issue by sg2219** [LCA-ActivityBrowser/activity-browser#494]
Hello everyone,

I installed activity browser and it worked fine for a few days. Now, all I see is a blank white screen but when I point the cursor on the tab, I can see the options(I have attached a screenshot for your reference). Could anyone help me with this, please?

Thank you.

![image](https://user-images.githubusercontent.com/77126765/103948316-db599900-5139-11eb-8f60-c17784281cad.png)

**Comment by dgdekoning** [comment]
This is interesting, I don't think I've ever seen this before.
Can you give me more information? when did you install the AB? Did you use the stable or development version? It looks like you're using windows, is that right?

**Comment by sg2219** [comment]
Thank you.
I've been using the stable version since August 2020 on a windows remote desktop. The problem occurred in December 2020 all of a sudden. 
![Screenshot 2021-01-08 at 15 43 38](https://user-images.githubusercontent.com/77126765/104027866-4b166500-51c8-11eb-904f-a2e53e3dc936.png)

**Comment by dgdekoning** [comment]
I have had some weirdness with screen-sharing the AB through Teams which is somewhat like this, but nothing as extreme as a completely white screen.
Something I found that looks similar to your problem is [this](https://community.teamviewer.com/English/discussion/comment/31199), do you know if there is a screen on the remote desktop that was turned off or disconnected?

**Comment by sg2219** [comment]
Thank you.
I have raised the question with the IT department in my research institute regarding the screen on the remote desktop. I'll let you know as soon as I hear from them.

**Comment by StpdFox** [comment]
Closed due to inactivity, if you still have this issue and your IT department couldn't help you feel free to re-open this issue
