### ISSUE TITLE
Ecoinvent consequential 3.7 can not be imported

### ISSUE THREAD

**Issue by levonamatuni** [LCA-ActivityBrowser/activity-browser#504]
Hi there!

The ab and the bw - all updated.
Can successfully import Ecoinvent 3.7 (3.7.1) for the cut-off and APOS models, but not for the conseq model.

The error screenshot is attached.

Thanks!

![MicrosoftTeams-image](https://user-images.githubusercontent.com/19741986/105048389-cea74000-5a6b-11eb-9d8d-b9191dec9dc8.png)

![image](https://user-images.githubusercontent.com/19741986/105048470-e979b480-5a6b-11eb-9286-be1f533eabfd.png)

**Comment by dgdekoning** [comment]
Hmm, interesting. It seems like it can't link all biosphere exchanges? Will look into this.

**Comment by eketju** [comment]
**Hello,** 

This error also happens with the consequential databases of other ecoinvent versions (3.6, 3.4, ...).

**Comment by rjulio31** [comment]
Hello, 
I have the same issue.
Is there any solution ?
