### ISSUE TITLE
Calculation setups behaviour

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#53]
CS only work if the project is reloaded... also, at start the CS shows 1,2,3 in "Products and amounts" as well as the 4 buttons (CS selection, new, rename, delete), but one cannot select from CS selection. It works once the project has been reloaded...

**Comment by haasad** [comment]
One way quick and dirty way to "solve" this would be to have either some kind of default or random CS if there are no user-defined CSs. Like this we wouldn't need to address this via UI (ie. disabling buttons etc).

I would personally like to have a random (created when AB is opened) CS in there at all times. This would help us to find bugs and special cases for the results tab and the sankey-window. But maybe that's confusing for the users.

**Comment by bsteubing** [comment]
resolved by #56

**Comment by haasad** [comment]
Calculate and Sankey buttons are still enabled, even if there are no CS present:
![image](https://user-images.githubusercontent.com/11636405/33759732-a85352c0-dc03-11e7-8206-fbd30aaec996.png)
What do you think about adding some kind of default or random CS if the users hasn't defined any? If you don't like the idea, we should at least disable the other two buttons.

**Comment by bsteubing** [comment]
I kind of like the idea for developers like us... but I think it is a bit confusing for users to get a random calculation setup. As they get stored, you might have to delete them again so the don't accumulate. Also, you can make one so quickly or just re-use the latest one you made in your project. So I would probably skip that for now...

**Comment by bsteubing** [comment]
Also, in my version the buttons are already hidden if there is no CS...

**Comment by bsteubing** [comment]
Sorry, I misread your comment... yes, the "calculate" and "sankey" buttons do still show and that doesn't make sense... so hiding them makes sense.

**Comment by haasad** [comment]
Fixed in #86
