### ISSUE TITLE
AB crashes when importing several excel databases

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#540]
The first one imported fine, the second one immediately crashed 
Process finished with exit code -1073741819 (0xC0000005)

**Comment by bsteubing** [comment]
to make it somewhat more specific - the Database Import Wizard crashed even before it attempted the import, but when I selected the file to be imported...

**Comment by StpdFox** [comment]
Closing this ticket since related ticket has been resolved and closed too. If this bug still persists please reopen this issue
