### ISSUE TITLE
Impact Categories Tree view not showing anything

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#541]
@marc-vdm and @dgdekoning I don't know if this on your radar or even an issue in your versions, but I get a totally empty tree view for the LCIA methods at this moment...

![image](https://user-images.githubusercontent.com/33026150/109283147-b5d63b00-781e-11eb-8ebb-36683c06b857.png)

**Comment by marc-vdm** [comment]
Interesting, I have no such issue on the most recent version on my side, not on Windows or Linux. 
Do you get errors?
Does the list view work?
Does search work?

I hope I can quickly fix it with that info!

**Comment by bsteubing** [comment]
I had to update my biosphere data, then for some reason the treeview showed everywhere (also in projects where I hadn't updated the biosphere data...)
