### ISSUE TITLE
Scenario LCA: clearer feedback on exchange imports

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#542]
The way we import scenario difference files is problematic at this moment for the following reasons:
- exchanges that are specified in the scenario difference file, but are not found in the LCI database ARE NOT REPORTED, but silently ignored... this makes the SDFs work, but fails to notify users about not using the data as specified. I could have a file with 100000 exchanges and as long as only one can be identified (and the other 99.99% not) it looks to the user as if all goes well - this is not good... 
- we need to inform users if exchanges could not be found (as a warning, still enabling calculations)
- one idea could be to give the option to the user to save a copy of the SDF where the rows (or better cells) are marked in red where exchanges were not identified correctly (or something similar, so he can understand what needs to be done)

**Comment by marc-vdm** [comment]
Closing this as resolved in #1025
