### ISSUE TITLE
AB starts minimized

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#544]
Since a while the AB starts minimized (not full screen) and I am not sure what this is the case or should be the case... if there is no specific reason for this, I would prefer to have it start in full screen, which would save me a click each time I start it...

**Comment by dgdekoning** [comment]
Given that the `run_activity_browser` method explicitly causes `showMaximized` to be called on the `QMainWindow` object, I have no idea why your AB starts minimized.

**Comment by marc-vdm** [comment]
This is still an issue for me.
Also related: #270

**Comment by marc-vdm** [comment]
Closing as stale
