### ISSUE TITLE
Activities disappearing

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#554]
Something severe went wrong linked to either importing databases or deleting databases... I could not track the issue down, but all activities from 2 of my databases were deleted, although I never touched these databases...!!! 
I have no idea when or how this happened, but these are clues:
- I recently deleted a database that used "Chemicals_V2"
- I had a couple of unsuccessful imports of another database that uses the "Chemicals_v2" 
 
In any case, this is a worst case scenario that data that the user does not intend to delete becomes deleted... and should be fixed. 

![image](https://user-images.githubusercontent.com/33026150/110298190-a01dfe00-7ff4-11eb-941d-6f91af2d4f78.png)

**Comment by dgdekoning** [comment]
Can you give me more information?

* Did all the unsuccessful imports go through the excel importer?
* What were the names of the other databases?
* Can you attach a list of package versions installed in your conda environment?

Perhaps this is related to #540, with the python crash suddenly causing in-memory objects to be deleted from the database?

**Comment by bsteubing** [comment]
A note of caution on this issue... I also just noticed other changes in my databases and I am starting to suspect that the source of all of this might lie outside of the AB, e.g. my synchronization software...

**Comment by bsteubing** [comment]
This was indeed the problem. No need to further look into this...
