### ISSUE TITLE
Debug window improvement

### ISSUE THREAD

**Issue by StpdFox** [LCA-ActivityBrowser/activity-browser#558]
When the debug window is openend in the AB, you can't switch back to the main window 

Also , I suggest we approach the debug window the same as is done in most IDE's by making a window at the bottom instead of taking over the whole screen

**Comment by Zoophobus** [comment]
This is partially fulfilled, the switching between windows is working, however the debug window still occupies the entire screen, which is still not ideal

**Comment by Zoophobus** [comment]
This has been changed in the PR #914 to follow the same graphical display as in IDE's with a window at the bottom of the screen, rather than using stacked windows
