### ISSUE TITLE
Activity created in brightway2 makes the AB bug

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#559]
Hello,

I am trying to create an activity through brightway2 and it triggers a bug in AB.

Here is the bw2 code I'm using to create the activity:

![image](https://user-images.githubusercontent.com/24285636/112202762-225b1480-8be8-11eb-98f5-ae17fe8df32e.png)

The bug happening is that the project where the new activity was created in does not open when I select it through the drop-down menu. Said project is thus inaccessible through AB.

Here is the debug window:

![image](https://user-images.githubusercontent.com/24285636/112202530-dd36e280-8be7-11eb-8199-8cd8f9e91521.png)

**Comment by dgdekoning** [comment]
Hello @MaximeAgez!

It looks like the conda environment where the `activity-browser` is installed uses python 3.6 or 3.7. While your brightway2 environment uses python 3.8. Python 3.8 introduces a new 'pickle' protocol version that is not present in previous versions, and brightway2 makes use of it when storing data. You can see #388 and https://github.com/brightway-lca/brightway2-data/issues/68 for more details. 

Currently the only solution to this is to use the Activity browser with python 3.8. You can install this version of python into the environment by using `conda install -n ab_dev python=3.8` .

**Comment by MaximeAgez** [comment]
It fixed the problem indeed. Thank you!
