### ISSUE TITLE
Adding new flows to the SS difference file crashes when no keys are added

### ISSUE THREAD

**Issue by CHarpprecht** [LCA-ActivityBrowser/activity-browser#562]
Hi,
we observed the following:
when additional flows are added to the excel of the superstructure difference file, scenario-based LCA can only be calculated if the keys or "unknown" are mentioned in the keys fields  in the excel file for the new flows. 
Yet, if the keys fields are left empty for the new flows, the calculation crashes.

I think, it would be good to either inform the user about this somewhere. The ideal case would be, I think, to somehow make it possible to just leave the keys fields empty in the excel.

**Comment by marc-vdm** [comment]
Closing this as resolved in #1025
