### ISSUE TITLE
Tree view for LCIA methods only shows methods with 3 tuple entries

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#563]
I have an LCIA method which has a fourth tuple entry ("IPCC 2013", "climate change", "GWP 100a", "my own variant") - this does not show up in the tree view, only in the list view

**Comment by marc-vdm** [comment]
@bsteubing & @StpdFo, the problem might be deeper than the treeview, see also #566.
Perhaps one of you also looking at/test the problems mentioned there could help identify where the actual problem lies?
@bsteubing, could you check what happens when you look at problem 3 in #566?

**Comment by StpdFox** [comment]
To clarify : 
When you duplicate an impact category to add another entry, ("One","Two","Three") when you copy this and add "Four" , it doesn't show up in the tree view, only in the list view.

i've looked for some hardcoded depths that might need to be hightened but that doesn't seem the case.
I think this is an issue linked to the treesearch/filtering.  Since the IC is does exist because it's shown in the listview

**Comment by mixib** [comment]
Other problems with the tree-view:

In projects where the list view works fine, the tree view shows Name: "something", Unit: "Unknown", #CFs: "0" when the search field is empty. 

![image](https://user-images.githubusercontent.com/53601545/115577121-6e22db80-a2c4-11eb-9a55-adaad80a328b.png)

When trying to look for impact categories, the result box becomes empty:
![image](https://user-images.githubusercontent.com/53601545/115577273-90b4f480-a2c4-11eb-9c13-18d7795001f9.png)

In projects without the default data, I would expect the result box to be empty but it shows the "something, unknown, 0" row.
![image](https://user-images.githubusercontent.com/53601545/115577693-eee1d780-a2c4-11eb-9487-21816e16c8e2.png)

**Comment by StpdFox** [comment]
The original problem with a copy of the impact category not showing in the tree-view has been fixed in the development version.

It was a problem with the flattening and data structure. 
This is more of a fix, i'm planning on reworking the treeview data structure on a later date
