### ISSUE TITLE
Comment column in Technosphere inputs and Biosphere flows

### ISSUE THREAD

**Issue by caaficus** [LCA-ActivityBrowser/activity-browser#567]
When creating an activity, sometimes I need to drop the same process within the "Technosphere input". It would be cool to have an extra column for comments, next to the "Formula" column to add descriptions or brief description of the processes included within the activity. 
![Ab_ex_des](https://user-images.githubusercontent.com/63497395/112962450-afe9b780-9146-11eb-9db5-477d36ee5104.png)

**Comment by marc-vdm** [comment]
We now have the comments field in the dev release.

**Comment by caaficus** [comment]
Great! Thanks a lot!
