### ISSUE TITLE
Adding uncertainty values to created processes

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#569]
Hi AB-team,

Adding uncertainty values for created processes or even modifying existing uncertainty values, seems impossible. Is it intentional? Or is it a bug? (using AB v2.6.3)

Thanks!

**Comment by StpdFox** [comment]
Hace you tried right clicking the uncertainty field ? 
There should be an option allowing you to modify it. 

![afbeelding](https://user-images.githubusercontent.com/8734631/113672576-3f97e480-96b8-11eb-862f-3c8900c4f698.png)

On my build i'm able to add and modify uncertainty. 
If this isn't what you meant i'll have to look into it some more.

**Comment by MaximeAgez** [comment]
It's there indeed. Guess my brain expected to be able to double click and input values. Sorry :)

**Comment by StpdFox** [comment]
I'll add that as a possible feature. It does seem the logical thing to do!
