### ISSUE TITLE
Cannot change parameters

### ISSUE THREAD

**Issue by nrajagopalan** [LCA-ActivityBrowser/activity-browser#574]
Hello!
I get the following issue when I start to name new parameters (see image) in the Activity Browser or try to change existing ones already created. How do I solve this issue?

Thanks!

![image](https://user-images.githubusercontent.com/82145886/113997333-5412e300-9858-11eb-8065-3227990fa520.png)

**Comment by StpdFox** [comment]
Hello @nrajagopalan !
I can't seem to recreate the issue you are having. 
Could you open the debug window and copy that output after you encounter this error?
Could you also specify what kind of parameter you are trying to add? Just any? or something specific?

**Comment by nrajagopalan** [comment]
The debug window doesnt seem to recognize this as an error (see image below). 
I'm just trying to add a normal parameter, change its name to something descriptive and apply a value to it. 
![image](https://user-images.githubusercontent.com/82145886/114019989-5d5b7a00-986f-11eb-9754-603729fe73e8.png)

**Comment by StpdFox** [comment]
This is strange. So you've added a parameter with some random values and when you try to change the name you get this error?

I'm still having trouble recreating your error. Even when adding 55 parameters.
I'm gonna look up the query error you are having and i hope i'll have an awnser for you soon.

**Comment by ntropy-esa** [comment]
Hi there,
It seems that the current development version has restored several bugs that had been fixes in 2.6.2.
See #465 may help in that case.

**Comment by nrajagopalan** [comment]
Hello, 
I tried the fix you suggested. But now, Im faced with another error (see below). Any suggestions short of deleting the project folder?
![image](https://user-images.githubusercontent.com/82145886/114858735-272b7680-9dea-11eb-8d39-9cf38298f66f.png)

**Comment by StpdFox** [comment]
After some searching it seems to be a version issue. 
You could try to compile it with 3.7 python or import pickle5 as pickle.

**Comment by nrajagopalan** [comment]
Hello @ntropy-esa and @StpdFox,
Thanks for your responses! I finally fixed the issue. I solved the Unsupported pickle protocol issue by following instructions from Issue #388. But then I still couldn't change parameters so I had to redo the fix from #465 which somehow again lead me to the unsupported pickle protocol error. After repeating the fix #388 again, Im finally able to change parameters!
