### ISSUE TITLE
Unable to add Parameters with only numbers in the name. 

### ISSUE THREAD

**Issue by StpdFox** [LCA-ActivityBrowser/activity-browser#575]
When a user tries to add a parameter with only a number in it's name it doesn't get added. it does throw an error but doesn't say anything to the user.This should give a prompt or be allowed to add.

**Comment by Zoophobus** [comment]
brightway does not allow parameter names to start with numbers, I've added a couple of other characters that are not allowed. Further characters are not allowed, for the moment these aren't included in the creation of an error message, at some point I might make a custom Error reporting class for the AB, then I will tackle this more thoroughly.

**Comment by Zoophobus** [comment]
I will close this for now, though feel free to reopen this issue
