### ISSUE TITLE
Changes in the description of an activity are not saved

### ISSUE THREAD

**Issue by KarinTreyer** [LCA-ActivityBrowser/activity-browser#577]
I open an activity and tick the two boxes "Edit Activity" and "Description".
Then I type any text in the "Description" field. As soon as I leave that field, the entry is gone.
(this is for v2.4.0)

**Comment by StpdFox** [comment]
I dont seem to be having this issue on  v2.6.3 , you should try updating the AB. Or is there any reason you are working on this version?

**Comment by KarinTreyer** [comment]
I had to downgrade my python from v3.9 to v3.8 so that the update of AB to v2.6.3 worked (that was apparently the reason I didn't have 2.6.3 so far). 
In v2.6.3, it works perfectly. 
Thanks!
