### ISSUE TITLE
Import local database with bw2package - activity parameters gone

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#579]
Hello,

After exporting a created database to a BW2Package and trying to re-import it, I noticed that the activity parameters were gone from the parameters.db (and consequently from the parameters tab of AB).

Here, I was supposed to have an activity-parameter "NG_carbon_content"

![image](https://user-images.githubusercontent.com/24285636/114784069-b08a6c80-9d48-11eb-84a2-ab8ace4cd545.png)

that does not appear in the list

![image](https://user-images.githubusercontent.com/24285636/114784083-b6804d80-9d48-11eb-826b-9b85456fc677.png)

or in the database

![image](https://user-images.githubusercontent.com/24285636/114784405-373f4980-9d49-11eb-8bac-59f6cfbae7a6.png)

The values of exchanges are reverted to the "original_amount" key. They are not calculated by the formula anymore (NG_carbon_content was supposed to be 0.75).

![image](https://user-images.githubusercontent.com/24285636/114784543-5ccc5300-9d49-11eb-95f9-3d9d7f68bb76.png)

I tried with the Excel export/import, it did not create any issue, so it seems related to the bw2package format.

**Comment by marc-vdm** [comment]
Sorry for the late reply. the bw2package format does indeed not support parameters. I'm not sure that is planned functionality either. Currently, the only supported way of exporting/sharing parameters is through the excel format.
