### ISSUE TITLE
Incompatibility with newer bw2io versions

### ISSUE THREAD

**Issue by cardosan** [LCA-ActivityBrowser/activity-browser#581]
The current requirement for AB is `bw2io >=0.7.dev1`, which prevents the import of     `bw2io >=0.8` . Unless there is a reason for avoiding `bw2io >=0.8`  (that [should not contain breaking changes](https://github.com/brightway-lca/brightway2-io/blob/master/CHANGES.md)) the requirement file should be updated

**Comment by StpdFox** [comment]
I don't see why not. 
Version the bw2io version is set to >=0.8 now in the yaml [here.](https://github.com/LCA-ActivityBrowser/activity-browser/commit/348851ac34eb2f10661f787b440f53bd46a4272e)
