### ISSUE TITLE
Suggestion for improvement: add possibility to copy calculation setup

### ISSUE THREAD

**Issue by cardosan** [LCA-ActivityBrowser/activity-browser#582]
Suggestion for improvement from colleague who started to use AB:

it would be useful to be able to copy calculations setup.
E.g. when one wants two create 2 or more CS with a lot of unit processes and/or IA methods that are similar but not exactly the same,re-making a new CS from scratch can be a pain. Being able to just copy one CS anb modify it would make the work easier.

**Comment by mixib** [comment]
Hi @cardosan and @StpdFox . This suggestion is related to #422. A "copy" LCA setup feature is already available in the development version, [ab_dev](https://github.com/LCA-ActivityBrowser/activity-browser#development-version).
![image](https://user-images.githubusercontent.com/53601545/115570461-6d874680-a2be-11eb-8bdc-02c9fa511cc8.png)
It works as I would expect within a project, but it doesn't cover this feature proposed by @dgdekoning:
>Perhaps it might even be a good idea to allow the exporting of created sets, so they can be shared between users...

**Comment by StpdFox** [comment]
Yes, the way things are getting copied are currently kinda limited. This is on the list of features to take a loot at! Thanks for the suggestion

**Comment by marc-vdm** [comment]
Users can currently copy calculation setups and drag impact category families from the tree view.
This has made working with calculation setups much easier. I hope you agree with me closing the issue, otherwise just re-open it and share your thoughts.
