### ISSUE TITLE
Suggestion for improvement: add comment field to activity exchanges

### ISSUE THREAD

**Issue by cardosan** [LCA-ActivityBrowser/activity-browser#583]
Suggestion for improvement from colleague who started to use AB:

it is always useful to be able to add comments  in exchanges. E.g. for (complex)  models/parametrised exchanges one might want to take note of what has been done. The best/easiest might be to add field in the activity tab right next to the field formula.

![AB](https://user-images.githubusercontent.com/11156305/115402949-36e0fb80-a1ec-11eb-81d3-5fe19f2d9662.png)

I think it would just need to add [a new field](https://2.docs.brightway.dev/intro.html#database-documents:~:text=The%20schema%20for%20an%20LCI%20dataset%20in%20voluptuous%20is%3A) in the exchanges of the activity, with maybe also some modification in bw2io to have the field created by default when importing a database.

**Comment by marc-vdm** [comment]
We now have the comments field in the dev release.
