### ISSUE TITLE
Starting new project problems

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#585]
Update:
I did this on W10 on the stable release, on Linux on the stable release and on Linux in the latest master.

In the latest stable release, I just tried starting a new project and loading the default data, this loaded the biosphere 3 data, but gave the below terminal output for loading impact categories [Linux only].

The resulting problem is that I only get 1 impact category [Linux only].

After this, the next issue occurred:
I tried deleting the project, and tried making one with the exact same name, this managed to load the previous, broken project [W10 & Linux].

```
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/d875ff7a-7342-4dcf-8ab7-d64c6837d0f2
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset project settings directory to: /home/*/.local/share/Brightway3/default.c21f969b5f03d33d43e04f8f136e7682
Reset metadata.
Loading user settings:
dirpath already loaded
Brightway2 data directory: /home/*/.local/share/Brightway3
Brightway2 active project: default
Qt Version: 5.12.9
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Reset project settings directory to: /home/*/.local/share/Brightway3/Soy_Test.7151300cf972902a7e1c99766b6f38b5
Reset metadata.
Loaded project: *
Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applied 2 strategies in 0.01 seconds
Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Title: Writing activities to SQLite3 database:
  Started: 04/23/2021 09:21:01
  Finished: 04/23/2021 09:21:02
  Total time elapsed: 00:00:00
  CPU %: 86.90
  Memory %: 2.97
Created database: biosphere3
Applying strategy: normalize_units
Applying strategy: set_biosphere_type
Applying strategy: drop_unspecified_subcategories
Applying strategy: link_iterable_by_fields
Applied 4 strategies in 1.85 seconds
Traceback (most recent call last):
  File "/home/*/anaconda3/envs/ab/lib/python3.7/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 1215, in run
    bw.create_default_lcia_methods()
  File "/home/*/anaconda3/envs/ab/lib/python3.7/site-packages/bw2io/__init__.py", line 95, in create_default_lcia_methods
    ei.write_methods(overwrite=overwrite)
  File "/home/*/anaconda3/envs/ab/lib/python3.7/site-packages/bw2io/importers/base_lcia.py", line 72, in write_methods
    method.write(self._reformat_cfs(ds['exchanges']))
  File "/home/*/anaconda3/envs/ab/lib/python3.7/site-packages/bw2data/method.py", line 67, in write
    super(Method, self).write(data)
  File "/home/*/anaconda3/envs/ab/lib/python3.7/site-packages/bw2data/project.py", line 356, in writable_project
    return wrapped(*args, **kwargs)
  File "/home/*/anaconda3/envs/ab/lib/python3.7/site-packages/bw2data/data_store.py", line 203, in write
    pickle.dump(data, f, protocol2)#=pickle.HIGHEST_PROTOCOL)
NameError: name 'protocol2' is not defined

```

**Comment by marc-vdm** [comment]
Update on deleting projects and them not being deleted:
It seems the projects are removed from the 'projects.db' file but the actual project folder is not removed from disk. Perhaps a line of code was forgotten somewhere?
For me the folders are under:
`~/.local/share/Brightway3`
(IIRC on windows it is under something like user/appdata/)

**Comment by StpdFox** [comment]
Going to check fi this is still relevent, 
by deleting a project and creating one with the same name it still points to the deleted version?

**Comment by Zoophobus** [comment]
At present this runs as I would expect, if you delete a project it removes it from the data stored AND used by both AB and BW, however it doesn't alter the contents (files and directories) on the disk. I would prefer to avoid doing this, if we show the user where the folder is (if they really want to delete the data) then they can remove it themselves.

I am more afraid of the ability of a user to misclick and delete their data than a user "struggling" to manage their computer. One is something we can avoid the other is the users responsibility.

**Comment by Zoophobus** [comment]
Okay, I've revised this after talking with Steubing! Brightway offers the functionality to delete the contents from disk, so I've basically just added an extra Dialog to ask the user for confirmation before deleting the disk contents. So now it is possible to remove the hard disk contents from within the AB
