### ISSUE TITLE
Impact categories with 3+ tuples not properly shown in figures

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#590]
In the EF/Process Contributions tabs, impact categories are shown with 3 tuples only, which might cause confusion with custom impact categories. This is not the case in the LCA Results tab (where more tuples are shown on figure axes).

![Screenshot from 2021-04-27 09-58-45](https://user-images.githubusercontent.com/34626062/116206552-72b91b00-a72e-11eb-88df-12fce9848606.png)
![Screenshot from 2021-04-27 09-59-24](https://user-images.githubusercontent.com/34626062/116206615-85cbeb00-a72e-11eb-8dc9-d977cb76c4a5.png)

**Comment by StpdFox** [comment]
I can't really make out much of the image you added. But the problem with 3+ tuples persists througout the AB. This is an issue we should take a look at.

**Comment by marc-vdm** [comment]
The problem I meant is that in the top figure, both impact categories (y-axis labels) are the same, while one of the two processes has 4 tuples (as shown in lower figure x-axis labels).

**Comment by Zoophobus** [comment]
This problem arises from the use of pandas and the MultiIndex class in pandas, when this takes a list of tuples it takes the first tuple as the standard, so if this tuple contains two elements all subsequent tuples are assumed to have two elements. If the first tuple is longer it will throw a more serious error as the interpreter will try to read unassigned elements within the tuple. The resolution to this has been to duplicate the tuples argument and provide dummy elements to those tuples that are shorter than the maximum. This fix has been applied within the base Contribution class and so should remain specific for the EF/Contributions tabs
