### ISSUE TITLE
Importer for ILCD - EF 3.0 LCIA method

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#591]
Hello,
I was wondering if it was in the plans of the AB/bw2 team to develop such an importer for the new ILCD LCIA method. If not, could someone point me to the current code responsible for importing the ILCD2.0 method (which is already present) so that I can adapt it for 3.0.
Thanks!

**Comment by bsteubing** [comment]
Dear Maxime, it is definitely the goal of the AB to include functionality to import LCIA methods, at least from a simple (e.g. Excel) based format. This is on our agenda, but we are not quite there yet. For now LCIA methods are included at the level of brightway (@cmutel) and to my understanding mainly based on ecoinvent's LCIA implementation although in principle brightway (and thus the AB) can import any LCIA method for which the data (and matching to ecoinvent environmental flows) is available. Thanks for making this issue.

**Comment by marc-vdm** [comment]
EF3.0 is available in BW/AB by default now

**Comment by ar-ali** [comment]
Hi, I am unable to see EF3.0 on my AB.
