### ISSUE TITLE
The "relink database" function should have a confirmation dialogue at the end

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#597]
We need a simple dialogue that confirms to users that the relinking of a database has worked correctly (or not)

**Comment by marc-vdm** [comment]
For whoever picks this up: When implementing the above, please also include handling of the following edge case.
When a database has no dependencies to re-link. The option should be greyed-out in the context menu. Currently, it is not greyed out and produces a non-functional popup like below:
![image](https://user-images.githubusercontent.com/34626062/153878285-54fc8126-afb4-45d6-89f6-368e13ddb53c.png)

**Comment by marc-vdm** [comment]
Additionally, the relink database action does not inform the user of 'failed re-links'. I'm having activities that are missing in the database being re-linked to, that just keep their old dependency.
While I agree that this should be the failure mode (keep the old dependency), I do think AB should inform the user of failed re-links.

**Comment by Zoophobus** [comment]
This should be solved by the PR #900. An additional QtWidget is created and used to provide an following popup window that informs the user if some of the exchanges in the tables are unsuccessfully relinked. At the moment buttons are provided with the activity names that allow the user to directly open the first five exchanges that had an unsuccessful relinking, alternative options to the links are possible for dicussion
