### ISSUE TITLE
Import/Export of LCA setups

### ISSUE THREAD

**Issue by cprato-qw** [LCA-ActivityBrowser/activity-browser#601]
Dragging and dropping all the Reference flows you're interested into inside the are takes time (if you use 80 at a time), having to redo the work if you accidentally delete a project or if you install AB on another environment is not the best. Would it be feasible to add this feature? or to simplify thereference flows selection?
Thanks, Carlo

**Comment by marc-vdm** [comment]
Duplicate/related to #582

**Comment by marc-vdm** [comment]
Users can currently `copy` calculation setups and drag impact category families from the tree view.
This has made working with calculation setups much easier. I hope you agree with me closing the issue, otherwise just re-open it and share your thoughts.

**Comment by marc-vdm** [comment]
One option could perhaps be to make one database with all the reference flows (you can duplicate the flows from the database you are working on) The links to the original database will remain for all exchanges. That way, you can easily export/share that database and just select all and drag them to the `Reference flows:` table in the calculation setup.

Hopefully this also helps!
