### ISSUE TITLE
Treatment activities produce a negative LCA result - only rest column has a value

### ISSUE THREAD

**Issue by cprato-qw** [LCA-ActivityBrowser/activity-browser#602]
After importing ecoinvent 3.7, if i select treatment processes such as "treatment of municipal solid waste, unsanitary landfill, wet infiltration class (500mm) " and Impact category IPCC 2013, after LCA calculaton i get  a result of -1.17

In my opinion this value should be positive

Moreover this result, if inspected in the EF contributions tab, is not separated between the GHGs, only the "Rest" column has a value

![image](https://user-images.githubusercontent.com/83971901/118961945-2942a100-b965-11eb-8c9d-afa915732c40.png)

**Comment by MaximeAgez** [comment]
Hello,

I think this is related to the choice that was made in brightway2 to go with the IO notation and not the LCA notation (see "Getting the signs right" section here: https://2.docs.brightway.dev/intro.html).

Long story short, there is a relation T = I-A between the 2 notations (with I being the identity matrix)
where T would be your classic technology matrix of ecoinvent, i.e., with 1s on the diagonal and negative values for the consumption of inputs elsewhere
and where A is the technology matrix used in Input-Output (and the one chosen by AB/brightway2), i.e., with 0s on the diagonal and positive values for the consumption of inputs elsewhere

Ultimately, from what I understand, in AB you need to call negative flows of waste treatment, unlike in SimaPro, OpenLCA & co.

**Comment by cprato-qw** [comment]
Thanks Maxime, i changed the sign in the process and i got the correct sign and separation of emissions in the outputs!
