### ISSUE TITLE
ab_dev fails to launch after installing in new environment

### ISSUE THREAD

**Issue by mixib** [LCA-ActivityBrowser/activity-browser#605]
I installed the AB dev in a new environment following the README instructions:

```
conda create -y -n ab_dev -c conda-forge -c cmutel -c bsteubing -c haasad -c pascallesage "activity-browser-dev>2019.10.30"
```

Different to #603, the installation seems successful; with no error messages. However, when trying to launch, the same error message as in  #604 appears.

**Comment by StpdFox** [comment]
The issue relates to a bug in [brightway](https://github.com/brightway-lca/brightway2-calc/issues/36) They are working on it, i'm trying to chip in but it did mess up conda.
