### ISSUE TITLE
Installation issue ValueError: unsopported pickle protocol 5

### ISSUE THREAD

**Issue by rickyme18** [LCA-ActivityBrowser/activity-browser#606]
Hi,
I am quite new into this python world and I need some help. I tried to installed BW2 and activity browser. BW2 apparently works, but i cannot open activity browser. I complete the installation process (i tried ab and ab_dev) and always this error appears:
ValueError: unsopported pickle protocol: 5 
![image](https://user-images.githubusercontent.com/85166016/120318170-d4494800-c2df-11eb-9b9a-7d19b11e0391.png)

Could you help me please?

Thanks in advance

**Comment by StpdFox** [comment]
Hey rickyme18,
Are you using python 3.7? One way to fix this error is to upgrade your env to python 3.8 by typing 
`conda install -c anaconda python=3.8` This should update python, which in turn updates the pickle version. 

Although this might not get AB working. We are currently having some trouble with brightway and some DLL's. But maybe you are still on the right version

**Comment by rickyme18** [comment]
Hi StpdFox,
Thanks a lot. I updated python adn  now I get a new rror I cannot solve:
![image](https://user-images.githubusercontent.com/85166016/120466477-69f7dc80-c39f-11eb-9262-b066e418108f.png)

**Comment by StpdFox** [comment]
Yeah , sadly this ia running error in Brightway which is getting looked at by the developers there. [This issue](https://github.com/brightway-lca/brightway2-calc/issues/36) seems to be affecting windows machines. 

I'm hoping/praying it'll be resolved this week. If you have experience with PyCharm you should be able to run it from pycharm if you clone the github and run it with the environment you set up in miniconda. 

But if you don't have much experience with that i'd suggest to wait it out till we fix this. I'll keep you up to date

**Comment by rickyme18** [comment]
Thanks a lot! Ill be lookig forward to it.

**Comment by cmutel** [comment]
To be clearer on the original issue, Brightway uses the latest version of the Pickle protocol by default. At some point you used Brightway with Python 3.8 (or higher), and it saved data to the database using the [new protocol added in 3.8](https://docs.python.org/3/whatsnew/3.8.html#pickle-protocol-5-with-out-of-band-data-buffers). Now you are trying to load this data using Python 3.7, and it doesn't understand the pickle format.

**Comment by StpdFox** [comment]
Thanks for the workaround Chris! This saved us a lot.

Closing this issue
