### ISSUE TITLE
cut-off slider delay/debounce when dragging

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#610]
It would be great to have a delay/debounce when dragging the cut-off slider. 
Currently the slider immediately updates figures/tables, which is wasted CPU time and makes dragging slower.

**Comment by nabilahmed739** [comment]
Fixed in commit: 79c156f0

**Comment by nabilahmed739** [comment]
Still needs to be merged to master

**Comment by nabilahmed739** [comment]
Fixed in Dev branch, commit: 79c156f08771f102fdd533cb94a21e2aa81e7cc9
