### ISSUE TITLE
Monte Carlo Simulation with superstructure scenarios

### ISSUE THREAD

**Issue by SteLue** [LCA-ActivityBrowser/activity-browser#619]
Following up on the comment in #615, it seems as if there is an error with the MC simulation when using the scenarios from the superstructure. 

Example: 
The impact of a system with two different scenarios (default and alternative scenario) for the background system leads, as expected, to two different carbon footprints:
![grafik](https://user-images.githubusercontent.com/87361160/125607527-7f68db21-8597-4478-bdee-6a7a70ea9b83.png)
The characterization results for the default scenario (ecoinvent_SSP2_2020) is 446 kg CO2-eq. and 305 kg CO2-eq. for the alternative scenario.

However, when running the MC simulation, for the alternative scenario, the mean and the uncertainty distribution are far off from the characterization result:
![grafik](https://user-images.githubusercontent.com/87361160/125609953-d4020a9d-567b-47ee-82d0-d1f89b10b3c6.png)

For the default scenario, the mean and the uncertainty from the MC simulation are the same as for the alternative scenario:
![grafik](https://user-images.githubusercontent.com/87361160/125610101-3b962c7e-51e4-4390-bbd1-f816b40b2f82.png)

My first thought was that the MC simulation only uses the data from the default scenario, however, as even the characterization result is quite away from the mean of the MC simulation and just within the uncertainty, that is probably not the case.

I appreciate any help or ideas on what might cause this error.

**Comment by bsteubing** [comment]
Sorry for the late answer, I just see this now. Here an answer that I gave previously on the AB discussion list: https://brightway.groups.io/g/AB-discussion 

Thanks for the good questions and analysis. The simple answer is: I would not recommend to use Monte Carlo simulation for future scenarios. The data behind the MC runs is most from the ecoinvent database and does NOT represent future data and is not in any way related to the scenario data. It is in fact still the same uncertainty data that was present in the underlying ecoinvent version. This is why you get the same results and curve. Of course uncertainty data “could” be generated and put behind the future scenario data, but this is not readily available at this moment.

I personally rather see the differences between the scenarios as an indication of uncertainty. I am also quite skeptical about the quantification of uncertainties for far-future scenarios…
