### ISSUE TITLE
LCA Calculation setup improvements

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#623]
[intended for after first major Bokeh update]

The `LCA Setup` tab could be improved with the following updates:

 **1 - LCA Setup Filtering**
LCA Setups could be given checkboxes (and a select all/deselect all option) for each entry in the `Reference Flows:`, `Impact categories:` and `Scenarios` tables. This would then be used to filter different options/combinations. 
This idea could be done several ways:
 1) The LCA Setup calculates all options, but the checkboxes define what is shown in figures/tables
 2) The LCA Setup calculates all options, each LCA Results Tab then has the same checkboxes per figure/table to define what is shown.
 3) The LCA Setup calculates only the selected checkbox combinations, and needs to re-calculate for each change of checkboxes. Considering the speed of AB, this might not be the preferred option.

I personally think Option 1 is the best choice here.

 **2 - LCA Setup Custom names**
A 'name' column could be added in the LCA setup `Reference flows:` table. These names (if present) could then be used in the Figures and Tables in the LCA results instead of the long piped names we currently have ( product | process | location | database ).

**3 - LCA Setup screen without Calculation Setups**
Resolved
~~When a project has no calculation setups, the calculation setup screen looks like below.~~
~~I suggest that AB does one of the following:~~
~~1) AB generates an empty setup when starting a new project (with something like 'default' as name or something)~~
~~2) AB has a 'stretch' added in the `Reference Flows:` and `Impact categories:` table fields when there is no setup to move the headers up~~
~~3) AB shows a completely different screen on how to make a calculation setup~~

~~I think option 1 is more work, but would be easier to understand for new users, while option 2 is probably only a few lines of code and would still have the same difficulty of operating AB.~~
~~If we go with 2, perhaps one additional feature could be to present better that the user would need to make a new setup.~~
~~This could perhaps be done with a prominently placed text or highlighting the `New` button (if that's even possible)~~

~~Also, the `copy` button does not really make sense when there are no setups to copy. Perhaps we could hide that when there are no setups present. Additionally, this is also a reason to go with option 2 or 3, as in option 1, users could end up with no calculation setups by deleting them (needing to either disallow this (and keep at least 1 setup, or go back to the option 3 screen).~~
![image](https://user-images.githubusercontent.com/34626062/126483120-fc1a3c15-4446-4a37-a4e6-b3c01f1ac0f5.png)

**Comment by nabilahmed739** [comment]
@marc-vdm Is this issue fixed? Status seems to be closed.

**Comment by marc-vdm** [comment]
I'm currently also working in the LCA setup tab, please let me know of any plans of major changes to avoid running into issues.

**Comment by marc-vdm** [comment]
Also good to try and fix at the same time:
#450
#524
#532
#533 
#675

**Comment by marc-vdm** [comment]
Closing this as it is superseded by #728
