### ISSUE TITLE
len 4 tuple impact category breaks impact category tree view in Dev branch

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#631]
In the current Dev branch, when I have an impact category with 4 tuples (climate change with biogenic for example), it is not possible to drag the impact category to a calculation setup. This gives the below error:

```
Traceback (most recent call last):
  File "/.../activity_browser/ui/tables/LCA_setup.py", line 125, in dropEvent
    self.model.include_methods(event.source().selected_methods())
  File "/.../activity_browser/ui/tables/impact_categories.py", line 104, in selected_methods
    tree_level = self.tree_level()
  File "/.../activity_browser/ui/tables/impact_categories.py", line 130, in tree_level
    if indexes[1].data() != '' or indexes[2].data() != '' or indexes[3].data() != '':
IndexError: list index out of range
```
This does not seem to be an issue for me in the Conda versions as my 4 tuple impact category does not even seem to be present there.

**Comment by bsteubing** [comment]
@StpdFox this is indeed still a problem... the tree view seems to be hard-wired to having 3 tuple entries, methods with 4 or more disappear and I have not checked what happens with tuples that have less than 3... can we make the tree view universally applicable for tuples of any (reasonable if necessary) length? I can't see what this has to be fixed on 3...
