### ISSUE TITLE
'Rest' values in contribution tab should not be 0 when result is 0

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#635]
When calculating small databases, there is a chance that the `Rest` value in the contributions results table/figure is 0. When this happens, all table fields (see figure below) are 0. Would it not be better to skip the `Rest` line in the case the value is 0?
![rest_0_values](https://user-images.githubusercontent.com/34626062/129582600-87042d12-3132-4a9a-acf3-0600cae93afc.png)

(If the rest value is > 0, the other columns are an empty string instead of 0 values.)

**Comment by Zoophobus** [comment]
This should be fixed with the latest PR #896
