### ISSUE TITLE
Database Parameter issue " Could not save changes" 

### ISSUE THREAD

**Issue by StpdFox** [LCA-ActivityBrowser/activity-browser#642]
Multiple people are having problems with importing a database. When they try to open or import the database they are faced with a parameter issue from the AB : 
![image](https://user-images.githubusercontent.com/8734631/131672024-99c3d3e3-c665-48ff-aca3-6bedf33f2cfc.png)

The parameter that's missing doesn't seem to be in the excel file either. So there's something going wrong with the import.

**Comment by marc-vdm** [comment]
Closing as stale
