### ISSUE TITLE
Ecoinvent import / biosphere update

### ISSUE THREAD

**Issue by miriconda** [LCA-ActivityBrowser/activity-browser#643]
Hi, When trying to import ecoinvent 3.7 or 3.7.1 in either the activity browser or directly through jupyter notebook, i keep getting either an error because my biosphere process needs to be updated (which i have done several times now) - in AB or zero processes - in jupyter. I deleted 3.6 and imported it again just to see, and that works fine. Any ideas? Thanks a lot!

**Comment by StpdFox** [comment]
This issue w
