### ISSUE TITLE
Import/Export of database in bw2package

### ISSUE THREAD

**Issue by csalasr** [LCA-ActivityBrowser/activity-browser#644]
Hello, 
Since I launched the upgrade of the activity browser, the option to import and export databases in bw2package format is not longer available. The only possible format in the wizard import database is .7z (see image below)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/78724353/133098500-8f6857ce-96f4-4484-99ed-60c4e6addc32.png)

Neither is possible to export (see image below):
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/78724353/133098718-b86f9cdb-43cb-49b2-a8d0-35e5667d71dd.png)

Any idea of how to solve this issue?

**Comment by StpdFox** [comment]
Oh , this is something we didn't plan on removing. I'm going to take a look at it and try to get an update out as soon as possible. 

Could you tell me what versions of Python and what AB you were running ? ( Release or Dev?)

**Comment by csalasr** [comment]
Thanks for your reply!
I am using Python 3.9.6 and AB release

**Comment by csalasr** [comment]
I also get this error when duplicating an activity

![image](https://user-images.githubusercontent.com/78724353/133263785-45c01b14-a606-4403-9936-3b87c0550c0f.png)

**Comment by StpdFox** [comment]
> Thanks for your reply!
> I am using Python 3.9.6 and AB release

Try switching to the Dev version, it should be working there. It's strange how the release suddenly changed since we haven't update that version. So it might be a library related problem.

**Comment by StpdFox** [comment]
> I also get this error when duplicating an activity
> 
> ![image](https://user-images.githubusercontent.com/78724353/133263785-45c01b14-a606-4403-9936-3b87c0550c0f.png)

And you are also unable to export? Else i think these might be unrelated issues. 

Also, you could try switching to python 3.8 with the `conda install -c anaconda python=3.8` command.

**Comment by csalasr** [comment]
> > Thanks for your reply!
> > I am using Python 3.9.6 and AB release
> 
> Try switching to the Dev version, it should be working there. It's strange how the release suddenly changed since we haven't update that version. So it might be a library related problem.

I tried to call the Dev version under the ab_dev environment but I could not... See below

![image](https://user-images.githubusercontent.com/78724353/133409723-534e8d06-3592-4129-b1d5-27384413b61d.png)

![image](https://user-images.githubusercontent.com/78724353/133409842-fce079c1-caf6-488c-9d16-9c24365c5024.png)

**Comment by csalasr** [comment]
> > I also get this error when duplicating an activity
> > ![image](https://user-images.githubusercontent.com/78724353/133263785-45c01b14-a606-4403-9936-3b87c0550c0f.png)
> 
> And you are also unable to export? Else i think these might be unrelated issues.
> 
> Also, you could try switching to python 3.8 with the `conda install -c anaconda python=3.8` command.

I did that already. No success so far

**Comment by csalasr** [comment]
Hello, any further advice to solve these issues? Thanks!

**Comment by StpdFox** [comment]
I've had trouble replicating your issue.  So there could be something wrong with your environment. 


> > > Thanks for your reply!
> > > I am using Python 3.9.6 and AB release
> > 
> > 
> > Try switching to the Dev version, it should be working there. It's strange how the release suddenly changed since we haven't update that version. So it might be a library related problem.
> 
> I tried to call the Dev version under the ab_dev environment but I could not... See below
> 
> ![image](https://user-images.githubusercontent.com/78724353/133409723-534e8d06-3592-4129-b1d5-27384413b61d.png)

When you install the Dev version you can just run the AB with the activity-browser command. 
I think you are doing that in this next image?

> ![image](https://user-images.githubusercontent.com/78724353/133409842-fce079c1-caf6-488c-9d16-9c24365c5024.png)

This issue is mostly caused by a wrong python version. ( Mostly older than 3.8). Just to be sure could you type python with you are in the ab_dev environment and check the version?

**Comment by csalasr** [comment]
Thanks! I still have the issue in the standard ab even though the python version is 3.8. Nevertheless, I upgraded the python version in the ab_dev environment from 3.7 to 3.8 and it seems to work.
