### ISSUE TITLE
AB stable version installation does not work anymore

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#650]
![image](https://user-images.githubusercontent.com/33026150/134652199-2795d5cf-39c8-4302-be39-b4df46509f4e.png)

**Comment by StpdFox** [comment]
This is a library update part on SALib part as far as i know. The fix is to install the package importlib_metadata as in #646 . 
`pip install importlib-metadata` should fix it.

**Comment by bsteubing** [comment]
OK, good to know that this would fix it, but can we also include that in our dependencies so that the AB runs "out of the box" again... ?

**Comment by nabilahmed739** [comment]
@bsteubing , I could not reproduce this issue but I have updated salib as per @StpdFox 's recommendation. This along with the fix for biosphere flows update for ecoinvent 3.8 import issue are implemented in #653 .

**Comment by cml-ie-lab** [comment]
@bsteubing I came across the same issue a few days ago. Indeed installing importlib_metadata (through conda) fixed it. Not even thought it was a bug.

**Comment by nabilahmed739** [comment]
@marc-vdm , Does this issue still exist? This issue showed up in environments where the order of the channels was not correct, right?

**Comment by marc-vdm** [comment]
not entirely certain, I ran in to it while helping someone else, not on my own computer

**Comment by bsteubing** [comment]
I have not seen this issue lately, so I think we can close this issue for now
