### ISSUE TITLE
Unable to import Ecoinvent 3.8

### ISSUE THREAD

**Issue by ar-ali** [LCA-ActivityBrowser/activity-browser#651]
Hi, 

I am unable to import Ecoinvent 3.8. Please find attached the screenshot. I already updated my biosphere. 

Best,
Abdur
![Capture](https://user-images.githubusercontent.com/75308720/134932530-7187f9b4-6211-45d9-8034-8b193e88e8b8.JPG)

**Comment by bsteubing** [comment]
thank you @ar-ali. we are working on this already, a fix should soon be there

**Comment by ar-ali** [comment]
Thanks for the quick response. I look forward to the fix.

**Comment by StpdFox** [comment]
Sadly this is a problem with a new version of Ecoinvent 3.8 and some compatibility. This resulted in some biosphere flows to be unlinked. We have a fix ready to deploy but we have to wait for the BW2io library to update.

A possible workaround at the moment would be to change a line in the Bw2io code on your environment.
File "~/anaconda3/envs/ab/lib/python3.7/site-packages/bw2io/data/__init__.py", line 300, in _add_new_ecoinvent_biosphere_flows assert version in {"33", "34", "35", "36"}
If you remove this line, you should be able to create a new project.

If things still don't work, try switching to the dev version of the AB.

We are trying to get this fixed as fast as possible, sorry for the delay

**Comment by StpdFox** [comment]
What is the error you are getting ? And are you running on the Dev version ?
