### ISSUE TITLE
can't load default database

### ISSUE THREAD

**Issue by qixinbo** [LCA-ActivityBrowser/activity-browser#652]
Dear developer,
I encountered a problem when creating a project via AB:
After creating a project, and then load the default database, it says in the backend:
`Traceback (most recent call last):
  File "D:\activity_browser\ui\widgets\dialog.py", line 360, in run
    bw.create_default_lcia_methods()
  File "D:\Programs\anaconda3\envs\ab\lib\site-packages\bw2io\__init__.py", line 110, in create_default_lcia_methods
    ei.write_methods(overwrite=overwrite)
  File "D:\Programs\anaconda3\envs\ab\lib\site-packages\bw2io\importers\base_lcia.py", line 53, in write_methods
    raise ValueError(
ValueError: Can't write unlinked methods (465 unlinked cfs)`

![image](https://user-images.githubusercontent.com/6218739/135211128-4fa259c2-8196-473f-a632-48e1230c4ae6.png)

And then at the GUI, there is nothing in the "Impact Categories" tab. 
![image](https://user-images.githubusercontent.com/6218739/135211157-cd364a8c-e9d6-4b7f-b35c-68c82df77fd9.png)

Does anyone shed some lights on this problem?

**Comment by StpdFox** [comment]
Sadly this is a problem with a new version of Ecoinvent 3.8 and some compatibility. This resulted in some biosphere flows to be unlinked. We have a fix ready to deploy but we have to wait for the BW2io library to update. 

A possible workaround at the moment would be to change a line in the Bw2io code on your environment. 
`File "~/anaconda3/envs/ab/lib/python3.7/site-packages/bw2io/data/__init__.py", line 300, in _add_new_ecoinvent_biosphere_flows
    assert version in {"33", "34", "35", "36"}`
If you remove this line, you should be able to create a new project. 

If things still don't work, try switching to the dev version of the AB. 

We are trying to get this fixed as fast as possible, sorry for the delay

**Comment by qixinbo** [comment]
Dear @StpdFox, thanks a lot for your quick response.
I have done as what you said, removing the line as follows:
![image](https://user-images.githubusercontent.com/6218739/135233306-5a14c6a9-0d23-46c9-88c8-7dc023d431c8.png)
However, the same error still exists.
I just test the dev version of AB, and then the error is the same.
Actually, I have added one "print" sentence in the above function just as the snapshot shows, however, it is noted that it doesn't print this sentence. 
Then I guess this function actually not executed?
