### ISSUE TITLE
Understanding results of global sensitivity analysis 

### ISSUE THREAD

**Issue by ar-ali** [LCA-ActivityBrowser/activity-browser#660]
Hi, 

Could some please explain the names of the columns in the table generated after running global sensitivity analysis? There are many columns and values. I am interested in the normalized sensitivity coefficient values. 

Best regards,
Abdur

**Comment by marc-vdm** [comment]
Have you checked out [this paper](https://onlinelibrary.wiley.com/doi/full/10.1111/jiec.13194) on GSA (in AB)? I hope that helps in your understanding. If it is still unclear afterwards, you could perhaps contact @bsteubing for additional help too.
