### ISSUE TITLE
Sankey diagrams

### ISSUE THREAD

**Issue by jbnsn** [LCA-ActivityBrowser/activity-browser#662]
Hello!

I really like the Activity Browser's sankey diagrams. Are they based on an existing Python module which can be used outside of the Activity Browser by any chance?

Thanks and best regards
Jonas

**Comment by nabilahmed739** [comment]
@jbnsn , we have added an SVG export feature for the Sankey and Graph Navigators.
![image](https://user-images.githubusercontent.com/6296604/136781051-1dce23ea-c5c9-452e-82a2-e88f00726507.png)

**Comment by jbnsn** [comment]
Great, thanks!
