### ISSUE TITLE
Calculation Setup dropdown menu not readible anymore

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#675]
The horizontal width of the dropdown menu to choose the calculation setup has become so narrow now that I cannot read anymore what the different choices are...

**Comment by marc-vdm** [comment]
I don't see the issue in the latest version.
Is this still an issue? If so, could you provide a screenshot?

**Comment by bsteubing** [comment]
seems this has been fixed
