### ISSUE TITLE
StopIteration error when Dragging individual impact cateogories (leaves) into the calculation setup

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#676]
I cannot drag individual impact categories anymore into the calculation setup from the tree view of the impact categories. This needs to be fixed.

**Comment by bsteubing** [comment]
Just to be clear, I see @StpdFox as a leader here, but I also assigned @nabilahmed739 and @marc-vdm as you were involved at this at some point.

**Comment by marc-vdm** [comment]
Linked to #631.
