### ISSUE TITLE
Updating AB or AB_Dev breaks AB

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#680]
I just updated both AB and AB_Dev from Conda and it broke my AB install, I get the same error in both:
`bw2calc` was updated to ` 1.8.0-py_0 --> 2.0.dev3-py_0`, I'm guessing that might be the problem.

```
Traceback (most recent call last):
  File "C:\Users\m\miniconda3\envs\ab\Scripts\activity-browser-script.py", line 5, in <module>
    from activity_browser.app import run_activity_browser
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\__init__.py", line 8, in <module>
    from .app import Application, run_activity_browser
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\__init__.py", line 7, in <module>
    from .application import Application
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\application.py", line 2, in <module>
    from .controller import Controller
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\controller.py", line 5, in <module>
    import brightway2 as bw
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\brightway2\__init__.py", line 3, in <module>
    from bw2calc import *
AttributeError: module 'bw2calc' has no attribute 'ComparativeMonteCarlo'
```

**Comment by marc-vdm** [comment]
I manually put the version back to 1.8 and this fixed the issue.

For those looking for a temporary fix:
`conda activate ab`*
`conda install bw2calc=1.8`

*If you're using ab_dev, or another conda environment name, use that instead of `ab`.

Seeing it is a version issue, probably updating the requirements should fix the above.

**Comment by bsteubing** [comment]
@marc-vdm could you try again? Perhaps you were just a few minutes too quick... I specified the dependencies this morning here: https://github.com/LCA-ActivityBrowser/activity-browser/commit/3aa5ee06876a64ba8abc28f2e85184c0d87caa1f 

Which resulted in this (for ab-dev):
![image](https://user-images.githubusercontent.com/33026150/140170385-6978c5d0-8e16-4908-8643-f6f7394788d9.png)

So for me all looks correctly here...

**Comment by bsteubing** [comment]
update: when I install the ab-dev like this, I get all of the latest bw packages which are not compatible and thus the AB does not run.
`conda create -n abd39 activity-browser-dev python=3.9`

**Comment by bsteubing** [comment]
OK, some light... the when using the "python=3.9" statement conda falls back to an AB version from haasad
`activity-browser-~ bsteubing/noarch::activity-browser-dev-2019.10.30-py_0`

while this is what you get when not adding the python=3.9 requirement:
`activity-browser-~ bsteubing/noarch::activity-browser-dev-2021.11.03-pypy_0`

What I don't get though is WHY it is doing this... our stable/meta.yaml lists this:
`python>=3.8, <=3.9`

So it should be possible using python 3.9, or not?

**Comment by bsteubing** [comment]
OK, I changed the requirement to 
`python>=3.8`

which seems to solve the issue. The AB can now be used with python 3.9

@StpdFox @nabilahmed739 @marc-vdm if any of you experience issues with this or see a problem, please re-open this issue

**Comment by haasad** [comment]
I removed the label `main` from the activity-browser and activity-browser-dev package on the `haasad` channel. Conda install shouldn't pick them up anymore.
