### ISSUE TITLE
OMP Error #15 AB crashes on LCA calculation

### ISSUE THREAD

**Issue by th-scntst** [LCA-ActivityBrowser/activity-browser#682]
With the newest version of the AB (2021.11.04), I have the problem that the LCA calculation stops without obtaining a result and the AB is closed. The shell shows the following error message:
![grafik](https://user-images.githubusercontent.com/88439210/140544784-4a5a8097-2bc5-4f5d-ae1c-a3ad655f8efb.png)

The problem was solved by deleting the mentioned document! 
In my case, I found the file mentioned in the error message in the folder of the environment > Library > bin > libiomp5md.dll!
After deleting it, the LCA calculation works fine.

In addition to deleting this file, we also tried to set the KMP_DUPLICATE_LIB_OK=TRUE, as it was also mentioned in the error message. However, after setting this to FALSE again, the LCA calculation still works!

**Comment by marc-vdm** [comment]
I was not able to replicate this problem, @StpdFox any thoughts?

**Comment by bsteubing** [comment]
I have actually discussed this with @th-scntst and we were able to fix it manually with the fix above, but let's see if other people for some reason also experience this

**Comment by MaximeAgez** [comment]
I am also experiencing this currently, after just updating the stable version of AB. 
Deleting the libiomp5md.dll file did the trick though.

**Comment by haasad** [comment]
@th-scntst, did you also experience this issue after running `conda update activity-browser-dev` or in a "fresh" environment?

@MaximeAgez you also use Windows, correct?

It would be helpful if you both could upload your environment information, otherwise this is really tricky to diagnose. Uploading the environment file created with ```conda env export -f issue682.yaml``` would be most helpful.

**Comment by MaximeAgez** [comment]
[issue682.yaml.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/7513515/issue682.yaml.txt)

That's the environment after having deleted the dll file. Nothing else has been changed since.

**Comment by haasad** [comment]
I also couldn't reproduce the problem :man_shrugging: A new environment with the same channel configuration looks exactly the same, but doesn't lead to this error when running the AB. I reckon this is caused by an "unclean" update of one of dependencies, since it doesn't happen in a fresh environment.

**Comment by th-scntst** [comment]
@haasad: I encounter this problem when updating the AB in an existing environment as well as when I'm using the command conda create -n newenv activity-browser-dev!
I have just set up a new environment and installed the development version of AB. However, the upload of the environment file in yaml isn't supported here, which is why I ask you how to provide you this file?

**Comment by haasad** [comment]
Hi @th-scntst, sorry about that, I just assumed this would work. You can either rename the file to issue682.txt or create it once more with `conda env export -f issue682.txt`. Seems like github doesn't like yaml :-)

This is indeed a more serious issue if it also happens in new environments.

**Comment by th-scntst** [comment]
@haasad: thank you for this hint!
Here the txt file with the environment information
[issue682.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/7518745/issue682.txt)
:

**Comment by haasad** [comment]
I think we can rule out a problem with the dependencies. I compared your environments with a fresh install of the activity-browser (and activity-browser-dev) and there are no differences, but for me it works without errors.

Maybe a bit far-fetched, but could it be that the anaconda distribution is doing something fishy compared to miniconda? @bsteubing, @marc-vdm, @StpdFox, @nabilahmed739, do any of you use anaconda and experience the error in a fresh environment?

```diff
diff --git a/issue682_maxime.yaml b/issue682_adrian2.yaml
index 5b2278e..9d24853 100644
--- a/issue682_maxime.yaml
+++ b/issue682_adrian2.yaml
@@ -127,4 +127,4 @@ dependencies:
   - xz=5.2.5=h62dcd97_0
   - zlib=1.2.11=h62dcd97_4
   - zstd=1.4.9=h19a0ad4_0
-prefix: C:\Users\Maxime\Anaconda3\envs\ab
+prefix: C:\Users\adrian\Miniconda3\envs\ab
```

```diff
diff --git a/issue682_th-scntst.yaml b/issue682_adrian.yaml
index 6689a5c..cea0b53 100644
--- a/issue682_th-scntst.yaml
+++ b/issue682_adrian.yaml
@@ -1,4 +1,4 @@
-name: abd
+name: ab
 channels:
   - conda-forge
   - defaults
@@ -6,7 +6,6 @@ channels:
   - bsteubing
   - haasad
   - pascallesage
-  - romainsacchi
 dependencies:
   - activity-browser-dev=2021.11.09=pypy_0
   - appdirs=1.4.4=pyh9f0ad1d_0
@@ -133,4 +132,4 @@ dependencies:
   - xz=5.2.5=h62dcd97_1
   - zlib=1.2.11=h8ffe710_1013
   - zstd=1.5.0=h6255e5f_0
-prefix: C:\Users\elke2\anaconda3\envs\abd
+prefix: C:\Users\adrian\Miniconda3\envs\ab
```

**Comment by vitekcode** [comment]
I was experiencing the same problem as @th-scntst on a fresh install of AB using anaconda; here is the list of dependencies [issue682.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/7545898/issue682.txt)

Following @th-scntst 's approach 👇🏼 the problem appears to be solved.
 
> The problem was solved by deleting the mentioned document! In my case, I found the file mentioned in the error message in the folder of the environment > Library > bin > libiomp5md.dll! After deleting it, the LCA calculation works fine.

**Comment by bsteubing** [comment]
thanks a lot @haasad for this hint (that anaconda might be the problem). I am using miniconda, so can't tell...

**Comment by haasad** [comment]
I don't think it's very likely, but I'm out of other ideas. The error doesn't happen in the windows github actions and I can't reproduce it on my Windows machine.
It looks to me like it's caused by something outside of the environment, Windows 11 maybe?

**Comment by th-scntst** [comment]
@haasad I actually had installed Windows 11 temporarily but then went back to Windows 10. I cannot fully prove it but the problem with the AB and the update to Windows 11 occured at a similar time. However, the error was still there after downgrading to Windows 10.

**Comment by bsteubing** [comment]
this is indeed another good lead: `Windows 11`
I know from @th-scntst that Windows 11 had been installed, although at the time of testing it had been reverted to Windows 10

**Comment by haasad** [comment]
@MaximeAgez @vitekcode Do you guys use Windows 11? We're trying to narrow down what differences there are outside of the specific AB environment.

**Comment by MaximeAgez** [comment]
Windows 10 for me

**Comment by vitekcode** [comment]
> @MaximeAgez @vitekcode Do you guys use Windows 11? We're trying to narrow down what differences there are outside of the specific AB environment.

I'm on Windows 10 too.

**Comment by haasad** [comment]
Possibly related issue I found while working on #694: https://github.com/conda-forge/conda-forge.github.io/issues/727

**Comment by haasad** [comment]
I assume that with the new releases of `mkl` and `intel-openmp` this issue shouldn't appear anymore, see also #694.

Please reopen if you encounter this problem again.
