### ISSUE TITLE
AttributeError: module 'bw2calc' has no attribute 'ComparativeMonteCarlo' 

### ISSUE THREAD

**Issue by cprato-qw** [LCA-ActivityBrowser/activity-browser#683]
After updating, as i was running into problems when trying to import ecoinvent3.8, i get this error message when trying to run ab, this is the log of updates + error:
[updatelog1.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/7495416/updatelog1.txt)

i tried running update bw2calc but i still get the same error msg.

When trying to import ecoinvent 3.8, i get this error message:
[errorlog import ei3.8.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/7495430/errorlog.import.ei3.8.txt)

**Comment by haasad** [comment]
Your environment uses python 3.7, which isn't really supported anymore in the activity-browser as far as I can see. I suggest creating a new environment following the installation instructions in the README. You can either first remove the old environment with `conda remove -n ab --all`, or just use another name, eg. `ab39` or similar.

**Comment by cprato-qw** [comment]
Thanks!
