### ISSUE TITLE
Use semantic versioning for the stable AB release

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#685]
I propose that the stable AB release should go back to using semantic versioning. See https://semver.org/ for details. In short: Increase the _major_ version (__2__.6.6 to __3__.0.0) for big, breaking changes, increase the _minor_ version (2.__6__.6 to 2.__7__.0) for non-breaking new features and icrease the _patch_ version (2.6.__6__ to 2.6.__7__) for small changes and bugfixes.

Version numbers like the ones used in recent releases (ie. 2.6.6d, 2.6.6c etc.) will either not work correctly or produce unpredictable behavior in the dependency resolver. This basically makes the AB unusable as a dependency for other projects.

Additionally the version numbers in the code haven't been updated since 2.6.3 in January:
https://github.com/LCA-ActivityBrowser/activity-browser/blob/2f125dad887285bbb74d5794684b0621e382373e/setup.py#L22
https://github.com/LCA-ActivityBrowser/activity-browser/blob/2f125dad887285bbb74d5794684b0621e382373e/activity_browser/info.py#L2

I made a pull request that automates this process, so there's no manual bumping of the version number required anymore. Only a new tag is required for a new release. See #684 

@StpdFox @bsteubing

**Comment by bsteubing** [comment]
Thanks for the suggestion, which is I think very good and which we should follow. Thanks for the other PR!

**Comment by bsteubing** [comment]
@nabilahmed739 should probably also read this so we are all on the same page for future versioning

**Comment by nabilahmed739** [comment]
Yes, Just last week we were discussing on the approach to streamline the versioning. This PR comes right on time.
Additionally, lately we have been spending a lot of time manually diagnosing user's environment / package compatibility issues as many users use the same environment for multiple applications(using bw but maybe bw2.5, etc.). Hence, we think it could be more efficient to have a compatibility check when AB starts and show diagnosis results(incompatible/missing package/etc.): #679 
@haasad , We have not started on the feasibility of the same yet, Your opinions/inputs are much appreciated as you have recently updated the CI config.
