### ISSUE TITLE
Global Sensitivity Analysis TypeError

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#690]
Hello,
While launching GSA after performing an MC I get a TypeError.

![image](https://user-images.githubusercontent.com/24285636/145102397-3794a06e-e778-4d0c-ac9e-dde6e2c5ae0d.png)

The error seems to be coming from the fact that the code checks whether the uncertainty_type is superior to 1 or not.

![image](https://user-images.githubusercontent.com/24285636/145102579-01d72d12-22ce-4c8f-94c0-002a27ec27b2.png)

I guess some of my flows do not have an uncertainty type defined, hence why the error. 
Are uncertainty_type properties supposed to automatically be defined (even as 0) whenever an exchange is created?

**Comment by maw-cu** [comment]
I solved this temporarily by skipping the drop_no_uncertainty_exchanges routine in the (sensitivity_analysis.py) file

**Comment by ar-ali** [comment]
Hi, skipping the drop_no_uncertainty_exchanges did not work for me.

**Comment by marc-vdm** [comment]
Resolved with #766
