### ISSUE TITLE
Excel database import does not ask for sheet in the file

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#697]
Basically the title. The excel database import dialog does not ask for which excel sheet to be imported, this could be a useful feature to have and not be too much work to implement -it is already present for scenario imports from excel-.

**Comment by bsteubing** [comment]
@marc-vdm : I think this is because the bw excel importer imports all sheets by default that are not specified with a "skip" argument (or something similar, I don't remember by heart)
