### ISSUE TITLE
Improve activity tab

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#7]
[Issue on bitbucket](https://bitbucket.org/cmutel/activity-browser/issues/18/enhance-activity-details-page)

The vertical layout of the activity tab needs to be improved to use the space more efficiently:
<img width="795"
src="https://cloud.githubusercontent.com/assets/11636405/26298108/36e93cf0-3ed6-11e7-8679-fec6271dd8fa.png">

Things to improve:
- Reduce margin space / unused vertical space
- Resize tables based on content
- Display comment only when triggerd by some event (eg. button, or hover tooltip)

From original issue on bitbucket:
- Allow tables to expand/collapse with more details, e.g. database, parameterized exchange, uncertainty type, uncertainty values

**Comment by cardosan** [comment]
Since I need for myself to explore formulas, I have added them to the Activity tab (see picture). 
If you wish I can push this change

![screenshot from 2017-11-30 19 13 48](https://user-images.githubusercontent.com/11156305/33447307-3046a62a-d603-11e7-8709-76d004e294fa.png)

**Comment by haasad** [comment]
I think this would be a very nice addition. @bsteubing, do you think we could add a switch in your new settings file, so people could turn this feature on and off?

**Comment by bsteubing** [comment]
Hi Adrian, lots of good ideas. I think we need to revise the way this information is displayed carefully so navigation is still fast, but space is used better. The hide buttons (which also still have a bug as you might have seen) are perhaps a good solution and could be used also for the comment. Another possibility is simply to make the activities widget scrollable. I'll also raise another issue for navigation, which is that it would be great if every exchange could be switched to by double-clicking on it (like in the original version of the AB). Parameters would be fantastic to have (if that is too much of a project, I could get one of my students to work on it...)!

**Comment by haasad** [comment]
Original issue was solved quite some time ago, now parameters can also be displayed as discussed here
