### ISSUE TITLE
Not able to run AB after updating the development version

### ISSUE THREAD

**Issue by AdelineJerome** [LCA-ActivityBrowser/activity-browser#703]
Hi,

I got some issues with AB (similar to issue #618) and I updated the development version. I am not able to run AB anymore and get the following error:
![image](https://user-images.githubusercontent.com/95700006/151813048-cc0c5813-0fcc-4879-950c-1126bf444dfb.png)

Best regards,
Adeline

**Comment by marc-vdm** [comment]
@cmutel Are you aware of an issue like this? I was not able to replicate this problem.

**Comment by cmutel** [comment]
This can only come from manually updating bw2calc. The AB should pin bw2calc to (I think) version 1.8.something.

**Comment by marc-vdm** [comment]
@cmutel Thanks for the quick comment! Feel free to unsubscribe again :)

@AdelineJerome Could you check which version of `bw2calc` your environment is using?
You can do this by typing `conda list` in the Anaconda prompt when you are in `ab_dev` (`conda activate ab_dev`) and then finding `bw2calc` in the list.

Anyway, I think you can fix this by doing the following:
```
conda activate ab_dev
conda install bw2_calc=1.8
```
and confirm with `y` when required.

**Comment by haasad** [comment]
If you've been using the AB for a longer time, chances are your environment uses a python version below 3.8. The most recent versions require 3.8 or greater. The pinning of bw2calc to 1.8 probably doesn't work for older python versions. I suggest re-installing the AB -> `conda remove -n ab_dev --all` and then following the [installation instructions in the README](https://github.com/LCA-ActivityBrowser/activity-browser#installation).

**Comment by AdelineJerome** [comment]
On the AB development version environment, I had:
![image](https://user-images.githubusercontent.com/95700006/151938056-62b52e30-c6b9-41e0-b59b-b6c8fda9ab4c.png)
On the stable version of AB environment that I created yesterday (and I can run AB normally there), I have: 
![image](https://user-images.githubusercontent.com/95700006/151938174-d8b5642b-8483-4d49-bd7c-90425d09ab95.png)

After downgrading the bw2calc package to the 1.8 version, I still get an error:
![image](https://user-images.githubusercontent.com/95700006/151938673-d75d5bdc-060e-40dd-8ed2-ddbc0a34194f.png)

The package called salib has the same version in the dev and non-dev environments (1.4.5)

**Comment by AdelineJerome** [comment]
> If you've been using the AB for a longer time, chances are your environment uses a python version below 3.8. The most recent versions require 3.8 or greater. The pinning of bw2calc to 1.8 probably doesn't work for older python versions. I suggest re-installing the AB -> `conda remove -n ab_dev --all` and then following the [installation instructions in the README](https://github.com/LCA-ActivityBrowser/activity-browser#installation).

Ok, I will use the new environment with the normal version then. When I remove the ab_dev environment, will it keep the projects created with it?

**Comment by marc-vdm** [comment]
@AdelineJerome, I'd indeed suggest trying the fix offered by @haasad above (which you may have missed as you posted at nearly the same time).

Please let us know if this fixes your issue!

**Comment by marc-vdm** [comment]
Yes you should keep access to all data stored in the projects. You should always have access to the same projects independent of the version of AB (stable or development).

**Comment by AdelineJerome** [comment]
I will continue with the stable version installed yesterday then. Thanks for the swift replies!
