### ISSUE TITLE
Check all dependency versions restrictions and pins

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#716]
We currently use the following dependencies:
https://github.com/LCA-ActivityBrowser/activity-browser/blob/043845aed913e0ec20b0f18c8e0d6d3a5dd32950/ci/recipe/stable/meta.yaml#L23-L42

We should check and update all those pins and evaluate if they are (still) necessary. There's some completely outdated pins (e.g. `fuzzywuzzy` is not even used anymore, `xlrd` problem was fixed a year ago).

There is also a large overlap of packages that are pinned directly by the AB, but also by brightway2 or one of its components. This regularly leads to conflicts. Ideally we should use more restrictive pinning for the `brightway2` metapackage, but let brightway2 "decide" what exact dependencies it needs to avoid conflicts.

We should also restrict the AB to python 3.8 and 3.9 for the moment, as there still issues with 3.10 (see e.g. #714)

**Comment by haasad** [comment]
I have started working on this in https://github.com/haasad/activity-browser/tree/rework-dependencies, but atm there's still a problem with the latest bw2calc=1.8.1, see discussions in https://github.com/brightway-lca/brightway2-calc/issues/43

**Comment by bsteubing** [comment]
@haasad I fully agree with this and will accept a PR when it is ready - thanks so much!!

**Comment by cmutel** [comment]
@haasad @bsteubing I don't think we need scipy <1.8 or bw2calc 1.8.0 as of this afternoon. In general, I think it is cleverest to pin to brightway2 (currently 2.4.2).
