### ISSUE TITLE
Reduce conda channels required for installation

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#717]
Currently we use 5 separate conda channels for the AB installation. While `conda-forge`, `cmutel` and `bsteubing` are obviously quite necessary, we use the `haasad` and `pasacllesage` channel only for one package each. If we could get rid of those channels, it would simplify the installation procedure and the dependency resolution when installing.

`haasad` channel:
- used to provide [`pypardiso`](https://github.com/haasad/PyPardisoProject), [`eidl`](https://github.com/haasad/EcoInventDownLoader) and `eidl7zip`
- `pypardiso` has since been accepted to `conda-forge`, see https://anaconda.org/conda-forge/pypardiso
- `eidl7zip` has been replaced by a pure-python solution in `eidl` v1.4.0, see [release notes](https://github.com/haasad/EcoInventDownLoader/releases/tag/v1.4.0)
- only `eidl` remains

`pascallesage` channel:
- only the `presamples` packages is needed from this channel, but the conda package is outdated and not getting updates (https://anaconda.org/PascalLesage/presamples/files)
- the latest 0.2.7 version is only available for windows, linux and osx users are stuck with 0.2.3

I suggest the following:
- host `eidl` and `presamples` on the `bsteubing` channel
- re-package `presamples` 0.2.7 from PyPI with a clean noarch package with github actions and upload to the `bsteubing` channel
- directly upload `eidl` to the bsteubing channel, either by providing me with a token for the channel or adding me as a contributor (we can work out the specifics later)
- I'm also open to transfer `eidl` to the LCA-ActivityBrowser org

@bsteubing, @marc-vdm let me know what you think about these suggestions.

**Comment by bsteubing** [comment]
Thanks @haasad for addressing this issue. I almost entirely agree, with one change:
- **the AB should get rid of the `presamples `dependency altogether** (I think it is hardly used and anyway more suitable for use in python directly with large datasets... it may also be/become outdated with bw2.5 @cmutel knows more about this)

@marc-vdm said that he could have a go at this (although if this is too much of a task, then we'll have to find another solution)
@haasad : could you please contact me to discuss how to best deal with `eidl`? Perhaps this is solved easiest in a quick call?

**Comment by cmutel** [comment]
+1 to removing presamples, this functionality is subsumed in 2.5. The presamples package will then just be campaign management, and updating it is not a priority right now.

**Comment by haasad** [comment]
I uploaded the noarch `presamples` build version 0.2.3 to the bsteubing channel:
```
conda search -c bsteubing presamples     
Loading channels: done
# Name                       Version           Build  Channel             
presamples                     0.2.3      h39e3cac_0  bsteubing
```
We can remove it again once the AB supports brightway 2.5

I also added `eidl`, see PR linked above.
```
conda search -c bsteubing eidl      
Loading channels: done
# Name                       Version           Build  Channel             
eidl                           1.4.1            py_0  bsteubing
```
