### ISSUE TITLE
AB_DEV crashes when launching simulation on MacBook

### ISSUE THREAD

**Issue by nanocate** [LCA-ActivityBrowser/activity-browser#718]
Hello, 

The av_dev crashes and then closes when launching a simple simulation with one impact category and one activity. Please see the error log below:

<img width="1094" alt="Screenshot 2022-02-16 at 11 34 36" src="https://user-images.githubusercontent.com/7212378/154247316-469ef4a5-f626-4392-88e1-183b0cfc5eb3.png">

**Comment by haasad** [comment]
Hi @nanocate,

this error sounds like you have a new Mac with the apple silicon M1 chip architecture. Unfortunately a lot of python packages don't fully support the M1 architecture yet, including some dependencies of the activity-browser.

We had a lengthy discussion in #705 trying to get it to work.

What you could try is the following:
```
conda activate ab_dev
conda remove pypardiso --force
conda install scikit-umfpack
```

Please let me know if this "fixes" your problem. If it doesn't, I'd be grateful if you can post the outputs of `conda info` and `conda list -n ab_dev --explicit` here, so I can help you troubleshoot this further.

**Comment by nanocate** [comment]
Hi @haasad, 

thanks for your quick response. I tried your suggestion but it still does not work. Please find below the outputs as requested:

(ab_dev) csalasr@caterins-macbook-air ~ % conda info

     active environment : ab_dev
    active env location : /Users/csalasr/opt/anaconda3/envs/ab_dev
            shell level : 2
       user config file : /Users/csalasr/.condarc
 populated config files : /Users/csalasr/.condarc
          conda version : 4.11.0
    conda-build version : 3.20.4
         python version : 3.8.12.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/csalasr/opt/anaconda3  (writable)
      conda av data dir : /Users/csalasr/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/cmutel/osx-64
                          https://conda.anaconda.org/cmutel/noarch
                          https://conda.anaconda.org/bsteubing/osx-64
                          https://conda.anaconda.org/bsteubing/noarch
                          https://conda.anaconda.org/haasad/osx-64
                          https://conda.anaconda.org/haasad/noarch
                          https://conda.anaconda.org/pascallesage/osx-64
                          https://conda.anaconda.org/pascallesage/noarch
          package cache : /Users/csalasr/opt/anaconda3/pkgs
                          /Users/csalasr/.conda/pkgs
       envs directories : /Users/csalasr/opt/anaconda3/envs
                          /Users/csalasr/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.8.12 Darwin/21.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

--------------------------------------

(ab_dev) csalasr@caterins-macbook-air ~ % conda list -n ab_dev --explicit
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/bzip2-1.0.8-h0d85af4_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2021.10.8-h033912b_0.tar.bz2
https://conda.anaconda.org/haasad/osx-64/eidl7zip-1.0.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/fribidi-1.0.10-hbcb3906_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/giflib-5.2.1-hbcb3906_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jbig-2.1-h0d85af4_2003.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jpeg-9e-h0d85af4_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libbrotlicommon-1.0.9-h0d85af4_6.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-12.0.1-habf9029_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libdeflate-1.10-h0d85af4_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.4.2-h0d85af4_5.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libiconv-1.16-haf1e3a3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libwebp-base-1.2.2-h0d85af4_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libzlib-1.2.11-h9173be1_1013.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/llvm-openmp-13.0.1-hda6cdc1_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/metis-5.1.0-h2e338ed_1006.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mysql-common-8.0.28-h694c41f_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.3-he49afe7_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pthread-stubs-0.4-hc929b4f_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tzdata-2021e-he74cb21_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xorg-libxau-1.0.9-h35c211d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xorg-libxdmcp-1.1.3-h35c211d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.5-haf1e3a3_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/gmp-6.2.1-h2e338ed_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/icu-69.1-he49afe7_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lerc-3.0-he49afe7_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libbrotlidec-1.0.9-h0d85af4_6.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libbrotlienc-1.0.9-h0d85af4_6.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libedit-3.1.20191231-h0678c8f_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libgfortran5-9.3.0-h6c81a4c_23.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libimagequant-2.17.0-h9bde063_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libllvm13-13.0.1-hd011deb_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libxcb-1.13-h0d85af4_1004.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lz4-c-1.9.3-he49afe7_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/nspr-4.32-hcd9eead_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1l-h0d85af4_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-8.1-h05e3726_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tbb-2021.5.0-h940c156_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h9173be1_1013.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/brotli-bin-1.0.9-h0d85af4_6.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libclang-13.0.1-default_he082bbe_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libgfortran-5.0.0-9_3_0_h6c81a4c_23.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libpng-1.6.37-h7cec526_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libxml2-2.9.12-h7e28ab6_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mkl-2022.0.0-h89fa619_782.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mpfr-4.1.0-h0f52abe_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.37.0-h23a322b_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.11-h5dbffcc_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zstd-1.5.2-h582d3a0_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/brotli-1.0.9-h0d85af4_6.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/freetype-2.10.4-h4cff582_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/krb5-1.19.2-hcfbf3a7_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libopenblas-0.3.18-openmp_h3351f45_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libtiff-4.3.0-h17f2ce3_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libxslt-1.1.33-h1acebb3_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mysql-libs-8.0.28-h115446f_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/nss-3.74-h31e2bf1_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.9.10-h1dd9edd_2_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/appdirs-1.4.4-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/charset-normalizer-2.0.12-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.11.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/dill-0.3.4-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/docopt-0.6.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/et_xmlfile-1.0.1-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/fasteners-0.17.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-3.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/itsdangerous-2.0.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lcms2-2.12-h577c468_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libblas-3.9.0-13_osx64_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libpq-14.2-hea3049e_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libwebp-1.2.2-h28dabe5_0.tar.bz2
https://conda.anaconda.org/cmutel/noarch/mrio_common_metadata-0.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/munkres-1.1.4-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openjpeg-2.4.0-h6e7aa92_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pox-0.3.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.21-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-3.0.7-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.9-2_cp39.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2021.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/six-1.16.0-pyh6c4a22f_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/soupsieve-2.3.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tabulate-0.8.9-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/typing_extensions-4.1.1-pyha770c72_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/unicodecsv-0.14.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/unidecode-1.3.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/voluptuous-0.12.2-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/werkzeug-2.0.3-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.37.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/xlrd-1.2.0-pyh9f0ad1d_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/xlsxwriter-3.0.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/astunparse-1.6.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/beautifulsoup4-4.10.0-pyha770c72_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2021.10.8-py39h6e9494a_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cffi-1.15.0-py39he338e87_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/click-8.0.3-py39h6e9494a_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/future-0.18.2-py39h6e9494a_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/kiwisolver-1.3.2-py39hf018cea_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcblas-3.9.0-13_osx64_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapack-3.9.0-13_osx64_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lxml-4.7.1-py39hf41e7f8_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/markupsafe-2.0.1-py39h89e85a6_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/multiprocess-0.70.12.2-py39h89e85a6_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/openpyxl-3.0.9-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/packaging-21.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/peewee-3.14.8-py39h06734b0_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pillow-9.0.1-py39h768cb32_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ppft-1.6.6.4-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/psutil-5.9.0-py39h89e85a6_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pysocks-1.7.1-py39h6e9494a_4.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-levenshtein-0.12.2-py39h89e85a6_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/qt-5.12.9-h2a607e2_5.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-60.9.0-py39h6e9494a_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/unicodedata2-14.0.0-py39h89e85a6_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/whoosh-2.7.4-py39h6e9494a_5.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/wrapt-1.13.3-py39h89e85a6_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/arrow-1.2.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/brotlipy-0.7.0-py39h89e85a6_1003.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cryptography-36.0.1-py39h209aa08_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/eight-1.0.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/fonttools-4.29.1-py39h89e85a6_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/fuzzywuzzy-0.18.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-3.0.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/numpy-1.22.2-py39h9d9ce41_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pathos-0.2.8-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-22.0.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pyprind-2.11.2-py39h6e9494a_1002.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pyside2-5.13.2-py39h71a569c_6.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/suitesparse-5.10.1-h7aff33d_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/asteval-0.9.23-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/flask-2.0.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/matplotlib-base-3.5.1-py39hb07454d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pandas-1.4.1-py39h4d6be9b_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-22.0.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/scipy-1.7.3-py39h056f1c0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/networkx-2.6.3-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/patsy-0.5.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/haasad/noarch/pypardiso-0.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/salib-1.4.5-pyh6c4a22f_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/scikit-umfpack-0.3.2-py39h4b7cfb1_1004.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/seaborn-base-0.11.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/cmutel/noarch/stats_arrays-0.6.5-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.26.8-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/cmutel/noarch/bw2calc-1.8.0-py_0.tar.bz2
https://conda.anaconda.org/cmutel/noarch/bw2parameters-0.7-py_0.tar.bz2
https://conda.anaconda.org/cmutel/noarch/bw_migrations-0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-2.27.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/statsmodels-0.13.2-py39hc89836e_0.tar.bz2
https://conda.anaconda.org/cmutel/noarch/bw2data-3.6.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/seaborn-0.11.2-hd8ed1ab_0.tar.bz2
https://conda.anaconda.org/cmutel/noarch/bw2analyzer-0.10-py_1.tar.bz2
https://conda.anaconda.org/cmutel/noarch/bw2io-0.8.6-py_1.tar.bz2
https://conda.anaconda.org/pascallesage/noarch/presamples-0.2.3-h39e3cac_0.tar.bz2
https://conda.anaconda.org/cmutel/noarch/brightway2-2.3-py_3.tar.bz2
https://conda.anaconda.org/haasad/noarch/eidl-1.3.3-py_0.tar.bz2
https://conda.anaconda.org/bsteubing/noarch/activity-browser-dev-2022.02.15-py_0.tar.bz2

**Comment by haasad** [comment]
What error did you get after the steps I listed in the comment above? Still the MKL error? The activity-browser itself is starting, right?

**Comment by nanocate** [comment]
Hi @haasad, 
Yes, that's right. The activity-browser starts. The error I get when launching the simulation is: 

Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
QObject::~QObject: Timers cannot be stopped from another thread
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

**Comment by cmutel** [comment]
@nanocate The environment you described still has `pypardiso` installed. Can you post the response after removing it with `conda remove pypardiso --force`?

**Comment by nanocate** [comment]
Hello, 
it seems to be working now. However, the "welcome" page as well as the sankey diagram appear as blank pages... there is nothing but a blank space.

**Comment by haasad** [comment]
Closing this in favour of #741 for the blank welcome screen issue
