### ISSUE TITLE
Tests on OSX sometimes fail because of a segmentation fault

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#723]
See discussions in #707 and #711, https://github.com/LCA-ActivityBrowser/activity-browser/commit/d6e29cc4b370da20d1f6105fd032ff3ab37a34bc

Example of a workflow that fails: https://github.com/LCA-ActivityBrowser/activity-browser/runs/5232989949?check_suite_focus=true

**Comment by haasad** [comment]
https://github.com/LCA-ActivityBrowser/activity-browser/issues/707#issuecomment-1043093725
> @haasad [this MacOs test](https://github.com/LCA-ActivityBrowser/activity-browser/runs/5232989949?check_suite_focus=true) failed twice, do I just keep re-running the test or is there a way to find if it is my code that is actually failing?

@marc-vdm I think it's highly unlikely that your changes cause the segmentation fault. My guess is that something with the tests itself causes the segfault. E.g. some python object that is garbage-collected too early which trips Qt and causes the segfault.

I'd argue that it's not worth to invest more time into this unless there's a report of a Mac AB users that experiences this segfault during real usage. We still test the functionality iteself on windows and linux. I'd just skip all the problematic tests, see my linked PR.

**Comment by marc-vdm** [comment]
I've moved the review on #724 to bs, but I'm assuming it will get merged! Thanks again for helping to sort this out, this is greatly appreciated.
