### ISSUE TITLE
update info in 'Help' > 'AB' popup

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#725]
The information in the 'Help' popup is outdated.
Both main developers/contact info (is Daniel's email still in use?) and copyright info could use an update.

![image](https://user-images.githubusercontent.com/34626062/154699734-9c07b37f-b7ea-4613-af09-7d988fd166d2.png)

**Comment by Zoophobus** [comment]
This should be updated in the latest development versions. Maybe we should check for some of the details, for example license information, at present we point to the license details on the github page.
