### ISSUE TITLE
lca calculations_lca scores

### ISSUE THREAD

**Issue by jmehreth** [LCA-ActivityBrowser/activity-browser#73]
when choosing many lcia methods (in my case 14), the display of the lca scores in the 'lca results' tab is not practical as it's impossible to read the overlapping numbers. a scroll bar would be handy!

**Comment by haasad** [comment]
![image](https://user-images.githubusercontent.com/11636405/34038560-164348f6-e18d-11e7-9684-1d566276762d.png)
this is how it looks on linux with 10 activities and 14 lcia methods

**Comment by bsteubing** [comment]
There are a lot of improvements to be done... thanks. I am planning to overhaul this together with some students in spring 2018...
