### ISSUE TITLE
Error importing Ecoinvent while extracting .7z file 

### ISSUE THREAD

**Issue by nabilahmed739** [LCA-ActivityBrowser/activity-browser#737]
Environment: Windows 10, Python 3.8

Stacktrace:
> Traceback (most recent call last):
>   File "C:\Users\user\Documents\...\activity-browser\activity_browser\ui\wizards\db_import_wizard.py", line 702, in run
>     self.run_extract_import()
>   File "C:\Users\user\Documents\...\activity-browser\activity_browser\ui\wizards\db_import_wizard.py", line 770, in run_extract_import
>     self.run_extract(tempdir)
>   File "C:\Users\user\Documents\...\activity-browser\activity_browser\ui\wizards\db_import_wizard.py", line 756, in run_extract
>     self.downloader.extract(target_dir=temp_dir)
>   File "C:\Users\user\Documents\...\activity-browser\activity_browser\ui\wizards\db_import_wizard.py", line 1218, in extract
>     self.extraction_process = subprocess.Popen(extract_cmd,  executable='7z.exe', stdout=subprocess.DEVNULL)
>   File "C:\ProgramData\Anaconda3\envs\ab_vis2\lib\subprocess.py", line 858, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\ProgramData\Anaconda3\envs\ab_vis2\lib\subprocess.py", line 1311, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by haasad** [comment]
Short-term fix: `conda install -c haasad eidl7zip`

**Comment by nabilahmed739** [comment]
Also, this looks like eidl is already include functions to extract 7z file, maybe this shouldnt be duplicated in AB.

**Comment by haasad** [comment]
> Also, this looks like eidl is already include functions to extract 7z file, maybe this shouldnt be duplicated in AB.

Yes, exactly. Ideally all to logic should be in `eidl` and only UI stuff specific to the AB should be needed. This is now the second time we run into issues, because the separation isn't clean (https://github.com/LCA-ActivityBrowser/activity-browser/issues/649#issuecomment-947984913).

**Comment by haasad** [comment]
@nabilahmed739 I made some small changes to `eidl`, which allows us to use eidl's `extract`-function again in the AB. I assigned you for review on the PR for the AB, let me know what you think.

The bug was introduced by my change in https://github.com/haasad/EcoInventDownLoader/releases/tag/v1.4.0
