### ISSUE TITLE
Negative values in contribution analysis aggregated under Rest

### ISSUE THREAD

**Issue by nabilahmed739** [LCA-ActivityBrowser/activity-browser#739]
In case of absolute the values are aggregated under rest:
![image](https://user-images.githubusercontent.com/6296604/155633075-1c366df1-7d1f-438b-8f56-19d418354299.png)

In case of relative, the contribution of the same negative is shown as positive:
![image](https://user-images.githubusercontent.com/6296604/155633294-6e3174ea-0344-454b-96ca-a861cb591143.png)

**Comment by marc-vdm** [comment]
Could you also have a look at #635 if you're working on this?

**Comment by nabilahmed739** [comment]
@marc-vdm I have already fixed this. 
I created this issue to link it to the PR which I will be creating soon.

**Comment by nabilahmed739** [comment]
The complete fix for this issue is the combination of bw2-analyzer update to version 0.11.2 and completion of PR #765
