### ISSUE TITLE
lca calculations_process contributions

### ISSUE THREAD

**Issue by jmehreth** [LCA-ActivityBrowser/activity-browser#74]
the legend on the right is too small for processes with longer names (so that it is impossible to read the full process name) -> a scroll bar would solve this probably.

**Comment by jmehreth** [comment]
the same for elementary flow contributions.

**Comment by haasad** [comment]
In my case the area of the plots are reduced, not the activity names, could you maybe post a screenshot (just drag-and-drop, or copy-paste).
![image](https://user-images.githubusercontent.com/11636405/34038814-e7c2e850-e18d-11e7-8840-c71b087c38c1.png)

**Comment by jmehreth** [comment]
and here the process contributions (on windows).

![image](https://user-images.githubusercontent.com/34546932/34038932-336ba4c2-e18e-11e7-9718-391462eec6bb.png)

**Comment by bsteubing** [comment]
happy to see these features being used! It is not perfect yet and actually just the first go at this... improvements are planned.
A quick workaround is perhaps to drag the slider between the tabs to the left so this tab gets the entire screen...

**Comment by haasad** [comment]
Fixed in #117

**Comment by haasad** [comment]
Long names are wraped now :+1: 
![image](https://user-images.githubusercontent.com/11636405/37609270-f98921ea-2b9c-11e8-88a8-6564c7ca815b.png)
