### ISSUE TITLE
No webviewer/HTML on Mac?

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#741]
One of my students is unable to see the welcome screen on AB. I'm not sure about other webviewers like the navigator at the moment.
MacOS version is: `Big Sur (11.2.2)`. 

<img width="1680" alt="Στιγμιότυπο 2022-03-01, 3 03 39 μμ" src="https://user-images.githubusercontent.com/34626062/156184244-1cff530e-18d0-4adb-a746-c6e0df27d960.png">

**Comment by haasad** [comment]
M1 architecture or not? Similar issue has been reported in #718, maybe it's a problem on Mac in general?

**Comment by marc-vdm** [comment]
Nope, it's a Mac with `2,6 GHz 6-core intel core i7`, so no M1, though I wouldn't know the exact model.

If it is indeed the same problem, it would be mac in general.

For now, my student will use bootcamp to use AB, that is probably easiest for this student.

**Comment by marc-vdm** [comment]
Update: Graph navigator/Sankey are also not available. There are no errors in the terminal.

**Comment by romainsacchi** [comment]
I second this.

**Comment by haasad** [comment]
I managed got to get my hands on a Macbook to test this. I added a fix in #745 and it now "works on my machine" :tm: 

@marc-vdm @romainsacchi @nanocate Could you please check if you still get the blank screen with the latest development version?

**Comment by romainsacchi** [comment]
Hmm, actually, I started from a blank slate (new environment, etc.) as we described it in #705 and I'm ending up with these Intel errors again...

`(base) romain@Romains-MBP ~ % CONDA_SUBDIR=osx-64 conda create -n ab python=3.9
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/ab

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0d85af4_4
  ca-certificates    conda-forge/osx-64::ca-certificates-2021.10.8-h033912b_0
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5
  libzlib            conda-forge/osx-64::libzlib-1.2.11-h9173be1_1013
  ncurses            conda-forge/osx-64::ncurses-6.3-he49afe7_0
  openssl            conda-forge/osx-64::openssl-3.0.0-h0d85af4_2
  pip                conda-forge/noarch::pip-22.0.4-pyhd8ed1ab_0
  python             conda-forge/osx-64::python-3.9.10-hea1dfa3_2_cpython
  python_abi         conda-forge/osx-64::python_abi-3.9-2_cp39
  readline           conda-forge/osx-64::readline-8.1-h05e3726_0
  setuptools         conda-forge/osx-64::setuptools-60.9.3-py39h6e9494a_0
  sqlite             conda-forge/osx-64::sqlite-3.37.0-h23a322b_0
  tk                 conda-forge/osx-64::tk-8.6.12-h5dbffcc_0
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h9173be1_1013


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate ab
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) romain@Romains-MBP ~ % conda activate ab
(ab) romain@Romains-MBP ~ % conda env config vars set CONDA_SUBDIR=osx-64
To make your changes take effect please reactivate your environment
(ab) romain@Romains-MBP ~ % conda deactivate
(base) romain@Romains-MBP ~ % conda activate ab
(ab) romain@Romains-MBP ~ % conda install activity-browser-dev=2022.03.11
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/ab

  added / updated specs:
    - activity-browser-dev=2022.03.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    krb5-1.19.2                |       hb49756b_4         1.2 MB  conda-forge
    libpq-14.2                 |       hea3049e_0         2.9 MB  conda-forge
    presamples-0.2.3           |       h39e3cac_0          24 KB  bsteubing
    scipy-1.8.0                |   py39h056f1c0_1        21.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        25.8 MB

The following NEW packages will be INSTALLED:

  activity-browser-~ bsteubing/noarch::activity-browser-dev-2022.03.11-py_0
  appdirs            conda-forge/noarch::appdirs-1.4.4-pyh9f0ad1d_0
  arrow              conda-forge/noarch::arrow-1.2.2-pyhd8ed1ab_0
  asteval            conda-forge/noarch::asteval-0.9.23-pyhd8ed1ab_0
  astunparse         conda-forge/noarch::astunparse-1.6.3-pyhd8ed1ab_0
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.10.0-pyha770c72_0
  brightway2         cmutel/noarch::brightway2-2.4.2-py_4
  brotli             conda-forge/osx-64::brotli-1.0.9-h0d85af4_6
  brotli-bin         conda-forge/osx-64::brotli-bin-1.0.9-h0d85af4_6
  brotli-python      conda-forge/osx-64::brotli-python-1.0.9-py39h9fcab8e_6
  brotlicffi         conda-forge/osx-64::brotlicffi-1.0.9.2-py39h9fcab8e_1
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py39h89e85a6_1003
  bw2analyzer        cmutel/noarch::bw2analyzer-0.10-py_1
  bw2calc            cmutel/noarch::bw2calc-1.8.1-py_2
  bw2data            cmutel/noarch::bw2data-3.6.4-py_0
  bw2io              cmutel/noarch::bw2io-0.8.6-py_1
  bw2parameters      cmutel/noarch::bw2parameters-0.7-py_0
  bw_migrations      cmutel/noarch::bw_migrations-0.1-py_0
  certifi            conda-forge/osx-64::certifi-2021.10.8-py39h6e9494a_1
  cffi               conda-forge/osx-64::cffi-1.15.0-py39he338e87_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.12-pyhd8ed1ab_0
  cryptography       conda-forge/osx-64::cryptography-36.0.1-py39h209aa08_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  dill               conda-forge/noarch::dill-0.3.4-pyhd8ed1ab_0
  docopt             conda-forge/noarch::docopt-0.6.2-py_1
  eidl               bsteubing/noarch::eidl-1.4.2-py_0
  eight              conda-forge/noarch::eight-1.0.0-py_0
  et_xmlfile         conda-forge/noarch::et_xmlfile-1.0.1-py_1001
  fasteners          conda-forge/noarch::fasteners-0.17.3-pyhd8ed1ab_0
  fonttools          conda-forge/osx-64::fonttools-4.30.0-py39h63b48b0_0
  freetype           conda-forge/osx-64::freetype-2.10.4-h4cff582_1
  future             conda-forge/osx-64::future-0.18.2-py39h6e9494a_4
  giflib             conda-forge/osx-64::giflib-5.2.1-hbcb3906_2
  gmp                conda-forge/osx-64::gmp-6.2.1-h2e338ed_0
  icu                conda-forge/osx-64::icu-69.1-he49afe7_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  importlib-metadata conda-forge/osx-64::importlib-metadata-4.11.2-py39h6e9494a_0
  importlib_metadata conda-forge/noarch::importlib_metadata-4.11.2-hd8ed1ab_0
  jbig               conda-forge/osx-64::jbig-2.1-h0d85af4_2003
  jpeg               conda-forge/osx-64::jpeg-9e-h0d85af4_0
  kiwisolver         conda-forge/osx-64::kiwisolver-1.3.2-py39hf018cea_1
  krb5               conda-forge/osx-64::krb5-1.19.2-hb49756b_4
  lcms2              conda-forge/osx-64::lcms2-2.12-h577c468_0
  lerc               conda-forge/osx-64::lerc-3.0-he49afe7_0
  libblas            conda-forge/osx-64::libblas-3.9.0-13_osx64_mkl
  libbrotlicommon    conda-forge/osx-64::libbrotlicommon-1.0.9-h0d85af4_6
  libbrotlidec       conda-forge/osx-64::libbrotlidec-1.0.9-h0d85af4_6
  libbrotlienc       conda-forge/osx-64::libbrotlienc-1.0.9-h0d85af4_6
  libcblas           conda-forge/osx-64::libcblas-3.9.0-13_osx64_mkl
  libclang           conda-forge/osx-64::libclang-13.0.1-default_he082bbe_0
  libcxx             conda-forge/osx-64::libcxx-12.0.1-habf9029_1
  libdeflate         conda-forge/osx-64::libdeflate-1.10-h0d85af4_0
  libedit            conda-forge/osx-64::libedit-3.1.20191231-h0678c8f_2
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_23
  libiconv           conda-forge/osx-64::libiconv-1.16-haf1e3a3_0
  liblapack          conda-forge/osx-64::liblapack-3.9.0-13_osx64_mkl
  libllvm13          conda-forge/osx-64::libllvm13-13.0.1-h64f94b2_2
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  libpq              conda-forge/osx-64::libpq-14.2-hea3049e_0
  libtiff            conda-forge/osx-64::libtiff-4.3.0-h17f2ce3_3
  libwebp            conda-forge/osx-64::libwebp-1.2.2-h28dabe5_0
  libwebp-base       conda-forge/osx-64::libwebp-base-1.2.2-h0d85af4_1
  libxcb             conda-forge/osx-64::libxcb-1.13-h0d85af4_1004
  libxml2            conda-forge/osx-64::libxml2-2.9.12-h7e28ab6_1
  libxslt            conda-forge/osx-64::libxslt-1.1.33-h1acebb3_3
  llvm-openmp        conda-forge/osx-64::llvm-openmp-13.0.1-hcb1a161_1
  lxml               conda-forge/osx-64::lxml-4.8.0-py39hf41e7f8_0
  lz4-c              conda-forge/osx-64::lz4-c-1.9.3-he49afe7_1
  matplotlib-base    conda-forge/osx-64::matplotlib-base-3.5.1-py39hb07454d_0
  mkl                conda-forge/osx-64::mkl-2022.0.0-h89fa619_782
  mrio_common_metad~ cmutel/noarch::mrio_common_metadata-0.1.1-py_0
  multiprocess       conda-forge/osx-64::multiprocess-0.70.12.2-py39h89e85a6_1
  multivolumefile    conda-forge/noarch::multivolumefile-0.2.3-pyhd8ed1ab_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  mysql-common       conda-forge/osx-64::mysql-common-8.0.28-h694c41f_0
  mysql-libs         conda-forge/osx-64::mysql-libs-8.0.28-h115446f_0
  networkx           conda-forge/noarch::networkx-2.7.1-pyhd8ed1ab_0
  nspr               conda-forge/osx-64::nspr-4.32-hcd9eead_1
  nss                conda-forge/osx-64::nss-3.74-h31e2bf1_0
  numpy              conda-forge/osx-64::numpy-1.22.3-py39hf56e92f_0
  openjpeg           conda-forge/osx-64::openjpeg-2.4.0-h6e7aa92_1
  openpyxl           conda-forge/noarch::openpyxl-3.0.9-pyhd8ed1ab_0
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pandas             conda-forge/osx-64::pandas-1.4.1-py39h4d6be9b_0
  pathos             conda-forge/noarch::pathos-0.2.8-pyhd8ed1ab_0
  patsy              conda-forge/noarch::patsy-0.5.2-pyhd8ed1ab_0
  peewee             conda-forge/osx-64::peewee-3.14.10-py39h9a19eac_0
  pillow             conda-forge/osx-64::pillow-9.0.1-py39hd2c7aa1_2
  pox                conda-forge/noarch::pox-0.3.0-pyhd8ed1ab_0
  ppft               conda-forge/noarch::ppft-1.6.6.4-pyhd8ed1ab_0
  presamples         bsteubing/noarch::presamples-0.2.3-h39e3cac_0
  psutil             conda-forge/osx-64::psutil-5.9.0-py39h89e85a6_0
  pthread-stubs      conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001
  py7zr              conda-forge/noarch::py7zr-0.18.0-pyhd8ed1ab_0
  pybcj              conda-forge/osx-64::pybcj-0.5.0-py39h89e85a6_2
  pybcpy             conda-forge/noarch::pybcpy-0.0.17-pyhd8ed1ab_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pycryptodomex      conda-forge/osx-64::pycryptodomex-3.14.1-py39h89e85a6_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pypardiso          conda-forge/noarch::pypardiso-0.4.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.7-pyhd8ed1ab_0
  pyppmd             conda-forge/osx-64::pyppmd-0.17.4-py39hfd1d529_0
  pyprind            conda-forge/osx-64::pyprind-2.11.2-py39h6e9494a_1002
  pyside2            conda-forge/osx-64::pyside2-5.13.2-py39h71a569c_6
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py39h6e9494a_4
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  pytz               conda-forge/noarch::pytz-2021.3-pyhd8ed1ab_0
  pyzstd             conda-forge/osx-64::pyzstd-0.15.1-py39h5d16cc6_0
  qt                 conda-forge/osx-64::qt-5.12.9-h2a607e2_5
  requests           conda-forge/noarch::requests-2.27.1-pyhd8ed1ab_0
  salib              conda-forge/noarch::salib-1.4.5-pyh6c4a22f_0
  scipy              conda-forge/osx-64::scipy-1.8.0-py39h056f1c0_1
  seaborn            conda-forge/noarch::seaborn-0.11.2-hd8ed1ab_0
  seaborn-base       conda-forge/noarch::seaborn-base-0.11.2-pyhd8ed1ab_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  soupsieve          conda-forge/noarch::soupsieve-2.3.1-pyhd8ed1ab_0
  stats_arrays       cmutel/noarch::stats_arrays-0.6.5-py_2
  statsmodels        conda-forge/osx-64::statsmodels-0.13.2-py39hc89836e_0
  tabulate           conda-forge/noarch::tabulate-0.8.9-pyhd8ed1ab_0
  tbb                conda-forge/osx-64::tbb-2021.5.0-h940c156_0
  texttable          conda-forge/noarch::texttable-1.6.4-pyhd8ed1ab_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.1.1-pyha770c72_0
  unicodecsv         conda-forge/noarch::unicodecsv-0.14.1-py_1
  unicodedata2       conda-forge/osx-64::unicodedata2-14.0.0-py39h89e85a6_0
  unidecode          conda-forge/noarch::unidecode-1.3.4-pyhd8ed1ab_0
  urllib3            conda-forge/noarch::urllib3-1.26.8-pyhd8ed1ab_1
  voluptuous         conda-forge/noarch::voluptuous-0.12.2-pyhd8ed1ab_1
  whoosh             conda-forge/osx-64::whoosh-2.7.4-py39h6e9494a_5
  wrapt              conda-forge/osx-64::wrapt-1.14.0-py39h63b48b0_0
  xlrd               conda-forge/noarch::xlrd-2.0.1-pyhd8ed1ab_3
  xlsxwriter         conda-forge/noarch::xlsxwriter-3.0.3-pyhd8ed1ab_0
  xorg-libxau        conda-forge/osx-64::xorg-libxau-1.0.9-h35c211d_0
  xorg-libxdmcp      conda-forge/osx-64::xorg-libxdmcp-1.1.3-h35c211d_0
  zipfile-deflate64  conda-forge/osx-64::zipfile-deflate64-0.2.0-py39h63b48b0_1
  zipp               conda-forge/noarch::zipp-3.7.0-pyhd8ed1ab_1
  zstd               conda-forge/osx-64::zstd-1.5.2-h582d3a0_0

The following packages will be DOWNGRADED:

  openssl                                  3.0.0-h0d85af4_2 --> 1.1.1l-h0d85af4_0
  python                          3.9.10-hea1dfa3_2_cpython --> 3.9.10-h1dd9edd_2_cpython


Proceed ([y]/n)? y


Downloading and Extracting Packages
libpq-14.2           | 2.9 MB    | ####################################################################################################### | 100% 
presamples-0.2.3     | 24 KB     | ####################################################################################################### | 100% 
krb5-1.19.2          | 1.2 MB    | ####################################################################################################### | 100% 
scipy-1.8.0          | 21.7 MB   | ####################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(ab) romain@Romains-MBP ~ % conda install scikit-umfpack
conda remove pypardiso --force
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/ab

  added / updated specs:
    - scikit-umfpack


The following NEW packages will be INSTALLED:

  metis              conda-forge/osx-64::metis-5.1.0-h2e338ed_1006
  mpfr               conda-forge/osx-64::mpfr-4.1.0-h0f52abe_1
  scikit-umfpack     conda-forge/osx-64::scikit-umfpack-0.3.2-py39h4b7cfb1_1004
  suitesparse        conda-forge/osx-64::suitesparse-5.10.1-h7aff33d_1


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/ab

  removed specs:
    - pypardiso


The following packages will be REMOVED:

  pypardiso-0.4.0-pyhd8ed1ab_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(ab) romain@Romains-MBP ~ % activity-browser
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
(ab) romain@Romains-MBP ~ % 
`

**Comment by marc-vdm** [comment]
@haasad Thanks! I will ask my student to update and check.
@romainsacchi sort of off-topic but for your post above: \` `...` \` only works for in-line code, you need \``` `...` \``` for code-blocks.

**Comment by romainsacchi** [comment]
I started anew and confirm that after doing what we described [here](https://github.com/LCA-ActivityBrowser/activity-browser/issues/705#issuecomment-1032446633), with the difference being:

`conda install activity-browser-dev=2022.03.11`

I get the following:

````
(ab) romain@Romains-MBP premise % activity-browser
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
````

despite having installed `scikit` and removed `pypardiso`.

**Comment by haasad** [comment]
@romainsacchi can you please try:
```
conda install --override-channels -c haasad/label/experimental -c conda-forge -c cmutel -c bsteubing activity-browser-dev
```

**Comment by romainsacchi** [comment]
<img width="811" alt="Screenshot 2022-03-12 at 20 05 35" src="https://user-images.githubusercontent.com/22473067/158031464-6b2345e3-2bc7-459a-82d9-1428e27d44c7.png">

Bingo!

**Comment by haasad** [comment]
`haasad/label/experimental` contains a version of brightway2 with slightly modified dependencies, I'll try to find a way to include this in brightway2, it's not very straightforward unfortunately

**Comment by JBenzien** [comment]
> @romainsacchi can you please try:
> 
> ```
> conda install --override-channels -c haasad/label/experimental -c conda-forge -c cmutel -c bsteubing activity-browser-dev
> ```

I have the same issues as @romainsacchi but this command does not work for me. It responds that there is an inconsistency in my packages and then installs 2019.10.30 of activity-browser-dev and reinstalls pypardiso.

**Comment by haasad** [comment]
Hi @JBenzien,

please try it in a new environment:
```
CONDA_SUBDIR=osx-64 conda create -n ab python=3.9
conda activate ab
conda env config vars set CONDA_SUBDIR=osx-64
conda install --override-channels -c haasad/label/experimental -c conda-forge -c cmutel -c bsteubing activity-browser-dev
```
If you already have an environment named `ab`, either remove it first with `conda remove -n ab --all` or choose a different name.

**Comment by JBenzien** [comment]
Thanks @haasad for the quick reply. Somehow it works now although I have tried the exact same commands for several times. Maybe it was helpful that I reinstalled my python installation today.

**Comment by JBenzien** [comment]
If I try to do it the way you mentioned above I get the same error message when trying to install the ipykernel package as when I try to install jupyter directly into the bw2 environment:

`The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - cmutel/noarch::brightway2==2.4.2=py_5
`

**Comment by haasad** [comment]
Does this work?:
```
CONDA_SUBDIR=osx-64 conda create -n bw2_issue741 -c haasad/label/experimental -c conda-forge -c cmutel brightway2 jupyter
```

**Comment by marc-vdm** [comment]
Closing as stale

**Comment by MarlePr** [comment]
@haasad @romainsacchi  I've tried everything mentioned above but I got the following error several times. As I just started working in Python, I don't know how to fix the error myself. 
This is what I did:
1. CONDA_SUBDIR=osx-64 conda create -n ab python=3.9
conda activate ab
conda env config vars set CONDA_SUBDIR=osx-64
conda install --override-channels -c haasad/label/experimental -c conda-forge -c
2. conda deactivate
3. conda activate ab
4. (ab) marlene.@18 ~ % activity-browser

Traceback (most recent call last):
  File "/opt/miniconda3/envs/ab/bin/activity-browser", line 6, in <module>
    from activity_browser import run_activity_browser
  File "/opt/miniconda3/envs/ab/lib/python3.9/site-packages/activity_browser/__init__.py", line 6, in <module>
    from PySide2.QtCore import QSysInfo, __version__ as qt_version
ImportError: dlopen(/opt/miniconda3/envs/ab/lib/python3.9/site-packages/PySide2/QtCore.cpython-39-darwin.so, 0x0002): Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE
  Referenced from: <01167352-4F24-347C-8C0A-A347F52A3E34> /opt/miniconda3/envs/ab/lib/libQt5Core.5.15.8.dylib
  Expected in:     <4EC4E077-EE60-3D48-A7DE-34C55BF3FAB2> /opt/miniconda3/envs/ab/lib/libc++.1.0.dylib

5. (ab) marlene.@18 ~ % pip install --force-reinstall PySide2

Installing collected packages: shiboken2, PySide2
  Attempting uninstall: shiboken2
    Found existing installation: shiboken2 5.15.7
ERROR: Cannot uninstall shiboken2 5.15.7, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps shiboken2==5.15.7'.

6. (ab) marlene.@18 ~ % activity-browser

Traceback (most recent call last):
  File "/opt/miniconda3/envs/ab/bin/activity-browser", line 6, in <module>
    from activity_browser import run_activity_browser
  File "/opt/miniconda3/envs/ab/lib/python3.9/site-packages/activity_browser/__init__.py", line 6, in <module>
    from PySide2.QtCore import QSysInfo, __version__ as qt_version
ImportError: dlopen(/opt/miniconda3/envs/ab/lib/python3.9/site-packages/PySide2/QtCore.cpython-39-darwin.so, 0x0002): Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE
  Referenced from: <01167352-4F24-347C-8C0A-A347F52A3E34> /opt/miniconda3/envs/ab/lib/libQt5Core.5.15.8.dylib
  Expected in:     <4EC4E077-EE60-3D48-A7DE-34C55BF3FAB2> /opt/miniconda3/envs/ab/lib/libc++.1.0.dylib

Thanks in advance for your help!

**Comment by haasad** [comment]
@MarlePr would you mind opening a new issue and describing exactly what you're trying to do? Please provide details about operating system, architecture etc.
Most of the information and solutions described in this issue are outdated and I don't expect they work anymore. A fresh installation on Mac should work out of the box, otherwise there could be some new/different problem.
