### ISSUE TITLE
Unable to import ecoinvent database in Activity browser

### ISSUE THREAD

**Issue by tejaspatil2098** [LCA-ActivityBrowser/activity-browser#742]
I am trying to import the Ecoinvent database into the activity browser, but it shows an error on the prompt window that the file specified cannot be found. Can someone explain to me what the problem could be?
Thank you.

![image](https://user-images.githubusercontent.com/70842611/157001016-60092bf0-694e-460b-b141-23bc76f3ff2f.png)

**Comment by haasad** [comment]
There was a bug fix that's not yet released in the stable version of the activity-browser: #737

You can either install the development version or run the following command to fix your current installation:
```
conda install -n ab -c haasad eidl7zip
```
Please let me know if that works

**Comment by tejaspatil2098** [comment]
I ran the command "conda install -n ab -c haasad eidl7zip" and tried to import the database again but now it shows a new error:

![image](https://user-images.githubusercontent.com/70842611/157022618-176e070c-b4b9-4eff-af74-58cb232bba56.png)

I removed the file and tried again but it shows the same error again and again.

I also tried to do the same in the developer version but it again show the same error as shown in the image

**Comment by haasad** [comment]
Hey @tejaspatil2098,

I wasn't able to reproduce your issue with a fresh installation of activity-browser-dev on windows. Can you confirm that you still experience this problem when starting the AB from a new installation like this:
```
conda create -n ab_issue742 activity-browser-dev
conda activate ab_issue742
activity-browser
```
If yes, it would be helpful if you could post the output of `conda list` of this new environment

**Comment by tejaspatil2098** [comment]
Hey @haasad,

Thank you for your comment. I discovered that the problem arrived because i was downloading the ecoinvent 3.8 version. But i got to know later that i have access only to 3.7.1 version of ecoinvent. 
I have successfully imported the database now. Thank you again.
