### ISSUE TITLE
Streamlining new databases/activities creation

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#759]
When making a new database or activity, it can be reasonable assumed that a user may want to edit these. It would be nice to enable editing by default on a database/activity on creation to save a click or two.

For the activity, it could even help already showing the (empty) technosphere & biopshere tables for faster drag/dropping + remembering empty table states (#761)

**Comment by Zoophobus** [comment]
This should now be in the development version
