### ISSUE TITLE
Unable to launch AB in v2.6.9

### ISSUE THREAD

**Issue by simb-sdu** [LCA-ActivityBrowser/activity-browser#762]
unable to launch activity browser

the command `activity-browser` returns "failed to create process"

freshly installed environment by
`conda create -n ab -c conda-forge -c cmutel -c bsteubing activity-browser`

**Comment by marc-vdm** [comment]
Could you export the full error message? I just re-installed as well to test but mine just starts without issue.
Could you also share what OS (e.g `Windows 10`/`MacOS Big Sur (11.2.2)` -and if you're on Mac, is it an M1 chip?-) you're on?

**Comment by simb-sdu** [comment]
> 

The full error message is "failed to create process". 
It is a windows 10. Everything worked until i updated to v2.6.9. the old version 2.6.8 still works fine

**Comment by marc-vdm** [comment]
So you type `activity-browser` and the only thing that happens is that is tells you `failed to create process` nothing else?
What [version of windows](https://support.microsoft.com/en-us/windows/which-version-of-windows-operating-system-am-i-running-628bec99-476a-2c13-5296-9dd081cdd808) specifically are you running?

Hopefully we can find something there.
Mine is:

```
Edition	Windows 10 Enterprise
Version		20H2
Installed on	‎13-‎1-‎2022
OS build	19042.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

```

**Comment by haasad** [comment]
Works fine on my windows installation as well. Does your conda path (as displayed by `conda info --base`) contain any spaces or special characters?

**Comment by haasad** [comment]
On Linux:
```
conda create -n äöü -c conda-forge -c cmutel -c bsteubing activity-browser
conda activate äöü
activity-browser
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

[1]    12414 abort (core dumped)  activity-browser
```

**Comment by simb-sdu** [comment]
> So you type `activity-browser` and the only thing that happens is that is tells you `failed to create process` nothing else? What [version of windows](https://support.microsoft.com/en-us/windows/which-version-of-windows-operating-system-am-i-running-628bec99-476a-2c13-5296-9dd081cdd808) specifically are you running?
> 
> Hopefully we can find something there. Mine is:
> 
> ```
> Edition	Windows 10 Enterprise
> Version		20H2
> Installed on	‎13-‎1-‎2022
> OS build	19042.1586
> Experience	Windows Feature Experience Pack 120.2212.4170.0
> ```
>
Udgave	Windows 10 Enterprise
Version	21H1
Installeret d.	‎06-‎10-‎2021
Operativsystemets build	19043.1586
Visning	Windows Feature Experience Pack 120.2212.4170.0

 
> Also, could you share the `conda list` output?


(base) C:\Users\simb>conda activate ab

(ab) C:\Users\simb>activity-browser
failed to create process.

(ab) C:\Users\simb>conda list
# packages in environment at C:\Users\simb\Anaconda3\envs\ab:
#
# Name                    Version                   Build  Channel
activity-browser          2.6.9                      py_0    bsteubing
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
asteval                   0.9.23             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
brightway2                2.4.2                      py_4    cmutel
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotli-python             1.0.9            py39h415ef7b_6    conda-forge
brotlicffi                1.0.9.2          py39h415ef7b_1    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1003    conda-forge
bw2analyzer               0.10                       py_1    cmutel
bw2calc                   1.8.1                      py_2    cmutel
bw2data                   3.6.4                      py_0    cmutel
bw2io                     0.8.6                      py_1    cmutel
bw2parameters             0.7                        py_0    cmutel
bw_migrations             0.1                        py_0    cmutel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py39hcbf5309_1    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39h7bc7c5c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      1.4.2                      py_0    bsteubing
eight                     1.0.0                      py_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fonttools                 4.31.2           py39hb82d6ee_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py39hcbf5309_4    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39hcbf5309_0    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_0    conda-forge
kiwisolver                1.4.0            py39h2e07f2f_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              13_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              13_win64_mkl    conda-forge
libclang                  13.0.1          default_h81446c8_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              13_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libxslt                   1.1.33               h65864e5_3    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
lxml                      4.8.0            py39h4fd7cdf_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-base           3.5.1            py39h581301d_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
mrio_common_metadata      0.1.1                      py_0    cmutel
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.12.2        py39hb82d6ee_2    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  2.7.1              pyhd8ed1ab_1    conda-forge
numpy                     1.22.3           py39h6331f09_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1n               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py39h2e25243_0    conda-forge
pathos                    0.2.8              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
peewee                    3.14.10          py39h539719c_0    conda-forge
pillow                    9.0.1            py39ha53f419_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pox                       0.3.0              pyhd8ed1ab_0    conda-forge
ppft                      1.6.6.4            pyhd8ed1ab_0    conda-forge
presamples                0.2.3                h39e3cac_0    bsteubing
psutil                    5.9.0            py39hb82d6ee_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py7zr                     0.18.1             pyhd8ed1ab_0    conda-forge
pybcj                     0.5.0            py39hb82d6ee_2    conda-forge
pybcpy                    0.0.17             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.14.1           py39hb82d6ee_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pypardiso                 0.4.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyppmd                    0.18.0           py39h415ef7b_0    conda-forge
pyprind                   2.11.2          py39hcbf5309_1002    conda-forge
pyside2                   5.13.2           py39hc084194_4    conda-forge
pysocks                   1.7.1            py39hcbf5309_4    conda-forge
python                    3.9.12          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyzstd                    0.15.1           py39h46500c5_0    conda-forge
qt                        5.12.9               h556501e_6    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
salib                     1.4.5              pyh6c4a22f_0    conda-forge
scipy                     1.8.0            py39hc0c34ad_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                60.10.0          py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.1               h8ffe710_0    conda-forge
stats_arrays              0.6.5                      py_2    cmutel
statsmodels               0.13.2           py39h5d4886f_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_0    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
voluptuous                0.12.2             pyhd8ed1ab_1    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_5    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_3    conda-forge
wrapt                     1.14.0           py39hb82d6ee_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipfile-deflate64         0.2.0            py39hb82d6ee_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge

(ab) C:\Users\simb>

**Comment by simb-sdu** [comment]
> Works fine on my windows installation as well. Does your conda path (as displayed by `conda info --base`) contain any spaces or special characters? Or any special characters in the environment name?

i just double checked, and there are no such issues

**Comment by marc-vdm** [comment]
Never seen this before. I also can't see any differences between your `conda list` output or OS versions

If I can believe google, it may have to do with your path as @haasad implied?
For example [here](https://github.com/frida/frida-website/issues/122#issuecomment-430644486) or [here](https://stackoverflow.com/questions/69160853/pip-failed-to-create-process-how-do-i-fix-this)

I'd suggest to do the following and hope this resolves the problem:
```
conda update conda
python -m pip install --upgrade pip --force-reinstall
conda create -n ab activity-browser
```

@haasad if you have other ideas, please let us know! This is a bit out of my depth.

**Comment by haasad** [comment]
> If I can believe google, it may have to do with your path as @haasad implied?

Yes, my suggestion with the path was also based on a superficial google search

> @haasad if you have other ideas, please let us know! This is a bit out of my depth.

Before going to for into other directions: @simb-sdu can you confirm that you still get the same behaviour when creating a completely new env, i.e.:
```
conda create -n ab_issue762 -c conda-forge -c cmutel -c bsteubing activity-browser
conda activate ab_issue762
```

And then my next step would be to re-install anaconda/miniconda, because a lot of google results regarding "failed to create process" in combination with python/anaconda point to some broken installation of anaconda.

**Comment by simb-sdu** [comment]
> > If I can believe google, it may have to do with your path as @haasad implied?
> 
> Yes, my suggestion with the path was also based on a superficial google search
> 
> > @haasad if you have other ideas, please let us know! This is a bit out of my depth.
> 
> Before going too far into other directions: @simb-sdu can you confirm that you still get the same behaviour when creating a completely new env, i.e.:
> 
> ```
> conda create -n ab_issue762 -c conda-forge -c cmutel -c bsteubing activity-browser
> conda activate ab_issue762
> ```
> 
> And then my next step would be to re-install anaconda/miniconda, because a lot of google results regarding "failed to create process" in combination with python/anaconda point to some broken installation of anaconda.

This did not directly resolve the issue

HOWEVER the issue magically disappeared the following day. I have no clue as to why - but I will nevertheless close this issue (an reopen if it occurs again - god forbid it)
