### ISSUE TITLE
monte carlo result - no distribution?

### ISSUE THREAD

**Issue by simb-sdu** [LCA-ActivityBrowser/activity-browser#768]
When calculating a monte carlo analysis, the results do not appear in a distribution, see sccreenshot
![image](https://user-images.githubusercontent.com/94962841/161029475-a89ddb21-a48d-4863-941b-242b26a39352.png)

The uncertainty was defined as a triangular distribution for the parameter determining the amount of the technoscphere flow

**Comment by marc-vdm** [comment]
What AB version are you using? And are you getting any errors in the terminal?

I'm getting results for version `2.6.9` with the same reference flow/impact category. Perhaps something isn't right with the `test` process?
![image](https://user-images.githubusercontent.com/34626062/161048933-364e21d0-397c-476f-aa59-dd65be53be2d.png)

**Comment by simb-sdu** [comment]
Thanks Marc, good to see it works, the error must be from my side on the ´test´ proces (it is my first try on using parameters and uncertainty in AB). using ´2.6.9´ as well. will give it another go and return to this thread
