### ISSUE TITLE
copy activity more than once does not work

### ISSUE THREAD

**Issue by jmehreth** [LCA-ActivityBrowser/activity-browser#77]
if I want to copy one ecoinvent activity more than once, it seems like it does not work (i.e. nothing happens). maybe the problem behind is a different one, but it would -in any way- be handy to be able to copy a dataset for multiple times

**Comment by haasad** [comment]
I get a this error:
 `peewee.IntegrityError: UNIQUE constraint failed: activitydataset.database, activitydataset.code`
Need to investigate why this only happens the second time, or rather how it works for the first copy.

**Comment by haasad** [comment]
fixed in #133
