### ISSUE TITLE
Suggestion for improvement: comment parameters and flows

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#774]
Hello,

I think this suggestion has already been given but I want to insist on it as I think it might be the biggest limitations of a wider spread of the activity-browser (speaking of expertise, seeing the reluctance of my own colleagues to make the change because of this specific issue). The issue in question being: the impossibility to add comments to parameters and flows.

Not having "comment boxes" to be able to enter the source for a parameter or a flow is a hindrance for the application of LCA and the transparency of models when shared, notably for critical reviews.

I do not think this change would require an overhaul. From what I see brightway already allows for the implementation of comments.

For parameters for instance, the new_project_parameters() method allows for any key to be created:
![image](https://user-images.githubusercontent.com/24285636/164481772-6269f795-a2e6-4608-b48d-42b59bf741a9.png)
And this information is transmitted to activity-browser as well. This is the Excel export of a random database within the project:
![image](https://user-images.githubusercontent.com/24285636/164481956-de20c305-28a6-44ae-8d8a-8520c7ddc827.png)
The comment "testing" is truly there. It is just a matter of displaying it within AB.

Similarly with the exchanges:
![image](https://user-images.githubusercontent.com/24285636/164487178-72b308db-f94a-4307-9281-e769dd087ac2.png)
![image](https://user-images.githubusercontent.com/24285636/164487285-2da79724-b338-4a11-93eb-639f1dba46f5.png)

I know the AB team knows about all of this, I'm just trying to emphasize the fact that I think it's a really low hanging fruit (though I might be wrong) that would improve the user experience by a lot and probably bring new users.

**Comment by marc-vdm** [comment]
Thanks for calling attention to this again. 

>Similarly with the exchanges:

I've recently added this to AB for activity exchanges. It's also in the most recent stable version. They work as you describe above. See #708 for additional information.


**For comments on parameters:**
Development on AB has been slow for a while. We currently don't have someone paid dedicated to AB, we're all doing development on a volunteer basis. If it's indeed already available in BW, I'll have a look to add comments to parameters as well. 

Could you check for me if comments also exist on other parameter levels (database/activity)


For the future, I'm happy to work together on developing features based on suggestions. Especially concrete suggestions like the one above demonstrating what code to use can really help us in development.

**Comment by MaximeAgez** [comment]
I tested for a database parameters it works the same:
![image](https://user-images.githubusercontent.com/24285636/164517278-4347374a-91d5-4bcb-b31c-5a6e2a9d87fe.png)

I do not dare trying with the activity parameters, because the group thing argument of activity parameters often breaks my parameters.db file. From the description though, it should accept any argument as well:
![image](https://user-images.githubusercontent.com/24285636/164517513-18cef8b6-92a5-4238-ad1e-dff7d6b347ce.png)

The issue where I saw it mentioned previously: #455

**Comment by marc-vdm** [comment]
Implemented in dev version
