### ISSUE TITLE
Activity browser Sankey Diagram

### ISSUE THREAD

**Issue by Hd1004** [LCA-ActivityBrowser/activity-browser#783]
Is there a way of downloading the Sankey diagram from the activity in any format like .png or something of that sort? There is a possibility of saving the EF contributions and Process contributions in csv, excel, png format but there is no possibility of saving the Sankey diagram.

**Comment by marc-vdm** [comment]
You can export the Sankey in [SVG](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics) format by using the below button:
![image](https://user-images.githubusercontent.com/34626062/167404131-9f62632a-52d6-4301-b082-d2c7e610564f.png)

**Comment by Hd1004** [comment]
![Screenshot (327)](https://user-images.githubusercontent.com/105209945/167417565-48941537-7127-40b8-ae79-57df542dbcd8.png)
I do not have that option. I don't know why.

**Comment by marc-vdm** [comment]
You're probably on an older version.
You can update AB with:
```
conda activate ab
conda update activity-browser
```

or AB dev with:
```
conda activate ab_dev
conda update activity-browser-dev
```

**Comment by marc-vdm** [comment]
That seems similar to https://github.com/brightway-lca/brightway2-calc/issues/43.
Could you try:
```
conda activate abrowser
conda install scipy=1.7
```
and let me know if that worked?

@haasad https://github.com/brightway-lca/brightway2-calc/issues/43 was closed, but to me the issue looks very similar, do you know if it's the same or something different?

**Comment by Hd1004** [comment]
Unfortunately, it did not work.
It is showing the same error

**Comment by haasad** [comment]
That issue should be fixed. My bet would be old python version, i.e 3.7 most likely. What's does `conda list python` say @Hd1004?

I'm pretty sure a fresh install should fix your problems:
- remove your environment: 
```
conda deactivate
conda remove -n abrowser --all
```
- then reinstall:
```
conda create -n abrowser activity-browser
```

**Comment by Hd1004** [comment]
@haasad 
Conda list python says this
![Screenshot (330)](https://user-images.githubusercontent.com/105209945/167429103-efdff683-5521-4235-9476-ef8fc514df78.png)
