### ISSUE TITLE
Activities Table Search reset after changing activity

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#785]
When user searches a database
![image](https://user-images.githubusercontent.com/34626062/167862292-e9fdfd6d-1a8c-409d-92f3-fa4e8d501dee.png)
And then changes an activity -for example adding an exchange to an activity-
![image](https://user-images.githubusercontent.com/34626062/167862806-bee4cdb6-b7ed-43da-8675-e30fc11be460.png)
The search is reset. (also a problem in treeview)

I'm assuming the table is reset on an activity change -which makes sense as an activity/product name could have changed-, though it would be nice if we could keep the search active.

**Comment by Joeytje50** [comment]
Note: Search should remain active for the current database; switching database should reset search, and switching back to the previous database should reinstate the search string

**Comment by Joeytje50** [comment]
Additional to this issue, there also seems to be a similar issue to #797 occurring when pressing return on the search box, meaning there is some other resizing logic being applied when pressing return. I think it would make sense to fix that alongside this search issue.
