### ISSUE TITLE
"Rest" info

### ISSUE THREAD

**Issue by Hd1004** [LCA-ActivityBrowser/activity-browser#789]
Hey guys, is there a way to find what is in the "Rest" of the Process contributions? I have attached a picture to explain it better.
![Screenshot (334)](https://user-images.githubusercontent.com/105209945/170674701-6d9a2c72-5026-42ac-b555-5bb9a3699d39.png)

**Comment by marc-vdm** [comment]
You can get more data available, though for the plot, it may become unreadable rather quickly (you can already see that the legend is difficult to follow with just these processes).

![AB_CA_menu](https://user-images.githubusercontent.com/34626062/170676610-fb4c8944-2e30-47d6-b5a0-733551bcca0d.png)

Our contribution analysis chart is always sorted from largest to smallest, so you see the main contributors first. The AB allows you to view contributions in 2 ways:

The first is `Relative` or `Top #` processes (top left red box). `Relative` shows any process that matches at least `x`% of the impact. `Top #` shows you the top `x` contributors (e.g. the top 5 contributors in each reference flow). 

With the red boxed menu on the right, you can change what number `x` is in the above explanation. You could for example show any process contributing at least 1% to the total impact, or show the top 3 processes.

When selecting larger amounts (lower % or higher #), the figure becomes harder to read, and it may be useful to instead switch to the table view.

Additionally, you can also aggregate processes automatically (the `Aggregate by:` menu). For example, by name of the products. This would for example group all processes producing `electricity, high voltage` into 1 number, this may help you better understand results too. Another example could be grouping locations, which could allow you to find major geographical hotspots, though we have no way of dealing with hierarchical geographies at the moment (for example, ReR (rest of Europe) is it's own region, which is not counted toward any individual European country, while in a certain process, ReR may have been every European country except Germany).

Finally, we are not able to show you the total result of each contributing process in AB at the moment. If you want that information you'll need to run the LCA in Brightway2.

Hope that helps!

**Comment by Hd1004** [comment]
Thank you @marc-vdm . This was very helpful. I appreciate it.

**Comment by marc-vdm** [comment]
cheers!
