### ISSUE TITLE
Source of biogas in this model

### ISSUE THREAD

**Issue by Hd1004** [LCA-ActivityBrowser/activity-browser#791]
Hey guys, can someone please help me figure out what the source of the biogas is for these processes shown in the image? It directly shows biogas purification to Biomethane but there is no incoming Biogas source for the process. Does anyone have any idea? Please help me out.
![Screenshot (337)](https://user-images.githubusercontent.com/105209945/171120513-caaa17a9-0147-4b71-b6de-48504f0b066f.png)
@marc-vdm

**Comment by marc-vdm** [comment]
I'd suggest having a look at the individual processes in AB and looking at their descriptions like shown below. If you have more in depth questions regarding processes, it is best to contact the database provider (I'm assuming ecoinvent -who also have much more detailed information on their website that we don't show in AB-), or more general LCA discussion places, like the Pré LCA list. We are better at helping you with AB specific issues.
![image](https://user-images.githubusercontent.com/34626062/171134653-baf1e85c-eeec-4ffa-94cd-9e2d4d6e952a.png)
