### ISSUE TITLE
Dependent or independent sampling in Monte-Carlo

### ISSUE THREAD

**Issue by em398** [LCA-ActivityBrowser/activity-browser#792]
Hi,
I was wondering whether the Monte Carlo calculation in AB employs dependent sampling when comparing multiple activities in an LCA setup? I know that there are ways to perform a dependently sampled MC in BW2 but I wasn't sure what is used in AB. 
I wanted to run a check by running a 100 iteration for the same activity duplicated in an LCA setup (ecoinvent steel production, electric, low-alloyed - RoW) but I am unable to insert the same activity twice. 
Many thanks in advance for your help!

**Comment by marc-vdm** [comment]
@cmutel Could you answer this one?

**Comment by cmutel** [comment]
@em398 The AB does do what you are calling dependent sampling. I had to look around a bit, but the [loop is here](https://github.com/LCA-ActivityBrowser/activity-browser/blob/be1113aa7214ea4441a66ad146334b7963be52f6/activity_browser/bwutils/montecarlo.py#L164). The **A**, **B**, and **C** matrices are sampled only once per Monte Carlo iteration, and then each combination of functional unit and impact category is calculated.

I am not sure why AB is reimplementing something already in Brightway core, but that is another discussion.

**Comment by bsteubing** [comment]
I can confirm this: it is dependent sampling
