### ISSUE TITLE
Refactor Monte-Carlo to use BW2 instead of own code.

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#793]
See #792 - [comment from chris](https://github.com/LCA-ActivityBrowser/activity-browser/issues/792#issuecomment-1142499832)

Additional thought: perhaps our code is custom because it's compatible with scenarios. If that's the case we should either 1) close this again or 2) see if it makes sense to move that code to BW.

**Comment by bsteubing** [comment]
I think this is part of a bigger project of moving LCA results calculation (including contribution analysis, MC, etc.) back to bw. One bottleneck is indeed the superstructure approach, which is for now only implemented in the AB
