### ISSUE TITLE
display of biosphere flows

### ISSUE THREAD

**Issue by jmehreth** [LCA-ActivityBrowser/activity-browser#80]
after adapting biosphere flows of an activity on the left (e.g. changing the amount), some biosphere flows (that have before been correctly displayed) don't show anymore. like in the screenshot.

[after closing the activity and reopening it, the biosphere flows are displayed correctly again WITH the adapted amounts]

![image](https://user-images.githubusercontent.com/34546932/34203412-4bd17280-e57b-11e7-897e-92a1fa525d2a.png)

**Comment by haasad** [comment]
Same problem as in #84, was fixed in https://github.com/LCA-ActivityBrowser/activity-browser/commit/f58d32c28f0de431c0b2a84420c1081eaecd2641
