### ISSUE TITLE
Fail to download activity browser in Mac M1

### ISSUE THREAD

**Issue by gleewriterly** [LCA-ActivityBrowser/activity-browser#800]
I installed both miniforge and miniconda in mac then in terminal proceeded to enter 

conda config --prepend channels conda-forge
conda config --append channels cmutel
conda config --append channels bsteubing

I'm assuming from the warning that these channels are already set-up? but what I did miss is the "default" channels
Moving on I then proceeded to install activity browser but it seems the installation stopped?
Would really appreciate your expert solution to this. ^^

<img width="866" alt="Screenshot 2022-06-16 at 20 31 54" src="https://user-images.githubusercontent.com/16835319/174141702-b3e4d7ac-153b-4945-8bd2-fdf2fad58ebf.png">

**Comment by haasad** [comment]
Hi @gleewriterly,

unfortunately Mac M1 still isn't fully supported, so the default installation instructions won't work. But we figured out a way to make it run in #705.

You can try the following:
```
CONDA_SUBDIR=osx-64 conda create -n ab python=3.9
conda activate ab
conda env config vars set CONDA_SUBDIR=osx-64
conda install --override-channels -c haasad/label/experimental -c conda-forge -c cmutel -c bsteubing activity-browser-dev
```

Please let me know if this works for you.

**Comment by gleewriterly** [comment]
Thank you it works!
