### ISSUE TITLE
Copy to clipboard does not work in Linux

### ISSUE THREAD

**Issue by Joeytje50** [LCA-ActivityBrowser/activity-browser#802]
Copying to the clipboard gives the error "Pyperclip could not find a copy/paste mechanism for your system." whenever you attempt to use the 'Copy to clipboard' functionality. To fix this, `pyperclip` needs to be installed. Manually installing pyperclip and then relaunching AB will allow you to copy on linux correctly.

**Comment by haasad** [comment]
Afaik the copy to clipboard functionality uses [`pandas.DataFrame.to_clipboard`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_clipboard.html#pandas-dataframe-to-clipboard) under the hood. As stated in the docs it requires either `xclip` or `xsel`. I assume if it doesn't find either of those it recommends installing `pyperclip` as a workaround.

On my linux machine it works fine without `pyperclip`, but I have `xclip` installed. What distro are you using?

**Comment by haasad** [comment]
Nice, welcome @Joeytje50 :partying_face: feel free to ping me if you have questions regarding the infrastructure of the AB (conda packaging, github actions etc.)
