### ISSUE TITLE
Copy to clipboard copies multiple duplicate rows when selecting multiple columns

### ISSUE THREAD

**Issue by Joeytje50** [LCA-ActivityBrowser/activity-browser#806]
Whenever copying columns in an activity (after #802), the resulting data will generate multiple identical rows of each entry (equal to the amount of columns selected), instead of simply putting a single row per entry in the clipboard.

Unlike previous suspicions this appears to happen on all platforms (Limux / Windows)

**Comment by Zoophobus** [comment]
Hi Joeytje50, does this still occur? I've searched for this behaviour a couple of times now but can't replicate it!
