### ISSUE TITLE
Toolbar still required?

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#81]
Now that projects can be changed in the inventory tab and the report bug button was banished to the menubar, is the toolbar still useful at all? 

We could move the debug-window-button  and the project management options to the menubar as well and get completely rid of the toolbar.

![image](https://user-images.githubusercontent.com/11636405/34208863-47894c74-e590-11e7-8758-29de6fcdb7ed.png)

**Comment by bsteubing** [comment]
I think the toolbar still has a value and could feature other things. The original version of the AB had a number of functions there, see here:  
![image](https://user-images.githubusercontent.com/33026150/35561404-807e2c76-05b0-11e8-8b8a-3dcce4688849.png)
From left to right: 
- search
- search by brightway key
- random activity 
- history (tab could appear once the user presses this button)
- back and forwards buttons for "activity BROWSER" type navigation
- edit activity
- calculate LCA results (with functional unit and LCIA method as defined in LCIA tab)

Further, from the modular LCA extension:
- new module
- save module
- open modular LCA database
- add database
- save database 
- close database

Graphing:
- show module as graph (type defined in drop-down menu)
- show modular system (several connected modules)

Similar buttons could be used to display a supply chain graph relating to the current activity.

**Comment by bsteubing** [comment]
btw: although the current search function using woosh is advanced, having a second search field to search within search results was really useful in the original version to quickly find desired activities...

**Comment by haasad** [comment]
Closed in favour of #95 where we will keep track of ideas for the toolbar.
