### ISSUE TITLE
1st level contributions

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#810]
We currently show total contributions (process contributions tab) and a Sankey (Sankey tab) in the results. What could have added value is to also include a system that shows us the impacts of a first level (all technosphere flows going in to the reference/functional flow) like in the example image below:
One major feature of the below image is the display of all used impact categories at once, allowing a quick overview of where each '1st level` contribution is contributing most to.
![image](https://user-images.githubusercontent.com/34626062/179555578-b2e56384-fb0e-459f-bf58-288feeed4e0b.png)

We could also consider a more 'advanced' version of the above where we could 'dig deeper' into processes, for example showing a [sunburst](https://duckduckgo.com/?t=ffab&q=sunburst+graph&iax=images&ia=images) or [treemap](https://duckduckgo.com/?q=treemap+graph&t=ffab&iar=images&iax=images&ia=images) figure. Perhaps where users can select certain flows to see their lower level impacts, either per level (1st/2nd etc) or per process (only dig into 1 process). These 2 figures lose 1 major benefit of the top figure though; we cannot use them for a total overview of all impact categories in 1 overview.

#### Technical considerations:
What we're effectively looking for is Structural Path Analysis/Power Series Expansion, commonly used in EEIOA. AFAIK, we don't have this in BW2. 

We could go 1 of 2 ways:
1. We can use the current multiLCAs from BW to calculate a bunch of processes
2. We can use the Sankey system, and use it's graph traversal

Both solutions are not ideal to expand to lower levels, but should both work well for only the 1st level. For only the 1st level, I'm guessing a multiLCA is faster for a few flows but many impact categories, but the graph traversal would be faster with many flows but slower with many impact categories, though this is just a guess.

**Comment by MaximeAgez** [comment]
If I can add on this idea, a low-hanging fruit would be to have the data behind the Sankey made available to users so that they can make their own graphics in Excel or whatnot, grouping whichever processes together as they please.

If I'm not mistaken everything is already made available in brightway with the GraphTraversal method:
![image](https://user-images.githubusercontent.com/24285636/181026803-7e7ba445-74a6-4264-9ae8-4efe722c6e17.png)
Just need to change the format to something more easily usable by users.

**Comment by marc-vdm** [comment]
Thanks for the input! Indeed, a text/table format would be nice, though it also has some inherent challenges such as the inability to show loops, like with the [contribution tree](https://www.openlca.org/project/parameters-2/) in openLCA.

Using the Sankey system in BW also has some limitations, see last paragraph of my OP for that, though I also haven't come up with a good solution yet.
