### ISSUE TITLE
what happens when I add an exchange?

### ISSUE THREAD

**Issue by simb-sdu** [LCA-ActivityBrowser/activity-browser#811]
Hi

trying to make it possible to copy exchanges from one activity to antoher #688 

I want to find the code that is executed when drag-and-dropping an exchange into an activity. Cant figure out where to look, can anyone clarify?

**Comment by marc-vdm** [comment]
@simb-sdu  Thanks for working on improvements and helping make AB better! There's also someone else looking at similar functionality (@Joeytje50), it might be good to coordinate this a little to avoid merge issues down the road. Could you email me at m.t.van.der.meide@cml.leidenuniv.nl so we can set up a meeting to coordinate?

**Comment by Zoophobus** [comment]
Hi, I was wondering what the status of this issue is, whether it should be closed, or still considered active? Also what is the status of the current work on this @Joeytje50?

**Comment by simb-sdu** [comment]
I have been working on it, got quite a way, but also got a bit stuck. See issues and my commit below

https://github.com/LCA-ActivityBrowser/activity-browser/issues/822

https://github.com/simb-sdu/activity-browser/commit/37dbdcc7168dfc7d48f88dfd87a630f1f46161fe

**Comment by Zoophobus** [comment]
I've just been looking at this, I'm going through all of the issues. If you don't mind I'll close this one so there's just the more recent issue and we can continue from there. I will warn you that I won't be able to spend too much time on this at the moment, due to the "few" other pressing issues!

**Comment by simb-sdu** [comment]
sure
