### ISSUE TITLE
Multiproduct in modelling process

### ISSUE THREAD

**Issue by Gabbo19** [LCA-ActivityBrowser/activity-browser#826]
Is possible add more than a product in a new activity model?

**Comment by Gabbo19** [comment]
> It's currently not possible in AB to have 1 process with multiple functions (like 2 products, or waste treatment + product). This will be added as functionality in due time, however, we have a workaround for now:
> 
> This is an example of 2 multifunctional systems. ![image](https://user-images.githubusercontent.com/34626062/185629657-ea58fb78-490b-4a47-bfcf-8ed23613ad3c.png) The left system produces heat and electricity. You can define 1 process with all inputs for the entire multifunctional system with all flows, and then define 1 process for each multifunctional output. The first process produces an abstract '1 unit' of all products together (in this case 'heat and electricity'. The amount of unit each of the output processes consumes is the allocation factor. For example 30% and 70% ![image](https://user-images.githubusercontent.com/34626062/185630479-ef5a0def-45e9-40f0-9556-943b60668eeb.png)
> 
> You can define the allocation amounts by hand, or as either parameters or flow scenarios.
> 
> You can import this database with the example: [MF_example_DB.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/9382509/MF_example_DB.xlsx)
> 
> If this solved your question, please close the issue.

Thank you very much!

**Comment by OliverLyon** [comment]
Anybody know how to add products in the Downstream Consumers section? I tried to drag from the database but it did not work. Thanks.

**Comment by exuexex** [comment]
> Anybody know how to add products in the Downstream Consumers section? I tried to drag from the database but it did not work. Thanks.

I have the same issue, could you solve it already?

**Comment by marc-vdm** [comment]
Hi @exuexex

The way connecting activities/biosphere flows together is done in Activity Browser is the opposite of what you're trying. By adding activities/biosphere flows to the downstream consumer. Please also check out our [tutorial](https://github.com/LCA-ActivityBrowser/activity-browser/wiki/Tutorials#your-first-lca) to learn how to use Activity Browser.

**Comment by exuexex** [comment]
> Hi @exuexex
> 
> The way connecting activities/biosphere flows together is done in Activity Browser is the opposite of what you're trying. By adding activities/biosphere flows to the downstream consumer. Please also check out our [tutorial](https://github.com/LCA-ActivityBrowser/activity-browser/wiki/Tutorials#your-first-lca) to learn how to use Activity Browser.

Hi @marc-vdm, thanks a lot for your answer! I understand what you mean now. 
Also, in addition to the OP, I have been wondering if it makes sense to show multi-outputs with (-) signs in technosphere flows, as it is the case in some other LCA softwares.

**Comment by marc-vdm** [comment]
We will have a major update that will include a 'proper' way of dealing with multifunctionality later (hopefully this year, but no guarantees), wait for that ;)
