### ISSUE TITLE
Main window leads to debug window

### ISSUE THREAD

**Issue by WSGrul** [LCA-ActivityBrowser/activity-browser#838]
The button Windows>>Main Window gives leads to the Debug Window.
Debug Window also leads to Debug Window, so there is currently no way out of the debug window.

**Comment by marc-vdm** [comment]
Thanks, most info in the debug window is also available in the terminal you start from, so that's probably a safe workaround until we have this fixed.

**Comment by Zoophobus** [comment]
This should be fixed in the latest version (check the dev branch)
