### ISSUE TITLE
display activities

### ISSUE THREAD

**Issue by jmehreth** [LCA-ActivityBrowser/activity-browser#84]
after adapting processes, the display of the activities on the right does not work properly anymore:
-of some processes, reference product, location etc are not displayed anymore
-of some processes, reference product, location etc are displayed wrongly (e.g. the process with the * (which is a copied-and-then-adapted process) has the reference product "sulfuric acid" and the location "RoW")

I assume these problems are connected with copying/adapting processes.

when I close and restart the activity browser, the display is correct again

![image](https://user-images.githubusercontent.com/34546932/34259603-37db4b6e-e663-11e7-8026-a23ecb958989.png)

**Comment by haasad** [comment]
According to @jmehreth, this might be connected to the column sorting of the tables. Ie it appears to just happen when rows are reordered by selecting a column to sort for

**Comment by haasad** [comment]
fixed in f58d32c28f0de431c0b2a84420c1081eaecd2641
