### ISSUE TITLE
Overall UI philosophy

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#85]
This is a big topic and has no single answer. The idea of this "issue" is to collect ideas for now. 

_Original UI philosophy:_

- the original idea was that everything is only a maximum of two clicks away

- Therefore the tabs and the vertical split into two panels

- I wanted to avoid that users have to switch between many individual full screen windows

**Comment by bsteubing** [comment]
Idea: the right panel increasingly features "manager" functionality (projects, databases, inventories). This should be on the right - the usual place for such functionality. But this means also to shift other tabs from left to right in order to maintain the drag-n-drop possibility. We should probably also enable to shift tabs from one side to the other and to have a menu that permits to show/hide certain tabs.

**Comment by haasad** [comment]
Two-click philosophy:
- I really like this as a guideline and i agree that programs that open many individual windows are annoying

Tab management:
- management on the right and display/edit on the left makes sense to me and is intuitively understandable i think
- there is a lot of improvement potential for the tabs
    - close splash screen tab after it loses focus (ie it's only ever there when the AB is opened)
    - only open the history tab on demand
    - make the `LCA CFs` tab behave like the `Activities` tab, ie. only display when a LCIA method is opened and open the cfs in subtabs
- while moving tabs from one side to the other would be a nice feature, I feel like this is something that many users might not use, because it's not something that you normally expect to be able to do

Full screen windows:
- I like the behaviour of the debug-window, where the two panels are hidden and some other widget is the window's main widget for the duration of a task. I think this would be a good option for the sankey window and other things that need as much screen space as possible.

**Comment by haasad** [comment]
There is another UI philosophy point that we need to discuss; the separation between data exploration and editing. I think that a lot of the issues that we have at the moment (#19, #57, #58, #80, #84) could be solved with a clearer separation between exploring and editing activities.

At the moment, any change in activity tab is treated as an edit to the activity. I would propose some kind of edit-mode with an `edit` and `save` button, where tables and names etc can only be changed in edit-mode. The changes are only applied when the `save`-button is clicked. This would allow to include consistency checks before writing the changes and be the central signal to update all the UI-elements that need updating.

The edit-mode would also prevent accidental modification of datasets and could easily be disabled for read-only background databases.

**Comment by bsteubing** [comment]
Good suggestions regarding Tab management and Full screen windows (above). I agree with everything except for the possibility to move tabs from right to left (and vice versa). For now everything works with the current combinations of tabs left and right. But with more functionality it might become convenient for users to move a tab to the other side to do drag and drop operations or to see specific information next to each other. Shouldn't be too difficult to implement anyway.

**Comment by bsteubing** [comment]
Regarding the separation between data exploration and editing: at this moment the ease of editing is convenient (although not fully developed), but also encourages accidental changes as the user does not need to confirm anything. The first version of the AB had a dedicated activity editing tab with a save button and choice of destination database:

![image](https://user-images.githubusercontent.com/33026150/34982327-650271fc-faaa-11e7-9125-2292c01d1a25.png)

It would make sense to reimplement an improved version of this.

**Comment by bsteubing** [comment]
Another interesting interface design can be found in CMLCA (although completely different than ours at this point). In CMLCA the user can choose which layout he prefers (something that we could also think about).

![image](https://user-images.githubusercontent.com/33026150/34982501-da4fa920-faaa-11e7-9d73-05876612fb73.png)

**Comment by cardosan** [comment]
+1 for separation between data exploration and editing....it happened to me that by mistake I removed exchanges (unwantedly clicked two times instead of one the right button)

**Comment by bsteubing** [comment]
@cardosan I totally agree... this is planned soon...
