### ISSUE TITLE
No default LCIA methods available

### ISSUE THREAD

**Issue by ar-ali** [LCA-ActivityBrowser/activity-browser#856]
Hi,

There are no default LCIA methods available when creating a new project. Only the biosphere database is created. 

Could someone please help?

Best,

Abdur

**Comment by Zoophobus** [comment]
Hi Abdur,

are you on the prospective LCA online course? If so do you want to chat with me on teams? My name is Jonathan Kidner, you should be able to find me.
KR
Jonathan

**Comment by ar-ali** [comment]
Hi Jonathan,

Thanks for the quick response.

I am not on the prospective LCA online course.

Do you want to meet on Webex instead? I can send you an invite. When do you
have time?

Best,

Abdur

**Comment by Zoophobus** [comment]
Hi Abdur,

I was wondering if you wouldn't mind if I tried to arrange a meeting on zoom, I'd prefer to avoid publicising my contact details too much?
KR
Jonathan

**Comment by Zoophobus** [comment]
Hi Abdur,

my apologies for taking so long, I've been chatting with the other developers and was wondering what happened regarding the LCIA methods being absent for you?

One thing that could help us is if you could send us your environment file. In addition we'd recommend you to try with the most up to date version of the activity browser as well, if it isn't already. So we're all on the same page when trying to deal with this.
KR
Jonathan

**Comment by Zoophobus** [comment]
Hi Abdur,
I wiped the LCIA methods in activity browser, I did this from the console with brightway2. To reload the default lcia methods I then invoked `brightway2.create_default_lcia_methods(overwrite=True)` from the respective project from the python prompt. Maybe this will have the desired result?
(Apologies for not offering this sooner, however I am still learning about both the AB and brightway2)

**Comment by ar-ali** [comment]
Hi Jonathan,

I still do not have the LCIA methods.

Would you share your email address and we can perhaps schedule a short
meeting?

Best,

Abdur

**Comment by Zoophobus** [comment]
Hi sorry, you can send me an email at j.h.kidner@cml.leidenuniv.nl

**Comment by Zoophobus** [comment]
Hi Abdur, have you made any progress on this issue, or do you still have a problem with the LCIA methods?

**Comment by ar-ali** [comment]
Hi Jonathan.

thanks for writing. I was about to contact you. The problem still exists.

Are you available on 06.02 or 07.02 between 13 and 16?

Best,

Abdur

**Comment by Zoophobus** [comment]
Hi Abdur, 
the 6th would be better for me, thanks
KR, Jon

**Comment by ar-ali** [comment]
Ok, I have sent a teams meeting. Best,Abdur Sent from my iPhoneOn 3. Feb 2023, at 15:17, Jonathan Kidner ***@***.***> wrote:﻿
Hi Abdur,
the 6th would be better for me, thanks
KR, Jon

**Comment by Zoophobus** [comment]
Hi Abdur, I'm sorry I had a bit of a busy weekend, I can't find any message on my email address I was wondering if you could send me a link on the email for meeting. Feel free to set it for tomorrow, just preferably before 13:00 for me

**Comment by Zoophobus** [comment]
Hi, thanks and apologies again!
