### ISSUE TITLE
LCA failed error

### ISSUE THREAD

**Issue by ar-ali** [LCA-ActivityBrowser/activity-browser#857]
Hi,

I created a few databases using BW. However, after that, I keep getting LCA failed error in AB. I have attached screenshots. 

Could someone please help?

Best,

Abdur 

![image](https://user-images.githubusercontent.com/75308720/194029529-247a6ec3-29de-49ee-82e8-3425adefa5fc.png)

![image](https://user-images.githubusercontent.com/75308720/194029729-d47887a2-8a21-4b24-b40e-89d5884513f7.png)

**Comment by ar-ali** [comment]
More information,

- I tried exporting a database from my project as an excel file. 
- I created a copy of this excel file. 
- I modified the exchanges and values of this excel file.  
- I imported the modified excel file
- I could not import them as they were unlinked exchanges
- I forgot to delete the activity codes in the modified database prior to importing them

Could this have caused my project to crash and my LCA calculation step to fail?

Is there a way to recover my project?

**Comment by Zoophobus** [comment]
Hi Abdur,

hopefully someone will correct me if I'm wrong, but the error is with the elements that you are trying to refer to in the database. A question I have for you is if you are using a background database?

KR,
Jonathan

**Comment by ar-ali** [comment]
I am using the ecoinvent and premise modified ecoinvent as my background database.

**Comment by ar-ali** [comment]
Yes, I am linking it to the premise ecoinvent background database.

**Comment by Zoophobus** [comment]
So is the LCE2023 activity located within this database?
I'm wondering if it might be possible to compare the keys, could you do that?

**Comment by ar-ali** [comment]
I created the LCE2023 database with activities. I exported this database,
modified it, and tried importing it database called '25'.

LCE2023 had biopshere and premise ecoinvent database as dependencies.

Could you please clarify which keys do you need?

**Comment by Zoophobus** [comment]
My apologies I am new to the LCA community and did not realise that LCE2023 is your own database. I realise that I have wasted too much of your time, sorry for that.

First of all the activity codes are not the issue.
Secondly, could you post a copy of the excel file you exported, this way we might be able to see what is going on with these files.

One thing I don't understand is that you had the import error (unlinked exchanges) but still had the database, this is rather confusing for me.

**Comment by Zoophobus** [comment]
Another point that I am unsure of is why you were exporting your database to excel to change the amounts in the exchanges. This is possible from within the Activity Browser in the activity details tab (after clicking on the "edit activity" check box at the top of the tab). This is probably a safer way to alter these values than exporting to excel.

I do think, however, that it should be possible to recover your project

**Comment by Zoophobus** [comment]
Hi Abdur,

I was just wanting to give you this link for the AB (https://www.youtube.com/playlist?list=PLCL5MSXsvM4Q6cFgcMoc_wTGwHv973lpo). In this channel there's a series of videos from the original creator where he provides a quick introduction to the AB. Unfortunately, there isn't really that much documentation on the AB, but maybe this can help you a bit.

**Comment by Zoophobus** [comment]
Dear Abdur,

my apologies for the delay and my previously presumptuous behaviour. We also encountered this problem in the course we had recently, and unfortunately we only found a work-around not a solution. It really would be a great help if we could get a version of your database so that we can replicate this error on our own systems, would that be possible?

KR,
Jonathan

**Comment by ar-ali** [comment]
Hi Jonathan,

thank you for your suggestions. I deleted the concerned database, and my AB project works fine. I would consider this issue to be resolved.

Best,

Abdur

**Comment by ar-ali** [comment]
Hi Jonathan,

thank you for your suggestions. I deleted the concerned database, and my project is again functional. I would consider this issue to be resolved.

Best,

Abdur
