### ISSUE TITLE
Excel database importer

### ISSUE THREAD

**Issue by Zoophobus** [LCA-ActivityBrowser/activity-browser#858]
The excel database importer appears to be featuring a range of bugs related to memory based issues. These issues are related to the brightway2 importer and need to be dealt with either in brightway, or in the generation of the software environment. 

An example of an unsuccessful importation process in GNU/Linux is as follows:
`Applying strategy: strip_biosphere_exc_locations
Applying strategy: set_code_by_activity_hash
Applying strategy: link_iterable_by_fields
Applying strategy: assign_only_product_as_production
Applying strategy: link_technosphere_by_activity_hash
Applying strategy: drop_falsey_uncertainty_fields_but_keep_zeros
Applying strategy: convert_uncertainty_types_to_integers
Applying strategy: hash_parameter_group
Applying strategy: convert_activity_parameters_to_list
Applied 19 strategies in 16.90 seconds
Could not link exchanges, here are 10 examples.:
[{'amount': 0.00262,
  'database': 'super_ei38_REMIND_el_20220923',
  free(): invalid pointer`

Another encountered error is `segmentation faults` both typical of faulty memory handling.
In contrast errors in Windows occur as errors with Peewee, any inclusion of these errors here would be appreciated

**Comment by Zoophobus** [comment]
In Peewee update logs 3.15.1 there is a fix for an issue introduced by sqlite 3.39.0. Versions that were present in my environment with the above errors. Updating peewee to version 3.15.3 has resulted in no more subsequent errors from the importer, however this is with limited testing.

**Comment by simb-sdu** [comment]
@Zoophobus I have a problem that might be related to this. did you find any workaround?
#1021
