### ISSUE TITLE
Import of database Ecoinvent 3.9 cutoff fails 

### ISSUE THREAD

**Issue by MarcoRudolf** [LCA-ActivityBrowser/activity-browser#866]
Hey everyone, 

Ecoinvent just released its new Database version 3.9. 
By trying to import the Database in my Project, the import fails and the following error is shown: 
"The import failed as required biosphere exchanges are missing from the biosphere3 database. Please update the biosphere by using 'File' -> 'Update biosphere...'" 
I updated the bioshpere3 database in my project, but the error still occurs. Anyone have an idea? 
(I work on a mac)
![Bildschirmfoto 2022-10-18 um 10 46 55](https://user-images.githubusercontent.com/116068376/196398902-9fc50870-63b9-424c-96fe-f427cdbee3a8.png)

Cheers, Marco

**Comment by Zoophobus** [comment]
Hi Marc,

there is an issue with the latest release from ecoinvent. Here's the message from CMutel on the topic. Please send a message if this doesn't help to solve your problem!

> Ecoinvent version 3.9 (system models consequential, cutoff, and EN15804; APOS will come later) were released today. New releases of Brightway bring compatibility for this new data.

Upgrading libraries

Upgrading: You should upgrade either the package `brightway2` or `brightway25` (or `brightway2_nosolver` or `brightway25_nosolver` if you are an ARM machine). Manually upgrading libraries like `bw2io` will probably break things. How exactly this will work depends on how you have your channels configured, but will be something like:

    conda update brightway2


Upgrading projects
There are substantial changes in version 3.9 - more than 300 new elementary flows, 31 elementary flows were deprecated and deleted, and the LCIA methods were completely redone. The inventory data was added to, but some sectors were changed a lot. Therefore, for now our recommendation is to start using 3.9 in new projects; we are developing a generic toolkit to do updates of inventory databases, but this will take some time.

Fixing errors
I have tested the import and calculation steps on brightway2 and brightway25, but I could easily have missed something. Please file errors at [https://github.com/brightway-lca/brightway2-io/issues](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrightway-lca%2Fbrightway2-io%2Fissues&data=05%7C01%7Cj.h.kidner%40cml.leidenuniv.nl%7C08b37033ca124c05831a08dab113171a%7Cca2a7f76dbd74ec091086b3d524fb7c8%7C0%7C0%7C638016992789270034%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iABzvoaw5Eukc102QzQS%2FrFcSn5vkluYm%2Bs1aqtRlw0%3D&reserved=0) and tag me (@cmutel). Responding to this email will spam 150 people, let's not do that.

**Comment by marc-vdm** [comment]
@Zoophobus, we also need to update AB to be able to update biosphere, see #840

**Comment by romainsacchi** [comment]
To use ei39, I believe you need to use `bw2io 0.8.8`. But for ei38 or prior, that's `bw2io 0.8.6`.
But @cmutel can maybe confirm.

**Comment by MarcoRudolf** [comment]
Hey everyone, 
thanks for the quick support!
I updated brightway2 as well as the ab (I use the standard version). 
Then I updated the biosphere3 database via the ab. Unfortunately, the same error still occurs. 

@romainsacchi , can it be that I have to manually switch to ```bw2io 0.8.8``` ? How do I know which Version of the biosphere is being used?

**Comment by romainsacchi** [comment]
I would indeed try to upgrade to `bw2io 0.8.8` if you intend to use ei39. And then, update the biosphere.

**Comment by cmutel** [comment]
Be careful here, 0.8.8 supports *only* ecoinvent 3.9, not earlier versions. I can fix this later but am indisposed for the next few days.

**Comment by iamz33** [comment]
Hi. Any update on this? Waiting to work with ecoivnent 3.9 using AB. Please let us know when it gets resolved. Tnx

**Comment by Zoophobus** [comment]
Hi all,

if anyone is still waiting to work with Ecoinvent 3.9 in the AB then there are the current recommended bw2io versions that will be required (0.8.8 for later versions). The problem remains, though, that you will need to maintain separate environments for the latest and older versions of Ecoinvent

**Comment by cprato-qw** [comment]
Hello

i have the following configuration
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/83971901/e9fb258c-fe1d-4277-a774-1b3e20c088b6)

but i'm still having troubbles importing Ecoinvent 3.9 via Activity Browser

This is my brightway version:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/83971901/c497bb6e-b2c2-4551-a0ca-2e42ec6c308b)

I tried with different version of bw2io but still getting errors.

Any idea?

**Comment by cprato-qw** [comment]
thank you marc, this solved it!

**Comment by AndonaDim** [comment]
> Hi there! Thanks for reaching out.
> 
> I see your AB version is a bit old. I would suggest trying to update and then trying again. As you have an older version, you need to go through a few special steps to update. You can [see the guide here](https://github.com/LCA-ActivityBrowser/activity-browser/discussions/1049).
> 
> Let me know if that fixes your problem or if you need more help!

Hii I had the same problem, updated the AB, but now when I run <activity-browser> I get:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/157387413/295e1beb-3434-4a36-8a08-d8c2c83aafbc)
Before the update I was able to run AB though. Any idea what´s going on?

**Comment by KanMengqing** [comment]
Hi, I'm still experiencing the same problem. I want to import ecoinvent 3.8 but I got the same warning message that "The import failed as required biosphere exchanges are missing.." Here are the versions of my bw2. How should I fix the problem? Thanks!!
<img width="521" alt="Screenshot 2024-07-11 at 1 04 04 PM" src="https://github.com/LCA-ActivityBrowser/activity-browser/assets/91225837/afd40a1d-6ea9-4079-b06d-747043bad098">

**Comment by marc-vdm** [comment]
Hi @KanMengqing 

Are you trying this on Activity Browser or on Brightway? These are two different things. Activity Browser has different tools for this than Brightway.
