### ISSUE TITLE
Characterisation Faktor of biosphere3 flow "carbon dioxide, non fossil, air" in EF v3.0

### ISSUE THREAD

**Issue by MarcoRudolf** [LCA-ActivityBrowser/activity-browser#868]
Hey everyone, 

I am working on a project where I use biogenic carbon in my LCA. 
According to the [EF v3.0 documentation](https://eplca.jrc.ec.europa.eu/permalink/TR_SupportingCF_FINAL.pdf) , the characterisation factor of _carbon, biogenic_ is 0. As in the biosphere3 database, a flow called "carbon, biogenic" does not exist, I used "carbon, non-fossil, air". 
In my results, the EF v3.0 method counts this flow with the characterisation factor 1, the IPPC GWP 100 (2013) instead counts it with characterisation factor 0 (as I need it). Any ideas on that? Which carbon flow of the biosphere3 database could I use to model biogenic carbon? 
Or do you recommend defining a new biosphere flow? 

Thanks for help on this. Cheers, 
Marco

**Comment by marc-vdm** [comment]
@MarcoRudolf, thanks for asking. We get our impact categories from Brightway. Lets see if @cmutel knows some more about this.

@cmutel: EF3 indeed states that biogenic should be considered 0 ([table 7](https://eplca.jrc.ec.europa.eu/permalink/TR_SupportingCF_FINAL.pdf#page=16)). As also stated in the EF3 report, there are three subcategories, which we also have in AB:
![image](https://user-images.githubusercontent.com/34626062/199921558-ca9001d5-1ef8-439a-937b-28b203a72dfb.png)

The `biogenic` subcategory correctly excludes any biogenic CO2 flows, while the complete impact category does include them. Could you clarify whether this is a bug or that there's something we're missing here?

**Comment by MarcoRudolf** [comment]
@Zoophobus , thanks for your answer. 
I just found out what my problem was. I accidentally selected the EF v3.0 **EN15804**, instead of the normal EF v3.0. 
With the corrected EF impact category I get valid results. 
Sorry for that, It was just my mistake and nothing wrong with the accounting of EF v3.0 for biogenic carbon (biosphere flow "carbon dioxide, non-fossil"). 

Characterisation factor carbon dioxide (biogenic) is 0 for EF v3.0, and 1 for EF v3.0 EN15804. 

Best, Marco
