### ISSUE TITLE
add new activity

### ISSUE THREAD

**Issue by jmehreth** [LCA-ActivityBrowser/activity-browser#87]
while it is possible to define the activity name as well as the activity location, it is not possible to

-change/define the unit
-alter the reference product

of a newly created activity. (or at least, I couldn't find out how)
plus, the reference product is not displayed in the inventory on the right, see picture.

![image](https://user-images.githubusercontent.com/34546932/35224979-43544508-ff87-11e7-843f-ebed330b1ed9.png)

**Comment by haasad** [comment]
Keeping track of this in #57
