### ISSUE TITLE
biosphere for ecoinvent 3.9

### ISSUE THREAD

**Issue by studentethz** [LCA-ActivityBrowser/activity-browser#870]
Dear AB-Team
I have an issue installing the new ecoinvent 3.9 database. It states, that some biospere flows are missing and that I should update the biosphere database. After doing so, the update added 3 new bisphrere flows, but the error remains. 
How can I solve this problem?

**Comment by marc-vdm** [comment]
Activity Browser does not support ecoinvent 3.9 yet. We are working on an update to fix this.

**Comment by studentethz** [comment]
Hi Marc, 
thank you for the fast reply! I'm using the AB for my Bachelor thesis. Can you estimate the release date of the update?

**Comment by marc-vdm** [comment]
We are not completely sure, some things still need to be fixed on the Brightway side.

You can however already use v3.9, but that currently means you will not be able to sue AB with older versions of ecoinvent anymore. If you want to try that, have a read at #866 -and feel free to ask how to upgrade `bwio` in case you don't know, we'd be happy to help-. 

If your use of v3.9 is not absolutely critical compared to older versions, it may be fastest to just use 3.8 or older, that way you won't rely on us providing updates to you. 

Either way, we will inform you here when the update is out.

Good luck with your thesis!

**Comment by studentethz** [comment]
Okay, thank you. My thesis is about a natural gas power plant. Ecoinvent updated this activities in particular. 
I'm thinking about setting up the AB on a other device and try out 3.9 there, to not loose any data. 
So it would be very kind if you could post a manual how to manually ubdate bwio. 
Have a nice day!

**Comment by marc-vdm** [comment]
Alright below are some instructions, you don't actually need another device, you can create different environments on the same computer. I'd advise you to use only one project with the environment where you use all v3.9 things though.

Just create an environment like normal, but also add the right version of `bw2io`:
`conda create -n ab_39 -c conda-forge -c cmutel -c bsteubing activity-browser bw2io=0.8.8`

It would help to give it a recognizable name, like `ab_39` above.

Then just use AB like normal:
`conda activate ab_39` to activate the environment
`activity-browser` to launch

This should give you the right library to work with v3.9.
Again, if you're using other databases as well, I'd recommend using a new project where you exclusively use 3.9, and no other versions.

Hope this helps, if you have further questions, please let us know. If we solved your problem, please close the issue :)

**Comment by studentethz** [comment]
Very nice, I think it worked. Tkans alot! 
I will close the issue:)

**Comment by mf093087** [comment]
when will the library support biosphere3 3.10?

**Comment by marc-vdm** [comment]
Once we add support for ecoinvent 3.10, you will also be able to install the 3.10 version of the ecoinvent biosphere. We are adding this in version [`2.10`](https://github.com/LCA-ActivityBrowser/activity-browser/milestone/9) of Activity Browser.  

You can subscribe to #1163 or our [updates mailing list](https://brightway.groups.io/g/AB-updates) to be notified of when we release this version.
