### ISSUE TITLE
ecoinvent 3.7.1

### ISSUE THREAD

**Issue by krissh2022** [LCA-ActivityBrowser/activity-browser#872]
I recently installed AB with ecoinvent 3.9. 
I would like to import the 3.7.1 database as well to compare the differences in the results of my modeled system between 3.9 and 3.7.1

I tried to do this fresh in a second computer, however I get error stating "The import failed as required biosphere exchanges are missing from the biosphere3 database. Please update the biosphere by using 'File' -> 'Update biosphere..."

this is opposite of the issue #866 . 

Any suggestions on how to import old versions of ecoinvent 3.7.1 now ? 

thanks

**Comment by JLTRoelofs** [comment]
I experience the same problem for ecoinvent 3.8. Any suggestions?

**Comment by Zoophobus** [comment]
Hi, could you specify whether you are using the same, or separate environments for these databases, AND what version of bw2io you have for them?

Unfortunately, there is still an issue in terms of backward compatibility when it comes to ecoinvent3.9. So creating an environment for version 3.9 will not work for older versions (such as 3.7, or 3.8). For the older environments you'll need to deprecate the version of bw2io to a version <0.8.8

**Comment by krissh2022** [comment]
I used seperate environments. 
May I know how to deprecate to the old version in activity browser to make it compatible to ecoinvent version 3.7.1?

**Comment by JLTRoelofs** [comment]
HI,, I use the same environmental for these databases. 
I assume I have bw2io 0.8.7 (https://github.com/brightway-lca/brightway2-io)

**Comment by marc-vdm** [comment]
Hi @krissh2022 and @JLTRoelofs,

There are two related issues at play here.
1. The version of `bw2io`, which should be [`0.8.6` for ecoinvent <=3.8 or `0.8.8` for ecoinvent 3.9](https://github.com/LCA-ActivityBrowser/activity-browser/issues/866#issuecomment-1282572756)
2. The biosphere database you use in a project. There are breaking changes in environmental interventions in the biosphere between ecoinvent `3.8` and `3.9`. These changes mean that once you upgrade the biosphere, it will not be compatible with <=3.8 again

Both these points together mean that you need:
1. Separate environments with the correct `bw2io` version
2. Different projects, one for each version of ecoinvent (which is in general good practice anyway), the biosphere database depends on the ecoinvent version

__It is currently not possible to have both ecoinvent 3.9 and <=3.8 working in the same project.__ This may come at a later point, I'm not sure, we depend on Brightway for this to work.

To deprecate to the older version of `bw2io` in a project:
`conda activate ENVIRONMENT_NAME`
`conda install bw2io=0.8.6`

If you'd want to switch back to the newer version, just run the above with the `0.8.8` version instead.

Hope this helps,

Marc

**Comment by JLTRoelofs** [comment]
Unfortunately this did not solve the problem.

I deprecate the version of bw2io to 0.8.6. but I still get the error "The import failed as required biosphere exchanges are missing from the biosphere3 database. Please update the biosphere by using 'File' -> 'Update biosphere..."

Any other suggestions?

**Comment by haasad** [comment]
@marc-vdm @Zoophobus 

one thing to consider is that a new install of AB currently installs bw2io 0.8.8 with the risk of leading users to update their biosphere in existing projects and thereby "breaking" them.

Would it make sense to pin bw2io and add separate install instructions for users wanting to use ecoinvent 3.9 until this is fixed?

**Comment by JLTRoelofs** [comment]
This may also contribute to the problem.
I think six months ago I installed AB and created some databases.
Yesterday I installed AB on another laptop and tried to import the databases (including biosphere). Unfortunately, I was not able to realize this importation.

**Comment by marc-vdm** [comment]
@haasad Thanks for thinking along! I think that's a great idea for now.

Would we pin it in [meta.yml](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/ci/recipe/dev/meta.yaml) or in [ab_dev.yml](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/ci/conda-envs/ab_dev.yml)?

**Comment by marc-vdm** [comment]
@JLTRoelofs It's not entirely clear to me whether you've also started a new project where you're using the older ecoinvent version? AFAIK it's not possible to deprecate the `biosphere` database currently. Sorry for that inconvenience.

**Comment by haasad** [comment]
https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/ci/recipe/stable/meta.yaml is where all the pins should be configured, dev dynamically uses the same pins. This ensures that the pins in stable are always up to date

**Comment by JLTRoelofs** [comment]
> @JLTRoelofs It's not entirely clear to me whether you've also started a new project where you're using the older ecoinvent version? AFAIK it's not possible to deprecate the `biosphere` database currently. Sorry for that inconvenience.

Yes, I also started a new project. 
My intention is to transfer exactly the same project and databases to another computer.

**Comment by haasad** [comment]
I tested pinning bw2io to 0.8.7, but it turns out this is a bad idea. There's no way to force conda to upgrade to 0.8.8 for users wanting to use ei3.9. 

Maybe add a warning or explanation to the README similar to https://github.com/brightway-lca/brightway2-io#compatibility-with-brightway2x? Depending on how long it takes until there's a solution for this in brightway, a lot of users will run into this problem.

**Comment by marc-vdm** [comment]
> There's no way to force conda to upgrade to 0.8.8 for users wanting to use ei3.9.

So how about we pin it to `0.8.7` and then add a disclaimer to the readme (similar to what you linked) that users need to make changes to AB if they want to use 3.9?

I think the majority of users will still be on 3.8 and breaking their AB when they update (and thus install `0.8.8`) would probably be most problematic right?

**Comment by marc-vdm** [comment]
@krissh2022 

I thought about this a bit more, you should be able to completely re-install the environment+AB on the 'other computer' you're also working on.
You can do this with the following __Be warned: this will remove all your databases etc on this computer!__

Close AB

Go to `C:\Users\krissh2022\AppData\Local\pylca` (replace krish2022 with the username in your computer)
Note that `AppData` is a hidden folder, but you can copy/type the path and you will go there.

If you're using the stable version:
`conda create -n ab -c conda-forge -c cmutel -c bsteubing activity-browser bw2io=0.8.7`
If you're using the dev version:
`conda create -n ab_dev -c conda-forge -c cmutel -c bsteubing activity-browser-dev bw2io=0.8.7`

Your `conda` will tell you the environment already exists, just confirm that you indeed want to remove everything.

Re-installing should get you the right things for older ecoinvent versions.

Please let us know if that doesn't work for you.

ps it's possible that your foreground databases are not compatible with the different biosphere databases anymore, as these have now changed a lot. Unfortunately I don't have a list of changes for you, so the only way to know is to try to import the database.

**Comment by Myrrm** [comment]
Hello there, I had the problem with importing the ecoinvent 3.8 database. Removing and re-installing as mentioned seemed to fix the problem. The database import ran fast and smoothly. 

BUT now I don't have any LCIA methods (and of course no corresponding data from biosphere3/ecoinvent). 
Is there something I'm not considering? - I'm quite new to AB, so I hope it's not a beginner related issue.

**Comment by Zoophobus** [comment]
Hi Myrrm, I'm sorry for the inconvenience, it is not a great situation for you to be put in. Some useful information that could help us is to know where the AB points to (if you go to file, settings and describe the location where Brightway Dir: is pointed), and where brightway points (if you can run `brightway2.projects.dir`) this should be **in** the same location as where AB points to. 
These are by default set to the same location, but something strange can always happen! If these are pointing to the same location then the databases haven't been setup, which would also be weird, but we'd be closer to figuring out whats gone wrong

**Comment by krissh2022** [comment]
@marc-vdm

thanks alot ! it worked. I was able to import ecoinvent 3.7.1.

**Comment by marc-vdm** [comment]
Alright great! I'll close this issue.

@Myrrm, if you need further help, don't hesitate to open a new issue.
