### ISSUE TITLE
Incorrect LCIA methods installed with bw2io `0.8.8`

### ISSUE THREAD

**Issue by romainsacchi** [LCA-ActivityBrowser/activity-browser#874]
I installed `activity-browser-arm` (which came with `bw2io 0.8.8`) and created a biosphere database and LCIA methods from within the AB. To my surprise, the LCIA methods listed under Impact Categories where those from ecoinvent < 3.9 (not ecoinvent 3.9) and are not really accessible:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/activity_browser/layouts/tabs/impact_categories.py", line 151, in open_method_tab
    new_tab = CFsTab(self, method)
              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/activity_browser/layouts/tabs/impact_categories.py", line 30, in __init__
    self.cf_table.model.sync(method)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/activity_browser/ui/tables/models/impact_categories.py", line 88, in sync
    self.build_row(obj) for obj in self.method.load()
                                   ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/bw2data/data_store.py", line 86, in load
    raise UnknownObject("This object is not registered and has no data")
bw2data.errors.UnknownObject: This object is not registered and has no data
```

I had to directly used `bw2io 0.8.8` in a notebook, using `bw2io.create_default_lcia_methods(overwrite=True)` to obtain the correct set of ecoinvent v.3.9 LCIA methods (Recipe 2016, EV 3.1, etc.).

**Comment by haasad** [comment]
Maybe completely unrelated, but did you experience any crashes (segmentation faults), when adding the default biosphere data?

**Comment by romainsacchi** [comment]
You're right, there was some kind of error when creating the default biosphere:

````
Loaded project: ei39
Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.00 seconds
Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Title: Writing activities to SQLite3 database:
  Started: 11/12/2022 14:36:02
  Finished: 11/12/2022 14:36:02
  Total time elapsed: 00:00:00
  CPU %: 100.00
  Memory %: 3.20
Created database: biosphere3
Wrote 762 LCIA methods with 227223 characterization factors
Reset project settings directory to: /Users/romain/Library/Application Support/Brightway3/ei39.f1469ad5eb0a071dc60323f6e0fce980
Reset metadata.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/activity_browser/controllers/project.py", line 55, in change_project
    bw.projects.set_current(name)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/bw2data/project.py", line 146, in set_current
    self._reset_meta()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/bw2data/project.py", line 171, in _reset_meta
    obj.__init__()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/bw2data/serialization.py", line 123, in __init__
    self.load()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/bw2data/serialization.py", line 128, in load
    self.data = self.deserialize()
                ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39/lib/python3.11/site-packages/bw2data/serialization.py", line 242, in deserialize
    return self.unpack(pickle.load(open(self.filepath, "rb")))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
````

**Comment by romainsacchi** [comment]
But I'm not sure if that's related.

**Comment by haasad** [comment]
would you mind testing it with python 3.9?

**Comment by romainsacchi** [comment]
Coming right up...

**Comment by romainsacchi** [comment]
Unfortunately, same result, but without the error this time.

`````
Loaded project: ei39_39
Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.00 seconds
Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Title: Writing activities to SQLite3 database:
  Started: 11/12/2022 15:44:48
  Finished: 11/12/2022 15:44:48
  Total time elapsed: 00:00:00
  CPU %: 100.80
  Memory %: 3.50
Created database: biosphere3
Wrote 762 LCIA methods with 227223 characterization factors
Reset project settings directory to: /Users/romain/Library/Application Support/Brightway3/ei39_39.e31379734fb59b1a970f3350f75f7ad0
Reset metadata.

`````

As you can see, even though `bw2io 0.8.8` is installed and used
`bw2io              cmutel/noarch::bw2io-0.8.8-py_0 None`

I get the set of LCIA methods from ecoinvent < 3.9, not 3.9:

<img width="626" alt="Screenshot 2022-11-12 at 15 47 31" src="https://user-images.githubusercontent.com/22473067/201479650-a777bc0e-e12d-463a-b7e7-d7d29b2f11dc.png">

And also, none of those are actually accessible:

````

Created database: biosphere3
Wrote 762 LCIA methods with 227223 characterization factors
Reset project settings directory to: /Users/romain/Library/Application Support/Brightway3/ei39_39.e31379734fb59b1a970f3350f75f7ad0
Reset metadata.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39_39/lib/python3.9/site-packages/activity_browser/layouts/tabs/impact_categories.py", line 151, in open_method_tab
    new_tab = CFsTab(self, method)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39_39/lib/python3.9/site-packages/activity_browser/layouts/tabs/impact_categories.py", line 30, in __init__
    self.cf_table.model.sync(method)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39_39/lib/python3.9/site-packages/activity_browser/ui/tables/models/impact_categories.py", line 88, in sync
    self.build_row(obj) for obj in self.method.load()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ei39_39/lib/python3.9/site-packages/bw2data/data_store.py", line 86, in load
    raise UnknownObject("This object is not registered and has no data")
bw2data.errors.UnknownObject: This object is not registered and has no data

````

**Comment by romainsacchi** [comment]
And the plot thickens...
The correct methods are actually available programatically:

![Screenshot 2022-11-12 at 15 52 41](https://user-images.githubusercontent.com/22473067/201479863-0dcebbdf-8189-4fe9-8da4-dff2f422c2ed.png)

**Comment by haasad** [comment]
I think something is broken with the threading here: https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/ui/widgets/dialog.py#L276-L314

I have been trying to find the issue, because for example on linux with python 3.10 this always leads to a segmentation fault and crashes violently. Also the tests for this part of the code fail on all operating systems but, just for 3.10.

**Comment by haasad** [comment]
I could imagine that updating the project settings from within the worker thread leads to problems:
https://github.com/LCA-ActivityBrowser/activity-browser/blob/0d4a531a472779371debd7af54f683d745ae2936/activity_browser/ui/widgets/dialog.py#L308

I'll run some tests :hammer:

**Comment by marc-vdm** [comment]
If I understand correctly this can now be closed since #875's merged right?

**Comment by Zoophobus** [comment]
I think that there is still an issue with threading involved here. @haasad I have also been having more widespread problems with segmentation faults on Linux, typically when loading databases, excel and remotely. There is also this issue from Pan6ora [https://github.com/LCA-ActivityBrowser/activity-browser/issues/867](url) that has "helped" me, although I'm confused by the latest message.

My previous assumption was that there could be some impact from python garbage collection and the QtThreads, although I'm now doubting that. I meant to try and change the use of threads in the code but still haven't gotten around to it, do you have any ideas on this?

**Comment by Zoophobus** [comment]
Okay my last comment left a lot of information out, sorry. Pan6ora used gdb to try and trace the memory issues, so I used this and consistently found it linking to Qt and the threads. Then I managed to find some issues on Stack that linked memory issues with QtThread cleanups, so I wanted to look into it some more but haven't found the time yet.

**Comment by Zoophobus** [comment]
@cmutel unfortunately we don't have a system to check this on, so we were wondering if you could check that this issue is resolved for us?

**Comment by marc-vdm** [comment]
@cmutel Pinging you to please review above request by @Zoophobus

**Comment by marc-vdm** [comment]
Closing as irrelevant
