### ISSUE TITLE
Fail to install Econivent 3.9 Database 

### ISSUE THREAD

**Issue by amisangelo** [LCA-ActivityBrowser/activity-browser#876]
When I'm trying to download the Ecoinvent 3.9 Database using my login, an error pops up saying I have to update the biosphere database as the "required biosphere exchanges are missing". I did that a couple of times, even opened a new project where I downloaded the Biosphere data again, but the same error is showing up. 
Can anyone help?

**Comment by Zoophobus** [comment]
Hi, there's only a work-around at the moment for this issue. For the moment I'll assume you have a fresh install (note that for you to download Ecoinvent 3.9 you need version 0.8.8 of the bw2io package), so for the moment, while we "patch" the activity-browser, you'll need to install the latest biosphere database by using the `bw.add_ecoinvent_39_biosphere_flows()`. I think it should be straightforward after this for you to install EcoInvent3.9

**Comment by Zoophobus** [comment]
Hi Amisangelo, if you are still having problems feel free to reopen this issue. For the moment, however, I will close this
