### ISSUE TITLE
Error while performing sensitivity analysis

### ISSUE THREAD

**Issue by studentethz** [LCA-ActivityBrowser/activity-browser#878]
Dear AB-Team,
If I perform a global sensitivity analysis with specific activities the following error occurs: 

<img width="650" alt="errror" src="https://user-images.githubusercontent.com/117648189/201929008-2156ce98-da8a-478a-88c2-9eeb5e2d06c0.png">

The error doesnt occur in general, for example if I just pick two random ecoinvent activities (with the same functional unit), everything works properly.
In my case, I tried locating the error to certain activites. The error occurs, if I include the ecoinvent activity "pipeline constructon" into the activity "market for natural gas, high pressure" and then perform a sensitivity analysis for the "market for natural gas, high pressure" activity. If I delete all the technosphere flows in "pipeline construction" it also works properly. 

How can I prevent this error? 

AB application version 2.6.9
Ecoinvent 3.8 cut-off

Kind regards,
Joe

**Comment by Zoophobus** [comment]
Hi Joe, that sounds quite peculiar, thanks for the detail, although I was wondering if you could copy the keys for the activities you are directly modelling? If we can replicate this then it will make it a lot easier to get to the root of the problem. Then we can go about seeing if we can prevent this error.

**Comment by studentethz** [comment]
I might found the problem: the nonetyp field was the empty uncertainity field of the "pipeline construction" included in the "natural gas market". If i fill this cell, the calculations proceed. 
I leave the issue open, if all works properly, I will close it.

**Comment by MaximeAgez** [comment]
Had the same issue  #690 but it should have already been dealt with : #766

**Comment by marc-vdm** [comment]
I see the problem now. @MaximeAgez thanks a lot for your comment!

@studentethz I'd reccomend you to switch to the `development` version of AB, the issue should be fixed there.
Do also keep in mind that you are using ecoinvent 3.8, which now requires you to install an older version of `bw2io`. So use the following to create a new environment and install AB:
`conda create -n ab_dev activity-browser-dev bw2io=0.8.7`

No worries about your projects/databases/files, you will still have access to everything, only AB will change.


Please close the issue if this fixed your issue :)
