### ISSUE TITLE
Error when modifying parameters

### ISSUE THREAD

**Issue by danielembc** [LCA-ActivityBrowser/activity-browser#882]
Hi everyone,

My project worked great until I decided to change a parameter.

If I try to change any value, I receive the following error message:

![image](https://user-images.githubusercontent.com/15629111/203154260-0a01bebf-cefa-45ad-abfc-5acb3ce614ff.png)

I have no clue about what to do next. Does anyone experience the same problem?

Thank you.

Kind regards,

Daniele
![image](https://user-images.githubusercontent.com/15629111/203154378-4bdbb084-e159-437e-b0d3-24325bfccc5c.png)

**Comment by Zoophobus** [comment]
Hi,
well the SQL message is, I think, stating that there is no parameter in the group transport_passenger_car_electric .... This would be the first place to start, so if you can identify what has happened to the parameter it is searching for you hopefully might get things to work again.

**Comment by Zoophobus** [comment]
Hi Dainielembc, have you managed to make any progress on this?

**Comment by danielembc** [comment]
Hi Jonathan,

I did not manage to work on the parameters file, so I just reinstalled....
then, it worked.

In any case, thank you a lot for your support.


Kind regards,
Daniele
