### ISSUE TITLE
Biosphere3 version made clear

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#884]
[_Nice to have_] 
As an LCIA method "operationalizer", I think it would be nice to have explicit different versions of biosphere3. When biosphere3 changes (mainly due to a new ecoinvent version coming out) the LCIA method would not work properly with the new version anymore. It would require an update. To make it clear and transparent to users of the LCIA method it would be nice to be able to link any version of the LCIA method to version numbers of elementary flows in AB/bw2.

**Comment by marc-vdm** [comment]
I agree, but this issue would better fit in [brightway2](https://github.com/brightway-lca/brightway2), as we get biosphere from BW. I'd suggest opening an issue there.
