### ISSUE TITLE
Discuss release strategy

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#899]
> I think we need to have a proper look at our release system anyway.
>
> What I think we need is a way to release smaller bugfixes/minor features to both `stable` and `dev` at the same time, while only testing 'larger' features on the `dev` that can, after we're happy, also be merged into `stable`. 
>
> @haasad Would you be able to help us figure out a system for this?
>
> I'm thinking, if we base all our new things from the a `stable` branch (e.g. a new branch, or just master), and then merge them into either `stable` or `dev` (e.g. master or a new branch called `development_release`/`beta` or something).
If I understand correctly, this would work for new features that don't depend on other new features, we could just merge them into both `stable` and `dev`.
> Then, if we'd have new features that depend on eachother, they'd need to be built on the same branch (based on `stable`), and eventually merge into the `dev` branch, and when the features work well (on their own branch), merge them into `stable` too.
>
> Would this make sense? Please think along, I'm hoping you have more experience with this!

_Originally posted by @marc-vdm in https://github.com/LCA-ActivityBrowser/activity-browser/issues/892#issuecomment-1340633994_

**Comment by haasad** [comment]
Proposal for a new release strategy:
- get rid of the development version (not completely, but don't mention it anymore in the README and don't tell users to use the development version)
- there's only one recommended way to install the AB and that's from conda-forge (`conda install -c conda-forge activity-browser`)
- make it as easy as possible for maintainers to make a new release (i.e. what is now the stable release)
- make regular releases (one single bug fix can already be enough to warrant a new patch level release)
- keep it simple with the git branches, i.e. base releases off of the master branch and use feature branches with a PR to master


Maybe that's a bit radical, but I'd argue that this is better both from a user's and from a maintainer's perspective than the current setup. I feel right now we abuse the development version due to the lack of stable releases. Last stable release was in March, so a user following the installation instructions misses out no all the features and bugfixes since then.
Also I'd try to keep the git branching as simple as possible. A more complicated setup with feature -> dev -> stable like you suggested can be useful, but without a clear process it just creates a lot of overhead for the maintainers.

**Comment by Pan6ora** [comment]
It doesn't seems that radical to me, but rather a good practice of continuous development. 
Looking at other projects I now about, a method to manage bugfixes and breaking features could be this one :

- every bug fix is pushed directly to `master`
- no `dev` branch but instead:
  - a branch prepare the next non-breaking release
  - a branch prepare the next breaking release
- push to conda are made every 2 weeks (for example) and not on every push on master. The action is triggered by happening a version tag to the last commit (2.6.10 at current state).

The idea is that the `master` branch contains latest bugfixes, but the conda package doesn't get updated too much. Thus, a "normal" user can use the conda version, where a developer should clone the repos to work with whatever version he/she wants.

For example as we are now in 2.6.9 we would have 3 main branches :

- `master` where bugfixes are pushed
- `2.7.x` where new features are pushed (ex: a plugin manager)
- `3.0.x` where we would work on breaking changes (ex: switch to Brightway25)

Once we've added some new features to the 2.7.x branch we merge it to master and tag the 2.7.0 version, and then create the branch 2.8.x (and so on).

An example of this system can be seen in the [darktable repos](https://github.com/darktable-org/darktable) for example. I think it is also a good way to stick to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

PS: I'm quite new to the development of AB. But as I'm getting more in more into it I feel concerned about this question and so did I let myself join the discussion :)

**Comment by Zoophobus** [comment]
Thanks @Pan6ora and @haasad, your contributions to CI/CD development are most definitely appreciated!

What I don't quite get is your suggestion @Pan6ora that we drop the dev branch and use numbered versions for the new branches. So what I'm not clear on is if (in this system) we would be working on forked branches named like `2.6.9-plugin-manager`? So that if Marc pushed a new feature to the `2.6.x` version then on Github the latest branch becomes `2.7.x`, so that then the plugin-manager would be pushed to the `2.7.x` branch. This then being merged with the master branch and we up the minor version branch to `2.8.x`?

(so that `2.6.9-plugin-manager` -> `2.7.x` -> `master` and `2.8.x` is created from the new `master`)

Sorry for my confusion and if I've not been clear

**Comment by Pan6ora** [comment]
> So that if Marc pushed a new feature to the 2.6.x version

The idea is that we cannot push new features to `2.6.x` version because any change or feature that are not bugfixes should be released in the 2.7 version.

To add new features you have to create a branch or a fork from the `2.7.x` branch, and when your feature is ready you can open a pull request to the `2.7.x` branch.

If you make your feature/fix in a fork you don't need a naming convention. You just have to create your pull request on the right branch depending on the nature of your change.

If you instead want to create a new branch, a naming convention such as 2.7.x-plugin-manager can be used. But it is not mandatory as the git tree clearly show which feature relates to which version.

Here is a quick example I made to show what it could looks like. Hope it helps.

![Example tree](https://user-images.githubusercontent.com/45113213/207590675-9355275c-b427-42e7-b86e-7518a5c9abeb.png)

**Comment by Pan6ora** [comment]
That's the idea.
If you have further questions about this system don't hesitate to ask.

Additional stuff I'm thinking about : 

- every pull request / merge should include the related CHANGELOG entry
- it is advisable to specify somewhere what we're aiming for the next big release. For example using issues:
  -  an issue `Activity Browser 3.0` with a ticklist of what has to be done with links to other issues
  - `3.0` tag for issues
- this could also be done for the 2.7 but I think it may be too complicated in our case (as there is currently no clear mid-term development plan). However a list of wanted changes/improvements could still be a good think to help contributors like me understand what they could help on.

**Comment by haasad** [comment]
> It doesn't seems that radical to me, but rather a good practice of continuous development.

I called it radical, because I mean radically simple compared to now/before. No more development version, just a single package that is kept up-to-date. The same goes for my suggestion to not use any complicated setup with several branches. I suggest just a master branch with new features or bugfixes in their dedicated branches and once they're ready you open a PR to master and they're reviewed and merged.

> I think it is also a good way to stick to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

I fully agree, see also https://github.com/LCA-ActivityBrowser/activity-browser/issues/685

And just so we're all on the same page. These are the steps that are currently required to make a new release with the switch to conda-forge:
* tag the master branch
  * eg. `git tag 2.7.0` + `git push origin 2.7.0`
  * the **github** release including changelog will then automatically be created (see https://github.com/LCA-ActivityBrowser/activity-browser/pull/733)
* wait until conda-forge's [regro-cf-autotick-bot](https://conda-forge.org/docs/maintainer/updating_pkgs.html#how-does-regro-cf-autotick-bot-create-automatic-version-updates) notices the new release and creates a PR in https://github.com/conda-forge/activity-browser-feedstock
  * review and merge the PR

>So what we should aim for is?
>
>    one release version (on conda-forge)

Yes, my suggestion is that the development version is only used to verify that packaging, installation etc. works, but shouldn't be used by AB users (unless it's to troubleshoot a specific issue, but the development version shouldn't be a "supported" installation method like it is now)

>    a branch system based on semantic versioning (1.0.0)*

semantic versioning yes, branch system no (more on this below)

>    regular releases from the main branch (bug fixes, either timed or n event based) to the release version

major version releases should be a planned thing (3.0.0), minor (2.x.0) and patch (2.7.x) releases should just be done by the maintainers as often as useful

Regarding the different branching systems that @marc-vdm and @Pan6ora suggested; I'd argue against using such a setup for the AB, because it creates additional overhead for the maintainer which will lead to less frequent releases. I'd propose to go with the simplest possible system first and only use a more complicated approach if there's a clearly defined need for it.
If the AB reaches a point with 10+ regular contributors, milestone planning, some kind of additional manual testing for new feature/dev/minor branches etc. it could make sense, but otherwise I think it's not worth the effort. If we don't do anything special with a 2.7.x or a dev branch we can just as well merge it to master directly.
What I'm proposing is that instead of deciding what branch to merge something into, PRs are just merged into master. When you make a release you check if any of the merged PRs since the last release includes a new feature, then you bump the minor version number, if it's only bugfixes you bump the patch version number.

**Comment by haasad** [comment]
@Zoophobus No matter what you discuss or agree on in your meeting tomorrow, I suggest we make a 2.7.0 release soon in any case. If you're in charge of the release and would like some support, let me know. A lot has changed since the last release. There's some pitfalls now, especially with conda-forge.

**Comment by Zoophobus** [comment]
@haasad I agree I should have done so sooner and I'm sure @bsteubing will agree too. I'm not aware of any pitfalls so I would be happy for some support, if you have the time.

**Comment by Pan6ora** [comment]
> What I'm proposing is that instead of deciding what branch to merge something into, PRs are just merged into master. When you make a release you check if any of the merged PRs since the last release includes a new feature, then you bump the minor version number, if it's only bugfixes you bump the patch version number.

@haasad  your proposal seems very logical to me, as the lightest solution possible (while still being clean). At the end it is a matter of where you think the "right complexity" is. But at least I think that both our propositions could be considered as "good practices".

If your system were to be chosen, I would argue that we should at least keep a `3.0.x` branch to centralize long-term ideas and breaking changes.

**Comment by haasad** [comment]
> At the end it is a matter of where you think the "right complexity" is. But at least I think that both our propositions could be considered as "good practices".

Yes, and I really like the example you made above. If the AB team decides they have the capacity to deal with the overhead of maintaining the additional branches then it's a very good system. It is also better suited for long-term planning (e.g. you can already prepare things for future releases instead of having a lot of open PRs with "waiting for xy release discussions).

> If your system were to be chosen, I would argue that we should at least keep a 3.0.x branch to centralize long-term ideas and breaking changes.

Yes, that makes a lot of sense :+1:
