### ISSUE TITLE
Align lables with automated releases + general label cleanup

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#907]
We have the fancy automated releases (#733) which is nice, but we're using many labels currently, some of which either overlap with release labels or where the release label was even removed (e.g. bug label). IMO, there are too many labels in general.

I just saw we missed a bunch of PRs in the release message because they didn't have the right label.

### proposal:
 - remove all labels except those in [changelog-configuration](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/ci/changelog-configuration.json), `info:parameters`, `info:macos-shenananigans`, `info:javascript`, `type:discussion`, and `monte-carlo`.
 - drop the `info:` and `type:` part of the labels names
 - add new labels if when we need them

Of course, it'd be good if someone else also checks if there are more labels that are useful -or some of the above which we should drop-, but I think we're pretty much covered with the above, perhaps a `high-priority` one could also make sense, but I think we generally know what has priority already.

**Comment by haasad** [comment]
If you would like to have a complete changelog, you can delete the release as described here: https://github.com/LCA-ActivityBrowser/activity-browser/issues/754#issuecomment-1072992104
Then relabel (optional also rename) the PRs and then redo the release again

**Comment by haasad** [comment]
And I agree that it makes sense to get rid of some of the labels. Here it's a bit confusing that labels are shared between PRs and issues.

Also the categories in https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/ci/changelog-configuration.json are totally up for debate, that's just suggestion that I made back then.

**Comment by marc-vdm** [comment]
> If you would like to have a complete changelog, you can delete the release as described here:

I think that's fine, we can also manually edit the file, just for the next version it'd be nice if we don't have to anymore :)

> Also the categories in https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/ci/changelog-configuration.json are totally up for debate, that's just suggestion that I made back then.

I think we could maybe drop `ui`, as that's most of the things in `features`, as we're a UI anyway. Perhaps we could do the opposite; 'backend changes' or something? Anyway, I think the rest of the list is good, but happy to discuss this!

**Comment by marc-vdm** [comment]
@haasad do you ahve access to the `bsteubing` channel? Jon and I don't and he's on holiday -yes, we are excellently organised- 😅. 
We have an unrelated issue with numpy -or rather, BW has one and we're temporarily fixing it on AB side by locking the version- that needs to be fixed in the new release.

**Comment by haasad** [comment]
Yes, I think he once added me as a collaborator. Do you want me to delete the latest AB package?

Alternatively you could:
a) make a 2.7.1 release
b) use the token in https://github.com/LCA-ActivityBrowser/activity-browser/settings/secrets/actions (assuming you have access, I don't) and do:
```
anaconda remove -t <thetoken> bsteubing/activity-browser/noarch/activity-browser-2.7.0-py_0.tar.bz2
```

**Comment by marc-vdm** [comment]
Nope I get a 404 to that link. don't have access to settings

**Comment by haasad** [comment]
I removed it :+1: worst case you could also run the command I posted above in a github action pipeline, because the pipeline can use the token :see_no_evil:

**Comment by Zoophobus** [comment]
@haasad sorry for this, this is my fault. Thanks so much for your help!

**Comment by haasad** [comment]
no worries, these things happen :-)

just two random thoughts:
- there's absolutely nothing wrong with making a PR with the fix, merging it and then tag 2.7.1 to make a new release
- if I'm not mistaken conda now uses strict channel priority by default, so I think it's likely that conda install will take [2.6.9 from conda-forge](https://anaconda.org/conda-forge/activity-browser/files) no matter what :neutral_face: 
- so you'll also have to release it to conda-forge (and fix the recipe there)

**Comment by haasad** [comment]
Made a PR for the conda-forge release: https://github.com/conda-forge/activity-browser-feedstock/pull/12

**Comment by marc-vdm** [comment]
Thanks a lot for taking care of this @haasad! Really appreciated.
I'll hide the off-topic comments to keep this conversation cleaner, but happy we had your help :)

**Comment by Zoophobus** [comment]
Hi sorry to enter this so late. So I have gone through the list of issues twice now (and changed my opinion in the process) and would like to continue to use some of the other labels. For example labels related to the the technology and some of the other topics (Brightway, Javascript, Monte Carlo, Parameters, Figures) as these allow me to "bin" the issues more easily.

So currently I am beginning to deal with the plots and working with Bokeh, having the Figures and Javascript tag can allow me to easily keep up to date with those issues that are related to this project. These could then be dropped after we complete these projects and integrate them, or as we might decide

I also do think that using a prioirty label could be useful, however I guess that having maybe just a single priority label could be enough. So we could just have the low priority label to tell others that an issue of ours isn't really that important.

**Comment by marc-vdm** [comment]
Alright, sounds good. So how about we keep part of the old system where we have label 'categories' then? Like:

- `tech:` and then the technology (e.g. `tech: BW`, `tech: JS`, `tech: Bokeh` etc)
- `PR:` (for pull request tags) and then something more spefic from the changelog file (e.g. `PR: breaking`, `PR: bug` etc)
- (neither list above is complete, just examples)

Then about the `discussion` label: I think we should actually drop this and start using the [discussions page](https://github.com/LCA-ActivityBrowser/activity-browser/discussions) more instead.

This would make the issues page (more) exclusive for actual code related things like bugs and new features, and any other discussion about AB (like this conversation) could then be put in the discussion section. We can also refer to a discussion in the same way as we refer to an issue in PRs (just `#number`), so we could keep doing that the same way. Additionally, with templates (#772), we could automatically add a `bug`/`feature`/`other?` label when they open a new issue.

Regarding priority: If we implement milestones, I don't think we need the priority labels anymore, the milestone would indicate priority (lower number == implemented faster), things without a milestone would clearly not be high on our list of priorities. Of course the milestones don't need to be set in stone and can be changed whenever we'd feel it makes sense (e.g. delaying a feature because it's not finished but we want to release the new version anyway).


What do you think of this idea?
