### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by gumpi391** [LCA-ActivityBrowser/activity-browser#908]
After installing anaconda (22.11.1) and  trying to open the activity browser using

`conda create -n ab -c conda-forge -c cmutel -c bsteubing activity-browser`
`conda activate ab`
`activity-browser`

on Windows 11 (Python 3.9.13), I get the error 

File "C:\Users\xxx\anaconda3\envs\ab\lib\site-packages\bw2data\data_store.py", line 172, in ProcessedDataStore
    (numpy_string('negative'), np.bool),
File "C:\Users\xxx\anaconda3\envs\ab\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'

Hence, I can't run the activity-browser.

**Comment by flixwar** [comment]
> Thanks for sharing! We just fixed this minutes ago, you don't need to re-install, all you need to do is:
> 
> If you're NOT already in the AB environment: `conda activate ab` `conda install numpy=1.23.5`
> 
> If you are already in the environment, just this is fine: `conda install numpy=1.23.5`
> 
> That will install the right version of numpy, which should fix your problem.
> 
> If the above fixed your problem, please close the issue (button below), otherwise, please let us know!

I have the same issue, but the approach above does not solve it. The following is displayed on top of it:

/Users/xyz/opt/anaconda3/envs/ab/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5

Numpy 1.23.5 therefore still does not fit.

**Comment by mkvdhulst** [comment]
I had the same issue when updating my ab_dev environment to the 2022.12.22 development version and tried this solution, but it did not fix the problem for me. After the downgrade, when trying to run <code>activity-browser</code> I receive a new error:

> File "C:\Users\xxx\Anaconda3\envs\ab_dev\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
>     return original_import(name, *args, **kwargs)
> ImportError: DLL load failed while importing QtWebEngineWidgets: The specified module could not be found.

In addition, I keep getting a pop-up window with the following message whenever updating packages or deactivating the ab_dev environment:

> The procedure entry point ??0PyWinBufferView@@QEAA@XZ could not be located in the dynamic library C:\Users\xxx\Anaconda3\envs\ab_dev\Library\bin\pythoncom39.dll.

Both errors seem to indicate that some references to file locations got lost. Is there any way to fix this?

**Comment by marc-vdm** [comment]
I would suggest creating a new environment like the following:
`conda create -n ab activity-browser`

In the very near future, we will drop support for the development version, the current stable version (2.7.0) and the development version are currently the same.

If you still experience this issue, please let us know, though I'm assuming the above will resolve your problem.

**Comment by mkvdhulst** [comment]
Good to know these things about the development version. 
I wanted to salvage my current ab_dev environment, but this turned out to be unnecessary. I made the switch to the stable version in a new environment and, as expected, this resolved the problem. Thank you for the quick response and useful input.

**Comment by marc-vdm** [comment]
We will make an official announcement when we're completely ready for the switch also ;)

**Comment by marc-vdm** [comment]
@gumpi391 I'm going to assume the issue was solved for you, otherwise, please just re-open the issue!
