### ISSUE TITLE
Error due to Pardiso solver failed

### ISSUE THREAD

**Issue by safdarabbas123** [LCA-ActivityBrowser/activity-browser#917]
Hi LCA Activity-browser community. 
i hope you all will be fine.
i have problem in activity-browser. i have attached screenshot of that error.
![ab problem screenshot](https://user-images.githubusercontent.com/112714003/213763657-0fbebbb5-957f-482d-b134-187228d9222b.png)

i shall be really thankful for valuable suggestion.
Thanks

**Comment by Zoophobus** [comment]
Hi safdarabbas123,

this might be related to a previous bug that I'm going to link to this. One way you may be able to confirm this is by running an excerpt from a previous developer of the AB haasad. Unfortunately he is no longer directly involved with the AB, however he does help us out when we're struggling.

https://github.com/haasad/PyPardisoProject/issues/36

If you could run his code snippet and tell us what the output is that would help.
`python -c "import pypardiso as pp; import numpy as np; import scipy.sparse as sp; A = sp.rand(5000, 5000, density=0.05, format='csr'); b = np.random.rand(5000); x = pp.spsolve(A, b); print(x.sum())"`

It would also help if you could provide us with the output from `conda list` from within your conda environment, it'll tell us at least what version of pypardiso you have

**Comment by safdarabbas123** [comment]
Dear Jonathan Kinder,
Thank you so much for your valuable suggestions. I have follow that code
and it resolve my issue.
With best regards,
safdar

**Comment by safdarabbas123** [comment]
Thank you so much
