### ISSUE TITLE
Changing the already build activities of custom databases from ecoinvent 3.8 to 3.9.1

### ISSUE THREAD

**Issue by iamz33** [LCA-ActivityBrowser/activity-browser#925]
Hi, 

Is there a way to replace already build databases of products from ecoinvent 3.8 to ecoinvent 3.9 without having to work manually on every activity? Like the same databases are created just that the same activity is taken from cutoff391 and not cutoff 38.

**Comment by Zoophobus** [comment]
Hi iamz33, 

I guess you have already been through this [bw2io page](https://github.com/brightway-lca/brightway2-io#compatibility-with-brightway2x), reading through it I suspect that any attempt to import a ecoinvent 3.8 to 3.9 database will not be without pain.

A hack you might try for this could be to use the AB database [relinking code](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/bwutils/strategies.py) to see if this can help resolve at least some of the links.

**Comment by marc-vdm** [comment]
Closing as stale
