### ISSUE TITLE
High CPU usage and poor performance when opening activities view

### ISSUE THREAD

**Issue by lfen7** [LCA-ActivityBrowser/activity-browser#926]
Hi everyone

When double-clicking a database and opening the activities view, CPU usage of the Activity Browser shoots up to 120% and the Activity Browser becomes laggy and slow to the point where it's unusable. This happens consistently, every time I open the activities view. When I first open the Activity Browser with no activities view open, everything is fine.

Fixes I have tried: re-installing Activity Browser in a new environment, creating a new project with only the biosphere3 database and installing the experimental version as described in #741 

I'm on a Mac with a 2.6 GHz 6-Core Intel Core i7 and Monterey (Version 12.5.1) installed. 

Thank you for any help on how to resolve this.

**Comment by Zoophobus** [comment]
Hi Ifen7,

would you mind providing the details of your environment (print the results from `conda list`) here?

Also could you explain what you're doing in more detail. Are you opening the "Graph Explorer" tab, or is the slow-down happening when you open the "Activity Details" tab?

KR

**Comment by lfen7** [comment]
Hi KR

I've narrowed the problem down to the "Project" tab. If I open the "Impact Categories" tab instead of the "Project" tab, everything works smoothly, no matter what is open on the right hand side ("Activity Details", "Graph Explorer", etc).

I'm not doing anything besides opening the "Activities" view. Same thing happens if the welcome screen is showing. 

The following is the output from `conda list`
[list.txt](https://github.com/LCA-ActivityBrowser/activity-browser/files/10577939/list.txt)

**Comment by Zoophobus** [comment]
Hi Ifen7

you have the CMutel and Bsteubing channels in this environment, did you follow the conda-forge installation instructions before this? This would be `conda create -c conda-forge -n AB activity-browser` we have migrated to conda-forge and will update the settings soon. We've been waiting for confirmation that this works on Macs before updating the instructions!

**Comment by haasad** [comment]
hi @lfen7 ,
can you please post the output of the following command:
```
python -c "from PySide2.QtCore import QSysInfo; print(QSysInfo.productType(), QSysInfo.productVersion())"
```

**Comment by lfen7** [comment]
@Zoophobus , yes, I originally installed the conda-forge version of activity-browser and had the same issues. I installed the activity-browser-arm version in an attempt to fix it. 
I now reinstalled activtiy-browser in a fresh environment as per your suggestion but the problem persists. 

@haasad I get the following: `osx 12.5`

**Comment by haasad** [comment]
The reason I'm asking is because we have some special configuration for Mac here:
https://github.com/LCA-ActivityBrowser/activity-browser/blob/a852901a0c82445042557fa2cef9c391dd2d245e/activity_browser/__init__.py#L13-L22
I unfortunately don't know all the details, but it sounded similar to what was reported in #741 that should have been fixed with #745. Maybe something change again with 12.5 and GPU hardware acceleration should be enabled again? I don't have a Mac machine to test this atm

**Comment by lfen7** [comment]
I re-enabled GPU hardware acceleration (by adding my OS version to the "supported" set). This does not seem to make a difference. It did, however, not break anything either.

I suspect the issue is somewhere in the `activity_biosphere_widget`. As soon as the widget is showing, the CPU usage spikes.

https://github.com/LCA-ActivityBrowser/activity-browser/blob/a852901a0c82445042557fa2cef9c391dd2d245e/activity_browser/layouts/tabs/project_manager.py#L16-L22

**Comment by lfen7** [comment]
Hi Jon

Thanks for the offer to meet. I sent you an email to your Leiden University email address. Let me know if you didn't get it. 

Best, 
Leo
