### ISSUE TITLE
Updating ab_dev gives error

### ISSUE THREAD

**Issue by avdoever** [LCA-ActivityBrowser/activity-browser#943]
After updating the ab (developer) I get the following message when trying to open the ab:

ImportError: DLL load failed while importing QtWebEngineWidgets: The specified module could not be found.

How can I solve this?

**Comment by Zoophobus** [comment]
Hi this is a rather annoying issue and it's due to some changes in PySide, or so I currently believe. If you could try running this `conda install qt-webengine` in the AB environment it should work

**Comment by avdoever** [comment]
Thanks, that worked!
