### ISSUE TITLE
Sankey is broken in v2.7.3

### ISSUE THREAD

**Issue by BenPortner** [LCA-ActivityBrowser/activity-browser#944]
I cannot generate a sankey diagram for activity A in attached database using AB v2.7.3. The sankey view pops up but nothing is shown and the AB seems to slow down significantly. It works fine in versions 2.7.2 and below.

Database: [lci-contribution-analysis.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/10855292/lci-contribution-analysis.xlsx)
Note: Import using AB. Database depends on biosphere3.

**Comment by Zoophobus** [comment]
Hi Ben,

sorry for the delay in responding, you do use linux right? You mean that the performance of the AB depreciates when you open just the sankey figure/tab? Excluding the graph-view and welcome page?

There might have been a recent issue that is related to this and involved changing the execution of some QT code. I'm pushing this onto the conda-forge repo, so maybe you can try downloading a later version tomorrow and test it there. I've been testing this on my machine and I don't have an issue, although I did with the conda release you mentioned.

**Comment by BenPortner** [comment]
Hi @Zoophobus,

I actually experienced this issue on a windows machine. Not sure it is just performance. The welcome page loaded just fine and the calculation results page as well but as soon as I switch to the Sankey tab everything gets slow and it doesn't show a graph for at least 1 minute (didn't try longer). Let me know when you uploaded the new version to conda then I'll try again :)

Thanks.
Ben

**Comment by Zoophobus** [comment]
Hmm, that makes this issue quite a bit more interesting, could you tell me your windows version?

**Comment by BenPortner** [comment]
I'm using Windows 11 Pro build 22621.1265 with Python 3.9.16 build h4de0772_0_cpython packaged by conda-forge.
