### ISSUE TITLE
re-implement the "Activity Browser experience"

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#95]
**Forward-backward buttons to re-implement the "Activity Browser" experience**
The original version of the AB had nice buttons to navigate through the browsing history very quickly. This idea originally inspired the name Activity Browser - to quickly explore LCA data. 

**Link- (or key) based navigation**
Each activity in brightway has a key. In addition to the search function, this key provides an alternative way to directly accessing an activity - by providing the link so to speak (the key). This was already present in the original AB and should be re-implemented. Also as the AB is a tool to work smoothly together with brightway2.

**Comment by bsteubing** [comment]
please see my answer in #81

**Comment by haasad** [comment]
Bernhard's answer in #81 with additional ideas for the toolbar. #81 was closed in favour of this issue:
> I think the toolbar still has a value and could feature other things. The original version of the AB had a number of functions there, see here:  
![image](https://user-images.githubusercontent.com/33026150/35561404-807e2c76-05b0-11e8-8b8a-3dcce4688849.png)
>From left to right: 
>- search
>- search by brightway key
>- random activity 
>- history (tab could appear once the user presses this button)
>- back and forwards buttons for "activity BROWSER" type navigation
>- edit activity
>- calculate LCA results (with functional unit and LCIA method as defined in LCIA tab)
>
>Further, from the modular LCA extension:
>- new module
>- save module
>- open modular LCA database
>- add database
>- save database 
>- close database
>
>Graphing:
>- show module as graph (type defined in drop-down menu)
>- show modular system (several connected modules)
>
>Similar buttons could be used to display a supply chain graph relating to the current activity.

**Comment by bsteubing** [comment]
I think with the recent advancements we can drop this for now.
