### ISSUE TITLE
Scenario LCA: A value is trying to be set on a copy of a slice from a DataFrame

### ISSUE THREAD

**Issue by mkvdhulst** [LCA-ActivityBrowser/activity-browser#963]
Hi,

Whenever I try to perform a Scenario LCA with a scenario difference file created with `premise`, my Anaconda Prompt fills up with the following error:

> C:\Users\hulstmkvd\Anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py:154: SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
>   new_prod.loc['flow type'] = 'production'
> C:\Users\hulstmkvd\Anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py:155: SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
>   new_prod.loc[scenario_cols] = prod_amt

When adding additional scenarios, e.g. a flow scenario file for my foreground system, loading takes extra long and for each operation (adding scenario, loading scenario file, running calculation), the Anaconda Prompt fills up with the same error code over and over again. 

Regardless of the errors, I am able to calculate and display LCA results that seem reasonable, so it is not breaking the Scenario LCA feature as far as I can tell. 

For context: I am running `activity-browser 2.7.5` and used `premise 1.5.0-beta3` to create a superstructure database and scenario difference file of ecoinvent 3.9.1 for several years and all three SSP2 scenarios of the IMAGE model. I uploaded the scenario difference file that is giving me these errors to file.io, where it can be downloaded until June 1st using [this link](https://file.io/zdzSYlmz07kY).

**Comment by marc-vdm** [comment]
Thanks a lot for sharing! 

AB still works as it's is only a warning because we do something Pandas is not happy with, but will still do. 

Anyway, we should fix this, as the things that's slowing you down is the printing of the warnings by Pandas, and we don't want AB to be slow for such a silly reason of course.

**Comment by Zoophobus** [comment]
Hi @mkvdhulst, this should be fixed in the latest conda release, if you update to the latest version hopefully it should be running faster
