### ISSUE TITLE
Activity `Name` and `Location` fields are read-only when creating new activity

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#964]
Activity `Name` and `Location` fields are read-only when creating new activity while the `Edit Activity` option is activated by default.

I know we set some tables to read/write when a new activity is created, but it seems we accidentally forgot the `Name` and `Location` fields to also be changed.

**Comment by Zoophobus** [comment]
On discussion there would also be the advantage of having the technosphere and biosphere tables to be opened automatically when creating the new activity.
