### ISSUE TITLE
AB version numbers

### ISSUE THREAD

**Issue by Zoophobus** [LCA-ActivityBrowser/activity-browser#965]
The AB versioning does not work across all systems and installations. The extraction of the version number fails in the info.py module leading to the use of the Error version number "0.0.0"

**Comment by marc-vdm** [comment]
What's more interesting, I just had a look at the site-packages in pycharm (this in the conda project):

![image](https://user-images.githubusercontent.com/34626062/236849383-af747593-4d6b-452d-89c9-ac01b9f1c5f2.png)

The library name has `0.0.0` in it too. In [info.py](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/info.py) I also replaced (again, in the site-package, not in the pycharm project)

```python
try:
    __version__ = version(__package__)
except PackageNotFoundError:
    __version__ = "0.0.0"
```
with
```python
__version__ = version(__package__)
```
and AB starts without issue

**Comment by haasad** [comment]
@Zoophobus Can you tell me in what context you don't get a correct version number? We only set a correct version number in the packaged AB, i.e. when installed with pip/conda

https://github.com/LCA-ActivityBrowser/activity-browser/blob/1504401b18381f753278e7ca9fe7424acd223d4d/activity_browser/info.py#L3-L6

and 

https://github.com/LCA-ActivityBrowser/activity-browser/blob/1504401b18381f753278e7ca9fe7424acd223d4d/setup.py#L20-L23

**Comment by haasad** [comment]
see https://github.com/LCA-ActivityBrowser/activity-browser/pull/684#issue-1047927977

**Comment by marc-vdm** [comment]
> We only set a correct version number in the packaged AB, i.e. when installed with pip/conda

For me, this is a problem with AB installed through conda, it was indeed already a problem with AB in an IDE

**Comment by Zoophobus** [comment]
Hi @haasad ,

sorry scratch my first post [out], the version number is being collected, however as @marc-vdm pointed out this information seems to be incorrect and provided as 0.0.0. This is from conda environments from conda-forge and bsteubing channels.

This does not occur for me on a newer system (the base conda environments should be more or less identical between systems)

**Comment by haasad** [comment]
It looks like this has always been broken for the AB package on conda-forge. In the github actions in this repo we rely on the git tag to determine the version, but the conda-forge feedstock uses a tarball so it doesn't have the git tag version info. It's just something we forgot to consider when moving to conda-forge. I'll make a PR with a fix.
