### ISSUE TITLE
Project dropdown should show full project names as tooltip

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#975]
The projects dropdown can be too small to show full project names when on a low resolution screen. I think we should add tooltips to each entry with the full project name of the dropdown so users can see the full name of the projects. In the example screenshots I have 2 projects with similar names and I can't see which is which.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/34626062/783b236b-88dc-47c2-9e49-6de611228fe7)

**Comment by Zoophobus** [comment]
Eeek! Do you mind my asking what the resolutions are? Just wondering if we should try and provide some alternative formats in these cases.

**Comment by marc-vdm** [comment]
1080p standard laptop display of my worklaptop 🤷  But my PR solves it well enough imo
