### ISSUE TITLE
Characterization factors for biogenic emissions in ReCiPe

### ISSUE THREAD

**Issue by elisapas** [LCA-ActivityBrowser/activity-browser#980]
Hi,

I have just realized after developing some calculations that biogenic emissions are accounted for in the ReCiPe midpoint (H). When checking the CFs in the AB:

![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/99656945/2c1bb10a-0ef1-45d1-a304-bcedc0cc07e0)

However, I think these emissions are not meant to be included in this methodology. Is there any way to change this? Could it maybe be something related to my installation? I have just updated the AB and I keep having the same issue.

Thank you in advance!

**Comment by Zoophobus** [comment]
Hi @elisapas,

there's not currently a function for this in the AB. We are working to allow people to edit the CFs, however there's still a bit more work required. These emissions are defined by others and the installation has no role (other than with the versions of brightway, which should remain constant for the AB) in determining these.

I will have a quick look in the brightway documentation and get back to you on how to make changes to the CFs programmatically

**Comment by marc-vdm** [comment]
@elisapas I'm not entirely certain this is not as it's supposed to be. However, if you think this is wrong, it'd also be best to make an issue on the [Brightway github](https://github.com/brightway-lca/brightway2/issues), where we get the impact categories from. 

And just for my personal interest; could you refer me to the page/source where it says that these flows are not supposed to be in the impact category?

**Comment by MaximeAgez** [comment]
ReCiPe does not follow the neutrality assumption of biogenic carbon. So you have positive emissions flows (those you share in your screenshot) but you also have negative CFs values for intakes of biogenic carbon (Carbon dioxide, to soil or biomass stock). 

If the inventory is made properly (which is not often the case if we are honest) both results (+/-1 and 0) should yield somewhat similar results on the whole life cycle.

If documentation of brightway doesnt show how to integrate new CFs here are the steps to follow:
new_method = bw2.Method("my new method")
new_method.register()
new_method.metadata["unit"] = 'kgCO2e'

data = [(('biosphere3', 'f628a923059142fe9e47788dd525bf43'), 1),
        (('biosphere3', 'e8d9cd6f680c48028e81eb3d74b175a5'), 29.8),
        (('biosphere3', '127a8f1b01bc42f4bb14bfd8caa46453'), 273),
        (('biosphere3', 'f90959dcecfc4e8fb648de8314416266'), 0),
        (('biosphere3', 'b30d7732c1c148588d3145c1a387a2e0'), 0),
        (('biosphere3', 'ff8eb79d1dc644aea2d4e9ab732b2840'), 0),
        (('biosphere3', '5795795833c64ea5bb7de87de3032aea'), 0),
        (('biosphere3', '347fc6b7666a46daa34786ab352f29e8'), 0),
        (('biosphere3', '07e0e1da24a143518bdf4e157534e3c3'), 0),
        (('biosphere3', '1cb1fe1911f347868d3d86d33457f053'), 0)]
new_method.write(data)

**Comment by elisapas** [comment]
Thank you all for your answers!

@marc-vdm I was a bit confused checking SimaPro because the flow "carbon dioxide, biogenic", as it is called in SimaPro, does not appear with a CF in the CF matrix of the ReCiPe method, so this is not taken into account in the calculations (see screenshot), and therefore retrieves the same results regardless of how much "carbon dioxide, biogenic" emissions you put in the process. But checking the documentation, it does not seem that ReCiPe itself excludes biogenic emissions, so the implementation in BW was correct :)  I will rather check if I was using a correct implementation of SimaPro.

![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/99656945/1f0ad998-15c3-4733-b41f-705e86630136)

Thanks @Zoophobus , it would be great to allow the users to change the CFs in the AB in the future. Looking forward to more updates on this!

Thanks for the code @MaximeAgez , I will try with that next time.

I can close this issue now.
