### ISSUE TITLE
Negative impact results when running Scenario LCA

### ISSUE THREAD

**Issue by siwije** [LCA-ActivityBrowser/activity-browser#989]
When calculating Scenario LCA (Fig 1), the LCA results end up being negative and unreasonably large (Fig 2), and the ratio in both EF and process contributions are misrepresented by exceeding both 0 and 1 for the relative cut-off type (Fig 3.). When Standard LCA is calculated, there doesn't seem to be any issues.

Fig 1.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/1239d0c5-5a84-4c53-bf9b-42273d0555fc)

Fig 2.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/71ace177-430f-48f3-a845-74d1ee9c0726)

Fig 3.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/50ad1b3a-0cc1-4291-9adc-1682305e1b22)

**Comment by siwije** [comment]
I forgot to mention that the version used for the above screenshots were 2.6.9. I now have 2.8.0 but the contribution plots don't add up to 1 and are not equally long, if you look carefully (Fig 1 & Fig 2). A minor detail but I thought I would mention it nonetheless. LCA Results have however become even more extreme (Fig 3) while remaining negative.

The processes analysed in these examples are not the same as in the first three pictures I posted but this doesn't seem to make any difference.

Fig 1
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/98d31c3c-0a46-4c21-b5c8-6fc56c89529a)

Fig 2
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/a614e785-6603-4dc7-a820-3792059c8372)

Fig 3
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/46d42bc2-d67a-4d34-97e3-548662f5893b)

**Comment by Zoophobus** [comment]
Hi @siwije 

thanks for updating the AB, so I have a few quick questions to ask:
1. What kind of scenario files are you using?
2. Parameters are involved in the LCA calculations, right?
3. Would it be possible to get a copy of your database? (it would make it easier for us to understand why some of the values in the contribution analyses are so extreme)

**Comment by siwije** [comment]
1. I'm not sure what you mean by this. I am using an excel file with parameters. However, at the time of posting I included parameters and databases that I have now removed. I'll attach both sets though. 
2. Yes.
3. Sure, thing. It will be attached to this message.
Default values:
[default_scenario_table.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/11800945/default_scenario_table.xlsx)

Test values for trying out the scenario LCA:
[EF41C110.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/11800947/EF41C110.xlsx)

The database:
[Black_tea_cutoff3point9_2023.zip](https://github.com/LCA-ActivityBrowser/activity-browser/files/11800967/Black_tea_cutoff3point9_2023.zip)

**Comment by siwije** [comment]
Because you said parameters being unstable in #991, I conducted an LCA analysis on the Black_tea database I sent you as well as one (testtea) where the parameters in the formulas were replaced with numbers which ended up in the picture below. I'll include the number-only database if you need it.

Number-only database:
[testtea.zip](https://github.com/LCA-ActivityBrowser/activity-browser/files/11801130/testtea.zip)

Comparison between numbers-only database and parameter database:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/0f9c6755-2460-416b-9e3d-cd8cf1b5e2d7)

**Comment by Zoophobus** [comment]
thanks @siwije, I'll try and get back to you soon with what I can find!

**Comment by siwije** [comment]
Just one last thing that is slightly related to this: It seems there is no mass conservation in between activities, meaning that the production amount for an acitivty is irrelevant when the activity is used as a technosphere flow for another activity. So if 2 products are made in activity A, they are both accounted for in an amount of 1 as a technosphere flow in activity B. Consequently, when a Standard LCA analysis is performed, that measures an X amount of the acitivity's product. 

Maybe this is standard LCA software procedure, but I just wanted to make sure.

**Comment by Zoophobus** [comment]
I'm not sure that I've understood your last point.

If I have, however, then you may have the wrong idea of the equations. What happens when you use the AB and BW, or generally all LCA software, is that you create a database that can generate the technosphere matrix. Each column of the matrix (not inverted) represents a flow for an activity/process, each row represents a specific element in the exchanges. If you multiply this by the "scaling vector" you get the product or "reference flows" of the AB, of course it's the "scaling vector" that we want (I guess this would all be clear to you). For me the helpful point here is to think of this as a series of simultaneous equations (sorry for the bad drawing):
![simple_equation](https://github.com/LCA-ActivityBrowser/activity-browser/assets/12627199/edfa2fd3-a852-4bfb-97ca-2a306e34a74d)
When solving the simultaneous equations each of the equations need to be "balanced", so if I were to solve the above I would manage the constants in equation i with those of i+1, so that I would be able to remove the second constant (a_i+1,2_). To be honest, at this point I've forgotten the intelligent methods for solving these, thankfully the computer is much better and "these equations" will be similarly solved using matrix algebra (as BW does). So all of the accounting of "process B needs x times that produced by process A" will be done within the matrix algebra.

**Comment by Zoophobus** [comment]
BTW If I've gotten this wrong please correct me and again sorry for my bad drawing skills

**Comment by siwije** [comment]
What you wrote is relating to the LCA calculations, right? How the impact is calculated? I mean that the 1.955 kilogram of black tea used by "Cup of tea" (fig 1) corresponds to the 1 kilogram produced by "tea pot" (fig 2) when defining/building the model.

Meanwhile when selecting a reference flow for _LCA setup_, its amount is the scaling factor for LCA calculations. So if ref_flow amount = 2, then the amount of "cup of tea" measured would be 2*1.955 kilograms which is the same as 2*1 kilogram black tea from "tea pot" (Fig 3).

Fig 1.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/3538ca11-79d3-4534-b676-32f4bd81170b)

Fig 2.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/c8a255fb-2584-4ac1-a341-650045111927)

Fig 3.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/5f41f4e7-e311-4ecd-b060-53d036049f7f)

**Comment by Zoophobus** [comment]
Hi @siwije,

yeah you understood me at least! Sorry I didn't understand you. I will check this later, however generally in the AB we overwrite the values, so in Fig 3. the 2 kg Cup of tea will be just that, 2 kg of black tea. So for the other points the "Tea pot" activity produces 1 kg of tea, while your cup of tea takes 1.955 kg of tea from "Tea pot" and produces 1.955 kgs. The contributions from the "Tea pot" activity will be 1.955 times those that you provided to the activity itself. When it comes to the LCA calculation (I think) what should be happening is that your 2 kg of black tea in the reference flow will be equivalent to the 2 kg of 2 times the amount from "Tea pot".

In the LCA equation (A is the technosphere matrix. s the scaling factor, f the "product"), sorry if I'm mangling the terms.
f = s*A
The reference flows represent those non-zero values of f, (Although you can provide a value of 0). Again anyone please correct me if I'm being stupid. Also please feel free to tell me if I'm being confusing

**Comment by siwije** [comment]
Alright! I think I understand now! Thanks for the help!

**Comment by Zoophobus** [comment]
Hey @siwije,

umm so I don't know how to really explain this, really it was a lucky find on my part otherwise I could have spent a lot longer going through this. However the source for your negative values might well be related to an update with the code in a bw dependency contourpy. Could you send me the results of `conda list contourpy`from your AB environment? If this is the case you will need to downgrade the package to 1.0.7

**Comment by siwije** [comment]
Hi @Zoophobus! Sorry for the late response. Here are the results from `conda list contourpy`:
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/03e93af3-871f-4012-acc4-32d0c6bc7e72)

**Comment by Zoophobus** [comment]
No worries @siwije this might actually be a red herring, I located the source of my problem and it wasn't anything that you were exposed to, I was working on updating the code for using multiple scenario files in another isolated branch. You could try downgrading this still, I'm not sure why (and neither are the bw developers) but I did see a big difference in the results from using contourpy=1.0.7 compared to 1.1.0 in my branch.

If you want to try this then just do the following:

`conda remove --force contourpy` to remove contourpy and none of it's dependencies
`conda install -c conda-forge contourpy=1.0.7` to install the specific version

**Comment by siwije** [comment]
While it did turn them positive, they (fig 2) don't result in the same values when comparing to a standard LCA (fig 1) and the rellative bars in process contribution don't add up to 1 (fig 3).
Fig 1.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/65c3372e-fbe8-4853-9737-7dd9444ff137)
Fig 2.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/fedf929d-3723-46f1-bef9-14baf228ceb5)
Fig 3.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/842c1baf-470e-4bdb-8640-1b3a62a2f627)

**Comment by Zoophobus** [comment]
Hi @siwije,

sorry I should have asked you for this before, could you provide the entire print out of your environment? I have no clue why there should be such an impact from the contourpy library, I have asked others in the bw community and they were stumped about this too. Still, it might be an idea to also open up an issue there so that this will get more visibility amoung the BW users.

Also just to confirm the results of fig1 & 2 should be identical right?

**Comment by siwije** [comment]
The printout is at the end of this entry.

>Also just to confirm the results of fig1 & 2 should be identical right?
The blue bars in Fig 1 & fig 2 should be identical and the orange and green bars should be different. I will attach the parameter sets I'm using (file 1).

>One final question are the scenarios from a parameter scenario file? (If yes could you try to build a flow scenario)
Yes. I'm not sure what you mean with "try to build a flow scenario". Do you mean build it from scratch? Because exporting the parameters as a flow scenario and then uploading that file (file 3) into a Scenario LCA just yields fig 1.

As I was going to include my default values in the excel file of the parameter sets, I realized that many of the parameters are not included in the models I am now using and some are grouped differently than the default values I'm using. Sorry for the confusion. I will include both files in case you are curious to look at both and plots of the new parameters. 

File 1. The parameter set from the last comment.
[EF41C110.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/11925826/EF41C110.xlsx)

File 2. The "new"/"corrected" parameter set used for fig 1-3.
[newest_test_parameters.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/11925832/newest_test_parameters.xlsx)

File 3. File 2 made into a flow scenario.
[flow_scen_newest_test_parameters.xlsx](https://github.com/LCA-ActivityBrowser/activity-browser/files/11925848/flow_scen_newest_test_parameters.xlsx)

Fig 1. Scenario LCA of the "new"/"corrected" parameter sets in the file "new_test_parameters".
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/2da4c4a0-9995-41bf-abc0-9fe0037a5926)

Fig 2.  Standard LCA of the "new"/"corrected" parameter sets in the file "new_test_parameters".
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/470990da-a1d8-4362-8412-b94cf1fcb487)

Fig 3.  Fig 1 except in the last parameter set, all values are set to 3.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/6943a6cb-9c6f-4eec-9617-b58f17827b1f)


# Name                    Version                   Build  Channel
activity-browser          2.8.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
asteval                   0.9.30             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
brightway2                2.4.3              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotli-python             1.0.9            py39h99910a6_8    conda-forge
brotlicffi                1.0.9.2          py39h99910a6_3    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2            py39hcbf5309_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.8              pyhd8ed1ab_1    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h68f70e3_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7            py39h1f6ef14_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      1.5.1              pyhd8ed1ab_1    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flask                     2.3.2              pyhd8ed1ab_0    conda-forge
fonttools                 4.40.0           py39ha55989b_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.76.3               h12be248_0    conda-forge
glib-tools                2.76.3               h12be248_0    conda-forge
gst-plugins-base          1.21.1               h001b923_1    conda-forge
gstreamer                 1.21.1               h6b5321d_1    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.7.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_metadata        6.7.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
inflate64                 0.3.1            py39ha55989b_3    conda-forge
intel-openmp              2023.1.0         h57928b3_46319    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
kiwisolver                1.4.4            py39h1f6ef14_1    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.15                 ha5c8aab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              17_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              17_win64_mkl    conda-forge
libclang                  15.0.4          default_h77d9078_0    conda-forge
libclang13                15.0.4          default_h77d9078_0    conda-forge
libdeflate                1.17                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.76.3               he8f3873_0    conda-forge
libhwloc                  2.9.1                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              17_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libtiff                   4.5.0                hf8721a0_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lxml                      4.9.2            py39h0942119_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.3            py39ha55989b_0    conda-forge
matplotlib-base           3.7.1            py39haf65ace_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.14          py39ha55989b_3    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numpy                     1.23.5           py39hbccbffa_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openpyxl                  3.1.2            py39ha55989b_0    conda-forge
openssl                   1.1.1u               hcfcfb64_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.2            py39h1679cfb_0    conda-forge
pathos                    0.3.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
peewee                    3.16.2           py39habf9222_0    conda-forge
pillow                    9.4.0            py39hcebd2be_1    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
platformdirs              3.6.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
pox                       0.3.2              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.6            pyhd8ed1ab_0    conda-forge
psutil                    5.9.5            py39ha55989b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py7zr                     0.20.5             pyhd8ed1ab_0    conda-forge
pybcj                     1.0.1            py39ha55989b_2    conda-forge
pybcpy                    0.0.17             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.18.0           py39ha55989b_0    conda-forge
pypardiso                 0.4.2              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppmd                    1.0.0            py39h99910a6_1    conda-forge
pyprind                   2.11.2          py39hcbf5309_1004    conda-forge
pyside2                   5.15.6           py39h56cbfbc_3    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.13          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyzstd                    0.15.8           py39h95af829_0    conda-forge
qt-main                   5.15.6               h9c3277a_1    conda-forge
qt-webengine              5.15.9               hb9a9bb5_5
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
salib                     1.4.7              pyhd8ed1ab_0    conda-forge
scipy                     1.10.1           py39hde5eda1_3    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
setuptools-scm            7.1.0              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               hcfcfb64_0    conda-forge
stats_arrays              0.6.5              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0           py39hbaa61f9_1    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.9.0             h91493d7_0    conda-forge
texttable                 1.6.7              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.6.3                hd8ed1ab_0    conda-forge
typing_extensions         4.6.3              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              15.0.0           py39ha55989b_0    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_0    conda-forge
vc                        14.3                hb25d44b_16    conda-forge
vc14_runtime              14.34.31931         h5081d32_16    conda-forge
voluptuous                0.13.1             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.34.31931         hed1258a_16    conda-forge
werkzeug                  2.3.6              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_7    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.15.0           py39ha55989b_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.1.2              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipfile-deflate64         0.2.0            py39ha55989b_3    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge

**Comment by Zoophobus** [comment]
Hi @Siwije,

sorry this might have been easier if we didn't have a rather long running and mystical bug in linux that makes importing excel databases almost impossible, without excel databases we can't export or import the parameters. Using the flow scenario as you provided makes things considerably clearer. Thanks for making this for me! Looking through the flow scenario you provided there's really just a single point regarding flows 4, 7 and 10. 

So all of these flows refer to the same process as they refer from. As the flow type is technosphere what we do is to find the proportion of the difference between the technosphere and production flows (what should really be happening here is that this produces a 0, however due to type conversions the value probably just becomes some minute fraction). I'm guessing that what you probably wanted was for these to be production flows, for that you just have to change the flow type to `production` in the excel file. 

Doing this (plus dropping one of your databases gives me these results)
![Screenshot from 2023-07-03 12-13-13](https://github.com/LCA-ActivityBrowser/activity-browser/assets/12627199/9ca4521e-846d-4455-b9a5-031b98ba6b3b)


![Screenshot from 2023-07-03 12-14-13](https://github.com/LCA-ActivityBrowser/activity-browser/assets/12627199/60e38ab5-f996-481d-a3fe-700e3b54b14a)

**Comment by Zoophobus** [comment]
@siwije

would you be okay with me using some of your results to create an issue with the matplotlib repo? contourpy is used in matplotlib so these differences might be of interest to them, or they might already have more information that can explain this to us

**Comment by siwije** [comment]
@Zoophobus 

It worked!

Though I noticed that one of the databases "test tea" (perhaps the one you omitted) resulted in a higher value than usual and I solved this as well.

First off: Apparently, some of the technosphere formulas weren't calculated. This is probably because I was experimenting with different proportion amounts between the production flow and the technosphere and biosphere flows.

Secondly: I retained some parameters that were automatically named after the activity they were conceived in ("Kettle_1" and "Tea_pot_1"). I believe this is a bug that happens when you open a formula and, without adding anything, press "Save".

When the first point was corrected and the second point were deleted, I received the same results.

Going back to your solution, is there any way of preventing the flow from being classified incorrectly (i.e. technosphere instead production) without doing it manually in the excel file? You see, I will be a lab assistant in a course using this software and I'm trying to formulate instructions so that they get the most out of it.

> would you be okay with me using some of your results to create an issue with the matplotlib repo?
Yes, I am okay with that.

**Comment by Zoophobus** [comment]
> Going back to your solution, is there any way of preventing the flow from being classified incorrectly (i.e. technosphere instead production) without doing it manually in the excel file?

Hi @siwije if this is what you already did then my apologies, the easiest way to create the flow scenario files is probably from the Activities table for your database. If you right click on an activity here and then click/go to the copy to clipboard you should then be able to copy all of the exchanges for the activity including the biosphere and product exchanges, which should be correctly labelled. This should, hopefully, work. If you, or anyone else are using Linux then you may have to install a system library so that the python library we use can execute this (here is the link that should help any one in need of this https://pyperclip.readthedocs.io/en/latest/#not-implemented-error).

**Comment by siwije** [comment]
> should then be able to copy all of the exchanges for the activity including the biosphere and product exchanges

But it doesn't include the parameter scenarios. You would have to make each scenario manually.

**Comment by Zoophobus** [comment]
True, generally we recommend against using parameters. Partially because they are not available in the bw2package files, but also because the results when using parameters are less reliable, this is both in brightway and the AB (it's difficult to address this because the code for parameters is in both the AB and brightway, whereas more generally the execution is performed in brightway and the AB provides a powerful graphical interface.) Until the issues around the parameter code are resolved, which will require a lot of discussion, it is probably better to use the flow scenarios especially between groups/students.

It is a pity because parameters could otherwise provide an incredibly powerful mechanism for testing different hypotheses, but it is the current reality for the software

**Comment by siwije** [comment]
It is indeed a powerful mechanism for testing mechanisms. I think I will give them a choice between running a database for each scenario, and exporting flow scenarios from the established parameters and then adjusting the flow type manually.

Thanks for the help!

**Comment by ljlazar** [comment]
Sure, thanks for asking. I made a simple example with a made up process for electricity on the one hand with the same process twice in an activity and on the other hand with the same absolute values but combined in one activity. While in the standard LCA the results are equal (as expected), in the scenario LCA the results differ. The results with the same process used twice are wrong. It seems that the formula calculations cannot handle this.

I attached some screenshots, please let me know if you need anything else which could be helpful.

![1](https://github.com/LCA-ActivityBrowser/activity-browser/assets/68371125/3176c3d0-8469-4ab3-b68a-61c98f56875c)


![2](https://github.com/LCA-ActivityBrowser/activity-browser/assets/68371125/00a614e6-7f72-4e80-be3b-2795be881e6f)


![3](https://github.com/LCA-ActivityBrowser/activity-browser/assets/68371125/b043f45f-598a-4283-b107-992ab75e5f49)


![4](https://github.com/LCA-ActivityBrowser/activity-browser/assets/68371125/21d49646-b49e-421f-b7b4-f569d7f63533)

![5](https://github.com/LCA-ActivityBrowser/activity-browser/assets/68371125/792bad3b-2e0a-4e9f-bf4d-923b22c1ebfb)

**Comment by Zoophobus** [comment]
@ljlazar thanks, thats absolutely perfect! Well not on the parameters side, but that's perfect detail on your part, I'll try and figure out what we should do to manage this, best wishes from the AB team!
