### ISSUE TITLE
Plugins - (de-)activation procedure

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#993]
Plugins currently (de-)acitvate when the `use` checkbox is clicked. To me it'd make more sense if we only read the checkbox state when the `Finish` button is clicked, not when the checkbox state changes. To me this would especially make sense when using multiple plugins.

Additionally, I'd suggest we re-name `Finish` to `Confirm`, which would be more in line with the above (confirming the changes to active plugins). We could also add a `Cancel` button then, which would not apply changes.

@Pan6ora @Zoophobus These are just some thoughts, not really a 'this must be changed' problem: what do you think?

**Comment by Zoophobus** [comment]
@marc-vdm @Pan6ora I think this would be good, this procedure can take time with the process for starting the jupyter notebooks server and could for other plugins. I think doing this outside of the checkbox and with a `Confirm` button might be a more user friendly approach

**Comment by Zoophobus** [comment]
@Pan6ora you can witness my butchery at your whim, my apologies for any excessive brutality. @marc-vdm has checked this and has okayed it so I've merged this with the master branch, I've also added some minor changes with the text that @marc-vdm suggested to help with any possible debugging that will be required
