### ISSUE TITLE
Plugins - plugin load message when plugin is disabled

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#995]
When I open AB with no active plugins, I still get a `Loading plugin ab_plugin_notebook` message. Do we still (partially) load plugins in the background, or is this just a `print` that shouldn't happen?

```
(ab-plugin) C:\>activity-browser
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/5c52672a-fb7c-4a9a-a287-4dca913a61ee
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Loading plugin ab_plugin_notebook
Loading user settings:
dirpath already loaded
Reset project settings directory to: C:\Users\meidemtvander\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loaded project: default
Brightway2 data directory: C:\Users\meidemtvander\AppData\Local\pylca\Brightway3
Brightway2 active project: default
Qt Version: 5.15.8
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Plugin-Notebook: server not running
```

Note that `Plugin-Notebook: server not running` is printed when I close AB again.

**Comment by Zoophobus** [comment]
Hmmm I'm thinking this could be potentially useful for debugging issues in the future when people are using plugins. At least here those plugins installed will be presented and for users less comfortable with conda it'll require less work on their part.

**Comment by Zoophobus** [comment]
Hmmm, @marc-vdm what system are you running this on, WIndows? In windows I get the `loading plugin ab_plugin_notebook`message but I don't get the 'Plugin-Notebook: server not running message. In Linux though I get an Error: plugin ab_plugin_template not installed, I'm not sure where this is creeping in though as it's not in the list of conda-packages.

**Comment by marc-vdm** [comment]
Yes, it's windows -you can also see from the printed `project directory` filepaths btw-

Specifically on the below, which is the latest windows version on my work computer:
```
Edition		Windows 10 Enterprise
Version		21H2
Installed on	‎13-‎1-‎2022
OS build	19044.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0
```

**Comment by marc-vdm** [comment]
> Hmmm I'm thinking this could be potentially useful for debugging issues in the future when people are using plugins. At least here those plugins installed will be presented and for users less comfortable with conda it'll require less work on their part.

Perhaps we should then differentiate between `installed` and `loaded` or something? IMO this could actually become confusing when trying to fix problems and it looks like plugins are loaded when they are not?

**Comment by Zoophobus** [comment]
What would be a good term for what's currently `loading` and what I would say is the `loading` when the plugin tab is actually opened? I'm currently thinking `loading` might be better for when the tab opens and `finding`, or `locating` could be used for when the AB is locating the plugins.

**Comment by Zoophobus** [comment]
Updates to the text are included
